### ISSUE TITLE
Cargo Boxes Despawn when entering Escape pod bay

### ISSUE THREAD

**Issue by harryingles** [dapperrobotbear/Stage9#1]
Computer specs : 17-4790, 16GB, GTX970

The bug occurs when taking cargo from the cargo elevator (not sure about which deck sorry) into an escape pod bay, I was attempting to use it to board the escape pod, however, it despawned as I went through the door. For all, I know this is intentional, but I thought I should probably check.

**Comment by metaphim428** [comment]
Yes, this is due to the Cargo elevator despawning when you get a certain distance from it.  Since the piece of cargo is from that room that despawned, it to despawned.

**Comment by harryingles** [comment]
Oh yeah, that makes sense. just thought I'd check it wasn't a bug
