### ISSUE TITLE
Standing up from Captain Chair facing wrong way

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#10]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**
When you get up from sitting in the Captain's Chair on main bridge, your char spins around and looks at the chair, instead of facing main viewer.

**Comment by scragnog** [comment]
not a bug as such. Your view returns to the direction your character was looking before sitting down, which in pretty much all cases will be the chair itself, before you clicked on it.

We're going to overhaul this system for v0.1.0
