### ISSUE TITLE
Some doors leading to the main shuttle bay won't open

### ISSUE THREAD

**Issue by Bt-btt** [dapperrobotbear/Stage9#100]
Some of the big doors connecting the main shuttle bay with the corridor on deck 4 won't open.

On the starboard side entering the corridor from the main shuttle bay entrance counterclockwise the first big door to the shuttle bay won't open.

On the  portside entering the corridor from the main shuttle bay entrance clockwise every big door leading to the shuttle bay won't open.

The NPC, knowing that these doors exist, are trying to get through the them, but fail and turn around eventually.

**Comment by scragnog** [comment]
confirmed. I forgot to unlock these doors. Fixed now. Thanks.
