### ISSUE TITLE
Phaser glitches when being used in turbolift - Settings menu zoom glitch

### ISSUE THREAD

**Issue by Rider51** [dapperrobotbear/Stage9#101]
Computer Specs and Info:
Windows 10 - Intel i5 CPU - 8GB RAM - GeForce GTX 760 GPU
Game Version: 0.0.9 QA2
First Bug:
You are unable to fire the phaser in turbolifts (Not sure why you would in the first place...); However when you hold down the phaser fire button and walk into a turbolift it will get stuck on and continue to fire when you leave the lift. Also, after doing that, if you drop the phaser it will go flying somewhere.

Second Bug:
When you are in the settings menu, if you right click  (the zoomkey) inside the menu once or spam it, the game view will continue to zoom in until you exit the menu, then it will reset.
![stage9-zoombug](https://user-images.githubusercontent.com/22503508/33298430-f353b0cc-d3ab-11e7-981d-9febf0b1b9ba.png)

**Comment by scragnog** [comment]
issue 1 fixed. Phaser will now not activate in turbolift but can be deactivated if you're firing it when you walk in there.

Issue 2 fixed. Player can now not zoom when menu is open.
