### ISSUE TITLE
Tractor Beam Sound doesn't go away

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#102]
Activated the tractor beam near the runabout while I was upstairs in the control room adjacent to the runabout.   I then walked clear across the shuttle bay, and climbed the stairs to Deck 3.   I could still hear the tractor beam sound effect.

**Comment by scragnog** [comment]
all fixed now. Set radius for the tractor sound.

I actually didn't realise you could disconnect from the control panel with the beam active. But... I kinda like it. Bug becomes feature! Yay!
