### ISSUE TITLE
[Request] Shuttles new gravity setting 

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#107]
For Space it’s great that shuttles don’t react to gravity anymore. But it’s a little hard to land  that way. A key to get the shuttle to go down would be nice. Up is space - I can’t figure out one for down so I guess it isn’t there yet because it just wasn’t needed until now.

**Comment by scragnog** [comment]
'lower shuttle height' added for final release now. Should resolve this issue.
