### ISSUE TITLE
Interior Shuttle Hatch Controls Don't Work

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#109]
You can't reopen the door when inside. Actually, you can. But there seems to be like 2 minute delay. If you click the button multiple times. But than it opens and closes the same amount of times you clicked it.

**Comment by scragnog** [comment]
by any chance is this in first-person no-headbob mode? I fixed a bug related to this last night.

**Comment by archer9234** [comment]
Yes I'm using FP no headbob.

**Comment by Gary-Baggins** [comment]
unable to recreate, please close @TheStrato @HPringles

**Comment by HPringles** [comment]
# Was Fixed For V10, Closing
