### ISSUE TITLE
Pick same destination in Turbolift it kicking you out of Turbolift and you fall though world

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#11]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**
Take a turbolift to any location, and when at the location, choose the same location in the tubolift, and you get kicked out of the tubolift and throw into space..

![stage9 screenshot 2017 11 25 - 21 14 52 35](https://user-images.githubusercontent.com/33987322/33234522-742e72a2-d228-11e7-8252-dd311eab2c0f.png)

**Comment by scragnog** [comment]
confirmed. Reported to Dapper for further investigation.

**Comment by Hackmancoltaire** [comment]
Fixed in 6792cbcbd3ea81676d10ced22c1560ba89df41e4

**Comment by dapperrobotbear** [comment]
Fixed in: 6792cbcbd3ea81676d10ced22c1560ba89df41e4
