### ISSUE TITLE
Hand Animation Gets Stuck When In Bodyless First Person Mode

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#111]
After a while. Either running or jumping a lot. The animations of the floating hands eventually get stuck. They randomly get unstuck. But the process repeats itself.

**Comment by Bt-btt** [comment]
I have the observed the same bug. It happens quite frequently. Also it is independend from the walking/sprinting speed and any jumping. It even happens in the slowest walking mode after a few seconds. After a while the hands move normal again.

**Comment by TheStrato** [comment]
I have had this problem as well. There doesn't seem to be any pattern to when it happens or when it fixes itself.

**Comment by Gary-Baggins** [comment]
unable to recreate, please close @TheStrato @HPringles can I also stop testing things that make me dizzy?

**Comment by HPringles** [comment]
# Confirmed

Saw this in QA2

**Comment by TheStrato** [comment]
Label derp.

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
