### ISSUE TITLE
Deck 13 - Room 0068 & Room 8980 gab between Door and Deck 13

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#112]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

Gab between door and deck 13

![stage9 screenshot 2017 11 28 - 15 39 28 81](https://user-images.githubusercontent.com/33987322/33325497-bc66bf80-d452-11e7-8c83-d8d820a75b4c.png)
![stage9 screenshot 2017 11 28 - 15 39 38 36](https://user-images.githubusercontent.com/33987322/33325498-bc7e8fa2-d452-11e7-9753-1c4e0c50a21c.png)

**Comment by scragnog** [comment]
same issue as previous ticket. Looking to adjust this for v0.1.0
