### ISSUE TITLE
Deck 13 - Shuttlebay 2 wall gabs and Text floating

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#113]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

**The text above the Entrence/Exit door is hovering bit out from the wall.**
![stage9 screenshot 2017 11 28 - 15 49 19 55](https://user-images.githubusercontent.com/33987322/33325895-d970e730-d453-11e7-811f-9b800c7d0eea.png)

![stage9 screenshot 2017 11 28 - 15 46 01 24](https://user-images.githubusercontent.com/33987322/33325947-f3843992-d453-11e7-9f0d-d1f885dbef3a.png)
![stage9 screenshot 2017 11 28 - 15 46 04 45](https://user-images.githubusercontent.com/33987322/33325948-f39d6dd6-d453-11e7-9721-08c6dac571f5.png)
![stage9 screenshot 2017 11 28 - 15 46 33 27](https://user-images.githubusercontent.com/33987322/33325949-f3b98138-d453-11e7-8284-fca821684ea2.png)
![stage9 screenshot 2017 11 28 - 15 46 37 58](https://user-images.githubusercontent.com/33987322/33325951-f3d9f774-d453-11e7-9632-49e80ea9c077.png)
![stage9 screenshot 2017 11 28 - 15 48 46 59](https://user-images.githubusercontent.com/33987322/33325953-f410c4b6-d453-11e7-9bed-aa0bf907483c.png)
![stage9 screenshot 2017 11 28 - 15 45 09 91](https://user-images.githubusercontent.com/33987322/33325946-f367ba42-d453-11e7-857f-7e7652ac6f89.png)

**Door leading out to Deck 13. Small gab**
![stage9 screenshot 2017 11 28 - 16 07 11 07](https://user-images.githubusercontent.com/33987322/33326814-434f90d2-d456-11e7-8556-22008e4476bb.png)

**Seems this wall is hovering a little over ground and the "blue forcefield line can be seen shining though"**
![stage9 screenshot 2017 11 28 - 15 46 49 92](https://user-images.githubusercontent.com/33987322/33325952-f3f80dd6-d453-11e7-9446-31b43bece01c.png)

**Comment by scragnog** [comment]
Wow you really do catch all the little details! :-D

all known issues. we're rebuilding shuttlebay 2 and shuttlebay 3 to match the plans for v0.1.0 so there's no point fixing these for this release.
