### ISSUE TITLE
Shuttlecraft Doesn't Slow Down Faster When Pressing The Other Direction

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#114]
When you're moving forward. Hitting reverse should slow down the Shuttle faster. It actually takes longer to go in reverse, when doing that. VS let go of the controls, and let the Shuttle come to a complete stop on its own.

**Comment by scragnog** [comment]
True. Limitation of the current system we're using for the shuttles. If and when we can rework/rebuild this, we will. Going to close this one for now and duplicate it in our internal tracker for a later release.
