### ISSUE TITLE
Shuttlecaft small gab in roof next to flight seats. 

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#115]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**
Go inside shuttle to the front seats, turn around and look up.

![stage9 screenshot 2017 11 28 - 16 01 53 82](https://user-images.githubusercontent.com/33987322/33326719-fa147d38-d455-11e7-8dfb-6f88b8b15beb.png)
![stage9 screenshot 2017 11 28 - 16 02 00 48](https://user-images.githubusercontent.com/33987322/33326720-fa2fb4e0-d455-11e7-9d09-e58b73f67329.png)

**Comment by scragnog** [comment]
Confirmed. This requires a remodel of the shuttle, so we'll push this one back for now. Thanks for reporting.
