### ISSUE TITLE
[Visual] Deck 25 Room: 2521 (Nacelles Control) Railing don't aliment looks like a easy way to cut your hand.

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#116]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

If you look at this railing corner, it looks like a accident about to happen. Watch your fingers.
![stage9 screenshot 2017 11 28 - 16 11 54 94](https://user-images.githubusercontent.com/33987322/33327215-4347c040-d457-11e7-84bc-f7bc82dcd24e.png)

**Comment by scragnog** [comment]
adjusted now, looks like it was just a bit misaligned.
