### ISSUE TITLE
Deck 36 - Gab between Turbolift and Deck 36 Main engineering

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#117]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

Small gab between Turbolift and deck 36
![stage9 screenshot 2017 11 28 - 16 16 36 68](https://user-images.githubusercontent.com/33987322/33327562-1798da5a-d458-11e7-9aaf-42e5f1343149.png)

**Comment by scragnog** [comment]
known issue. This is because of the gap between turbolift/room and the hallway, where the door itself takes up space but doesn't have a floor. Going to aim to readdress this for v0.1.0
