### ISSUE TITLE
Deck 36 Main Engineering - Gabs around warp core area

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#118]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**
In main engineering is a few gabs here and there around warpcore.

![stage9 screenshot 2017 11 28 - 16 22 31 99](https://user-images.githubusercontent.com/33987322/33327817-b4572df6-d458-11e7-951f-f2b3820decac.png)
![stage9 screenshot 2017 11 28 - 16 22 35 92](https://user-images.githubusercontent.com/33987322/33327818-b4739040-d458-11e7-8994-6e389ae7ad60.png)
![stage9 screenshot 2017 11 28 - 16 22 41 09](https://user-images.githubusercontent.com/33987322/33327819-b48cab7a-d458-11e7-8b88-e826dd86c814.png)
![stage9 screenshot 2017 11 28 - 16 22 56 71](https://user-images.githubusercontent.com/33987322/33327821-b4a513d6-d458-11e7-844b-c07701931f5b.png)
![stage9 screenshot 2017 11 28 - 16 23 04 55](https://user-images.githubusercontent.com/33987322/33327823-b4c945d0-d458-11e7-8308-2a743bf31599.png)

**Comment by OssiBRI** [comment]
Plus, the cylinder behind the warpcore is missing completely:
![78cdf51106c7a6112c0073bc0921f71e](https://user-images.githubusercontent.com/34159074/33781085-88c3700c-dc53-11e7-946c-09e8d0eaf9a3.jpg)

**Comment by Gary-Baggins** [comment]
Gaps listed are no longer there and the cylinder behind the warpcore is now there, although there are 2 small gaps either side of the arch on the floor seen from this view
https://cdn.discordapp.com/attachments/422132672178159616/423450412608389120/unknown.png
and one small gap in the floor in this view
https://cdn.discordapp.com/attachments/422132672178159616/423450626266103808/unknown.png
so i will suggest this ticket stays open as to not create a new on just for the same area, please tag  windows and rooms @TheStrato @HPringles

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
