### ISSUE TITLE
Turbolifts - Driffent colour scheme in the turbolift, also bright lights... 

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#119]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**
While you using the Turbolifts, and gets "teleported" from one Turbolift to another they don't have same colors scheme some are dark others very bright. 

![stage9 screenshot 2017 11 28 - 16 28 36 92](https://user-images.githubusercontent.com/33987322/33328218-b74a11f8-d459-11e7-87c0-7549be117b10.png)
![stage9 screenshot 2017 11 28 - 16 29 25 72](https://user-images.githubusercontent.com/33987322/33328219-b766442c-d459-11e7-962c-9d1adf49bfbb.png)
![stage9 screenshot 2017 11 28 - 16 29 34 29](https://user-images.githubusercontent.com/33987322/33328220-b77d39ac-d459-11e7-9876-4d3f2aa2ef5a.png)
![stage9 screenshot 2017 11 28 - 16 29 50 72](https://user-images.githubusercontent.com/33987322/33328221-b795ae38-d459-11e7-9438-6cbfa9fe7b65.png)
![stage9 screenshot 2017 11 28 - 16 30 17 67](https://user-images.githubusercontent.com/33987322/33328222-b7ad4a5c-d459-11e7-9347-7c1c5448a61e.png)
![stage9 screenshot 2017 11 28 - 16 30 27 09](https://user-images.githubusercontent.com/33987322/33328224-b7eba6e4-d459-11e7-8efc-2d3dbc45070f.png)

**Comment by Gary-Baggins** [comment]
Unable to test due to system limitations @TheStrato @HPringles

**Comment by HPringles** [comment]
# Unconfirmed

I believe this is due to the amount of light outside the turbolift 

@scragnog @dapperrobotbear Can you confirm?

**Comment by kaadaq** [comment]
I believe HPringles is correct.   I have lighting changes that occur within the lift as it moves around.   It responds to external lighting.  @TheStrato please advance

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
