### ISSUE TITLE
Console on Main Shuttlebay has OPEN shuttlebaydoor but nowhere near it

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#12]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

In main shuttlebay directly across the main shuttlebay door, you can find a console facing away that has the options to "open" shuttle bay doors. (it don't work, and i don't think it's meant to be a working console) 

![stage9 screenshot 2017 11 25 - 21 12 43 62](https://user-images.githubusercontent.com/33987322/33234534-beab22e4-d228-11e7-9556-3ce18cadbe6b.png)

**Comment by scragnog** [comment]
fixed now (and replaced with something much cooler!)
