### ISSUE TITLE
Shuttlecraft Auto Door System Triggers While Inside Another Shuttle

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#120]
If you open up a Shuttlecraft and than drive another one near the first ones door. That shuttles door will constantly trigger open and close. The Shuttle you're driving will start being pulled in and get stuck together.

**Comment by scragnog** [comment]
the trigger issue is resolved. But as far as collision goes, that's engine physx stuff that we can't really control. Will close this ticket as the main issue is sorted now.
