### ISSUE TITLE
Cargodoor - Door gab center where doors slide in and out

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#121]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**
When cargodoors are open, if you look into where they slide into the wall, you see gabs on both sides. 

![stage9 screenshot 2017 11 28 - 16 48 13 47](https://user-images.githubusercontent.com/33987322/33329143-30c3207c-d45c-11e7-9c75-ff4e9b64386d.png)
![stage9 screenshot 2017 11 28 - 16 48 16 93](https://user-images.githubusercontent.com/33987322/33329144-3154b0dc-d45c-11e7-8293-0e3169b494ee.png)

**Comment by scragnog** [comment]
well spotted. so I've realigned the door to be in the center of the frame and stretched it out now to fill the space. There's still a problem where you can see through the inset bits of the foots, because they don't sit flush with the frame, but it's better!
