### ISSUE TITLE
[Crash Bug] Might be result of alot of ALT+TAB in and out

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#122]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

**Fatal error!**

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffff

0x00000000C1E1CB73 Stage9-Win64-Shipping.exe!UNavigationSystem::GetNavOctreeElementData() []
0x00000000C1E357C9 Stage9-Win64-Shipping.exe!UNavigationSystem::UpdateNavOctreeElement() []
0x00000000C1E34CEA Stage9-Win64-Shipping.exe!UNavigationSystem::UpdateComponentInNavOctree() []
0x00000000C1B98EF9 Stage9-Win64-Shipping.exe!UActorComponent::ExecuteRegisterEvents() []
0x00000000C1BA43F4 Stage9-Win64-Shipping.exe!UActorComponent::RegisterComponentWithWorld() []
0x00000000C1B52F0C Stage9-Win64-Shipping.exe!AActor::IncrementalRegisterComponents() []
0x00000000C1D0380B Stage9-Win64-Shipping.exe!ULevel::IncrementalUpdateComponents() []
0x00000000C18AA0C8 Stage9-Win64-Shipping.exe!UWorld::AddToWorld() []
0x00000000C18BBF7A Stage9-Win64-Shipping.exe!UWorld::UpdateLevelStreamingInner() []
0x00000000C18BBC87 Stage9-Win64-Shipping.exe!UWorld::UpdateLevelStreaming() []
0x00000000C1930393 Stage9-Win64-Shipping.exe!UGameViewportClient::Draw() []
0x00000000C1867C5C Stage9-Win64-Shipping.exe!FViewport::Draw() []
0x00000000C191B8D1 Stage9-Win64-Shipping.exe!UGameEngine::RedrawViewports() []
0x00000000C1920C10 Stage9-Win64-Shipping.exe!UGameEngine::Tick() []
0x00000000C1471173 Stage9-Win64-Shipping.exe!FEngineLoop::Tick() []
0x00000000C14767DC Stage9-Win64-Shipping.exe!GuardedMain() []
0x00000000C147683A Stage9-Win64-Shipping.exe!GuardedMainWrapper() []
0x00000000C147CEB0 Stage9-Win64-Shipping.exe!WinMain() []
0x00000000C2986093 Stage9-Win64-Shipping.exe!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253]
0x00000000D0822774 KERNEL32.DLL!UnknownFunction []
0x00000000D1C60D51 ntdll.dll!UnknownFunction []
0x00000000D1C60D51 ntdll.dll!UnknownFunction []

**Comment by Gary-Baggins** [comment]
Unable to recreate please close @TheStrato @HPringles

**Comment by TheStrato** [comment]
Most likely a one off error. Will close for now.
