### ISSUE TITLE
Transporter Room 1 - You can jump through the ceiling

### ISSUE THREAD

**Issue by harryingles** [dapperrobotbear/Stage9#123]
When standing on the transporter console, you can jump through the ceiling, it doesnt have collisions on.

![desktop screenshot 2017 11 28 - 15 58 15 13](https://user-images.githubusercontent.com/16962690/33329774-24663b68-d455-11e7-8950-42a970f54989.png)

**Comment by scragnog** [comment]
fixed now. Already did this on the other rooms, but these mirrored ones are a different mesh. Fixed here now too.
