### ISSUE TITLE
[Intro Sequence] issue with graphics and suggestion 

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#124]
Awesome with an Intro Sequence love it... 

**Issue:**

1. When Enterprise warps out the first time, it seems to warp strangely down center of the screen.
2. When Enterprise warps though the screen and text appear, the end of Enterprise nacelles seems to flash few secs after.

**Suggestion**
Add warp sound effect when flying though the screen :)

**Comment by TheStrato** [comment]
To add to the "intro sequence" thread, when the ship is warping past during the credits there is a pop sound after it gets past the camera. 
~specs in bio~

**Comment by Gary-Baggins** [comment]
Unable to test in QA2 as intro sequence is not included. @TheStrato @HPringles

**Comment by kaadaq** [comment]
still present as of 0010-HF1.   Pop is also present.

@HPringles, please remove Needs Validation

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
