### ISSUE TITLE
Remote Saucer Sep. Leaves Shuttles & Turbolift Stranded in space

### ISSUE THREAD

**Issue by HPringles** [dapperrobotbear/Stage9#126]
# Stage 9 Bug report
### PC Specifications
**CPU**       : Intel i7-4790
**RAM**       : 16GB DDR4
**STORAGE**   : 2TB HDD 7200RPM + 120GB SSD(boot drive)
**GPU**       : NVIDIA Geforce GTX 970 4GB

### Bug Report

**TYPE**      : Functional

Triggering Remote Saucer Separation after leaving shuttlebay 1 despawns the room, but not the shuttles left inside it. Meaning they get left behind floating in space.

### Related Images

![desktop screenshot 2017 11 28 - 16 37 10 34](https://user-images.githubusercontent.com/16962690/33331998-02571fb4-d45b-11e7-9312-5d27c033315c.png)

**Shuttles left in space**

![desktop screenshot 2017 11 28 - 16 45 00 95](https://user-images.githubusercontent.com/16962690/33332219-8f18e1c6-d45b-11e7-9764-33d60cf95cac.png)

**Last used turbolift left in space**

**Comment by Gary-Baggins** [comment]
Confirmed, please tag windows @TheStrato @HPringles

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
