### ISSUE TITLE
Fatal Error - Shuttlebay 1 remote opening

### ISSUE THREAD

**Issue by harryingles** [dapperrobotbear/Stage9#127]
# Stage 9 Bug report
### PC Specifications
**CPU**       : Intel i7-4790
**RAM**       : 16GB DDR4
**STORAGE**   : 2TB HDD + 120GB SSD(boot)
**GPU**       : Zotac NVIDIA Geforce GTX 970 4GB

### Bug Report

**TYPE**      : Crash

Fatal error occured when remote opening shuttlebay 1 from inside the shuttle from shuttlebay 2

Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000be9f

0x000000004F7CB041 Stage9-Win64-Shipping.exe!TOctree<FNavigationOctreeElement,FNavigationOctreeSemantics>::RemoveElement() []
0x000000004F7CB8C8 Stage9-Win64-Shipping.exe!FNavigationOctree::RemoveNode() []
0x000000004F7CB81D Stage9-Win64-Shipping.exe!UNavigationSystem::RemoveNavOctreeElementId() []
0x000000004F7D3D71 Stage9-Win64-Shipping.exe!UNavigationSystem::UnregisterNavOctreeElement() []
0x000000004F7D57E0 Stage9-Win64-Shipping.exe!UNavigationSystem::UpdateNavOctreeElement() []
0x000000004F7D4CEA Stage9-Win64-Shipping.exe!UNavigationSystem::UpdateComponentInNavOctree() []
0x000000004F538EF9 Stage9-Win64-Shipping.exe!UActorComponent::ExecuteRegisterEvents() []
0x000000004F5443F4 Stage9-Win64-Shipping.exe!UActorComponent::RegisterComponentWithWorld() []
0x000000004F4F2F0C Stage9-Win64-Shipping.exe!AActor::IncrementalRegisterComponents() []
0x000000004F6A380B Stage9-Win64-Shipping.exe!ULevel::IncrementalUpdateComponents() []
0x000000004F24A0C8 Stage9-Win64-Shipping.exe!UWorld::AddToWorld() []
0x000000004F25BF7A Stage9-Win64-Shipping.exe!UWorld::UpdateLevelStreamingInner() []
0x000000004F25BC87 Stage9-Win64-Shipping.exe!UWorld::UpdateLevelStreaming() []
0x000000004F2D0393 Stage9-Win64-Shipping.exe!UGameViewportClient::Draw() []
0x000000004F207C5C Stage9-Win64-Shipping.exe!FViewport::Draw() []
0x000000004F2BB8D1 Stage9-Win64-Shipping.exe!UGameEngine::RedrawViewports() []
0x000000004F2C0C10 Stage9-Win64-Shipping.exe!UGameEngine::Tick() []
0x000000004EE11173 Stage9-Win64-Shipping.exe!FEngineLoop::Tick() []
0x000000004EE167DC Stage9-Win64-Shipping.exe!GuardedMain() []
0x000000004EE1683A Stage9-Win64-Shipping.exe!GuardedMainWrapper() []
0x000000004EE1CEB0 Stage9-Win64-Shipping.exe!WinMain() []
0x0000000050326093 Stage9-Win64-Shipping.exe!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253]
0x0000000039D81FE4 KERNEL32.DLL!UnknownFunction []
0x000000003C31EF91 ntdll.dll!UnknownFunction []
0x000000003C31EF91 ntdll.dll!UnknownFunction []

### Related Images

DRAG AND DROP RELATED IMAGES HERE - ADD COMMENTS TO THEM IF REQUIRED

**Comment by scragnog** [comment]
great template!

You know can't perform this from within the shuttlebays, only outside the ship.

**Comment by harryingles** [comment]
I believe I was outside the ship @scragnog .

I opened it from the shuttle that came from bay 2

**Comment by scragnog** [comment]
Ok thanks. We'll test this more here
