### ISSUE TITLE
NPC's Are Able To Push Active Shuttles

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#128]
If you use a Shuttle, land it, and a NPC walks into it. It can easily push it away, as they move.

**Comment by Gary-Baggins** [comment]
Not observed, please close @TheStrato @HPringles

**Comment by HPringles** [comment]
# Confirmed

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
