### ISSUE TITLE
Despawning Shuttlebay 1 When Using Remote Shuttlebay 2 From Inside Bay 1

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#129]
When you remote shuttlebay 2. You guys close the Main Bay so that you can unload it. But you can trigger remote bay 2 from inside bay 1. Unloading it and getting you stuck.

**Comment by Gary-Baggins** [comment]
Needs more info/further testing @TheStrato @HPringles

**Comment by Gary-Baggins** [comment]
I was able to confirm this this time, please tag with bug @TheStrato @HPringles

**Comment by TheStrato** [comment]
I linked the two tickets since they both have a lot of info on them.

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
