### ISSUE TITLE
Graphic issue: Battle bridge main viewer don't align center

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#13]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**
Main viewer on Battle bridge top and bottom edge don't align in the center. 

![stage9 screenshot 2017 11 25 - 21 38 45 22](https://user-images.githubusercontent.com/33987322/33234558-406c9344-d229-11e7-8afd-8f65372fa98d.png)

**Comment by scragnog** [comment]
applied a temporary fix for now. This whole area needs remodeeling, but at least the gaps are gone now.
