### ISSUE TITLE
Deck 4 - Can walk through main shuttle bay door

### ISSUE THREAD

**Issue by VigoHornblower** [dapperrobotbear/Stage9#131]
Specs:
Windows 10
Intel Core i5-4460 cpu @ 3.20ghz
NVidea GeForce GTX 1060 (6GB VRAM)
Resolution: 1440x900

Version:
Stage9-Windows-v009-QA-Release-2

![bandicam 2017-11-28 19-31-34-857](https://user-images.githubusercontent.com/34043160/33351666-e7468666-d472-11e7-9006-1e48ebb1cf2c.jpg)

**Comment by Gary-Baggins** [comment]
Unable to recreate, please close @TheStrato @HPringles

**Comment by TheStrato** [comment]
More object clip, known concern. Will close this ticket.
