### ISSUE TITLE
Deck 4 - Turbolift stop mislabeled

### ISSUE THREAD

**Issue by VigoHornblower** [dapperrobotbear/Stage9#132]
Shouldn't it be "Shuttlebay 1 | Stern" instead of "Shuttlebay 1 | Bow"?
![deck4](https://user-images.githubusercontent.com/34043160/33351897-fe7fdbba-d473-11e7-94eb-1c3a9d050659.jpg)
![bandicam 2017-11-28 19-37-33-256](https://user-images.githubusercontent.com/34043160/33351902-021c4272-d474-11e7-96bf-34a3f0e2a061.jpg)

**Comment by Gary-Baggins** [comment]
Confirmed, please tag windows and accuracy @TheStrato @HPringles

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
