### ISSUE TITLE
Warp particles visible inside ship

### ISSUE THREAD

**Issue by VigoHornblower** [dapperrobotbear/Stage9#133]
When in warp, sometimes you can see a particle fly through the ship. (Very apparent in main shuttle bay)
![bandicam 2017-11-28 21-34-46-894](https://user-images.githubusercontent.com/34043160/33355220-9035b7cc-d484-11e7-8fbe-549655510f76.jpg)

**Comment by winfel** [comment]
I also had this on the bridge once. A particle was coming through the screen into the bridge.

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
