### ISSUE TITLE
Jump through ceiling - Data's Quarters

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#134]
If you stand on Data's desk in his quarters (Deck 2) and jump, you can go through the ceiling.

**Comment by HebaruSan** [comment]
I set up Ansel for this, might as well share even if it's a duplicate:

![stage9-win64-shipping screenshot 2018 02 02 - 21 19 44 27](https://user-images.githubusercontent.com/1559108/35755605-db10186e-085f-11e8-87f7-75fb4eea54c0.png)

**Comment by kaadaq** [comment]
Previously fixed.
