### ISSUE TITLE
Tricorder & Phaser 1 don't move with head

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#135]
Tricorder in Ready Room, and Phaser 1 in Data's quarters don't move with your body as you turn.   You end up holding it cocked off to the side, which makes it impossible to "aim" them.    Problem persists in both 1st person and 3rd person modes.

**Comment by Gary-Baggins** [comment]
I am only seeing this in 1st person mode although aiming in 3rd person could also do with some polishing, please tag windows, props and bug @TheStrato @HPringles

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
