### ISSUE TITLE
04|9768 Wall rail crossing the corridor

### ISSUE THREAD

**Issue by TheStrato** [dapperrobotbear/Stage9#136]
![image](https://user-images.githubusercontent.com/34151516/33469313-c8b72956-d627-11e7-81c2-f40e99e09987.png)

**Comment by Gary-Baggins** [comment]
Need more info @TheStrato @HPringles

**Comment by TheStrato** [comment]
Just need someone to go to that area and see if you see the chair rail across the corridor.

**Comment by HPringles** [comment]
I don't believe this is possible to access in V10 due to lots of locked doors around shuttlebay 1

**Comment by TheStrato** [comment]
@scragnog Can you validate this in editor please and thank you.

**Comment by TheStrato** [comment]
Spoke with Corridors Dev, issue doesn't exist in current version. Closing this ticket.
