### ISSUE TITLE
Padd from Main Engineering

### ISSUE THREAD

**Issue by TheStrato** [dapperrobotbear/Stage9#139]
I picked up a Padd from the center console in Main Engineering and it didn't show up in my hand in front of my face until I had walked back to the turbolift and went to a new deck, as soon as the door opened and I started to walk out of the turbolift is popped up in my right hand. 

Specs are in my bio.

**Comment by Gary-Baggins** [comment]
Issue seems to be fixed, please close @TheStrato @HPringles

**Comment by TheStrato** [comment]
Probably fixed with the handhelds updates. Closing this ticket.
