### ISSUE TITLE
Fatal error! Was flying around in Shuttle craft

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#14]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**
Was flying the shuttlecraft ind and out of Main Shuttlebay and Shuttlebay 2, and i activated remote opendoors to shuttlebay 2 and sat in chair to start fly the shuttle again.. 

(Only happen one time)

Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000002b

0x0000000084C0E179 Stage9-Win64-Shipping.exe!UNavigationSystem::RemoveNavOctreeElementId() []
0x0000000084C16501 Stage9-Win64-Shipping.exe!UNavigationSystem::UnregisterNavOctreeElement() []
0x0000000084C0707C Stage9-Win64-Shipping.exe!UNavigationSystem::OnComponentUnregistered() []
0x000000008498A4B0 Stage9-Win64-Shipping.exe!UActorComponent::UnregisterComponent() []
0x00000000849414FF Stage9-Win64-Shipping.exe!AActor::UnregisterAllComponents() []
0x0000000084AE4B70 Stage9-Win64-Shipping.exe!ULevel::IncrementalUnregisterComponents() []
0x0000000084697C9B Stage9-Win64-Shipping.exe!UWorld::RemoveFromWorld() []
0x000000008469E385 Stage9-Win64-Shipping.exe!UWorld::UpdateLevelStreamingInner() []
0x000000008469E007 Stage9-Win64-Shipping.exe!UWorld::UpdateLevelStreaming() []
0x0000000084712953 Stage9-Win64-Shipping.exe!UGameViewportClient::Draw() []
0x00000000846496DC Stage9-Win64-Shipping.exe!FViewport::Draw() []
0x00000000846FDC41 Stage9-Win64-Shipping.exe!UGameEngine::RedrawViewports() []
0x00000000847031E0 Stage9-Win64-Shipping.exe!UGameEngine::Tick() []
0x00000000842520A3 Stage9-Win64-Shipping.exe!FEngineLoop::Tick() []
0x000000008425773C Stage9-Win64-Shipping.exe!GuardedMain() []
0x000000008425779A Stage9-Win64-Shipping.exe!GuardedMainWrapper() []
0x000000008425DEA0 Stage9-Win64-Shipping.exe!WinMain() []
0x00000000857694F3 Stage9-Win64-Shipping.exe!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253]
0x00000000D0822774 KERNEL32.DLL!UnknownFunction []
0x00000000D1C60D51 ntdll.dll!UnknownFunction []
0x00000000D1C60D51 ntdll.dll!UnknownFunction []

**Comment by scragnog** [comment]
looks like the navmesh crashed. Will leave this one for now and see if it crops up again. Hoping it's just a one-off quirk.

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
