### ISSUE TITLE
Nacelle Control Room. Nacelle Tube Door.

### ISSUE THREAD

**Issue by TheStrato** [dapperrobotbear/Stage9#140]
I have to be touching the collision point of the big door into the Nacelle tube for the door to stay open otherwise if I am any further back from the door on that upper catwalk it will just open and close right away.

Specs in bio.

**Comment by Gary-Baggins** [comment]
I believe that with the implementation of controlling said door from the console as you walk in this is now fixed/no longer an issue, close at your discretion @TheStrato @HPringles
