### ISSUE TITLE
Sitting shadows 

### ISSUE THREAD

**Issue by TheStrato** [dapperrobotbear/Stage9#141]
I found this while I was in Data's quarters but I would guess it might happen anywhere. When I sat in his desk chair, the shadow was still the one from when I had walked up to the chair from the side in the picture. I don't know if you can make a "sitting" shadow or just find a way to make the shadows turn off when the player is sitting. 

![image](https://user-images.githubusercontent.com/34151516/33471896-10b3095c-d635-11e7-8806-fb857826493d.png)

**Comment by Gary-Baggins** [comment]
Confirmed, please tag windows @TheStrato @HPringles

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
