### ISSUE TITLE
Tasha's Hologram

### ISSUE THREAD

**Issue by TheStrato** [dapperrobotbear/Stage9#142]
When you are standing, you can see Tasha's Hologram from any angle, but when you sit in his desk chair she is facing away from the chair and thus is just a barely visible side profile of the hologram light. I would guess that Data would spend a lot of time sitting there and glancing at her Hologram so could it be made that you can see the Hologram from the desk chair sitting position as well? 

![image](https://user-images.githubusercontent.com/34151516/33472037-f30d1518-d635-11e7-82a7-f17fcce82aa9.png)

**Comment by Gary-Baggins** [comment]
Confirmed, please tag windows, props and accuracy @TheStrato @HPringles

**Comment by TheStrato** [comment]
@HPringles You are missing some of the requested labels on a few of these tickets. Please look them over a bit more as you are doing them. Inaccuracy breeds inefficiency.

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
