### ISSUE TITLE
Missing polygon on Bridge Ceiling

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#143]
Missing polygon on bridge ceiling. Sorry I couldn't zoom in. Print screen shows an image of when I first alt tab back into the game, and not of the time I press it.
![image](https://user-images.githubusercontent.com/29221029/33472282-3205e7e4-d637-11e7-9687-2787e6dcb3bb.png)

**Comment by TheStrato** [comment]
When watching the status report video from @scragnog I also saw that little black triangle in the mirrored position on the other side of that same section of glass. So this one is basically above Riker's chair, the other one is above Troi's chair.

**Comment by Gary-Baggins** [comment]
I'm not seeing this in V10QA2, please close @TheStrato @HPringles
