### ISSUE TITLE
Picard's Bed

### ISSUE THREAD

**Issue by TheStrato** [dapperrobotbear/Stage9#144]
The blanket on Picard's bed has floating corners instead of hanging down like a blanket would on a bed that is raised up like that. The blanket looks like it would if that riser wasn't under the bed and it was sitting on the floor.  

![image](https://user-images.githubusercontent.com/34151516/33472580-90df234c-d638-11e7-86ac-76e56a228348.png)

**Comment by Gary-Baggins** [comment]
Confirmed, please tag windows and accuracy @TheStrato @HPringles

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
