### ISSUE TITLE
Label blur when turbolift is moving.

### ISSUE THREAD

**Issue by TheStrato** [dapperrobotbear/Stage9#145]
This label is right below the left corner of the turbolift control screen and I couldn't really catch it that well with snipping tool but I can try to get a gif with gyazo if you need me too, but whenever I go anywhere in the lifts this label will blur and tear all different directions. 

Specs in my bio. 

![image](https://user-images.githubusercontent.com/34151516/33473308-877cb5dc-d63b-11e7-8af5-5e2b309bdbb5.png)

**Comment by TheStrato** [comment]
Update: After watching the review video, all the labels like that one I mentioned blur in the same way when the turbolift is moving.

**Comment by Gary-Baggins** [comment]
unable to recreate please close @TheStrato @HPringles

**Comment by TheStrato** [comment]
This was also visible in @scragnog videos.

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
