### ISSUE TITLE
[Visual/Functional???] Missing Warp Stars

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#146]
![missingstars](https://user-images.githubusercontent.com/34159074/33482526-c0e015f4-d699-11e7-80d3-bd33fdff2b97.jpg)
Windows 7 Home Premium SP1 64x 
Intel Core i5-2430M CPU 2.40 GHz 
8.00 GB RAM 
NVIDIA GeForce GT 540M
V0.0.9 Windows Desktor

The warp stars are missing on all decks with a window/shuttle bay.

Grafics are set on high. Only tested with warp 1 so far.

**Comment by OssiBRI** [comment]
Addition: They were missing in v008 either, when effects were not set to excellent. Since there's no "excellent" in v9...

**Comment by OssiBRI** [comment]
I just had a hunch an switched v-sync off. The warp stars are back :-)

**Comment by OssiBRI** [comment]
Okay, this just worked once, they're gone, again.

**Comment by Gary-Baggins** [comment]
Warp stars present please close @TheStrato @HPringles

**Comment by OssiBRI** [comment]
Uhm, no. While I'm quit sure, thus us a problem with my graphic card drivers, this never happened before v9, without the "excellent" effect level.
It still happens every now and then.
I am able to recreate this in v8, by choosing an effects level lower than excellent.

**Comment by TheStrato** [comment]
@scragnog Would you be able to work with them directly to determine if this is their issue or ours?

**Comment by tenko23** [comment]
@HPringles @TheStrato - moved to Bugz.
