### ISSUE TITLE
Tractor Beam Emitters Have No Wall Check

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#147]
When using the Tractor beam next to the runabout. You can push the runabout outside the ship. But the beam will stay connected when going threw the roof the the main bay. https://imgur.com/a/bzJnu

**Comment by cheveffect09** [comment]
confirmed issue still in QA4,
Step 1. Go to main shuttle bay and open the main door
Step 2. Tractor the runabout using the one next to it
Step 3. While its in the beam push it out of the bay and it allows you to move it around the outside of the ship ignoring the wall.
![runpic1](https://user-images.githubusercontent.com/5516753/37575521-b6606732-2b7b-11e8-81f7-2739455912bd.png)
![runpic2](https://user-images.githubusercontent.com/5516753/37575522-b699c7f2-2b7b-11e8-974d-83749a2b74d7.png)

**Comment by kaadaq** [comment]
Confirmed in GM-1 as well.  @TheStrato  please advance
![image](https://user-images.githubusercontent.com/34050343/37576091-e556c552-2b00-11e8-8762-80a1a3c5747d.png)

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
