### ISSUE TITLE
Some Weird Blur On The Bodyless Hands

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#148]
When your move around in headless mode and look down. Some weird blur effect is happening on the hands. https://imgur.com/a/iZ7Si I have motion blur off. Not sure if that's related to this bug.

**Comment by Gary-Baggins** [comment]
unable to recreate please close @TheStrato @HPringles

**Comment by TheStrato** [comment]
Is this an end user graphics issue or something you guys can fix @scragnog ?

**Comment by scragnog** [comment]
this is temporal AA, part of the UE4 engine. You really only see this when framerate is dropping below a certain threshold. It's not something we can fix directly other than just optimise performance.

**Comment by TheStrato** [comment]
Noted. Will close this ticket.
