### ISSUE TITLE
Weird NPC Spawning when getting in shuttlebay 1 from a shuttle

### ISSUE THREAD

**Issue by jpcardin** [dapperrobotbear/Stage9#149]
When spawning shuttlebay 1 from a shuttle (leaving from shuttlebay 2) all the NPC's spawn at the same place/area

I was able to repeat this bug, with varying degrees of spawning issues

![spawnissue](https://user-images.githubusercontent.com/34181671/33512944-41bc6c6e-d707-11e7-8fca-86729e4a5653.png)

**Comment by jpcardin** [comment]
When initiating saucer separation from a shuttle leaving shuttlebay 2, the shuttlebay 1 door goes back to an open state, with the inside unloaded and then proceeds to close and then seperate.
![seperation](https://user-images.githubusercontent.com/34181671/33513022-ea1d42ec-d708-11e7-9cee-c720ac9c5dc4.png)

**Comment by Gary-Baggins** [comment]
Not observed, please close @TheStrato @HPringles

**Comment by HPringles** [comment]
# No longer an issue 

@TheStrato

**Comment by TheStrato** [comment]
No longer an issue. Closing the ticket.
