### ISSUE TITLE
Shuttlecraft 2 can't open doors and exit on Main shuttlebay

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#15]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

If you take the shuttle from shuttlebay 2 and fly up to Main Shuttlebay, you can fly in and land, But you can't open shuttlecraft doors to exit onto shuttlebay.

**Comment by harryingles** [comment]
I can't find a way of making any of the shuttles doors close(apart from the one in shuttlebay 2 which you can only close from the outside). The inside buttons never work

**Comment by scragnog** [comment]
All fixed now. This one had been bugging me, but it should be fixed :-D
