### ISSUE TITLE
[Functional] No Yellow Alert

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#150]
Windows 7 Home Premium SP1 64x
Intel Core i5-2430M CPU 2.40 GHz
8.00 GB RAM
NVIDIA GeForce GT 540M
V0.0.9 Windows Desktop

Clicking on "Yellow Alert" has no effect. No sound, no additional alert lights (on main bridge).

**Comment by kaadaq** [comment]
It also doesn't deactivate red alert.    It's just a dead button.

**Comment by OssiBRI** [comment]
It also didn't work in the previous versions.

**Comment by Gary-Baggins** [comment]
Yellow alert working on main bridge although no sound (was there a sound?) recommend leaving this one open until we can confirm sound Vs no sound please tag windows @TheStrato @HPringles

**Comment by TheStrato** [comment]
I am asking the composer.

**Comment by OssiBRI** [comment]
There was a sound when at the start if every yellow alert. Something like a shirt chime.

**Comment by HPringles** [comment]
@OssiBRI @TheStrato why is this closed?

**Comment by OssiBRI** [comment]
Clicked The wrong Button, sorry.

**Comment by OssiBRI** [comment]
https://m.youtube.com/watch?v=MeElfVfdzI0
At about 39  seconds into the video you can hear the sound which was played when yellow alert was called out.

**Comment by TheStrato** [comment]
Still waiting for a reply from the music Dev about this.

**Comment by TheStrato** [comment]
Per the composer, there is a sound for this and it has been added to the assets areas. 
@scragnog This was the yellow alert ticket I was talking about.

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
