### ISSUE TITLE
Wrong cut-out when selecting main engineering

### ISSUE THREAD

**Issue by SvenBrunk** [dapperrobotbear/Stage9#153]
The cut-out for main engineering is Deck 36, but it does not show the section where main engineering is.
On the top right you can see at least the warp core energy conduits that lead to main engineering, but most of the chart shows the reactant loader.

**Comment by Gary-Baggins** [comment]
Confirmed, to clarify this is referring to the image you see when selecting main engineering in the turbo lift, please tag windows and accuracy @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
