### ISSUE TITLE
Parts of Hallways are Invisible

### ISSUE THREAD

**Issue by Davjo64** [dapperrobotbear/Stage9#154]
**Specs:**
Windows 8.1
Intel Core i5-4200U CPU @1.60GHz 2.30 GHz
8 GB RAM
64 bit
Intel HD Graphics Family

-Appears on most decks
-Usually by doors, corners, and long stretches of hallways
-Ceilings are also invisible, but only on the same places that the walls are
-Deck 7 isn't affected
-The invisible portions are still solid
-I don't need to do anything unusual to replicate this glitch, it always looks like this
-It didn't happen in any previous versions

![corners on deck 9](https://user-images.githubusercontent.com/34198410/33520679-bc3f29d2-d78d-11e7-9188-a416c0b223d6.png)
![deck 9](https://user-images.githubusercontent.com/34198410/33520680-bc4cd6ea-d78d-11e7-9acb-b91e17283d2a.png)
![deck 10](https://user-images.githubusercontent.com/34198410/33520681-bc56450e-d78d-11e7-96a8-83ff4c05da94.png)
![doors on deck 9](https://user-images.githubusercontent.com/34198410/33520682-bc5fbcce-d78d-11e7-95c7-ec632e4d6c95.png)
![in between the walls deck 10](https://user-images.githubusercontent.com/34198410/33520684-c2b3caf2-d78d-11e7-8359-3a236083d007.png)

**Comment by Gary-Baggins** [comment]
I believe these are now fixed including the wall outside Picard's quarters, please close @TheStrato @HPringles

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
