### ISSUE TITLE
[Functional] Cannot shoot women

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#155]
Windows 7 Home Premium SP1 64x
Intel Core i5-2430M CPU 2.40 GHz
8.00 GB RAM
NVIDIA GeForce GT 540M
V0.0.9 Windows Desktop

When shooting with Phaser, only men die. Female NPCs are not effected.

**Comment by TheStrato** [comment]
This has already been addressed. It is based on the NPC models they are using and there is already a fix on the way.

**Comment by HPringles** [comment]
Duped issue , Closing
