### ISSUE TITLE
[Visual] Deck 2|Worf's Quarters

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#156]
Windows 7 Home Premium SP1 64x
Intel Core i5-2430M CPU 2.40 GHz
8.00 GB RAM
NVIDIA GeForce GT 540M
V0.0.9 Windows Desktop

The door sign on Worf's quarters says "Lt. Crd. Worf", he's only Lieutenant (Lt.) in Season 7. As a Lt. Cdr. he would have a right for bigger quarters (as Troi, who also is Lt. Cdr.).

**Comment by Sciencekeeper** [comment]
That’s not correct. Worf was promoted to Lt Commander early. Same time he was promoted to chief of security. On Generations his next promotion was to rank of commander. He was Lt only in season 1

**Comment by Sciencekeeper** [comment]
No.  Memory alpha confirms you. I was wrong. Wow i really thought he was Lt Cmdr....

**Comment by OssiBRI** [comment]
He got promoted in Generations on the holodeck.

**Comment by Gary-Baggins** [comment]
https://en.wikipedia.org/wiki/Worf#The_Next_Generation
In 2366, he was promoted to lieutenant (TNG: "Evolution"). After an accident caused the death of Lt. Marla Astor, Worf brought the orphaned Jeremy Astor into the House of Mogh through the rite of R'uustai (TNG: "The Bonding").

In 2371, he was promoted to lieutenant commander (Star Trek Generations). After the destruction of the Enterprise-D, Worf took an extended leave to evaluate his future. He was at a monastery on the Klingon colony of Boreth when he was ordered to go to Deep Space 9 to advise Captain Sisko when a Klingon fleet massed at the station. When he arrived, he was met by former Enterprise-D crew member and DS9's Chief of Operations, Miles O'Brien. (DS9: "The Way of the Warrior").

Worf was only promoted to lieutenant commander after season 7 of TNG had finished, therefore his quarters should only read lieutenant.

Please tag windows and accuracy @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
