### ISSUE TITLE
[Visual] Ready Room|Alert Lights Missing

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#157]
Windows 7 Home Premium SP1 64x
Intel Core i5-2430M CPU 2.40 GHz
8.00 GB RAM
NVIDIA GeForce GT 540M
V0.0.9 Windows Desktop

In Picard's Ready Room there should be blinking indicators for red alert at the upper light rails.
![missingredalert](https://user-images.githubusercontent.com/34159074/33529288-43ee6d20-d86f-11e7-8358-28fcda4aa238.jpg)

**Comment by Gary-Baggins** [comment]
Confirmed, please tag windows and rooms.

**Comment by Jaredsfs1** [comment]
confirmed, please remove validation, and add enhancement/accuracy @HPringles @TheStrato

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
