### ISSUE TITLE
Head bouncing through walls

### ISSUE THREAD

**Issue by winfel** [dapperrobotbear/Stage9#158]
When in the mode where the head is bouncing backwards and forwards there are a number of places where you can look through walls. You just have to go near them and then look down. Then your heard cuts through the wall and you see behind it.
<img width="1512" alt="screenshot 2017-12-04 03 13 07" src="https://user-images.githubusercontent.com/423495/33533441-6c528f08-d8a1-11e7-9b17-e24482b632d8.png">

**Comment by Gary-Baggins** [comment]
Can confirm although this is handy for making sure the turbo lift is moving, this also may be intentional by the devs for the same reason. Feedback from devs required @TheStrato @HPringles

**Comment by Gary-Baggins** [comment]
test @HPringles

**Comment by TheStrato** [comment]
@scragnog Comments?

**Comment by Jaredsfs1** [comment]
Confirmed @TheStrato @HPringles , please remove validation.  

As an addendum this occurs all the way through QA3 , and is present basically anywhere you can walk if you run into a bulkhead fast enough.

**Comment by jeppelykke** [comment]
@HPringles transferred to bugz
