### ISSUE TITLE
Main shuttle bay: Chairs too low.

### ISSUE THREAD

**Issue by winfel** [dapperrobotbear/Stage9#159]
In many places there are chairs in front of control panels. When you sit down on them you recognize some ergonomic problems. You are sitting too low to be able to control anything. The horizontal part of the controls is in the hight of your eyes.
<img width="1512" alt="screenshot 2017-12-04 03 18 05" src="https://user-images.githubusercontent.com/423495/33533554-22cd419c-d8a2-11e7-9b57-16dbd330abf1.png">

**Comment by Jaredsfs1** [comment]
@TheStrato confirmed, you can remove validation tag, but please add enhancement in it's place as this isn't really a bug, it's expected behavior, just not performing optimally. (or @HPringles )

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
