### ISSUE TITLE
Shuttlecaft name bug, and extra spawn when you fly off.

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#16]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

**Bug 1.** Both shuttles (Little one and big one) in Shuttlebay 2 are called: 'No Name'

**Bug 2.** When taking out the shuttle 'No Name' and fly around and into Main Shuttlebay, and flys back out and down to Shuttlebay 2 again, then the room resets and another Shuttlecraft 'No Name' has re spawned, and not alot of room for you to land in.

![stage9 screenshot 2017 11 25 - 22 12 35 85](https://user-images.githubusercontent.com/33987322/33234925-e879626a-d22e-11e7-998e-bd143ec6c204.png)
![stage9 screenshot 2017 11 25 - 22 06 24 63](https://user-images.githubusercontent.com/33987322/33234968-9cb7ddc4-d22f-11e7-8698-8f6bb3e86944.png)

**Comment by harryingles** [comment]
I saw this too, however when you restart the game the names SOMETIMES work

**Comment by scragnog** [comment]
Name issue is fixed now. The duplication of the shuttle can't really be solved as it's tied to the map, which means after the map has unloaded and then loads again, it creates a new shuttle. Will close for now because there won't be a fix for this in v009. Possibly v0.1.0
