### ISSUE TITLE
Switching to another bridge when not on the bridge

### ISSUE THREAD

**Issue by winfel** [dapperrobotbear/Stage9#160]
When pressing one of the buttons for the different bridge designs, when not on the bridge nothing should happen. It does though. When in the main shuttle bay, you "fall from the ceiling" to the place where you were and when in engineering you end up in outer space.

**Comment by Gary-Baggins** [comment]
additional bridges are now accessible in a holodeck simulation, please close @TheStrato @HPringles

**Comment by TheStrato** [comment]
This is a respawn issue. When you select another bridge from the menu it sounds like it is trying to respawn you at the starting location(the TL next to the bridge) and missing the mark.

**Comment by Jaredsfs1** [comment]
@TheStrato This is no longer possible as a bug in QA3 as there is no Bridge selector in the Menu anymore. The selection can only be made outside the holodeck doors.

**Comment by TheStrato** [comment]
NaB.
