### ISSUE TITLE
Crash report - Mac

### ISSUE THREAD

**Issue by tenko23** [dapperrobotbear/Stage9#162]
LoginId:09039d78d94fe6e33ed6a2b4e63982d0
EpicAccountId:

 SEGV_MAPERR at 0x3

FGenericPlatformMisc::RaiseException(unsigned int) Address = 0x10c553e9b (filename not found) [in Stage9]
FOutputDevice::Logf(wchar_t const*, ...) Address = 0x10c65256d (filename not found) [in Stage9]
FDebug::AssertFailed(char const*, char const*, int, wchar_t const*, ...) Address = 0x10c61b334 (filename not found) [in Stage9]
FShaderCache::InternalSetGraphicsPipelineState(FShaderCacheState&, FRHIGraphicsPipelineState*) Address = 0x10d4ade5f (filename not found) [in Stage9]
FMetalRHICommandContext::RHISetGraphicsPipelineState(FRHIGraphicsPipelineState*) Address = 0x10e0ec7ee (filename not found) [in Stage9]
FExecuteRHIThreadTask::DoTask(ENamedThreads::Type, TRefCountPtr<FGraphEvent> const&) Address = 0x10d4906f5 (filename not found) [in Stage9]
TGraphTask<FExecuteRHIThreadTask>::ExecuteTask(TArray<FBaseGraphTask*, FDefaultAllocator>&, ENamedThreads::Type) Address = 0x10d4904da (filename not found) [in Stage9]
FNamedTaskThread::ProcessTasksNamedThread(int, bool) Address = 0x10c55bdb7 (filename not found) [in Stage9]
FNamedTaskThread::ProcessTasksUntilQuit(int) Address = 0x10c55b868 (filename not found) [in Stage9]
FRHIThread::Run() Address = 0x10d4744f9 (filename not found) [in Stage9]
FRunnableThreadPThread::Run() Address = 0x10c57744a (filename not found) [in Stage9]
FRunnableThreadPThread::_ThreadProc(void*) Address = 0x10c564d06 (filename not found) [in Stage9]
_pthread_body Address = 0x7fff50d516c1 (filename not found) [in libsystem_pthread.dylib]
_pthread_body Address = 0x7fff50d5156d (filename not found) [in libsystem_pthread.dylib]
thread_start Address = 0x7fff50d50c5d (filename not found) [in libsystem_pthread.dylib]

**Comment by Gary-Baggins** [comment]
Feedback needed from devs, please tag mac and crash @tenko23 @HPringles

**Comment by tenko23** [comment]
It may be near the same crash report, but I just checked it and it did it again on launch:...

LoginId:09039d78d94fe6e33ed6a2b4e63982d0
EpicAccountId:

 SEGV_MAPERR at 0x3

FGenericPlatformMisc::RaiseException(unsigned int) Address = 0x1034e9e9b (filename not found) [in Stage9]
FOutputDevice::Logf(wchar_t const*, ...) Address = 0x1035e856d (filename not found) [in Stage9]
FDebug::AssertFailed(char const*, char const*, int, wchar_t const*, ...) Address = 0x1035b1334 (filename not found) [in Stage9]
FShaderCache::InternalSetGraphicsPipelineState(FShaderCacheState&, FRHIGraphicsPipelineState*) Address = 0x104443e5f (filename not found) [in Stage9]
FMetalRHICommandContext::RHISetGraphicsPipelineState(FRHIGraphicsPipelineState*) Address = 0x1050827ee (filename not found) [in Stage9]
FExecuteRHIThreadTask::DoTask(ENamedThreads::Type, TRefCountPtr<FGraphEvent> const&) Address = 0x1044266f5 (filename not found) [in Stage9]
TGraphTask<FExecuteRHIThreadTask>::ExecuteTask(TArray<FBaseGraphTask*, FDefaultAllocator>&, ENamedThreads::Type) Address = 0x1044264da (filename not found) [in Stage9]
FNamedTaskThread::ProcessTasksNamedThread(int, bool) Address = 0x1034f1db7 (filename not found) [in Stage9]
FNamedTaskThread::ProcessTasksUntilQuit(int) Address = 0x1034f1868 (filename not found) [in Stage9]
FRHIThread::Run() Address = 0x10440a4f9 (filename not found) [in Stage9]
FRunnableThreadPThread::Run() Address = 0x10350d44a (filename not found) [in Stage9]
FRunnableThreadPThread::_ThreadProc(void*) Address = 0x1034fad06 (filename not found) [in Stage9]
_pthread_body Address = 0x7fff7d6666c1 (filename not found) [in libsystem_pthread.dylib]
_pthread_body Address = 0x7fff7d66656d (filename not found) [in libsystem_pthread.dylib]
thread_start Address = 0x7fff7d665c5d (filename not found) [in libsystem_pthread.dylib]

**Comment by HPringles** [comment]
Is this in v9 or V10 QA2?

**Comment by tenko23** [comment]
v9.

**Comment by HPringles** [comment]
@TheStrato Can This be closed?

**Comment by TheStrato** [comment]
@tenko23 I will close this issue for now. If you get the same results in V10 tag me here and we will re-open the ticket.
