### ISSUE TITLE
[Visual] Missing Red Alerts in various rooms

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#163]
Windows 7 Home Premium SP1 64x
Intel Core i5-2430M CPU 2.40 GHz
8.00 GB RAM
NVIDIA GeForce GT 540M
V0.0.9 Windows Desktop

At the top of the view screen on the **battle bridge** should be an indicator for red alert.

![screen2-battlebridge1-encounteratfarpoint](https://user-images.githubusercontent.com/34159074/33546461-5894d224-d8e1-11e7-9c08-eb48511723d7.jpg)

**Comment by OssiBRI** [comment]
In main **engineering** are some missing, as well:

![er_missingred](https://user-images.githubusercontent.com/34159074/33657166-b650092c-da78-11e7-8016-e73b6a704420.jpg)

**Comment by OssiBRI** [comment]
There's one missing on the Generations bridge as well.

![missingredgenerations](https://user-images.githubusercontent.com/34159074/33809252-3fcec89a-ddf4-11e7-8c85-29b1dd4e1739.jpg)

This one actually misses on the Season 2-7 bridge, too.

**Comment by Gary-Baggins** [comment]
Red alert light above battle bridge main viewer - missing
Indicated sickbay red alert lights - missing
Indicated main engineering red alert lights - missing
Indicated Generations bridge (holodeck version) red alert lights - missing. Also the captain's chair is weirdly illuminated. https://cdn.discordapp.com/attachments/422132672178159616/423494749199269899/unknown.png
Indicated season 2 - 7 bridge red alert lights - present on both sides.  
please tag windows and accuracy @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@HPringles transferred to Bugz
