### ISSUE TITLE
[Visual] S2-7 Main Bridge|Animation goes the wrong way

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#164]
Windows 7 Home Premium SP1 64x
Intel Core i5-2430M CPU 2.40 GHz
8.00 GB RAM
NVIDIA GeForce GT 540M
V0.0.9 Windows Desktop

From Season 2 on, the blinking lights under the viewscreen go from the center to the edges.

![vs](https://user-images.githubusercontent.com/34159074/33546695-fa3ed89a-d8e1-11e7-828e-0924d5f90912.jpg)

**Comment by Gary-Baggins** [comment]
Viewscreen lights are indeed going from the centre to the edges, please close @TheStrato @HPringles

**Comment by TheStrato** [comment]
I will leave this closed as there is another chase lights ticket, but there is a difference in the direction of the light in the show near the season 2-3 area.
