### ISSUE TITLE
[Functional] Runabout disappears

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#165]
Windows 7 Home Premium SP1 64x
Intel Core i5-2430M CPU 2.40 GHz
8.00 GB RAM
NVIDIA GeForce GT 540M
V0.0.9 Windows Desktop

I tried to fly The runabout from shuttlebay one to bay two. Since there's no remote opener within the runabout, I landed the runabout directly infront of bay one, went back in and took a type 15, landed it next to the runabout and triggered the remote for bay two. 
With the main shuttlebay's door closing the runabout disappears. When you go back to the main bay it's still gone.

**Comment by tenko23** [comment]
@TheStrato
