### ISSUE TITLE
Tractorable Shuttle Bay 2 Door

### ISSUE THREAD

**Issue by cheveffect09** [dapperrobotbear/Stage9#167]
In shuttle bay 2 if you aim the right side tractor beam at the shuttle bays door it will actually register it as an object and the beam will resize to match the doors shape then when you move the tractor beam away from the door it stays  glitched  to that size until you turn it on and off again.

**Comment by OssiBRI** [comment]
Also, the tractor beam kills NPCs.

**Comment by Gary-Baggins** [comment]
Unable to test as my stupid caveman brain can't figure out how to work the tractor beam, although I would at least tag windows so that a dev or someone else can have a look @TheStrato @HPringles

**Comment by HPringles** [comment]
# Confirmed

**Comment by jeppelykke** [comment]
@HPringles transferred to bugz
