### ISSUE TITLE
[Functional] Battle Bridge|CONN inverted

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#168]
Windows 7 Home Premium SP1 64x
Intel Core i5-2430M CPU 2.40 GHz
8.00 GB RAM
NVIDIA GeForce GT 540M
V0.0.9 Windows Desktop

When you sit down at the conn on the battle bridge, the mouse movements seem to be inverted. Up ist down, left is right,... .
OPS and the other stations seem to be alright.

**Comment by jason3fc** [comment]
In addition to this I have noticed that the NPC sitting at CONN has an inverted comm badge as well.

**Comment by Gary-Baggins** [comment]
I am unable to even sit at either conn station in the battle bridge, I can however sit in the captain's chair and the station to the rear right hand side where I note the camera position is far too low, recommend leaving this open with my notes added.  Please tag windows and rooms @TheStrato @HPringles

**Comment by HPringles** [comment]
# Confirmed

**Comment by jeppelykke** [comment]
@HPringles transferred to bugz
