### ISSUE TITLE
Shuttelbay 2 doors disappear on remote open doors (inside)

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#17]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**
If you enter big Shuttle 'No Name' in shuttlebay 2, and use the in shuttle remote open shuttlebay 2 doors, then the doors disapears when opening. 

![stage9 screenshot 2017 11 25 - 21 56 50 91](https://user-images.githubusercontent.com/33987322/33234955-7b327164-d22f-11e7-8216-13fa36cb54ed.png)
![stage9 screenshot 2017 11 25 - 21 56 56 08](https://user-images.githubusercontent.com/33987322/33234956-7b492404-d22f-11e7-8a40-81f8ced93834.png)

**Comment by scragnog** [comment]
This one is unfortunate, and we won't have a solution for v0.0.9. This is a symptom of the shuttlebay matching the set and not the plans, where the flat door inside the shuttlebay goes upwards, and out of the exterior hull, so we remove it. Intention here is that the player will use the 'open shuttlebay doors' option outside the shuttle.
