### ISSUE TITLE
[Visual] Runabout: Right window is blind

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#170]
Windows 7 Home Premium SP1 64x
Intel Core i5-2430M CPU 2.40 GHz
8.00 GB RAM
NVIDIA GeForce GT 540M
V0.0.9 Windows Desktop

![missingwindow](https://user-images.githubusercontent.com/34159074/33763881-749360e2-dc12-11e7-98b3-2fa81c010fa5.jpg)

As you can see: you don't see anything outside the right (as in starboard) side window of the runabout cockpit.

**Comment by Gary-Baggins** [comment]
Confirmed (although I saw this yesterday in QA2) please tag windows and accuracy @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
