### ISSUE TITLE
Writing on containers in Cargo Elevator are mirrored

### ISSUE THREAD

**Issue by winfel** [dapperrobotbear/Stage9#171]
The writing on the containers in 02|4357 is mirrored.

<img width="1512" alt="screenshot 2017-12-08 17 34 19" src="https://user-images.githubusercontent.com/423495/33775520-f5d80000-dc3e-11e7-8a64-175bb10ac7c9.png">
<img width="1512" alt="screenshot 2017-12-08 17 34 55" src="https://user-images.githubusercontent.com/423495/33775539-ffd73c56-dc3e-11e7-9420-ffa9f842ec1d.png">

**Comment by Gary-Baggins** [comment]
No mirrored markings found, please close @TheStrato @HPringles
