### ISSUE TITLE
[Functional] Season 1 Bridge: Can't sit down

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#172]
Windows 7 Home Premium SP1 64x
Intel Core i5-2430M CPU 2.40 GHz
8.00 GB RAM
NVIDIA GeForce GT 540M
V0.0.9 Windows Desktop Release

Cannot sit down on any chair on the new Season 1 bridge.

**Comment by Gary-Baggins** [comment]
Confirmed (holodeck version) but i believe this is intentional, feedback from devs required @TheStrato @HPringles

**Comment by HPringles** [comment]
@scragnog

**Comment by TheStrato** [comment]
Sittable chairs is being worked on.

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
