### ISSUE TITLE
[Visual] Deck 8-Corridor

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#173]
Windows 7 Home Premium SP1 64x
Intel Core i5-2430M CPU 2.40 GHz
8.00 GB RAM
NVIDIA GeForce GT 540M
V0.0.9.1 Windows VR Release

When you come from the turbolifts on deck 8 and go to Picard's quarters and turn right to the forcefield instead of left to the quarters, there are wall parts missing.

**Comment by Gary-Baggins** [comment]
Duplicate/ known issue please close @TheStrato @HPringles

**Comment by HPringles** [comment]
# Duplicate
