### ISSUE TITLE
[Visual]Battle bridge view screen

### ISSUE THREAD

**Issue by Gary-Baggins** [dapperrobotbear/Stage9#174]
View screen on Battle bridge does not go all the way to the edge of the frame.
https://media.discordapp.net/attachments/335566814324981791/397765019376418816/unknown.png?width=1179&height=664

**Comment by Gary-Baggins** [comment]
Confirmed fixed, please close @TheStrato @HPringles

**Comment by TheStrato** [comment]
OP says issue is fixed. Closing this ticket.

**Comment by Gary-Baggins** [comment]
Spoke too soon, this is back in QA4.

**Comment by Gary-Baggins** [comment]
![image](https://user-images.githubusercontent.com/35035873/37555360-0f81a488-29de-11e8-9c06-1f22fc678c28.png)

**Comment by Gary-Baggins** [comment]
Fixed (again) in V10HF1 @TheStrato @HPringles

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
