### ISSUE TITLE
[function] Turbo lift despawning

### ISSUE THREAD

**Issue by Gary-Baggins** [dapperrobotbear/Stage9#175]
This is really specific but I've managed to duplicate it twice (3 times in total) so here goes.
start game obviously select warp 9 and allow the ship to arrive at DS9, then go to transporter room 1/2, exit the turbo lift and enter transporter room 2 and let the doors close behind you, then go back to the turbo lift and select arboretum and the lift will despawn.

**Comment by Gary-Baggins** [comment]
I know for a fact this is fixed as it's the very first thing I tested go ahead and close this puppy @TheStrato @HPringles

**Comment by TheStrato** [comment]
OP says issue is fixed. Closing the ticket.
