### ISSUE TITLE
VR: Grab environment elements in Main Shuttle Bay

### ISSUE THREAD

**Issue by 200h** [dapperrobotbear/Stage9#176]
Version 0.0.9.1
Windows 10 Pro
Intel i7-7700K
16 GB RAM
NVIDIA GeForce GTX 1080 Ti
HTC Vive

While in the corridor surrounding the Main Shuttle Bay, I can use the VR controllers to grip static elements, like a wall, and reposition them in game space. I found this while attempting to press a door button. Grabbed the wall instead. Was able to grab archways and a few other elements.

**Comment by 200h** [comment]
As a follow up to this, I was able to only grab anything with the left controller (or the first controller the Vive booted up with, I turn them on from left to right).

I also was able to grab all comm badges - including mine - with the same controller.

**Comment by Gary-Baggins** [comment]
Unable to test on desktop, please tag VR @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@TheStrato  Confirmed for version: VR-v0091

Random image from Deck 02. 
![20180324094750_1](https://user-images.githubusercontent.com/33987322/37862144-8d90ff3a-2f48-11e8-960f-d35db9c72605.jpg)

**Comment by dapperrobotbear** [comment]
Known issue. Test grabbing against v10 desktop, or VR when it's out.

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
