### ISSUE TITLE
Door Textures Inconsistencies

### ISSUE THREAD

**Issue by 200h** [dapperrobotbear/Stage9#177]
Specular texture direction is inconsistent from the left door to the right door. The right door has the  "brushed metal" specular running up/down while the left door has the texture running left/right. Turbolift doors and the larger doors look to have consistent up/down texture direction.

I'm guessing you'll either have to rotate your UVs or rotate the texture.

Not sure if this is by design or not. Figure I'd put that here.

**Comment by Gary-Baggins** [comment]
Needs more clear info/further testing @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
