### ISSUE TITLE
Hands seperate from body when in bodyless first person

### ISSUE THREAD

**Issue by DeputyBeagle** [dapperrobotbear/Stage9#178]
![image](https://user-images.githubusercontent.com/36313340/36050285-db4a3a2a-0ddd-11e8-8707-bd731ce176f2.png)

Windows 10
nVidia Geforce GTX 1060 6GB
All decks

**Comment by Gary-Baggins** [comment]
This is an intentional game mechanic, please close @TheStrato @HPringles

**Comment by TheStrato** [comment]
NaB. Closing.
