### ISSUE TITLE
Bounding box/hitbox on star drive impluse engine incomplete or not solid

### ISSUE THREAD

**Issue by DeputyBeagle** [dapperrobotbear/Stage9#179]
![image](https://user-images.githubusercontent.com/36313340/36065973-eb92615c-0e99-11e8-8be6-7c0b7e7d9a3c.png)

![image](https://user-images.githubusercontent.com/36313340/36065917-23acab52-0e99-11e8-82ea-4ecb4f113003.png)

Top and sides of impulse engine do not have hitboxes. Front however does have a hitbox

**Comment by Gary-Baggins** [comment]
Confirmed, please tag windows @TheStrato @HPringles

**Comment by tenko23** [comment]
@jeppelykke - Did this get moved???

**Comment by TheStrato** [comment]
Ticket was moved. Confirmed as on BugZ.
