### ISSUE TITLE
Turbolift 06 - Central Corridor (blocked invisible wall)

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#18]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**
Take the turbolift 06 to Central Corridor, when you exit the turbolift you come to hidden wall blocking your path.

![stage9 screenshot 2017 11 25 - 22 53 24 15](https://user-images.githubusercontent.com/33987322/33235428-a3ca960c-d238-11e7-96fe-e9e04d059b17.png)
![stage9 screenshot 2017 11 25 - 22 53 51 50](https://user-images.githubusercontent.com/33987322/33235381-e49c5f72-d237-11e7-8b0b-b0a18551b821.png)
![stage9 screenshot 2017 11 25 - 22 54 04 06](https://user-images.githubusercontent.com/33987322/33235382-e4b3daee-d237-11e7-83fb-30cff235e649.png)

**Comment by scragnog** [comment]
all fixed!
