### ISSUE TITLE
Windows Mixed reality headsets show distorted stereo view (Samsung Odyssey)

### ISSUE THREAD

**Issue by blunderbust** [dapperrobotbear/Stage9#180]
1. Windows 10 Home 1709, EVGA 1050 ti sc
2. 0.0.9 (VR)
3. Everywhere

It seems to stem from Unreal Engine build 4.18.  There have been some solutions posted [https://answers.unrealengine.com/questions/733962/windows-mixed-reality-steamvr-image-distorts-on-ro.html](https://answers.unrealengine.com/questions/733962/windows-mixed-reality-steamvr-image-distorts-on-ro.html)

Build 4.17 seems to work.  No verification if 4.19 has a fix for the issue.

**Comment by JoshWobbles** [comment]
Same issue, confirm this does not happen in v006 deferred renderer but does happen in the latest v0091

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz

**Comment by tenko23** [comment]
@TheStrato

**Comment by JoshWobbles** [comment]
Request reopen, issue not fixed. Will also effect Vive Pro.
