### ISSUE TITLE
Shuttles

### ISSUE THREAD

**Issue by tuvok2018** [dapperrobotbear/Stage9#181]
I've flown several shuttles out and placed them exactly to the front of the ship dead central above and below the very front when you're in contact with the hull. I left one on top of the window of the main bridge dead central also.  Upon returning to the bridge using emergency transport and looking out of the view screen the shuttles were really far away but in the middle of the view screen and the one in the top of the hull could barely be seen in through the glass at the top.  I tried changing bridges and season 2-7 the shuttles are central whereas the rest they are off to the right.  You couldn't see the shuttle anymore out of the glass except on season 2-7 and there are no stars either when travelling at warp except also on season 2-7 bridge.  The ships follow you at warp also and do not get left behind.

**Comment by TheStrato** [comment]
Several aspects of this ticket might be solved with the changes made in v10. Closing this ticket.
