### ISSUE TITLE
Win - V0010-QA1 Warp core lights not working

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#182]
The Warp Core pulsing lights do not work. The sound effect plays as normal, but neither direction works.

![image](https://user-images.githubusercontent.com/5162659/37248341-e8addd76-249d-11e8-8409-c38d783b176b.png)

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by Jaredsfs1** [comment]
confirmed on Mac QA2.

Additionally, Reaction Pulse sound does not change with ship speed.

![screen shot 2018-03-12 at 10 46 37 pm](https://user-images.githubusercontent.com/35311046/37367447-c510c930-26d9-11e8-8a1d-ea25708a6508.png)



Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by mikebarber1** [comment]
Still ocurring in QA 4

**Comment by OssiBRI** [comment]
Still there in the Windows Release.
![grafik](https://user-images.githubusercontent.com/34159074/37650067-2348f7fc-2c34-11e8-9ac1-8d55724ab5ba.png)
Althoug you can see a glimps of the animation, when you fire a phaser at the warp core.

Effects and textures are set to "epic".

**Comment by mikebarber1** [comment]
fixed in mac release hotfix

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
