### ISSUE TITLE
Win - V0010-QA1 Engerining outter Isolation door 

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#183]
When triggering the Warp Core breach sequence. The outer isolation door collision turns on before the door lowers. You get trapped in the room. Also, the button sound effect when triggering the event can be pressed over and over again.

Correct behavior is Isolation Door lowers after 5 seconds. 

Steps to recreate:

Start Warp Core Breach event.
Inner Isolation door lowers. Outer Isolation doors collision goes down at the same time. 5 seconds latter, the outer door lowers. Trapped between the doors.

**Comment by Gary-Baggins** [comment]
As soon as you trigger the event you are unable to to go through either blast door before they start to close.

**Comment by kaadaq** [comment]
Confirmed

**Comment by kaadaq** [comment]
FYI, still an issue as of QA3

**Comment by jeppelykke** [comment]
@HPringles transferred to bugz

**Comment by tenko23** [comment]
@TheStrato
