### ISSUE TITLE
Win - V0010-QA1 View screen indicators

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#184]
All the lights are triggering at the same time. 

![image](https://user-images.githubusercontent.com/5162659/37248371-d3558cfc-249e-11e8-8c99-613c91683c46.png)

**Comment by HPringles** [comment]
Duplicate @TheStrato ?

**Comment by TheStrato** [comment]
There is another accuracy ticket about the chase lights. Closing this ticket.
