### ISSUE TITLE
Win - V0010-QA1 Detacted head casts shadow

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#185]
When in none head bob mode the head casts a shadow. 
![image](https://user-images.githubusercontent.com/5162659/37248377-fa3041aa-249e-11e8-9df4-86d524286aba.png)

**Comment by kaadaq** [comment]
Also noticed this when entering Worf's quarters.

**Comment by kaadaq** [comment]
I didn't screenshot it, but at one point on the bridge there were TWO head shadows without bodies.  I think one was the tactical officer.  Was standing on the starboard ramp, facing aft engineering station.  As above, 1st person, head bob off

**Comment by HPringles** [comment]
# Confirmed Issue

Known Bug

**Comment by MrPeppow** [comment]
Can't reproduce anymore. Is fixed? @HPringles @TheStrato

**Comment by HPringles** [comment]
@scragnog

**Comment by jeppelykke** [comment]
@HPringles transferred to bugz
