### ISSUE TITLE
Win - V0010-QA1 Blowing up relay station

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#186]
When blowing up the station with a torpedo. Torpedo isn't visible. You can also keep blowing it up. 

Proper event. 

Fire Torpedo, Torpedo flies to relay. Explodes into pieces. Torpedo can't be fired again.

Reproduce Event.

Press Fire Torpedo.
Sound of Torpedo triggers. Nothing visible. Relay blows up.
Fire Torpedo again. Relay shock wave triggers again.

**Comment by HPringles** [comment]
# Confirmed Bug

**Comment by jeppelykke** [comment]
@HPringles transferred to bugz

**Comment by tenko23** [comment]
@TheStrato
