### ISSUE TITLE
Win - V0010-QA1 Corridor visible on Battle Bridge Viewscreen

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#187]
Deck 8 corridor is visible at all times on the Battle Bridge View Screen. 

Correct Behavior.

Nothing visible on the View Screen except exterior view.

![image](https://user-images.githubusercontent.com/5162659/37248429-4cdac730-24a0-11e8-8adf-6d4c1c8c266c.png)

**Comment by Gary-Baggins** [comment]
I also have seen this.

**Comment by harryingles** [comment]
Confirmed 
![desktop screenshot 2018 03 11 - 14 19 30 28](https://user-images.githubusercontent.com/16962690/37254555-50e013ca-2537-11e8-956b-004baf62e889.png)

**Comment by Jaredsfs1** [comment]
Confirmed still in QA2 on Mac.


Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz

**Comment by tenko23** [comment]
@TheStrato
