### ISSUE TITLE
Win - V0010-QA1 Deck 8 Capt. Picard's Quaters

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#188]
Coming out of Deck 8 Captain Quarters Port Turbolift. Heading left down the large corridor. The right side junction walls are missing. 

Correct Behavior.

Solid walls.

![image](https://user-images.githubusercontent.com/5162659/37248463-de7def0a-24a0-11e8-9634-97560e48a77f.png)

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by jgbr** [comment]
verified on Mac in QA2

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz

**Comment by tenko23** [comment]
@TheStrato
