### ISSUE TITLE
Win - V0010-QA1 Main Shuttlebay

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#189]
Going to Main Shuttle bay causes the game to crash (both deck 3 and 4) when going to any of the lift stops.

**Comment by TheStrato** [comment]
@archer9234 This needs a lot more information and a log file attached.

**Comment by archer9234** [comment]
I'm closing the issue. It did finally load. But it took like 3 minutes to load the deck. V9 was just a few seconds.
