### ISSUE TITLE
Turbolift button 06 - incorrect labeled

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#19]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**
Turbolift button 06 is labeled incorrectly 'Transporter room 2&3' it should be 'Transporter Room 1,2,3,4 | Science lab'

**Comment by scragnog** [comment]
adjusted now, good catch!
