### ISSUE TITLE
Win - V0010-QA1 Deck 2 Lighting

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#190]
Coming out of the Deck 2 Port Crew Quarters Turbolift. All of Deck 2's lighting is too dark.

![image](https://user-images.githubusercontent.com/5162659/37248511-3fa24528-24a2-11e8-83f9-e323425c3838.png)

**Comment by Sciencekeeper** [comment]
Confirmed seems to be a problem with the Cube Map

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by MrPeppow** [comment]
Can confirm, happens on Linux QA1 on Deck 2, 6, 7, 9, 10, 12 and 13

**Comment by scragnog** [comment]
lowering cubemap intensity made these corridors darker. added some pointlights in, problem solved!

**Comment by jeppelykke** [comment]
Confirmed fixed for: Win - V0010-GM1

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
