### ISSUE TITLE
Win - V0010-QA1 Deck 7 Arboretum

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#192]
Entire Deck 7 Arboretum lighting is too dark. 

![image](https://user-images.githubusercontent.com/5162659/37248578-9aedae30-24a3-11e8-8412-bafbe29afc87.png)

**Comment by HPringles** [comment]
# Confirmed Issue

The deck is very dark, as archer said

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz

**Comment by tenko23** [comment]
@TheStrato
