### ISSUE TITLE
Win - V0010-QA1 Steller Cartogrophy

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#193]
The Cartography screen graphics are not visible. Just a bright light is visible. 

What is the expected correct behavior?

The Star field map texture.

![image](https://user-images.githubusercontent.com/5162659/37248587-f7513d04-24a3-11e8-8543-ba1b16a1566a.png)

**Comment by kaadaq** [comment]
Replicated here -- I'm blinded out anytime I'm facing away from the door

**Comment by HPringles** [comment]
# Confirmed Issue

***Screenshot***

![desktop screenshot 2018 03 11 - 16 45 22 74](https://user-images.githubusercontent.com/16962690/37256299-73f30822-2550-11e8-909a-1415c21d4ede.png)

This image is taken from just outside the bulkhead doors, whilst they are open

**Comment by jgbr** [comment]
On Mac too, blinded as you walk in, never redraws. if you sneak up to the door you see a blank empty space and the other deck map running around it

**Comment by Jaredsfs1** [comment]
Confirmed still in QA2 on Mac.  it's crazy bright...

![screen shot 2018-03-12 at 10 35 21 pm](https://user-images.githubusercontent.com/35311046/37370110-8f56cdf0-26e1-11e8-9469-cf154e67031e.png)


Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz

**Comment by tenko23** [comment]
@TheStrato
