### ISSUE TITLE
V0010-QA1 - Crash when accessing Emer. Turbolift (not reproducible)

### ISSUE THREAD

**Issue by EazyCheeze1978** [dapperrobotbear/Stage9#194]
**Summary**

Entry onto the Emergency Turbolift on Deck 1 Bridge causes crash.

***What is the expected correct behavior?***

Possible further movement and the ability to proceed to the Battle Bridge if such a redirect is programmed yet.

**Steps to reproduce (not reproducible, it turns out! These are the steps I took)**

1. Go to deck 1 from the transporter, dodging lots of NPCs on the way blocking the way to the 'lift
2. Find that the Show NPCs checkbox state doesn't persist between decks, nor does it actually remove them (I still can't get past them)
3. Go to the Ready Room and order some Tea, Earl Grey, Hot
4. Move to the Emergency Turbolift and enter
5. crash!

[UE4CC-Windows-62BBDB064831D12616A3ABA5CAB02A6B_0000.zip](https://github.com/dapperrobotbear/Stage9/files/1799960/UE4CC-Windows-62BBDB064831D12616A3ABA5CAB02A6B_0000.zip)

**Comment by jeppelykke** [comment]
@HPringles Transferred  to bugz

**Comment by tenko23** [comment]
@TheStrato
