### ISSUE TITLE
Win - V0010-QA1 Nine Forward

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#195]
Exterior corridor is intersecting the 9 Forward windows. 

What you should see instead

The corridor should lead to another rec room.

![image](https://user-images.githubusercontent.com/5162659/37248597-55678e66-24a4-11e8-81a6-d59bc427f2e1.png)

Spline numbers are on outside the room too.

![image](https://user-images.githubusercontent.com/5162659/37248599-6b16f42c-24a4-11e8-854c-b0fa2de3ca93.png)

These doors/walls are hollow. You can fall out the map. 

![image](https://user-images.githubusercontent.com/5162659/37248609-c3f2f4ba-24a4-11e8-82ed-717656984913.png)

There are six Turbolift stops visible on Deck 9 that do not work and display numbers.

 What you should see instead

These stops shouldn't be avaible.

![image](https://user-images.githubusercontent.com/5162659/37249712-9751851e-24ba-11e8-9176-cab12fde68a2.png)

**Comment by TheStrato** [comment]
@archer9234 This needs a lot more information and a log file attached.

**Comment by jeppelykke** [comment]
Floor outside Nine Forward is flashing 
![stage9 screenshot 2018 03 11 - 13 48 48 52](https://user-images.githubusercontent.com/33987322/37253605-33b4cafa-2534-11e8-8220-55b7c63ffeed.png)

**Comment by jeppelykke** [comment]
@TheStrato I have the same  numbers on my turbolift control panel, what log file do you need to see ?

**Comment by TheStrato** [comment]
Any crash files will be found in <user>\AppData\local\Stage9\Saved\Crashes. Just zip up the last folder in the Crashes folder and attach it when you need to send your log file with a report.

**Comment by kaadaq** [comment]
Last issue (Coordinate-based TL stops on the TL panel for Deck 9) is reconfirmed in QA4

**Comment by jeppelykke** [comment]
No-longer valid... Fixed in HF1
