### ISSUE TITLE
Win - V0010-QA1 10 Foward

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#196]
One forcefield is the old version. 

![image](https://user-images.githubusercontent.com/5162659/37248640-97a454d4-24a5-11e8-8c5b-0b52be0a7e9d.png)

**Comment by jeppelykke** [comment]
On the left entrance to Ten Forward is a wall miss alignment. 

![stage9 screenshot 2018 03 11 - 13 31 43 65](https://user-images.githubusercontent.com/33987322/37253343-db2aa998-2530-11e8-9d0d-0ceabb3d33ee.png)

**Comment by HPringles** [comment]
# All issues Confirmed

**Comment by jeppelykke** [comment]
No-longer valid
