### ISSUE TITLE
Win - V0010-QA1 TOS Bridge Viewscreen

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#197]
Blank only displaying white.

![image](https://user-images.githubusercontent.com/5162659/37248692-b8052630-24a6-11e8-8c61-2842b8ed7d1d.png)

**Comment by HPringles** [comment]
# Confirmed Issue

***Seems to be related to the stellar cartography issue #193 ***

**Comment by Gary-Baggins** [comment]
Confirmed.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz

**Comment by tenko23** [comment]
@TheStrato
