### ISSUE TITLE
V0010-QA1 - Malformed Deck 8 corridor

### ISSUE THREAD

**Issue by EazyCheeze1978** [dapperrobotbear/Stage9#198]
**Summary**

Encountered the deck 8 corridor, with missing walls

***What is the expected correct behavior?***

Not to see open space in this area of the ship

**Steps to reproduce**

1. Go to the Bridge, and warp to Earth (the Enterprise now being in the Spacedock)
2. Warp to the Arboretum (one may pop right out of the ship!)
3. Warp to Deck 8 (ditto)
4. Turn right from the Turbolift corridor
5. There it is!

**Relevant logs and/or screenshots**

![stage9-win64-shipping screenshot 2018 03 10 - 20 03 11 46](https://user-images.githubusercontent.com/37255420/37248741-ec508cb6-249e-11e8-9c75-87a64d230d1d.png)

**Possible fixes**

Go directly to Deck 8 without warping to another location from the Bridge first?

**Comment by Verox-** [comment]
Does this only happen if you warp first?

**Comment by EazyCheeze1978** [comment]
Nope, it happens whether or not I warped. I am seeing the initial system's nebula through the walls now in fact.

**Comment by OssiBRI** [comment]
It might be the same error, like [this one](https://github.com/dapperrobotbear/Stage9/issues/173) in the V9 Windows VR version.

**Comment by harryingles** [comment]
Also confirmed - not warped yet 
![desktop screenshot 2018 03 11 - 14 22 25 82](https://user-images.githubusercontent.com/16962690/37254601-dd4d00ca-2537-11e8-9c02-a5a13de77bcc.png)

**Comment by Jaredsfs1** [comment]
Confirmed on Mac in QA2, also, does not require warp first:

![screen shot 2018-03-12 at 10 21 10 pm](https://user-images.githubusercontent.com/35311046/37361279-e747a110-26c8-11e8-98e9-904ade84fd0e.png)
![screen shot 2018-03-12 at 10 21 25 pm](https://user-images.githubusercontent.com/35311046/37361280-e7541af8-26c8-11e8-860b-2430805f7552.png)

Found to starboard of Captain's Quarters.


Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by MrPeppow** [comment]
Can confirm on Linux QA1
![screenshot_20180314_121644](https://user-images.githubusercontent.com/13747941/37400025-cb89d43c-2783-11e8-847f-f79194d4aa5b.jpeg)

**Comment by MrPeppow** [comment]
Seems fixed in HF1. @HPringles @HPringles

**Comment by jeppelykke** [comment]
@HPringles No Longer valid

**Comment by tenko23** [comment]
@TheStrato

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
