### ISSUE TITLE
Start Menu- Show NPCs unchecked, when game is loaded, NPCs are on.

### ISSUE THREAD

**Issue by Cacille** [dapperrobotbear/Stage9#2]
Start game menu. Game tab, Show NPC's. I uncheck it. 
I then apply, save, and exit. 
Load game, enter bridge. NPCs are on.
Check settings - Show NPCs is Checked. 

Bug first alerted by Anna on Youtube and confirmed by JimVR Youtuber. https://www.youtube.com/watch?v=zk6VcNipCFc

Confirmed by Cacille. Standard Desktop, not VR.

**Comment by metaphim428** [comment]
Yes, currently this is a known issue. We are hoping to have this fixed soon.
