### ISSUE TITLE
Transporter room - Deck 6 Room 7535 incorrect lable

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#20]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

Transporter room on Deck 6 Room 7535 should be Transporter Room 1, and not 3 as that is labeled on: Deck 6 Room 2960 as where it belongs.

**Comment by scragnog** [comment]
Another one well spotted! Thanks
