### ISSUE TITLE
V0010-QA1 - Engineering has no ceiling! - fixed, but now there's a gap between wall and ceiling.

### ISSUE THREAD

**Issue by EazyCheeze1978** [dapperrobotbear/Stage9#200]
**Summary**

Upon arriving in Engineering, I find it has no ceiling; the warp core is sticking up into the skybox.

***What is the expected correct behavior?***

Not to see open space in this area of the ship.

**Steps to reproduce**

4. Go to Engineering (after going to Deck 8 and several other locations on board) and look up 
5. There it is!

**Relevant logs and/or screenshots**

![stage9-win64-shipping screenshot 2018 03 10 - 20 31 16 97](https://user-images.githubusercontent.com/37255420/37248906-6bbb2daa-24a2-11e8-82d3-95d776c7c81a.png)

**Comment by HPringles** [comment]
# Confirmed Issue

Also reported by a number of other testers

**Comment by jgbr** [comment]
On Mac too.

**Comment by dapperrobotbear** [comment]
Reconfirm in QA2

**Comment by EazyCheeze1978** [comment]
@TheStrato Verified fixed in QA2!

**Comment by nkjellman** [comment]
@TheStrato Verified as fixed however the ceiling is slightly too high. There is a crack along the wall where space is visible.

**Comment by TheStrato** [comment]
Reopened in light of new information for @dapperrobotbear

**Comment by dapperrobotbear** [comment]
Please attach a screenshot of where the gap is that is clearly identifiable. Thanks.

**Comment by TheStrato** [comment]
@dapperrobotbear Pretty sure Scrag fixed this one already. Will close for now.
