### ISSUE TITLE
Win -V0010-QA1 Room 06-8044 Does not spawn 

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#201]
Summary

Room 06-8044 open up to exterior space (room does not spawn)

Steps to Reproduce
1. Approach door 06-8044 (Adjacent to forcefield, three lefts from Transporter Rooms 1 & 2)
2. Door opens to open space
3. Back up and door closes, reapproach and door opens to space again

![image](https://user-images.githubusercontent.com/34050343/37248965-a8f58e32-24ab-11e8-8575-97359604757d.png)

**Comment by kaadaq** [comment]
May be related to texture quality.  tried again today with epic texture and it spawned ok

**Comment by dapperrobotbear** [comment]
Reconfirm in QA2

**Comment by Gary-Baggins** [comment]
Confirmed fixed @TheStrato please close.

**Comment by TheStrato** [comment]
Fixed by Dapper, confirmed by Gary. Closing this ticket.
