### ISSUE TITLE
Win V0010-QA1 Incomplete Mesh in Worf's Bedroom

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#203]
Summary

Wall panels do not join up in Worf's bedroom.  Light from the corridor beyond is visible.

Steps to reproduce
1. Enter Worf's Quarters on Deck 2
2. Enter bedroom area and approach wall near chair.

Screenshot:
![image](https://user-images.githubusercontent.com/34050343/37249163-153cbfe4-24b0-11e8-897e-8eea8971e44c.png)

**Comment by jeppelykke** [comment]
Also notice a floor issue at the entrance to the room
![stage9 screenshot 2018 03 11 - 11 24 02 81](https://user-images.githubusercontent.com/33987322/37252768-6d1edbb2-2527-11e8-9768-b3666d4e7a82.png)

**Comment by dapperrobotbear** [comment]
Can't fix the carpet at the moment, but fixed the wall piece. Reconfirm in QA2

**Comment by EazyCheeze1978** [comment]
QA2: Kaadaq's issue is fixed, but as per Bear's comment, carpet near the door is not.

**Comment by Gary-Baggins** [comment]
Confirmed fixed @TheStrato please close.

**Comment by TheStrato** [comment]
Fixed by Dapper, confirmed by Gary. Closing this ticket.
