### ISSUE TITLE
Win - V0010-QA1 - Certain rooms do not unload

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#204]
**Summary**

When you visit certain rooms, they remain loaded. Two I found are the transporter rooms, and the holodecks (not the programs).

***What is the expected correct behavior?***

These rooms should be unloaded for performance.

**Steps to reproduce**

1. Simply visit the room, and it will remain loaded.

**Relevant logs and/or screenshots**
![2018-03-10 3](https://user-images.githubusercontent.com/29221029/37249200-a617f2f2-24a8-11e8-994e-f002867d8e7c.png)
I know that this is the ship loading bug, but it gives you a good idea of what is going on. The holodecks do not show up till you visit them. You do not have to run a program.

**Comment by Gary-Baggins** [comment]
Confirmed. Transporter room 2 and shuttle bay 2 do not unload.

**Comment by dapperrobotbear** [comment]
Fixed in QA2. Please test again once that's released

**Comment by TheStrato** [comment]
Fixed by Dapper, confirmed by Gary. Closing this ticket.
