### ISSUE TITLE
Win - V0010-QA1 - Holodeck Door Controls

### ISSUE THREAD

**Issue by cheveffect09** [dapperrobotbear/Stage9#205]
**Summary**
While in the Holodeck if you keep repetitively pressing Q to open and close the door quickly it will constantly flicker between animations. 

***What is the expected correct behavior?***
You should only be able to call for the door once it is completely vanished then close it once it has completely reappeared any action between the animations of it reappearing and vanishing should be disabled.

**Steps to reproduce**

1. Go To any Holodeck
2. Keep pressing Q to open and close the main Holodeck door as fast as  you can.

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by scragnog** [comment]
this is now on a 'do once' node, with a flipflop and a reset event. Fancy that! FIXED! BOOM HEADSHOT!

**Comment by Gary-Baggins** [comment]
Door only re-appears one the animation is finished and visa-versa when spamming Q as it should @TheStrato @HPringles

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
