### ISSUE TITLE
Win - V0010-QA1 NPC's Spawn even if setting is off

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#206]
Summary
NPC's will spawn on a new deck even when the setting for NPC's is off.

Desired Behavior:
NPC's are not spawned when setting is off in menu.

Steps to Reproduce:
1. Turn off NPC's in context menu.  Click "OK".
2. Tack turbolift to a new deck
3. New spawned rooms will have NPC's in them.

Screenshot:
![image](https://user-images.githubusercontent.com/34050343/37249737-02505f52-24bb-11e8-88c0-b583aa863b98.png)

**Comment by kaadaq** [comment]
Checking and unchecking the box will make them despawn.   However, sitting in a chair and then standing will make them respawn, even if setting is off.

**Comment by dapperrobotbear** [comment]
Check in QA2

**Comment by Gary-Baggins** [comment]
Confirmed fixed @TheStrato please close. although on the main bridge they spawn for a split second then disappear.

**Comment by Gary-Baggins** [comment]
Marked this as confirmed earlier but I just visited the nacelle control room and was greeted by an npc.

**Comment by HPringles** [comment]
# Confirmed Fixed 

Same issue with female NPCs as #279 

@TheStrato I'd just close this one

**Comment by TheStrato** [comment]
Issues that will be fixed with other things. Closing this ticket.
