### ISSUE TITLE
Win - V0010-QA1 Type 3 Phaser

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#207]
The Type 3 Phaser beam effect bends towards the direction the mouse points. Spinning around will cause the rifle to go sideways.

What you should see instead

Beam should stay straight with the model

Steps to reproduce

Body-less Mode.
Fire the gun and aim with mouse.
Spin around fast to cause rifle to go sideways.

![image](https://user-images.githubusercontent.com/5162659/37249754-858b9eea-24bb-11e8-87d5-723803927b1a.png)

![image](https://user-images.githubusercontent.com/5162659/37249745-3603c834-24bb-11e8-8a84-9d16b85b3b7f.png)

**Comment by dapperrobotbear** [comment]
Known issue. Our aim offsets are whacky. Try different head bob modes.

**Comment by JonathanNStewart** [comment]
An additional related issue is that the red aiming dot finds the surface closest to the player, including their hands/arms, as seen in the top figure. Not only should the dot be where the phaser is firing, but it should also ignore the player's body.

**Comment by MrPeppow** [comment]
Can confirm on Linux @HPringles 
![screenshot_20180315_231747](https://user-images.githubusercontent.com/13747941/37494061-9409e3b0-28a7-11e8-8a51-4268f0f54dbb.jpeg)
Continous shooting and shaking the mouse does this pretty reliably

**Comment by dapperrobotbear** [comment]
:( yea. Aim offsets.

**Comment by scragnog** [comment]
I've made a few tweaks for now. But phasers still aim in strange directions. Until we rebuild the way these aim offsets work, there's not a lot we can do, at least not for v10. Marking as complete for now.

**Comment by TheStrato** [comment]
Closing the ticket. More work will be done later on this issue.
