### ISSUE TITLE
Win - V0010-QA1 Holodeck Program Main Bridge 2364 Doors

### ISSUE THREAD

**Issue by cheveffect09** [dapperrobotbear/Stage9#208]
**Summary**

While in the Holodeck and running the U.S.S. Enterprise NCC-1701-D Main Bridge (2364) program all doors on the bridge open and you can fall through them and back down on to the top of deck 12 where the holodecks are and can walk along them top side.

***What is the expected correct behavior?***

All doors on the holodeck version of the 2364 bridge should not open while the program is running this would prevent the player from being able to fall through. 

**Steps to reproduce**

1. Go to either holodeck on deck 12 and run the Main Bridge (2364) program
2. Walk up to any of the doors and they will open.
3. If you go to the upper turbo lift door you can land on top of the outside of the holodeck corridor 

**Relevant logs and/or screenshots**

![desktop screenshot 2018 03 11 - 15 31 24 79](https://user-images.githubusercontent.com/5516753/37249792-49be7518-2542-11e8-82d9-9e96a8303485.png)
![desktop screenshot 2018 03 11 - 15 31 48 52](https://user-images.githubusercontent.com/5516753/37249803-97f136a8-2542-11e8-90a3-88434470e1f2.png)
![desktop screenshot 2018 03 11 - 15 31 58 78](https://user-images.githubusercontent.com/5516753/37249804-983c0de0-2542-11e8-8726-ce35d941133a.png)
![desktop screenshot 2018 03 11 - 15 32 00 88](https://user-images.githubusercontent.com/5516753/37249805-986fbdc0-2542-11e8-959d-8027c3f158dc.png)

**Comment by nkjellman** [comment]
To add to this, the 2364 bridge's audio can be heard from outside the program, and in another holodeck.

**Comment by harryingles** [comment]
Same issue here

**Comment by trekkeriii** [comment]
Also, I would like to note, that when you load the 2264 bridge, the color/graphics quality of the Corridor outside the bridge changes. Goes back to normal when you load another bridge.

**Comment by dapperrobotbear** [comment]
All the doors should locked.

**Comment by dapperrobotbear** [comment]
Confirm in QA2

**Comment by Gary-Baggins** [comment]
Confirmed fixed @TheStrato please close.

**Comment by TheStrato** [comment]
Fixed by Dapper, confirmed by Gary. Closing this ticket.
