### ISSUE TITLE
Win - V0010-QA1 - Map errors on upper level of main shuttlebay

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#209]
**Summary**
There are several mistakes in the upper level of the main shuttle bay corridors.

**Relevant logs and/or screenshots** Since both GitHub, Imgur, and Discord have a 10 MB limit so people who still have Dial-up in 2018 can use their service, I can't upload any of my screens.
-A double wall issue near the control room.
-Old force field by the stairs.
-The front left and front right corners of the corridor have a wall missing as well as z-fighting on the floor.

![2018-03-11](https://user-images.githubusercontent.com/29221029/37251334-2c57db1a-24dc-11e8-9fa9-c342a16ea277.jpg)
![2018-03-11 1](https://user-images.githubusercontent.com/29221029/37251335-2c657a40-24dc-11e8-85b7-2bba7fb1d276.jpg)
![2018-03-11 2](https://user-images.githubusercontent.com/29221029/37251336-2c72fe7c-24dc-11e8-840c-10f2557975c4.jpg)
![2018-03-11 3](https://user-images.githubusercontent.com/29221029/37251337-2c8011ac-24dc-11e8-9a9f-1b01a09fd69c.jpg)
![2018-03-11 4](https://user-images.githubusercontent.com/29221029/37251338-2c8c8694-24dc-11e8-806a-37f7069d2ada.jpg)

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by kaadaq** [comment]
I also encountered something similar on the upper level observation windows near the runabout:
![image](https://user-images.githubusercontent.com/34050343/37258711-134a0e88-2552-11e8-8d36-23700630b480.png)

The door is 03:8485

**Comment by HPringles** [comment]
***Confirmed***

**Comment by dapperrobotbear** [comment]
Bug with QA1, please re-test in QA2

**Comment by HPringles** [comment]
# Not Fixed

@TheStrato Please close this and #237

**Comment by TheStrato** [comment]
Not fixed, re-assigned.

**Comment by kaadaq** [comment]
The one I reported near 03:8485 (bottom screenshot) is fixed in QA2, including the floor

**Comment by dapperrobotbear** [comment]
Please confirm against QA3

**Comment by HPringles** [comment]
# Partial Fix

Previously mentioned bugs are fixed

New wall has disappeared
![desktop screenshot 2018 03 14 - 22 26 22 17](https://user-images.githubusercontent.com/16962690/37434320-1c0deec2-27d7-11e8-8b74-4d1d33f142fc.png)

**Comment by dapperrobotbear** [comment]
These walls should return in QA4

**Comment by Sciencekeeper** [comment]
@TheStrato i can't find any missing walls on Deck 3 and 4 anymore

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
