### ISSUE TITLE
height issue Sitting in Ten Forward Barstool

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#21]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**
Height issue Sitting on the Barstool in Ten Forward, your lower then the NPCs.

![stage9 screenshot 2017 11 25 - 23 12 11 11](https://user-images.githubusercontent.com/33987322/33235442-cb5c6bb4-d238-11e7-807a-c5e04c8610cf.png)

**Comment by scragnog** [comment]
fixed now
