### ISSUE TITLE
Win - V0010-QA1 - Main Shuttle bay Super Lag Spikes

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#211]
**Summary**

From the point where you select the main shuttle bay, till you leave the main shuttle bay, there are crazy lag spikes. In the turbolift, the game will appear frozen for like 30 seconds.

If you attempt to minimize the game while it is frozen in the turbolift, as soon as the freeze ends, it will minimize. After that, the main shuttle bay is playable when you go back in. If you do not minimize during the turbolift freeze, you will get these constant lag spikes where it will be smooth for a second, with a lag every other second. This will continue till you leave the main shuttle bay. If you minimize the game after you reach the main shuttle bay, the lag spikes will continue.

***What is the expected correct behavior?***

No turbolift freeze, and no lag spikes.

**Steps to reproduce**

1. Go to the main shuttle bay and you will see the game freeze right after the lift begins moving.
2. To see the lag spikes while in the main shuttle bay, don't minimize the game. To not have lag spikes, minimize the game while the game appears frozen in the turbolift.

**Comment by harryingles** [comment]
Confirmed issue - Fixed partially by reducing gfx quality to low - not ideal though

**Comment by trekkeriii** [comment]
I can confirm this. Not consistent. Usually if I got to Main Shuttlebay initially, it's fine, but if I am in the game for a while, then go to Main Shuttlebay, I need to restart the game to efficiently navigate the Main Shuttlebay.

**Comment by dapperrobotbear** [comment]
We had duplicate objects in maps that were added at the last moment. Re-test with QA2.

**Comment by Jaredsfs1** [comment]
This is definitely far far better in QA2.  I was getting huge lag when facing the starboard half of the bay in QA1.  It's almost as smooth as V09 at this point (but looks way better thanks to the reflections).


Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by MrPeppow** [comment]
Can confirm for Linux HF1

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
