### ISSUE TITLE
Win - V0010-QA1 - Runabout collides with force field.

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#212]
**Summary**

When you fly the Runabout out of the main shuttle bay, it seems to get stuck on the force field. Judging on where it gets stuck, I don't think it is the Runabout that is the problem. I think it is the player colliding with the force field.

Edit: It seems that sometimes when you ram into the force field, the game can crash.

***What is the expected correct behavior?***

The Runabout should fly through the force field.

**Steps to reproduce**

1. Fly the Runabout towards the force field
2. To actually get the Runabout in and out of the shuttle bay, you practically have to fly at the force field sideways Tokyo Drift style. :D

**Relevant logs and/or screenshots**

![2018-03-11 19](https://user-images.githubusercontent.com/29221029/37251462-8de05202-24de-11e8-9bc0-e7fb20743a16.jpg)

**Possible fixes**

This issue doesn't happen in the mid size shuttle. I think its the player that is colliding biased on where the Runabout gets stuck.

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by trekkeriii** [comment]
I can confirm this as well.

**Comment by dapperrobotbear** [comment]
Confirmed one of the meshes wasn't set to be a vehicle and was colliding with the shield. Confirm in QA2

**Comment by Gary-Baggins** [comment]
Confirmed fixed @TheStrato please close.

**Comment by TheStrato** [comment]
Fixed by Dapper, confirmed by Gary. Closing this ticket.
