### ISSUE TITLE
Win - V0010-QA1 - NPC just get invisible and do not despawn

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#214]
**Summary**

If there is a bunch of NPCs standing in your way and you turn off the NPCs Setting they become invisible. But they are still there somehow. Doors open and close because they still walk araound and they still stand in your way...

***What is the expected correct behavior?***

No NPCs Setting should despawn the NPCs

**Steps to reproduce**

1. leave Transporter Room
2. follow Hallway around the Ship
3. there is a bunch of NPCs blocking your way
4. Turn of NPSc

**Relevant logs and/or screenshots**

Well a Screenshot from invisible NPCs is not that easy :-)

**Possible fixes**

**Comment by mikebarber1** [comment]
You can see the shadow of the invisible NPC's on some of the bulkheads

**Comment by harryingles** [comment]
# Confirmed Issue

**Comment by Gary-Baggins** [comment]
Confirmed.

**Comment by dapperrobotbear** [comment]
Check in QA2

**Comment by EazyCheeze1978** [comment]
@TheStrato fixed in QA2! Ghost ship going on here in Deck 2...

**Comment by dapperrobotbear** [comment]
Please close your issues if they're fixed. Thanks. 😄
