### ISSUE TITLE
Win - V0010-QA1 - Deck 4 Main Shuttle Bay - You can run through a piece of a Wall

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#215]
**Summary**

A peace of the Wall in Main Shuttle bay is only visible, but you can run through and fall of the Ship.

***What is the expected correct behavior?***

Well you should not be able to run through a wall

**Steps to reproduce**

1. Just walk right in

**Relevant logs and/or screenshots**

![wallisuedeck4](https://user-images.githubusercontent.com/33996890/37251906-b68fcf9a-2518-11e8-8afb-f288b40a3ebe.jpg)

**Possible fixes**
Im sure its just a change in the settings

**Comment by HPringles** [comment]
# Confirmed Issue

***Further Testing***

Confirmed to be the border/surround section of door 2325 - labelled as a crew lounge

***Screenshot***

![desktop screenshot 2018 03 11 - 17 17 41 100](https://user-images.githubusercontent.com/16962690/37256284-49bdf990-2550-11e8-9a9f-66afb93d0b4b.png)
![Uploading Desktop Screenshot 2018.03.11 - 17.17.46.93.png…]()

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
