### ISSUE TITLE
Win - V0010-QA1 - Deck 01 | Bow turbolift ride to main bridge aft throws you into space

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#216]
**Summary**
Taking the Bow turbolift from main bridge, to Aft bridge, throws you out of the turbolift into space.

***What is the expected correct behavior?***
Turbolift takes you to the aft section of the main bridge.

**Steps to reproduce**
1. Enter Bow Turbolift next to captain picards readyroom.
2. Take choose to goto Main Bridge AFT section.
3. Enjoy the view from space, as turbolift leaves you behind.

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 11 - 10 59 15 73](https://user-images.githubusercontent.com/33987322/37252471-6f223522-2521-11e8-90ba-7503999a48b4.png)
![stage9 screenshot 2018 03 11 - 10 59 24 06](https://user-images.githubusercontent.com/33987322/37252470-6c3d8a8c-2521-11e8-852e-400b7571f09d.png)

**Comment by HPringles** [comment]
# Partially Confirmed Issue

***Further Testing***

It seems as if these turbolift 'flings' are somewhat random and can be observed from many different lifts on many different journeys

**Comment by dapperrobotbear** [comment]
Confirm in QA2

**Comment by Gary-Baggins** [comment]
Confirmed fixed @TheStrato please close.
