### ISSUE TITLE
Win - V0010-QA1 - Deck 02  Multi door gaps and wall issues

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#217]
**Summary**
Took a walked around Deck 02, and noticed a few issues here and there... 

***What is the expected correct behavior?***
That there no space gab between the floor and doors. 
That the walls are not "mirrored/flipped" 

**Steps to reproduce**
1. Goto deck 02 Rooms: 4496,4075,4007,4486,6898,6926,6811,2920,5596,5647,6204
2. watch the gab in floor between hallway and door.

**Relevant logs and/or screenshots**

![stage9 screenshot 2018 03 11 - 11 12 57 16](https://user-images.githubusercontent.com/33987322/37252598-d40f3122-2523-11e8-8c54-91c27acbcfd0.png)

**Steps to reproduce**
3. Goto deck 02 rooms: 6797,6913,6887,6619 
4. Take a look at the walls it seems they "flipped/mirrored" so the red text is facing left instead of the on the right side for the wall panel.

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 11 - 11 31 05 54](https://user-images.githubusercontent.com/33987322/37252615-1b034dfc-2524-11e8-9932-f068f5708e2a.png)

**Comment by HPringles** [comment]
# Confirmed Issue

***Both Issues confirmed****

***Screenshot***

![desktop screenshot 2018 03 11 - 17 26 17 98](https://user-images.githubusercontent.com/16962690/37256362-69692070-2551-11e8-9cad-7298f3e3a22d.png)
This gives a better view of the second issue

**Comment by dapperrobotbear** [comment]
Oooh, that's a new one.

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
