### ISSUE TITLE
Win - V0010-QA1 - PC Version is forceing my SteamVR to boot up!

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#218]
**Summary**
When starting the game, Steam is booting up my VR headsets. 

***What is the expected correct behavior?***
That the PC only version do not require to boot up my VR headset.

**Steps to reproduce**
1. Turn off VR in steam as you not using it. 
2. Start up the game.
3. Watch as steam start up Steam VR

**Possible fixes**

**Comment by dapperrobotbear** [comment]
This is a build thing. Optimally we'd have a single binary that could be desktop or VR….but not sure how to get this to prefer one over the other. Until then I suggest just unplugging your headset's power or USB to prevent it from booting up.

**Comment by TheStrato** [comment]
A fix was given. Closing the ticket.
