### ISSUE TITLE
Win - 0010-QA1 - Body of Enterprise fails to warp to Earth causing player to drop out of turbolift, able to watch it move through space to the disembodied corridor

### ISSUE THREAD

**Issue by EazyCheeze1978** [dapperrobotbear/Stage9#219]
**Summary**

I warped to Earth using the helm console, then went to various places around the ship; after the first I started popping out of the turbolift and hanging in space.

***What is the expected correct behavior?***

I should stay in the turbolift until I reach my destination and never see space.

**Steps to reproduce**

1. Go to the Bridge, and warp to Earth
2. Go to Deck 2, and visit Data's and Worf's quarters; no ill effects so far...
3. Go to Deck 8 - This is where the pop-out first occurs, about halfway along the journey. (used the emergency transport to turbolift to be able to get back in the deck. The missing walls I reporter earlier still occur.)
4. Go to Deck 12, the sickbay - the pop-out occurs immediately, and this time I'm able to get great shots of the 'lift in motion and arrived at its destination!

**Relevant logs and/or screenshots**

<img width="960" alt="2018-03-11 05_38_34-greenshot" src="https://user-images.githubusercontent.com/37255420/37252519-3bd9d480-24f0-11e8-9604-b0b0bf9410f5.png">
<img width="960" alt="2018-03-11 05_41_16-greenshot" src="https://user-images.githubusercontent.com/37255420/37252520-3beaf2b0-24f0-11e8-9c25-99f62be83d05.png">
<img width="960" alt="2018-03-11 05_41_45-greenshot" src="https://user-images.githubusercontent.com/37255420/37252521-3bfbcd1a-24f0-11e8-839e-736ebc5914ee.png">

**Comment by Gary-Baggins** [comment]
Confirmed this happened to me whilst warping from Mars to Earth.

**Comment by dapperrobotbear** [comment]
Reconfirm in QA2

**Comment by Gary-Baggins** [comment]
Confirmed fixed @TheStrato please close.

**Comment by TheStrato** [comment]
Fixed by Dapper, confirmed by Gary. Closing this ticket.
