### ISSUE TITLE
Deck 02 Room 4357 Cargo Elevator, on console menu is mirrored!

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#22]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**
Deck 02 Room 4357 Cargo Elevators, the menu console is mirrored. 

![stage9 screenshot 2017 11 25 - 23 18 48 47](https://user-images.githubusercontent.com/33987322/33235461-0639a530-d239-11e7-9768-bf4adcf15010.png)

**Comment by scragnog** [comment]
fixed!
