### ISSUE TITLE
Win - V0010-QA1 - You can reach the end of the skybox

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#220]
**Summary**

If you keep on flying the Enterprise in one direction, eventually you will reach the sky dome. On a side note, when the space dome collides with the ship, it reminds me of when Dr. Crusher was caught in the shrinking warp bubble universe.

***What is the expected correct behavior?***

The sky dome needs to follow you. 

**Steps to reproduce**

1. Fly the ship in any direction and you will reach the edge.

**Relevant logs and/or screenshots**

![2018-03-11 30](https://user-images.githubusercontent.com/29221029/37252540-8567767a-24f0-11e8-8ec3-5c6c7d085e2a.jpg)
![2018-03-11 23](https://user-images.githubusercontent.com/29221029/37252541-8575b104-24f0-11e8-9852-cdb233bbde15.jpg)
![2018-03-11 24](https://user-images.githubusercontent.com/29221029/37252542-858393dc-24f0-11e8-9e4e-a2055c9b1350.jpg)
![2018-03-11 25](https://user-images.githubusercontent.com/29221029/37252543-858eedd6-24f0-11e8-9048-97ac62163a3f.jpg)
![2018-03-11 26](https://user-images.githubusercontent.com/29221029/37252544-859b3f82-24f0-11e8-9a91-c98a3eca317a.jpg)
![2018-03-11 29](https://user-images.githubusercontent.com/29221029/37252545-85b4f8c8-24f0-11e8-9dae-18ece55bba98.jpg)
![2018-03-11 31](https://user-images.githubusercontent.com/29221029/37252596-83fd86de-24f1-11e8-9e4c-b9de84e8e965.png)

**Possible fixes**

The sky dome needs to remain anchored to the player, however the rotation needs to be updated. We had this issue in Grand Theft Space. I believe there is a certain shader you can use so it will always render behind everything. I am sure Unreal Engine 4 has this. This way you will still see objects outside the sky dome dome. You aught to do the same with the sun too since it seems to be anchored.

Keep in mind. When you go to warp, you don't want it to be anchored. After all, in this case, you are actually supposed to be flying past the stars.

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by dapperrobotbear** [comment]
Hahahaha. Ooops. ;)

**Comment by scragnog** [comment]
Out of curiosity, how long did it take to fly to the edge of the spacebox?
Your suggestion to anchor it to the player does make sense, but there's issues with that approach where planets/ships etc in the space location are all anchored to the location of the spacebox. I think a good solution for now is just to make the outer spacebox itself MUCH bigger. The player will still be able to fly to the edge, if they're happy to spend an hour flying there!

**Comment by scragnog** [comment]
short term fix - spaceboxes are now 10x the original size. Until we have a better solution, this will have to do. It'd take a player a loooong time to fly out to the edge.

**Comment by nkjellman** [comment]
@scragnog I suppose that could work, but what about the sun?

Why not just anchor everything to an invisible anchor object, then do the spacedone and the sun differently so only the rotations are updated?

**Comment by Gary-Baggins** [comment]
@scragnog flew for 10 minutes in one direction, wasn't able to reach the edge.

**Comment by TheStrato** [comment]
Temp. solution in place. Closing this ticket.
