### ISSUE TITLE
Win - V0010-QA1 - Deck 06 | 8044 Science Lab 12 sign floating 

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#221]
**Summary**
Visit my friend in Science Lab 12, and notice a small gab in the floor leading into Science lab 12, was about to say good bye to my friend when i noticed a small red sign floating.

***What is the expected correct behavior?***
No sign on that equipment at all.

**Steps to reproduce**

1. Visit Science Lab 12, and look at the equipment on the right side of table. 
2. Look closely at the red sign floating.

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 11 - 10 51 22 68](https://user-images.githubusercontent.com/33987322/37252641-dc920a6c-2524-11e8-9dbc-76f1a08463e0.png)
![stage9 screenshot 2018 03 11 - 10 53 35 28](https://user-images.githubusercontent.com/33987322/37252642-dd60b9a2-2524-11e8-91b5-a8b11d02d271.png)

**Possible fixes**
Delete the red sign, that equipment do not need such label.

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by dapperrobotbear** [comment]
Not much can be done about the carpet ATM, but fixed the table.

**Comment by TheStrato** [comment]
Fixed by Dapper, confirmed by Gary. Closing this ticket.
