### ISSUE TITLE
Win - V0010-QA1 - Deck 02 6627 + 6619 Cargo Elevator multi bugs

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#222]
**Summary**
When visiting Deck 02 | 6627 & Deck 02 | 6619 Cargo elevator rooms, there is a gap next to the doors and floor of the room. Both inside and outside of the rooms. (both end of room) 

You can also pick up the tractor beams in the room. 

***What is the expected correct behavior?***
When walking to the rooms you don't see space, but a floor, nor the options to pickup the tractor beam equipment. 

**Steps to reproduce**
1. Visit deck 02 rooms: 6619 & 6627 
2. Look at floor near doors. 
3. Enter room and pickup tractor beam. 

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 11 - 11 34 15 82](https://user-images.githubusercontent.com/33987322/37252728-9758be08-2526-11e8-8362-1d49eedd6882.png)

**Possible fixes**
Stick/hook/nail the equipment to the floor

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by dapperrobotbear** [comment]
Reconfirm in QA2

**Comment by Gary-Baggins** [comment]
Confirmed fixed @TheStrato please close. As for the floor it's been stated that can't be fixed yet.

**Comment by TheStrato** [comment]
Fixed by Dapper, confirmed by Gary. Closing this ticket.
