### ISSUE TITLE
Win - V0010-QA1 - Deck 13 - The Brig, player can put phaser though forcefield

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#224]
**Summary**
Player can pick up a phaser and put hand though the force field allowing you to shoot the person behind the force field. 

***What is the expected correct behavior?***
That and is blocked from passing though the force field.

**Steps to reproduce**
1. Goto Deck 13 - The Brig
2. Pickup the phaser 
3. Walk over to force field and put hand/phaser thought and shoot the NPC behind the force field.

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 11 - 12 38 20 88](https://user-images.githubusercontent.com/33987322/37252922-87b3311e-252a-11e8-84a3-282d20ebd41d.png)

**Possible fixes**
Make hands drop down to your body if walk into a force field.

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by kaadaq** [comment]
Also occurs with the Phaser Rifle....goes thorough most solid objects (forcefield, doors, etc)

**Comment by dapperrobotbear** [comment]
This is a long standing issue, not sure what can be done about it. Will diagnose but probably won't be fixed for v10

**Comment by jeppelykke** [comment]
@HPringles Transferd to Bugz
