### ISSUE TITLE
Win - V0010-QA1 - Door frame miss aligned on Captain's ready room deck 1

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#225]
**Summary**
When you exit the Captains ready room, there seem to be miss aligned doorframe. 

***What is the expected correct behavior?***
That the doorframe is at the door not inside the ready room. 

**Steps to reproduce**
1. Enter the captains ready room. 
2. turn around and look at door

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 11 - 12 31 45 73](https://user-images.githubusercontent.com/33987322/37252946-265e14dc-252b-11e8-90b6-eacff62e2137.png)

**Possible fixes**
Move door frame to door

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by jgbr** [comment]
also bridge noises can be heard with door closed

**Comment by scragnog** [comment]
known issue, won't be fixed for v10

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
