### ISSUE TITLE
Win - V0010-QA1 -  Deck 01 Emergency Turbolift door frame out of alignment

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#226]
**Summary**
When you inside Emergency turbolift the door frame seems to be little to low making it out of alignment. 

***What is the expected correct behavior?***
Door frame reach the top of the wall so no gap.

**Steps to reproduce**
1. Enter Emergecny Turbolift on deck 01
2. Turn around open doors and look at top of door,

**Relevant logs and/or screenshots**

![stage9 screenshot 2018 03 11 - 13 01 11 84](https://user-images.githubusercontent.com/33987322/37253092-12736812-252d-11e8-8faa-58af8907e535.png)

**Possible fixes**
Raise the doorframe.

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by dapperrobotbear** [comment]
Reconfirm in QA2

**Comment by Gary-Baggins** [comment]
Confirmed fixed @TheStrato please close.
