### ISSUE TITLE
Win V0010-QA1 Removable handle on Engineering Access Panel

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#227]
Summary
I was able to remove the handle(?) mesh from the coolant access panel door near the warp core.   It came off in my hand (half formed) and I was able to drop it to the floor.

Expected
Handle stays attached.

Reproducible Steps
1. Approach panel
2. Mouse on handle and hit enter

Screenshot:
![image](https://user-images.githubusercontent.com/34050343/37253262-e2785c98-2505-11e8-98f7-d867859ed3ec.png)

**Comment by HPringles** [comment]
# Confirmed Issue

***Further Information***

It is clear this is an unintended bug as the rear of the handle is not rendered.

**Comment by dapperrobotbear** [comment]
We added a system so you could pick up most objects in the game. Guess we forgot to set that one as static.

**Comment by dapperrobotbear** [comment]
Reconfirm in QA2

**Comment by Gary-Baggins** [comment]
Confirmed fixed @TheStrato please close.
