### ISSUE TITLE
Win - V0010-QA1 -No Visable Enterprise model when in 3RD person mode

### ISSUE THREAD

**Issue by CaptainWallis** [dapperrobotbear/Stage9#229]
When flying the Enterprise in 3rd person, there is no ship model. All you can see is floating corridors in space.

**Comment by harryingles** [comment]
# Confirmed Issue

***Screenshot***

![desktop screenshot 2018 03 11 - 16 37 47 86](https://user-images.githubusercontent.com/16962690/37255873-a642e082-254a-11e8-9b27-d5f2d153e16d.png)

You can see the bridge outline (just about) and not the exterior of the ship

**Comment by Gary-Baggins** [comment]
Confirmed.

**Comment by HPringles** [comment]
# Known Issue - Will be fixed for V0010-QA2 - According to @scragnog

**Comment by scragnog** [comment]
I believe this is fixed now. Totally my bad.

**Comment by Gary-Baggins** [comment]
Verified fixed in QA3 @TheStrato @HPringles  please close.

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
