### ISSUE TITLE
Sitting on NPCs chairs makes you sit inside them

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#23]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

If you go sit on NPC Data's chair, you sit inside his body... 
![stage9 screenshot 2017 11 25 - 23 14 21 38](https://user-images.githubusercontent.com/33987322/33235474-4227f682-d239-11e7-927e-a176f9666a67.png)

If you choose to go sit on Captain Picards chair you sit behind him. 
![stage9 screenshot 2017 11 25 - 23 14 36 43](https://user-images.githubusercontent.com/33987322/33235475-4c24d92a-d239-11e7-81b9-ff32f2a41e55.png)

**Comment by scragnog** [comment]
fixed for now. chairs that have generic npcs in can be sat in (and the npc disappears) but for named crew, you can't get in their chairs any more.
