### ISSUE TITLE
Win - V0010-QA1 - Transporter room 1 Animation error

### ISSUE THREAD

**Issue by CaptainWallis** [dapperrobotbear/Stage9#230]
There appears to be an animation error, where the animated transporter sliders on the LCARS display are on the left hand side.

![transporter room 1 error](https://user-images.githubusercontent.com/37252136/37253463-fe59e048-2529-11e8-908e-d0198f4f3b7d.jpg)

**Comment by harryingles** [comment]
Same issue here 
![desktop screenshot 2018 03 11 - 14 05 11 93](https://user-images.githubusercontent.com/16962690/37254413-5b1bbcb0-2535-11e8-87b3-4dcd6424699d.png)

**Comment by TheStrato** [comment]
#261 is a more complete report. Closing this ticket.
