### ISSUE TITLE
Win - V0010-QA1 Main Shuttlebay Cargo Elevators

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#232]
A portion of both cargo elevator shafts extend past the exterior mesh of the ship. 

![image](https://user-images.githubusercontent.com/5162659/37253803-0aa13256-250d-11e8-8674-908a6c61f139.png)

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by dapperrobotbear** [comment]
Doh!

**Comment by dapperrobotbear** [comment]
Reconfirm in QA2

**Comment by HPringles** [comment]
# Verified Fix 

@TheStrato

**Comment by TheStrato** [comment]
Fixed by Dapper, confirmed by Pringles. Closing this ticket.
