### ISSUE TITLE
V0010 QA1 - NPCs seems to congregate and get stuck in corridors 

### ISSUE THREAD

**Issue by HPringles** [dapperrobotbear/Stage9#233]
**Summary**
NPCs seem to congregate and get stuck in the smaller sub-corridors (especially deck 6- not tested other decks as of yet). It causes extreme frame rate drops and stops the player from accessing the corridors

***What is the expected correct behavior?***
NPCs should walk around the ship in a human way and not collide or get stuck with each other

**Steps to reproduce**

1.Load the game
2.Wait for around 30 seconds - 1 minute
3.Walk around the corridors and NPCs will eventually start to get stuck in the smaller side-corridors

**Relevant logs and/or screenshots**

![lotsanpcs](https://user-images.githubusercontent.com/16962690/37254037-8ba3ca98-2531-11e8-8b70-a21e57e76c68.png)

**Comment by Gary-Baggins** [comment]
Confirmed.

**Comment by dapperrobotbear** [comment]
I think there may be a bug where they cannot find a destination and their destination gets set to 0,0,0 which makes them all try to walk to the center of the world. I'll debug it.

**Comment by MrPeppow** [comment]
Can confirm



![screenshot_20180314_121813](https://user-images.githubusercontent.com/13747941/37399739-e4fed6d4-2782-11e8-82f3-236e77ebe0d0.jpeg)

**Comment by jeppelykke** [comment]
@HPringles transferred to bugz

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
