### ISSUE TITLE
V0010-QA1 - Game Crash on main bridge

### ISSUE THREAD

**Issue by HPringles** [dapperrobotbear/Stage9#234]
**Summary**
Main bridge game crash shortly after entering.

The map was taking 2 or three seconds to load each room every time which I assume is part of the proble,

***What is the expected correct behavior?***
The game should not crash and the maps should be loaded before the doors open

**Steps to reproduce**
Have not been able to reproduce the exact situation

**Relevant logs and/or screenshots**

[UE4CC-Windows-0A8C5A2646AC20F16365A39253694424_0000.zip](https://github.com/dapperrobotbear/Stage9/files/1800397/UE4CC-Windows-0A8C5A2646AC20F16365A39253694424_0000.zip)

**Comment by dapperrobotbear** [comment]
We changed the way rooms load, but not sure why they would crash. Please reconfirm this when QA2 comes out.
