### ISSUE TITLE
V0010-QA1 - Holodeck Arch can be toggled from outside the holodeck

### ISSUE THREAD

**Issue by HPringles** [dapperrobotbear/Stage9#235]
**Summary**
After loading a holo deck program, the Q key can toggle the arch from outside the program - not game breaking as the player can still enter, but immersion breaking

***What is the expected correct behavior?***
Arch should not be able to be toggled from outside the holodeck

**Steps to reproduce**

1.Load a program
2.Press Q

**Relevant logs and/or screenshots**

None

**Comment by trekkeriii** [comment]
Actually, I think this needs to remain. Because of the episode "Cost of Living". Be interesting if they could make it so that the Door is transparent like in that episode.

**Comment by nkjellman** [comment]
Also, there should be a way to end the program. If you run all the holodecks at once, your FPS will have a bad time.

**Comment by Gary-Baggins** [comment]
Can confirm this is still present in Q2, pressed Q in sickbay and heard the sound.

**Comment by scragnog** [comment]
Aww yeah! Guess who's on a roll tonight?! Fixed!

**Comment by Gary-Baggins** [comment]
I'm getting the opposite of this problem, load a programme, enter holodeck, press Q (for door vanish) then can still walk into the hallway through the location from where the doors just vanished @scragnog @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
