### ISSUE TITLE
Win V0010-QA1 Phaser Issues

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#236]
Summary

With head bob off, phaser swings excessively from side to side while you walk.   Also, dropping phaser in the turbolift has it fall through the floor (no collision).

Desired Result

Phaser motion more controlled while moving.  Should be able to set down a phaser pretty much anywhere (necessary to operate consoles, like turbolift)

Reproducible Steps
1. Picked up Type 2 phaser from the Brig Console
2. Walked to Turbolift
3. Dropped phaser

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
