### ISSUE TITLE
Mac - V0010-QA1 - Deck 3 - 04 Shuttlebay 1 Offices | Bow -- Bulkheads not loading to the left and right of the turbolift door

### ISSUE THREAD

**Issue by mikebarber1** [dapperrobotbear/Stage9#237]
Take the turbolift to Deck 3 - 04 Shuttlebay 1 Offices | Bow
When exiting the lift to the left and right the bulkheads or whatever should be loading at the end of the corridor isn't loading and you can see straight thru to the shuttlebay.
![2018-03-10 21 26 18](https://user-images.githubusercontent.com/25273387/37255112-22ffb19a-251e-11e8-9cc7-3da9ad4bd232.jpg)

macOS 10.12.6 on 
2016 MacBook Pro 15" w/ Radeon Pro 4600 4GB & 27" LG 5K monitor.
Core i7 2.9 GHz + 16 GB Ram
V10 QA Release 1

**Comment by dapperrobotbear** [comment]
There was a hallways duplication in QA1. Fixed in QA2 which will be released soon.

**Comment by trekkeriii** [comment]
Windows version same issue #209

**Comment by Jaredsfs1** [comment]
Also Confirmed: 
Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by jgbr** [comment]
Not fixed

**Comment by TheStrato** [comment]
Not Fixed. Re-assigned.

**Comment by JonathanNStewart** [comment]
This is also an example of the glitching carpets.

**Comment by jgbr** [comment]
The carpets seem randomly placed as some report it fixed and then it crops up again

**Comment by dapperrobotbear** [comment]
Please reconfirm original problem, else close this bug and create another specific one for the other problem. Thx.

**Comment by mikebarber1** [comment]
Working correctly in QA4 on Mac
