### ISSUE TITLE
V0010-QA1 - Deck 13 - Collison Map of Brig Desk is incorrect

### ISSUE THREAD

**Issue by HPringles** [dapperrobotbear/Stage9#242]
**Summary**
The collision for the desk in the brig is incorrect, phasers can be supported by it even when not visually touching it.

***What is the expected correct behavior?***

Nothing should collide with the desk if it is not touching it.

**Steps to reproduce**

1.Go to Deck 13/Brig
2.Pick up the phaser on the desk
3.Move away from the desk slightly
4.Drop the phaser and see if it lands wrong,
5. If it landed correctly, repeat steps 2 to 4.

**Relevant logs and/or screenshots**

![desktop screenshot 2018 03 11 - 17 46 18 100](https://user-images.githubusercontent.com/16962690/37256551-321e1848-2554-11e8-842c-08cde68acf31.png)

**Comment by dapperrobotbear** [comment]
Fixed in >QA4

**Comment by HPringles** [comment]
# Confirmed Fixed

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
