### ISSUE TITLE
V0010-QA1 Deck 10 Computer Core - Old Style Forcefields

### ISSUE THREAD

**Issue by HPringles** [dapperrobotbear/Stage9#243]
**Summary**
Old style, interactive forcefields still in place on Deck 10/Computer Core

***What is the expected correct behavior?***

New Style, bluer, interactive forcefields should be in place

**Steps to reproduce**

1.Go to the computer core
2.Forcefields in stairwells are wrong

**Relevant logs and/or screenshots**
![desktop screenshot 2018 03 11 - 17 58 56 50](https://user-images.githubusercontent.com/16962690/37256703-32c8200c-2556-11e8-88ea-2a818545a972.png)

**Comment by trekkeriii** [comment]
Confirmed

**Comment by dapperrobotbear** [comment]
There's a lot of old style forcefields around. But I can quickly switch these out.

**Comment by EazyCheeze1978** [comment]
Fixed indeed! New forcefields, that react to my pushing and everything. Good!

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
