### ISSUE TITLE
V0010-QA1-Deck 12/Sickbay - Phaser/Hypospray does not interact with female NPCs

### ISSUE THREAD

**Issue by HPringles** [dapperrobotbear/Stage9#244]
**Summary**
NPCs (female) do not have ragdoll physics

***What is the expected correct behavior?***

Female NPCs should ragdoll when shot with a phaser or hit with a hypospray

**Steps to reproduce**

1.Go to sickbay
2.Pick up phaser from the CMO's office
3.Shoot the female NPC which is persistently by the biomedical scan display

**Relevant logs and/or screenshots**

![desktop screenshot 2018 03 11 - 18 06 44 84](https://user-images.githubusercontent.com/16962690/37256770-4ffed930-2557-11e8-8d64-0c3efbef61f6.png)

**Comment by trekkeriii** [comment]
I think it's been mentioned before that they would have to actually build female NPCs to be just like the male ones. I think the male ones are just built into their developer tools.

**Comment by HPringles** [comment]
Oh yeah - I remember now. Forgot they were a different model entirely

**Comment by dapperrobotbear** [comment]
Correct. Female NPCs are a different (older) NPC class that we'll be abandoning when we have newer models. Will see if there's something quick I can do.

**Comment by dapperrobotbear** [comment]
Managed to get the old NPC class to react to phasers and hypos. Probably the last time that class will be edited before being removed.

**Comment by EazyCheeze1978** [comment]
Poor Nurse Ogawa flopped like a fish in front of the brain scan display! Fixed. :)

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
