### ISSUE TITLE
Win - V0010-QA1 - Earth sky-box

### ISSUE THREAD

**Issue by Gary-Baggins** [dapperrobotbear/Stage9#245]
The sky-box around Earth looks like a patchwork quilt to me, I'm not sure if this is a bug or just my computer not being powerful enough to load it in.

**Comment by HPringles** [comment]
# Unable to duplicate

***Further Testing***

Most likely a PC performance issue
@Gary-Baggins stated that settings were on the lowest.

**Comment by Gary-Baggins** [comment]
Was due to pc setting.
