### ISSUE TITLE
Win - V0010-QA1 - Deck 12 Holodeck area Corridor Turbolift gaps

### ISSUE THREAD

**Issue by trekkeriii** [dapperrobotbear/Stage9#247]
**Summary**

Can see outer-space looking down at the floor at the gap between Corridor and Turbolift. Also along the wall opposite of the Holodecks

***What is the expected correct behavior?***

Not seeing space. Maybe a smaller gap

**Steps to reproduce**

1. Go to Deck 12, Holodecks
2. Look down as you step in or out of Turbolift.
3.

**Relevant logs and/or screenshots**

(Paste any relevant logs - please use code blocks  to format console output,
logs, and code as it's very hard to read otherwise.)

![20180311153752_1](https://user-images.githubusercontent.com/4651111/37257619-59471ca6-2542-11e8-8056-7f8281401ce4.jpg)
![20180311153754_1](https://user-images.githubusercontent.com/4651111/37257620-5bc789ca-2542-11e8-8ce0-01cca76b15f8.jpg)
![20180311153802_1](https://user-images.githubusercontent.com/4651111/37257623-5e0b0dc4-2542-11e8-93ed-f8f871dae162.jpg)

**Possible fixes**

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
