### ISSUE TITLE
Win - V0010-QA1 - Deck 12 Holodeck doors stay open inside program

### ISSUE THREAD

**Issue by trekkeriii** [dapperrobotbear/Stage9#248]
**Summary**

If you move towards the Holodeck exit to trigger it to open, it will not close if you move away. Have leave and come back in to correct.

***What is the expected correct behavior?***

Should close if you are not near it.

**Steps to reproduce**

1. Go to Deck 12, Holodecks
2. Launch a Bridge Simulation
3. Enter
4. Go to the door after entering to trigger it to open.
5. Don't go into the Corridor, move back.
6. Door stays open
![20180311154843_1](https://user-images.githubusercontent.com/4651111/37257797-0998e516-2544-11e8-9983-2e9a2407c59a.jpg)

**Relevant logs and/or screenshots**

(Paste any relevant logs - please use code blocks  to format console output,
logs, and code as it's very hard to read otherwise.)

**Possible fixes**

**Comment by HPringles** [comment]
# Confirmed Issue

Related to #235 #205

**Comment by dapperrobotbear** [comment]
We need to come up with a better way to summon/dismiss the doors, and other functions.

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
