### ISSUE TITLE
Win - V0010-QA1 - Season 1 Bridge viewscreen chase lights

### ISSUE THREAD

**Issue by trekkeriii** [dapperrobotbear/Stage9#249]
**Summary**

Viewscreen Chase lights moving in wrong direction

***What is the expected correct behavior?***

Should be moving inward. This changed in Season 2, but for Season 1, chase lights moved inwards.

**Steps to reproduce**

1. Go to Season 1 Bridge on Holodeck
2. Turn on Encounter at Farpoint episode
3. Compare viewscreens

**Relevant logs and/or screenshots**

(Paste any relevant logs - please use code blocks  to format console output,
logs, and code as it's very hard to read otherwise.)

**Possible fixes**

**Comment by trekkeriii** [comment]
#184 Related issue

**Comment by jeppelykke** [comment]
@HPringles transferred to bugz
