### ISSUE TITLE
Main Shuttlebay Controlroom Console has option to close Shuttlebay Doors even if the Doors are already closed

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#25]

**Comment by kaadaq** [comment]
Related:   If the Main Shuttlebay door is open, and you enter a shuttlecraft, the console still has a button for opening the shuttle bay door.

**Comment by Sciencekeeper** [comment]
@TheStrato please close. This is resolved

**Comment by TheStrato** [comment]
OP says issue is fixed. Closing the ticket.
