### ISSUE TITLE
Mac V0010-QA1 Turbolift destination scroll

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#250]
Attempting to use the scroll bar in the turbo lift at any location does not work. Scrolling results in the camera slightly zooming in but not moving. To go below the first four locations described, you have to scroll the bars section not the linear one.

This happens using click and pull or scroll.

It is very 'finicky' about where you click and pull or scroll when putting pointer over destinations. The linear bar does however move when you move the destinations bars. 

Mac OS High Sierra 10.13.3

**Comment by dapperrobotbear** [comment]
Sorry, can you be more descriptive about which bars? The bar on the right (orange) is the scroll handle. Left clicking and dragging that bar is the only supported way of scrolling the destination list. Right-Clicking is the zoom behavior.

**Comment by Jaredsfs1** [comment]
Not confirmed.  I am able to click and drag the scroll bar in the turbo lift as in previous versions of Stage9

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by jgbr** [comment]
resolved in QA2
