### ISSUE TITLE
Mac - V0010-QA1 - Turbolift, any location, static or moving, Camera/PoV zooming in and out.

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#253]
Problem: I don't know how to describe this bar as you look around the turbo lift and finally stop on a point, any point, the camera is doing a gentle zoom in and out. Almost like a breathing action.

Can place, destination, turbo lift moving or stationary. 

:Replicate by boarding any turbo lift anywhere.

Camera should stay static.

**Comment by dapperrobotbear** [comment]
I think the camera is trying to spring in and out and hitting the walls. We'll have to decrease the spring size when entering the turbolift.

**Comment by jgbr** [comment]
This is also doing it when camera is stationary anywhere else on the ship.

**Comment by jgbr** [comment]
Hmm slightly disorientating particularly in the turbo lift. Recommend cancelling this feature. Turbolift one however definitely a bug?

**Comment by dapperrobotbear** [comment]
We have a head-bob, non-head bob mode for that. But the non head bob mode is probably going to get removed anyhow. We'll eventually be toning down this movement. But no this is not a bug.
