### ISSUE TITLE
Mac - V0010-QA1 - Deck 25 / Nacelle Control issues. "Deactivate Plasma Stream" does not work when Observation hatch is open

### ISSUE THREAD

**Issue by mikebarber1** [dapperrobotbear/Stage9#254]
Go into Nacelle control and from the console in the center of the room open the observation hatch. After the door is open attempt to deactivate the plasma stream. Clicking on the option doesn't do anything - the menu options stay visible as if you clicked nothing. After about 30 seconds when the door open warning sound stops the plasma stream will stop.

Also if you get a good run going and manage to get inside the nacelle (past the area where the injectors are (the bits at the floor and ceiling firing towards each-other)) you fall out of the ship

And lastly you can open the maintenance door but you cannot fit thru it.

macOS 10.12.6 on
2016 MacBook Pro 15" w/ Radeon Pro 4600 4GB & 27" LG 5K monitor.
Core i7 2.9 GHz + 16 GB Ram
V10 QA Release 1

**Comment by HPringles** [comment]
# Confirmed

I saw this earlier, but assumed it was a feature, so that the crew don't make themselves radioactive by mistake

**Comment by dapperrobotbear** [comment]
- You should be able to deactivate the plasma stream regardless of the hatch status.
- The plasma stream stops after 45 seconds to prevent degradation of the forcefield (like in the show).
- The maintenance door height is a known issue.

**Comment by HPringles** [comment]
@dapperrobotbear There's a UI bug on the controls as well


If you open the hatch with the stream active and then wait for it to deactivate, the panel still shows 'deactivate plasma stream'

**Comment by Jaredsfs1** [comment]
The "deactivate plasma stream" option works if the hatch is closed.  However, if you open the hatch first, the stream cannot be disabled via the control.  If however you deactivate the stream and then open the hatch, you can activate the stream with the hatch open and deactivate the stream at any time (irrespective of hatch position).  It's only if you open the hatch with the stream active that you can no longer control the stream.

![screen shot 2018-03-12 at 10 43 46 pm](https://user-images.githubusercontent.com/35311046/37354336-cb15eba2-26b7-11e8-8c13-30eccb189d68.png)


Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by dapperrobotbear** [comment]
Oh the joys of instating a ship wide state machine. I'll look into it.

**Comment by MrPeppow** [comment]
Confirmed on Linux QA1 @HPringles

**Comment by dapperrobotbear** [comment]
Fixed in QA4

**Comment by Gary-Baggins** [comment]
Confirmed fixed in windows @TheStrato @HPringles

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
