### ISSUE TITLE
Win - V0010-QA1 Remote Saucer Seperation

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#255]
When you trigger remote separation from a shuttle. Return to the main bridge. Forcing the parts to come back together. Remote Separation doesn't reset in the shuttle.

What is the expected correct behavior?

Shuttle Remote Saucer Separates ship. Return to bridge. Reset ship. Remote separation is available in shuttles again. 

Steps to reproduce

Go in shuttle. Remote Separate.
Go back to main bridge.
Shuttle only has access to remote open bay doors.

![image](https://user-images.githubusercontent.com/5162659/37258578-660f5152-2550-11e8-8da8-9593eebf8209.png)

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by HPringles** [comment]
Win Bug @TheStrato

**Comment by dapperrobotbear** [comment]
Reconfirm in >QA3

**Comment by TheStrato** [comment]
Placed in the pipeline.

**Comment by kaadaq** [comment]
Unable to confirm -- after launching from Shuttlebay 2 and performing remote saucer sep, I can't take the Turbolift.....well, anywhere, really.

**Comment by kaadaq** [comment]
Still an issue as of ONGOING-1

**Comment by kaadaq** [comment]
Still an issue as of ONGOING-1
![image](https://user-images.githubusercontent.com/34050343/38006331-910015e4-3212-11e8-940e-481a616b6bd7.png)
@TheStrato @HPringles , please put back in pipeline

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
