### ISSUE TITLE
Win - V0010-QA1 Planets Atmoshpere Follows View Screen

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#256]
When warping to a new destination. Planet atmospheres follow with the ship. This happens to all planets with moving clouds or ozone layer aurora.

What is the expected correct behavior?

Planets atmosphere stays connected to the planet model when ship is leaving the system. 

Steps to reproduce

Choose a new destination.
Be in a system with a planet.
Warp in/out.

![image](https://user-images.githubusercontent.com/5162659/37258671-9479e0d8-2551-11e8-84f2-a666563b5bca.png)

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by trekkeriii** [comment]
Confirmed.

**Comment by kaadaq** [comment]
Confirmed trekkeriii comment about Relay station debris:
![image](https://user-images.githubusercontent.com/34050343/37318602-cf09535a-2641-11e8-9912-c64297a94c8f.png)

**Comment by jeppelykke** [comment]
@HPringles This has been moved over to Bugz (bug report nr #15), this is a double bug report
