### ISSUE TITLE
Win - V0010-QA1 No Indication For Current Location On Warp Menu

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#257]
Current locations have no indication on the warp destination menu. Telling you are in this location. This would cause confusion to people and think a location is broken. 

What is the expected correct behavior?

The current loaded map would be greyed out, not in the menu, or would say something like "Current Location not selectable". 

![image](https://user-images.githubusercontent.com/5162659/37258774-0402b0aa-2553-11e8-8a65-3d0266b3ee57.png)

**Comment by HPringles** [comment]
# Confirmed Missing Feature

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
