### ISSUE TITLE
Mac - V0010-QA1 - Crash on restart button

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#260]
**Summary**

Crash of Stage 9 while attempting to restart the program during the Pogo video on the bridge.

***What is the expected correct behavior?***

While the video is playing, clicking the restart button in the UI twice should reset the game to the starting point.

**Steps to reproduce**

1.Turbolift to Bridge
2.Sit in Captain's chair
3.Click on the left-hand command control console
4.Stand up
5. Open UI (ESC)
6. Click Restart
7. Click Restart Again

**Relevant logs and/or screenshots**

```
LoginId:2ead80538140a6425e4e9fb724d89a41
EpicAccountId:

 SEGV_MAPERR at 0x3

FGenericPlatformMisc::RaiseException(unsigned int) Address = 0x108e7ddab (filename not found) [in Stage9]
FOutputDevice::Logf(wchar_t const*, ...) Address = 0x108f7c42d (filename not found) [in Stage9]
FDebug::AssertFailed(char const*, char const*, int, wchar_t const*, ...) Address = 0x108f45254 (filename not found) [in Stage9]
FAsyncLoadingThread::TickAsyncThread(bool, bool, float, bool&, FFlushTree*) Address = 0x108fe5a71 (filename not found) [in Stage9]
FAsyncLoadingThread::Run() Address = 0x108fe70cf (filename not found) [in Stage9]
FRunnableThreadPThread::Run() Address = 0x108ea136a (filename not found) [in Stage9]
FRunnableThreadPThread::_ThreadProc(void*) Address = 0x108e8ec16 (filename not found) [in Stage9]
_pthread_body Address = 0x7fff56f6f6c1 (filename not found) [in libsystem_pthread.dylib]
_pthread_body Address = 0x7fff56f6f56d (filename not found) [in libsystem_pthread.dylib]
thread_start Address = 0x7fff56f6ec5d (filename not found) [in libsystem_pthread.dylib]
```

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by jgbr** [comment]
Replicated on another Mac.

**Comment by HPringles** [comment]
Mac Crash @TheStrato

**Comment by TheStrato** [comment]
Done.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
