### ISSUE TITLE
V0010-QA2 - transporter display misaligned

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#261]
**Summary**

The animation for the "Energize" function on the transporter room displays is incorrect in Transporter Room 1 (Across the hall from spawn point, Transporter Room 2).

***What is the expected correct behavior?***

The animation should be aligned with the corresponding placement on the LCARS display.

**Steps to reproduce**

1.Spawn into Stage9 V10
2.Leave Transporter room and cross the hall
3.View Transporter control station display.

**Relevant logs and/or screenshots**

![screen shot 2018-03-10 at 10 36 55 pm](https://user-images.githubusercontent.com/35311046/37260972-f520ae4a-256e-11e8-8732-ad542539f221.png)

**Possible fixes**
Align display animation layer with display top layer.

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by HPringles** [comment]
# Duplicate Bug Report

#230 @TheStrato

**Comment by TheStrato** [comment]
I will close #230 as this one has a more complete report.

**Comment by Jaredsfs1** [comment]
Still Present in QA2 (Mac)

**Comment by scragnog** [comment]
resolved for qa3

**Comment by Gary-Baggins** [comment]
Confirmed fixed in Windows @TheStrato @HPringles

**Comment by TheStrato** [comment]
@Jaredsfs1 can you confirm this is fixed in the Mac QA3?

**Comment by Jaredsfs1** [comment]
Confirmed - this is fixed in QA3 on Mac @TheStrato

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
