### ISSUE TITLE
Win - V0010-QA1 - Doorframe colors on Holodeck/Shuttlebay/Brig inside

### ISSUE THREAD

**Issue by trekkeriii** [dapperrobotbear/Stage9#262]
**Summary**

The color is tan, different than the door

***What is the expected correct behavior?***

Should be the same as the door,

**Steps to reproduce**

1. Enter the Holodeck, Shuttlebay 2, or Brig (any other usage of this doortype)
2.
3.

**Relevant logs and/or screenshots**

(Paste any relevant logs - please use code blocks  to format console output,
logs, and code as it's very hard to read otherwise.)
![20180311205400_1](https://user-images.githubusercontent.com/4651111/37260989-1954eb0a-256f-11e8-9b4f-c4f6bb782f1b.jpg)
![20180311205421_1](https://user-images.githubusercontent.com/4651111/37260990-1b76d074-256f-11e8-8b11-effc140dc269.jpg)
![20180311205538_1](https://user-images.githubusercontent.com/4651111/37260991-1d87681a-256f-11e8-97b3-5678e7dee2ff.jpg)

**Possible fixes**

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
