### ISSUE TITLE
V0010-QA2 - Hallway texture error -Deck 6

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#263]
**Summary**

Upon leaving the Transporter room into Deck 6, hallways and other hallways, the bulkhead texture has a bright spot that illuminates as you pass every single bulkhead section.

***What is the expected correct behavior?***

Lighting and texture should be smooth, not focused or repeating.

**Steps to reproduce**

1.Spawn into Stage9
2.Leave Transporter Room 2, turn left
3.Turn right at the junction end
4. Start Walking (or Jogging for best effect) along the curving corridor as it turns left
5. At about a third of the distance across the hallway, every single bulkhead will illuminate in a single white spot (see screen shot below)

**Relevant logs and/or screenshots**
![screen shot 2018-03-10 at 10 38 21 pm](https://user-images.githubusercontent.com/35311046/37261076-d3e662b4-256f-11e8-98f4-6212f697cf21.png)

**Possible fixes**

smooth texture or lighting map layer at that distinct point.

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by Jaredsfs1** [comment]
Issue still present in QA2 (Mac)

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
