### ISSUE TITLE
Mac - V0010-QA1 - Transporter room 4 door doubled

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#264]
**Summary**

The door to Transporter Room 4 on Deck 6 is doubled, and includes an outer door labeled Transporter Room 2.

***What is the expected correct behavior?***

The door should be single and display Transporter Room 4.

**Steps to reproduce**

1.Leave Transporter Room 2 after spawning 
2.Turn left and then right to walk all the way to the opposing side of the Deck where Transporter Room 3 and 4 should be found.
3.Observe a double door, one labeled Transporter Room 4, and the other labeled Transporter Room 2.

**Relevant logs and/or screenshots**
![screen shot 2018-03-10 at 10 40 07 pm](https://user-images.githubusercontent.com/35311046/37261129-7011bf1c-2570-11e8-90d1-d32287cb7ae6.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by dapperrobotbear** [comment]
Reconfirm in QA2

**Comment by nkjellman** [comment]
Judging by the FPS drop when this happens, I think it is more than just the door being doubled. I bet it is the whole transporter room.

**Comment by dapperrobotbear** [comment]
There was a problem with the instanced room spawner as well that would probably explain the FPS drop. Should be fixed in QA2.

**Comment by jgbr** [comment]
Fixed in my Mac build

**Comment by HPringles** [comment]
# Verified Fixed 

Fixed Windows @TheStrato

**Comment by TheStrato** [comment]
Fixed by Dapper, confirmed by JGBR and Pringles. Closing the ticket.

**Comment by TheStrato** [comment]
Re-opened at the request of @Jaredsfs1

**Comment by Jaredsfs1** [comment]
Returned in QA2,  the door is fixed now, and shows only Transporter Room 4 as expected. But when it opens: Miles O'Brian.  

I think that the entirety of Transporter Room 2 was being duplicated in that location, and the door was just the symptom.

![screen shot 2018-03-12 at 6 29 46 pm](https://user-images.githubusercontent.com/35311046/37314145-e7629a06-2628-11e8-8a3b-293f6e43a1af.png)


Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by TheStrato** [comment]
So is this a "not cannon" thing now?

**Comment by jgbr** [comment]
This should have been a new ticket. The door opening issue was replicable but miles issue isn’t on Mac

**Comment by HPringles** [comment]
Can we close this now? New issue created @thestrato

**Comment by TheStrato** [comment]
NPC duplication branched to #327. Closing this ticket.
