### ISSUE TITLE
Mac - V0010-QA1 - Battle Bridge turbo interior door mesh

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#265]
**Summary**
The  emergency turbo on the bridge has a mesh alignment error when inside looking out.

***What is the expected correct behavior?***

Looking through the doorway from inside the emergency turbo out onto the bridge should only be obstructed by the door frame.

**Steps to reproduce**

1.Go to the bridge
2.enter the emergency turbo
3.turn around and face back onto the bridge

**Relevant logs and/or screenshots**

![screen shot 2018-03-10 at 10 56 18 pm](https://user-images.githubusercontent.com/35311046/37261194-fd538ba8-2570-11e8-91a8-9f2456b9710d.png)

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

mesh alignment

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by dapperrobotbear** [comment]
Probably won't be fixed for v10. But should be fixed.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
