### ISSUE TITLE
Mac - V0010-QA1 - Bridge Turbo object spawn colission 

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#266]
**Summary**

There is an issue with taking a turbo route to the Bow Bridge location that passes near the Ready room (or presumably the observation lounge)which causes  a blue/green (hull?) fragment to appear inside the Aft turbolift.

***What is the expected correct behavior?***

Taking a turbo to the Bridge Bow and walking to the Aft Bow turbo should not result in a collision object in the turbolift. 

**Steps to reproduce**

1.Take the turbolift from anywhere to the Bridge Bow
2.Exit the turbo and walk directly to the Aft turbo and enter
3.Observe a green/blue mesh piece from possibly the hull inside the turbo, that disappears after a few seconds.

**Relevant logs and/or screenshots**

![screen shot 2018-03-10 at 10 57 48 pm](https://user-images.githubusercontent.com/35311046/37261325-f8010c88-2571-11e8-97a8-d9d72b0f59d3.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by dapperrobotbear** [comment]
This might be the new blocker volume. Will explore.

**Comment by dapperrobotbear** [comment]
Please confirm in QA2

**Comment by jgbr** [comment]
fixed in QA2

**Comment by TheStrato** [comment]
Fixed by Dapper, confirmed by JGBR. Closing ticket.
