### ISSUE TITLE
Mac - V0010-QA1 - Bridge view screen zoom issue

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#267]
**Summary**

The standard zoom option acts unexpectedly when looking at the viewscreen on the bridge.

***What is the expected correct behavior?***

Zooming when looking at the view screen should zoom the view as it normally would when looking at a static image.

**Steps to reproduce**

1.Travel to the Bridge
2.Face the view screen
3.Right-Click the mouse to zoom the view
4.Observe the zoom function normally on the Bridge room, but not the view of the outside of the ship, which remains static as if you had simply walked closer to the display.

**Relevant logs and/or screenshots**

![screen shot 2018-03-11 at 9 17 04 pm](https://user-images.githubusercontent.com/35311046/37261394-756e9a78-2572-11e8-832d-5a189ebc4e18.png)

![screen shot 2018-03-11 at 9 17 05 pm](https://user-images.githubusercontent.com/35311046/37261396-7bd99a3e-2572-11e8-83c6-8868baaea641.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by dapperrobotbear** [comment]
The new parallax screen does this. I'm pretty sure this works as expected.

**Comment by HPringles** [comment]
@TheStrato Needs closing I believe

**Comment by TheStrato** [comment]
NaB. Closing this ticket.
