### ISSUE TITLE
Mac - V0010-QA1 - Bridge Door missing label

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#269]
**Summary**

There's no door label on the Bridge door when entering the bridge from the Observation Lounge stairway.

***What is the expected correct behavior?***

01 Bridge?

**Steps to reproduce**

1.Exit the Bridge toward the Observation Lounge
2.Turn around, allow the Bridge door to close
3.Observe the Door is blank

**Relevant logs and/or screenshots**

![screen shot 2018-03-10 at 11 11 26 pm](https://user-images.githubusercontent.com/35311046/37261679-bea4805c-2574-11e8-8fba-f38ca066a31b.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by dapperrobotbear** [comment]
Doors only have labels on one side generally. So this door has the label on the other side. It's probably desirable to have doors with labels on both for cases such as this.

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
