### ISSUE TITLE
You can shoot yourself with the phaser

### ISSUE THREAD

**Issue by HPringles** [dapperrobotbear/Stage9#27]
When in headbob mode, the phaser can be aimed at your own character, causing you to ragdoll. The only solution atm is to restart the game,

**Comment by scragnog** [comment]
@dapperrobotbear what do you reckon? Can we get the phaser to ignore the player pawn? I hesitate to mess in the bps here as they're complex enough as-is.

**Comment by nkjellman** [comment]
This is a bug that could be turned into a feature. You just need to make the player re spawn.

**Comment by dapperrobotbear** [comment]
Agreed. We can easily make this kill the user and re-spawn.

**Comment by Cacille** [comment]
I think re-categorizing this bug as a feature and leaving it (or enhancing it) will be good for future gameplay. It'll be way easier to implement story quests or dangerous situations the player must learn to avoid!

**Comment by jeppelykke** [comment]
Cacille, for story wise simple emergency transportation to Sickbay where you rematerialize on Sickbay "medical bed" with doctor and chef security officer standing next to bed..

**Comment by HPringles** [comment]
# Fixed in V10
