### ISSUE TITLE
Mac - V0010-QA1 - PADD/Tricorder displays low Resolution

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#270]
**Summary**

The image on PADDs in V10 is very low res, and different than in previous versions. The Tricorder has the same issue.

***What is the expected correct behavior?***

Either the same high Res. (Detryon Emission Analysis?) animation as in previous versions of Stage9 or a higher resolution image of the new image.  The image on tricorders could also be improved (as it's the same one)

**Steps to reproduce**

1.Pick up any PADD or Tricorder, I found them on Deck 1 in the Ready Room and Observation Lounges 
2.Observe the image resolution, even zoomed, the resolution does not improve for the main displays.

**Relevant logs and/or screenshots**

![screen shot 2018-03-10 at 11 02 06 pm](https://user-images.githubusercontent.com/35311046/37261770-6c41dad4-2575-11e8-8171-b1de15fa41f3.png)

![screen shot 2018-03-11 at 9 34 02 pm](https://user-images.githubusercontent.com/35311046/37261774-6e68fd92-2575-11e8-8979-d6c1fad9979e.png)

**Possible fixes**
Go higher resolution on that image file or revert to the ones from previous Stage9 builds.

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
