### ISSUE TITLE
Mac - V0010-QA1 - Shuttle Bay 1 Control Room mesh

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#272]
**Summary**

A "seam" where window meshes meet in the Control Room in Shuttle Bay 1 is incorrectly placed so there's a gap.  This happens several times in the room.

***What is the expected correct behavior?***

There should not be a "seam"

**Steps to reproduce**

1.Travel to the upper level of the Shuttle Bay
2.Enter the Control Room and walk up to the corners where windows meet one another
3.Observe the gaps between meshes.

**Relevant logs and/or screenshots**

![screen shot 2018-03-10 at 11 26 14 pm](https://user-images.githubusercontent.com/35311046/37262136-a6d1af60-2577-11e8-81e7-6954d496a967.png)

**Possible fixes**

Move or extend meshes to meet or overlap slightly

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by HPringles** [comment]
Win bug bug @TheStrato

**Comment by TheStrato** [comment]
Done.

**Comment by jeppelykke** [comment]
it's all around the shuttlebay 

![stage9 screenshot 2018 03 14 - 19 53 23 90](https://user-images.githubusercontent.com/33987322/37425105-8727cfbc-27c2-11e8-81dd-0ed782d3dfe0.png)
![stage9 screenshot 2018 03 14 - 19 53 31 53](https://user-images.githubusercontent.com/33987322/37425106-8743032c-27c2-11e8-8df4-3ab6769df88f.png)
![stage9 screenshot 2018 03 14 - 19 54 18 73](https://user-images.githubusercontent.com/33987322/37425107-87600bfc-27c2-11e8-9d45-c8248712013a.png)

**Comment by jeppelykke** [comment]
Also with walls:

![stage9 screenshot 2018 03 14 - 19 59 55 84](https://user-images.githubusercontent.com/33987322/37425247-f6e14856-27c2-11e8-9ae5-37856b619b96.png)
![stage9 screenshot 2018 03 14 - 20 00 00 35](https://user-images.githubusercontent.com/33987322/37425249-f841b0b4-27c2-11e8-8e7e-d0889fdb5e75.png)

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
