### ISSUE TITLE
Mac - V0010-QA1 - Shuttle Bay 1 Texture/Image Missing

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#273]
**Summary**

The UFP logo on the staircase bannister is missing it's texture.

***What is the expected correct behavior?***

The UFP logo.

**Steps to reproduce**

1.Travel to the Shuttle Bay 1 Forward section
2.Approach the staircase above the ceremonial bell 
3.Face the bell and pan view up to the bannister above, the UFP logo on either side of the words is missing a texture or image file.

**Relevant logs and/or screenshots**

![screen shot 2018-03-10 at 11 32 44 pm](https://user-images.githubusercontent.com/35311046/37262250-5de2653c-2578-11e8-83ab-fcc95e2e4920.png)

**Possible fixes**

Replace the missing file.  It was present in Stage9 V09

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by nkjellman** [comment]
This is on the Windows version too.

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by HPringles** [comment]
Win Mac Bug Accuracy @TheStrato

**Comment by TheStrato** [comment]
Done.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
