### ISSUE TITLE
V0010-QA1 - Picards Quarters Door SFX missing

### ISSUE THREAD

**Issue by trekkeriii** [dapperrobotbear/Stage9#274]
**Summary**

When entering Picards Quarters, no sound sfx plays when door opens/closes. Only one, not both

***What is the expected correct behavior?***

Should hear sound

**Steps to reproduce**

1. Go to Deck 8
2. Enter Picard's quarters first door you come to enter.
3.

**Relevant logs and/or screenshots**

**Possible fixes**

**Comment by nkjellman** [comment]
Still present in QA 2.

**Comment by Jaredsfs1** [comment]
#344

**Comment by scragnog** [comment]
Unable to confirm in-editor. Will see if this is resolved in QA3.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
