### ISSUE TITLE
V0010-QA1 Audio traveling through walls (Season 1 Bridge & Small Shuttle)

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#275]
**Summary**

When the Season 1 bridge is loaded in the Holodeck, you can hear it everywhere on deck 12. Along with that, when a holodeck is running the Season 1 bridge, the lighting outside the holodeck, and in other holodeck programs seems to be affected.

Additionally, when you have flown a small shuttle, you can hear it everywhere on the ship, no matter how far away you go.

***What is the expected correct behavior?***

The Season 1 bridge audio should only be heard when you are inside the program, or when you are outside, and close enough to the door for it to be opened. (I suppose I should also point out that the other bridges are mute when you have the door open, and are in the hallway.) Additionally, the lighting shouldn't change outside the season 1 bridge.

The shuttle should get quieter when you are far away from it.

**Steps to reproduce**
For the Season 1 bridge.
1. Go to the holodeck and run the Season 1 Bridge (2364) program.
2. Walk around the rest of the deck, heck even run a different program in one of the other holodecks and you will still hear it. (Could be a good way to get audio in the All Good Things bridge lol).

For the shuttle audio.
1. Go to one of the shuttle bays.
2. Open the shuttle bay door.
3. Fly one of the small shuttles.
4. When you leave the shuttle, you will continuously hear the audio.

**Comment by jgbr** [comment]
This applies to being in Picard's quarters and hearing bridge noises [Mac] with door shut.

**Comment by HPringles** [comment]
Win Mac Bug @TheStrato

**Comment by TheStrato** [comment]
Done.

**Comment by scragnog** [comment]
these are great catches! Both fixed now for the next QA release :-)

**Comment by Gary-Baggins** [comment]
Holodeck audio confirmed stops as soon as you step out.
Shuttle audio confirmed fades away after a certain distance.
Please close @TheStrato @HPringles

**Comment by jgbr** [comment]
wait till mac check

**Comment by TheStrato** [comment]
@jgbr @ me on here when you have checked this please.

**Comment by Jaredsfs1** [comment]
Confirmed Holodeck audio for 1701 bridge ends when you leave the holodeck.  
Confirmed the shuttle engine sounds fade as you walk away.
Shuttle audio intensity does however continue playing at the same level as when you exit the driver station and does not "fall off" or drop down to "idle", which is a bug in itself.  I'll report it separately.
@TheStrato please close.

**Comment by TheStrato** [comment]
Remaining issues will be put on a new ticket. Other issues resolved. Closing this ticket.
