### ISSUE TITLE
V0010-QA1 You see stars when loading the holodeck program

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#277]
**Summary**

When you load the holodeck program and open the doors, you can see outside into space.

***What is the expected correct behavior?***

You should see the holodeck itself, when the bridge loads.

**Steps to reproduce**

1. Simply run any program.
2. Walk up to the door and let it open quickly.

3. You can repeat it by switching to another program.

**Possible fixes**

Leave the holodeck room enabled. Since you are making a portal there, it shouldn't matter what is behind the doorway. Additionally, if we could end the program from the holodeck programs menu, that would be nice. With this fix, it is just a matter of removing the portal.

**Comment by HPringles** [comment]
# Confirmed Issue

I saw this in testing yesterday, but it's a rendering issue similar to others.

**Comment by nkjellman** [comment]
@TheStrato I thought about it. If you leave the holodeck room loaded while the program is running, the lights will shine on the interior portion of the door. It won't look strangely dark.

**Comment by TheStrato** [comment]
Let's not do a lot of speculating about ways to fix the issues. It is our job to report the bugs and let the pro's decide how they will fix things.

**Comment by scragnog** [comment]
ok, I've done the best solution I can here. Basically, the empty holodeck will now *always* be spawned, so when you switch programs, it'll fade back to the holodeck instead of stars. there's a minor issue where you see the empty holodeck for a split second when walking through the portal, but this is way better than it was I think.

**Comment by jeppelykke** [comment]
@scragnog Confirmed fixed for windows

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
