### ISSUE TITLE
V0010-QA1 - Hallway carpet edge flickering

### ISSUE THREAD

**Issue by JonathanNStewart** [dapperrobotbear/Stage9#278]
**Summary**

Since this may be a more general issue with a general fix, I'll list this minor inconvenience. Where two corridors meet, the edge of the carpet flickers between the two colours of the adjoining carpets. I've attached an image where it's halfway between two colours. It also happens more extremely at the side entrances to Nine Forward.

***What is the expected correct behavior?***

A fixed transition between the two carpets.

**Steps to reproduce**

1. Leave the transporter room, take the turbolift to the right to Stellar Cartography | Starboard.
2. Exit the turbolift and continue straight until an open area with seats.
3. The flickering is at the start of the corridor to Nine Forward to the right.

**Relevant logs and/or screenshots**

![hallwaycarpetflickering](https://user-images.githubusercontent.com/37262529/37270848-06b21cbc-2596-11e8-9d07-b1f24d004b96.png)

**Possible fixes**

Align the two carpets better, or place one a fraction lower than the other.

**Comment by JonathanNStewart** [comment]
#195

**Comment by JonathanNStewart** [comment]
This problem is also mentioned in #195

**Comment by jgbr** [comment]
still present in QA2

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
