### ISSUE TITLE
Mac - V0010-QA1 - NPC noises after disabling them, re-appear as move decks

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#279]
**Summary**

When you disable NPC's anywhere on the ship, you can still hear them walking around and pressing buttons. Also when you move  another map, then they re - appear even though the menu system still has them marked as off. 

***What is the expected correct behavior?***

I guess you shouldn't hear them walking if not present!

**Steps to reproduce**

1. menu system
2.disable NPCs
3.:Listen
4: You have to click it on and off again to get them to go away but noise persists.

**Comment by jgbr** [comment]
This is also happens if you move from an empty bridge, to the conference room and back to the bridge, they come back even with it disabled.

**Comment by dapperrobotbear** [comment]
NPC triggers were adjusted for QA2, reconfirm.

**Comment by jgbr** [comment]
fixed in QA2

**Comment by jgbr** [comment]
Sorry to say but this works everywhere but the computer data core where an NPC appeared.

**Comment by TheStrato** [comment]
@dapperrobotbear Reported as almost fixed. See above

**Comment by HPringles** [comment]
@dapperrobotbear @TheStrato This is fixed for all male NPCs, the female NPCs do not, and have never(I believe) turned off with this function

**Comment by dapperrobotbear** [comment]
We're phasing out the old version of that NPC, so I won't try to make this work for them.

**Comment by jgbr** [comment]
Still in QA3. Stand at the read bridge stations and you can hear people walking about even if disabled.

**Comment by HPringles** [comment]
# Needs Confirmation

**Comment by TheStrato** [comment]
As stated by Dapper, this is an issue with the old NPC's and won't be addressed unless it affects the new NPC's when they are tested. Closing this ticket.
