### ISSUE TITLE
Observation lounge, can't walk around the table

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#28]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

In the Observation lounge off the main bridge, you can't walk around the table near the windows. 

![stage9 screenshot 2017 11 26 - 13 32 06 67](https://user-images.githubusercontent.com/33987322/33240152-dc10c40e-d2b1-11e7-8a42-1c5c2898516d.png)

**Comment by scragnog** [comment]
been meaning to fix this for a while. Thanks for the reminder! All sorted now (table is more centered in the room)
