### ISSUE TITLE
V0010-QA1 - Battle Bridge - No saucer drawn - see maps

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#280]
**Summary**

When on the battle bridge you see corridors of the ship drawn not eh map you are on, not the underside of the saucer [when not separated]. 

***What is the expected correct behavior?***

Underside of saucer

**Steps to reproduce**

1.visit battle bridge
2. look at main view screen
3.

![untitled](https://user-images.githubusercontent.com/37260734/37272936-1dbb86c0-25d0-11e8-8003-4b6462599244.jpeg)

**Comment by jgbr** [comment]
Still in QA2

**Comment by jgbr** [comment]
@TheStrato Mac issue

**Comment by TheStrato** [comment]
Done.

**Comment by dapperrobotbear** [comment]
Please reconfirm against QA4

**Comment by jgbr** [comment]
Removed so view screen just sees lower down view point.

Bottom of saucer is not drawn but no longer shows map so is workable.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugs
