### ISSUE TITLE
V0010-QA1 - Engine crash when leaving main shuttle-bay in shuttlecraft. 

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#281]
When attempting to leave from the main shuttlebay in a normal shuttle the build crashed with the following error.

I attempted this again by leaving the shuttle once I had taken control when still inside the enterprise and the error was the same.

LoginId:2389ca07914a64dd3c1d9ba38a1e5d89
EpicAccountId:

 #0 at 0x7fff5cb78e3e

__pthread_kill Address = 0x7fff5cb78e3e (filename not found) [in libsystem_kernel.dylib]
abort Address = 0x7fff5cad5312 (filename not found) [in libsystem_c.dylib]
__cxa_bad_cast Address = 0x7fff5aab0f8f (filename not found) [in libc++abi.dylib]
default_terminate_handler() Address = 0x7fff5aab1113 (filename not found) [in libc++abi.dylib]
Unknown() Address = 0x7fff5be3beab (filename not found) [in libobjc.A.dylib]
std::__terminate(void (*)()) Address = 0x7fff5aacc7c9 (filename not found) [in libc++abi.dylib]
__cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) Address = 0x7fff5aacc26d (filename not found) [in libc++abi.dylib]
std::__1::__throw_system_error(int, char const*) Address = 0x7fff5aa9f7af (filename not found) [in libc++.1.dylib]
std::__1::mutex::lock() Address = 0x7fff5aa91c93 (filename not found) [in libc++.1.dylib]
GASingleton<gameanalytics::logging::GALogger>::sharedInstance() Address = 0x10083dc29 (filename not found) [in Stage9]
gameanalytics::logging::GALogger::e(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) Address = 0x10083f225 (filename not found) [in Stage9]
gameanalytics::threading::GAThreading::thread_routine(void*) Address = 0x10086163e (filename not found) [in Stage9]
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void* (*)(void*), void*> >(void*) Address = 0x10086231c (filename not found) [in Stage9]
_pthread_body Address = 0x7fff5ccb46c1 (filename not found) [in libsystem_pthread.dylib]
_pthread_body Address = 0x7fff5ccb456d (filename not found) [in libsystem_pthread.dylib]
thread_start Address = 0x7fff5ccb3c5d (filename not found) [in libsystem_pthread.dylib]

**Comment by jgbr** [comment]
Still present in QA2

**Comment by jgbr** [comment]
@TheStrato Mac issue

**Comment by TheStrato** [comment]
Done. And added Crash as well.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
