### ISSUE TITLE
V0010-QA2 Emergency Turbolift Visible Outside

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#282]
Emergency Turbolift visible on the exterior. Leaving the ship from either main or shuttle bay 2. 

What is the expected correct behavior?

Emergency Turbo should not be visible outside.

![image](https://user-images.githubusercontent.com/5162659/37288040-a22e4896-25dc-11e8-8326-1fae2b4f5aab.png)

**Comment by OssiBRI** [comment]
Also the side windows to the left is still just black.

**Comment by Gary-Baggins** [comment]
Confirmed bug. I went straight from transporter room 2 (from game start) to shuttle bay 2 and exited the ship, I did not go to the bridge first.

**Comment by kaadaq** [comment]
Confirmed.   I exited ship via main shuttle bay in a pod, and it was there.  Never visited the bridge.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
