### ISSUE TITLE
V0010-QA2 Corridor sizes

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#283]
**Summary**

Deck sizes different on many decks. Maybe per the plans. Mainly on Deck 10 when leaving ten forward and heading into the core of the saucer. 

***What is the expected correct behavior?***

Check against plans. 

**Steps to reproduce**

1. Walking into the core of the ship from ten forward.
2. Go to Picards quarters from there, some corridors shrink in width others go squat. 
3.

**Relevant logs and/or screenshots**
![untitled](https://user-images.githubusercontent.com/37260734/37295694-b4d07a08-2610-11e8-96e8-7018cf2cc505.jpeg)

![untitled2](https://user-images.githubusercontent.com/37260734/37295786-f0d6d09c-2610-11e8-88f2-37a16e5ce133.jpeg)

**Comment by HPringles** [comment]
# Unconfirmed

I assume these are correct, as the devs have followed the plans when laying them out

@TheStrato Can you confirm?

**Comment by TheStrato** [comment]
@scragnog Can confirm this.

**Comment by jgbr** [comment]
@TheStrato Mac issue

**Comment by TheStrato** [comment]
Done.

**Comment by jeppelykke** [comment]
@HPringles transferred to bugz
