### ISSUE TITLE
V0010-QA2-Deck 1/Bridge - Party Mode Doesn't Work

### ISSUE THREAD

**Issue by HPringles** [dapperrobotbear/Stage9#285]
**Summary**
Activating party mode brings up a black viewscreen and no flashing lights for around 30 seconds and then flashing lights come on.

***What is the expected correct behavior?***
Party mode should play the pongo data and picard clip with sound, have flashing lights sooner.

**Steps to reproduce**

1.Go to the bridge
2.Click the left hand captains chair panel
3.Wait

**Relevant logs and/or screenshots**

![desktop screenshot 2018 03 12 - 16 44 24 14](https://user-images.githubusercontent.com/16962690/37297256-15d63604-2615-11e8-85c9-735c4ba8da08.png)
To begin with
![desktop screenshot 2018 03 12 - 16 47 23 26](https://user-images.githubusercontent.com/16962690/37297271-1cfa0e42-2615-11e8-9703-81624daace77.png)
After about 30 seconds

**Comment by jgbr** [comment]
Replicated on Mac. Also can not get out of it unless you quit and re-enter the program.

**Comment by jgbr** [comment]
@TheStrato Mac and windows bug

**Comment by TheStrato** [comment]
Done.

**Comment by Gary-Baggins** [comment]
Confirmed.

**Comment by TheStrato** [comment]
@Gary-Baggins Confirmed fixed or.... ?

**Comment by Gary-Baggins** [comment]
In QA4 if I go to a low stress area like the unexplored sector then even my machine can run this with little to no lag, there's a slight deviation "when the beat drops" where the lights flash over head a split second before but that's about it.

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
