### ISSUE TITLE
V0010-QA2 - Small wall gap on Main bridge

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#287]
**Summary**
Was walking around the main bridge when noticed i could see small gap in the wall.

***What is the expected correct behavior?***
A wall not emergency turbo lift in the gap. 

**Steps to reproduce**
1. Visit main bridge goto door leading to obs. lounge. 
2. Turn around and look at wall.

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 12 - 18 15 18 86](https://user-images.githubusercontent.com/33987322/37299014-60221c2a-2622-11e8-9208-10a3abd2deb0.png)

**Possible fixes**

**Comment by jgbr** [comment]
replicated on Mac

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by jgbr** [comment]
@TheStrato Mac and windows issue

**Comment by TheStrato** [comment]
Done.

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
