### ISSUE TITLE
V0010-QA2 - Deck 02 | 6627 Cargo Elevator Room all items is mirrored 

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#288]
**Summary**
Visit Deck 02 Room 6627 Cargo Elevator room and noticed the entire rooms props are mirrored. 

***What is the expected correct behavior?***
Read able text on all props!

**Steps to reproduce**
1. Visit Deck 02 Room 6627
2. Look at all text labels.

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 12 - 18 31 06 32](https://user-images.githubusercontent.com/33987322/37299600-0be467ba-2624-11e8-8b70-a2c480cc4a0e.png)
![stage9 screenshot 2018 03 12 - 18 31 12 59](https://user-images.githubusercontent.com/33987322/37299601-0bfef544-2624-11e8-950f-4be21cd54ec1.png)
![stage9 screenshot 2018 03 12 - 18 31 18 66](https://user-images.githubusercontent.com/33987322/37299602-0c19c52c-2624-11e8-8d2b-6b43b42d12fe.png)
![stage9 screenshot 2018 03 12 - 18 31 23 73](https://user-images.githubusercontent.com/33987322/37299603-0c33f8ca-2624-11e8-96c7-1fdfce8a2491.png)

(Paste any relevant logs - please use code blocks  to format console output,
logs, and code as it's very hard to read otherwise.)

**Possible fixes**
Undo mirror of room, and place the props again.

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by HPringles** [comment]
Bug Mac Win Accuracy @TheStrato

**Comment by TheStrato** [comment]
Done.

**Comment by TheStrato** [comment]
@HPringles This is a props label not a graphics label.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
