### ISSUE TITLE
Phaser not aiming where red dot is.

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#29]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

Phaser alignment is way off from where you aiming with mouse. 

![stage9 screenshot 2017 11 26 - 13 31 44 12](https://user-images.githubusercontent.com/33987322/33240156-ee82ba70-d2b1-11e7-8fac-a9ce265b6fe7.png)

**Comment by scragnog** [comment]
known bug. Our implementation of aimoffsets is inaccurate at best. Plans are to overhaul this system for v0.1.0. Will close this for now.
