### ISSUE TITLE
Mac - V0010-QA2 - Transporter 3 bar energise bars in wrong place

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#290]
In short: the 'up and down bars' for 3 pronged energise are in the wrong location are in the wrong location on the transporter room main panel. This applies to all transporter rooms on the miles o Brian deck BAR actually miles one. 
![untitled1](https://user-images.githubusercontent.com/37260734/37300179-3dc65c7c-261d-11e8-9123-b13a5cf4bde9.jpeg)

**Comment by HPringles** [comment]
# Duplicate Bug Report

#230

**Comment by TheStrato** [comment]
#261 is a more complete report. Closing this ticket.
