### ISSUE TITLE
Win - V0010-QA2 - Deck 03 missing walls near room: 3146 & 3135

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#291]
**Summary**
Visited Deck 03 and notices missing walls. 

***What is the expected correct behavior?***
A wall  or 2

**Steps to reproduce**
1. Take turbolift to  03 Shuttlebay 1 (upper) 
2. Get off turbolift at: 04 Shuttlebay officers |  Bow
3. Look to the left and then to the right missing walls.

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 12 - 18 47 03 72](https://user-images.githubusercontent.com/33987322/37300691-e1decc96-2626-11e8-9c88-febd774f63a1.png)
![stage9 screenshot 2018 03 12 - 18 46 55 45](https://user-images.githubusercontent.com/33987322/37300692-e1fed464-2626-11e8-9285-2688396312b1.png)

**Possible fixes**
Insert missing walls.

**Comment by HPringles** [comment]
# Duplicate Bug

#237 @TheStrato

**Comment by TheStrato** [comment]
#237 is a more complete ticket of the same issue. Closing this ticket.
