### ISSUE TITLE
V0010-QA2 -  Saucer Separation missing on Battle Bridge console

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#293]
**Summary**
Went to the Battle Bridge to test Saucer Separation

***What is the expected correct behavior?***
Use console on Battle bridge to activate Saucer Separation

**Steps to reproduce**
1. Goto Battle Bridge 
2. Try use Console

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 12 - 19 20 51 46](https://user-images.githubusercontent.com/33987322/37302085-cfdbaef2-262a-11e8-818d-fe714453ba10.png)

**Possible fixes**
Enable Saucer Separation from console again.

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by HPringles** [comment]
Win Mac Bug @TheStrato

**Comment by TheStrato** [comment]
Done.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
