### ISSUE TITLE
V0010-QA2 - Deck 1 Bridge - Red Alert Stand down Problem

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#294]
**Summary**

If Red Alert is activated and you turn down to yellow Alert, Red Alert stays active and the yellow Indicators are activated also. That looks not right....

***What is the expected correct behavior?***

Red Alert should turn off, then yellow Alert should turn on.

**Steps to reproduce**

1. go to Bridge
2. activate Red Alert
3. activate yellow Alert
4. look around

**Relevant logs and/or screenshots**
![alertissue](https://user-images.githubusercontent.com/33996890/37302131-f7108c54-262a-11e8-9eaa-e1be4b6e4db9.png)

**Possible fixes**

Turn off Red Alert by pressing the yellow Alert Button

**Comment by HPringles** [comment]
@TheStrato Bug, Win,Mac ,

**Comment by TheStrato** [comment]
Done.

**Comment by Gary-Baggins** [comment]
Confirmed bug.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz, (double post: check #Bug 28)
