### ISSUE TITLE
V0010-QA2 - Deck 09 - Nine Forward  (multi bugs) fall though the ship

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#295]
**Summary**
Went to relax in Nine Forward and wanted to step up to the window to take in the view, then fell though the ship.

***What is the expected correct behavior?***
Walking on a solid light/ramp.

**Steps to reproduce**
1. Goto Nine Forward 
2. Step on the lights if you dare :)

**Relevant logs and/or screenshots**
![error](https://user-images.githubusercontent.com/33987322/37302674-7cd9e9ec-262c-11e8-949e-3901e5646ed8.jpg)

**Also issue with Nine Forward door**
You can see though the door when getting near it

![stage9 screenshot 2018 03 12 - 19 26 46 08](https://user-images.githubusercontent.com/33987322/37302682-839a96a0-262c-11e8-9535-b4dd9316af58.png)

**Can see though walls**
![stage9 screenshot 2018 03 12 - 19 36 38 35](https://user-images.githubusercontent.com/33987322/37302786-d43f90ce-262c-11e8-902b-5a1193cdd75e.png)
![stage9 screenshot 2018 03 12 - 19 36 33 23](https://user-images.githubusercontent.com/33987322/37302787-d4581a68-262c-11e8-9f14-f1cdc6427010.png)

 **Possible fixes**
Make Lights, door and walls solid.

**Comment by jgbr** [comment]
@TheStrato MAC and windows

**Comment by TheStrato** [comment]
Done.

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
