### ISSUE TITLE
V0010-QA2 - Torpedo Launches from wrong location II like Issue #271 (MAC Version)

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#296]
Summary

When firing the torpedo from the Tactical station, the torpedo launches from somewhere much above the ship.

What is the expected correct behavior?

Torpedo should launch from the Drive Section. Somewhere in the middle

Steps to reproduce

1.Travel to the Bridge
2.Activate the Tactical console and fire torpedo
3. Torpedo comes from somewhere over the ship

Relevant logs and/or screenshots
![torpedo](https://user-images.githubusercontent.com/33996890/37303002-6c7b99aa-262d-11e8-843c-70f7dc95e87d.png)

**Comment by Sciencekeeper** [comment]
#271

**Comment by HPringles** [comment]
Win Mac Bug @TheStrato

**Comment by TheStrato** [comment]
Done, and added Accuracy too for "not cannon" issues. @HPringles

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
