### ISSUE TITLE
V0010-QA2 - Deck 12 Sickbay Sply. Door has wrong deck number

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#297]
**Summary**
Was looking around in Sickbay when i noticed a high number for Deck 12 

***What is the expected correct behavior?***
Door should be Deck 12 | 

**Steps to reproduce**
1. Visit sickbay

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 12 - 19 59 12 74](https://user-images.githubusercontent.com/33987322/37303885-35dfa29e-2630-11e8-889f-92c404abe4cd.png)

**Possible fixes**
Change Deck number label to 12.

**Comment by HPringles** [comment]
@TheStrato Accuracy

**Comment by TheStrato** [comment]
Done.

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
