### ISSUE TITLE
V0010-QA2 - Holodecks arc gaps

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#298]
**Summary**
If no program is loaded into the holodeck you have the normal Yellow grid room, if you enter it and turn around you can see small gaps at the edge of the Holodeck arc.

***What is the expected correct behavior?***
Clean Arc.

**Steps to reproduce**
1. Enter a holodeck without loading program.
2. Turn around and look at the edge of the Holodeck arc. 

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 12 - 20 04 07 66](https://user-images.githubusercontent.com/33987322/37305290-449f6ebe-2634-11e8-946a-7c8d37be6fb6.png)
![stage9 screenshot 2018 03 12 - 20 03 40 84](https://user-images.githubusercontent.com/33987322/37305291-44bb3e1e-2634-11e8-99a8-1e48d5a5650e.png)

**Possible fixes**

**Comment by jgbr** [comment]
@TheStrato Mac and windows issue

**Comment by TheStrato** [comment]
Done.

**Comment by nkjellman** [comment]
@TheStrato I should mention that the holodeck door frames are missing collisions. Same thing seems to be happening with the large door frames in the main shuttle bay.

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
