### ISSUE TITLE
V0010-QA2 - Replicators  still shows and then removes a previous drink that was already returned to the replicator when ordering a new drink [VID INCLUDED]

### ISSUE THREAD

**Issue by Hamza151** [dapperrobotbear/Stage9#299]
So i put a drink back into the replicator slightly on the edge of the thing and it (as expected) dissapears again. But when ordering a new drink from the replicator the drink i previously mentioned shows up as "being made" alongside the newly ordered drink but then dissapears again (and the newly ordered drink gets replicated as expected)

ive managed to reproduce this 3 times already on three different replicators on two different decks.
sometimes a new drink doesnt get replicated at all and the original "put back" drink is the only one that shows up when doing it. 

**What is the expected Behavior?**

When putting back a drink the drink should not be expected to return for a few seconds when ordering a new drink. 

**How to _Giggles_ "replicate" this issue**

Put a drink slightly off the edge of the replicator and interact with the replicator again. its fairly tedious to aim the drink to be put just right but ive done it three times now.

link to vid evidence: https://youtu.be/KFdcz1g9jqQ

Edit: recreated it some more and managed to input "drink ghost" while recording: https://youtu.be/KMJY1MhlWMg

Edit: Also these videos are hidden on youtube, no one can see it except for the people i sent a link to, which is you guys

**Comment by jgbr** [comment]
@TheStrato Mac and windows issue

**Comment by TheStrato** [comment]
Done.

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
