### ISSUE TITLE
Some bugs via the Discord

### ISSUE THREAD

**Issue by Cacille** [dapperrobotbear/Stage9#3]
There's not much info in each, this is just a collection of the bugs people mentioned overnight during first day release. I collected them all and figured to remember them, submitting them together would be fine. Otherwise Scragnog's gonna forget about em. Feel free to close if bugs are known, and no reply needed. 

 - Ejection into space when sitting in OBS lounge or Captain's chair

- there is an alignment bug in the  corner  left to the door in the observation lounge. You can look through it into the corridor...

- I know you mentioned this in your video bout the observation lounge... but also, the skylight in the bridge, a.k.a. spcacelight, is still not transparent aluminum - it's shiny carbon fiber (or something ;p )~  
-what is this cool, orange light accent to the right of the fish tank - on the wall

- transporter platform ceilings aren't solid

- NPCs spawning literally ON DS9  (NPC falling out of ship really)

- MAC issue - hey I have a problem with fullscreen, I set my resolution and then click fullscreen and apply but I can't click on anything. I can only click in windowed fullscreen if I apply fullscreen I have to force quit the game and restart

**Comment by scragnog** [comment]
all issues resolved except -
- npcs falling out of ship are a hard one to resolve. No solution yet.
- Mac issue - unable to test here to confirm
