### ISSUE TITLE
Deck 29 Room 3913 Lt. Cmd. Worf  (multi bugs)

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#30]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

1. NPC spawns faceing into the wall in the side room. 

![stage9 screenshot 2017 11 26 - 13 38 07 16](https://user-images.githubusercontent.com/33987322/33240178-4a2653d2-d2b2-11e7-9ca4-c129dad9f79f.png) 

2. Any items pickup (phasers, Tricorder) that's droped near his frontdoor (inside room, when faceing out towards the hallway) falls though the ship.

**Comment by scragnog** [comment]
1 is fixed now (as well as some clipping issues I spotted incidentally)

2 is an ongoing bug that has no immediate solution. Some floors don't seem to occlude physics objects when dropped, so they fall through.
