### ISSUE TITLE
V0010-QA2 Missing Wall Collisions In Main Shuttlebay

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#300]
The wall and doors in the Main Shuttle Bay. Where the Onizuka, El-Baz, and Yeager Shuttle Pods spawn have no collision. You can fall out the map. As well as Turbolift wall that brings you the Center Bay door controls and the wall behind the Orville Shuttle Pod. 

What is the expected correct behavior?

Shouldn't be able to walk through the door.

Steps to reproduce

Head to the middle of the Shuttle Bay. Left side maintenance area.
Find the wall with the black window behind the Shuttles. Walk through and fall out.

![image](https://user-images.githubusercontent.com/5162659/37310570-b6859dd8-261a-11e8-9c8b-6667c48d0cfc.png)

![image](https://user-images.githubusercontent.com/5162659/37310591-c2a32b76-261a-11e8-9842-7b597ce207b3.png)

![image](https://user-images.githubusercontent.com/5162659/37310867-b8840010-261b-11e8-9f2c-dc27f7928b27.png)

![image](https://user-images.githubusercontent.com/5162659/37310883-c711950c-261b-11e8-8581-a3af61c8444a.png)

![image](https://user-images.githubusercontent.com/5162659/37310934-f7b5a9d2-261b-11e8-94a0-ab3c89ca521f.png)

![image](https://user-images.githubusercontent.com/5162659/37310967-091260c6-261c-11e8-9ef7-49e2404f6a43.png)

**Comment by HPringles** [comment]
Bug Win Mac Rooms @TheStrato

**Comment by TheStrato** [comment]
Done.

**Comment by Jaredsfs1** [comment]
Confirmed on Mac too in QA2

**Comment by kaadaq** [comment]
Confirmed.  Walked right through the wall by 04:2306 and fell into space.
![image](https://user-images.githubusercontent.com/34050343/37377855-c9a0f870-2702-11e8-86ff-110c9505bd53.png)

**Comment by archer9234** [comment]
Bug QA3 @TheStrato

**Comment by kaadaq** [comment]
Still active as of QA4 @TheStrato

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
