### ISSUE TITLE
V0010-QA2 Main Shuttle Bay Cargo Doors Left Unlocked

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#301]
The left and right doors are allowed to be opened near the front of the Main Shuttle Bay.

What is the expected correct behavior?

Cargo Bay doors should be locked.

Steps to reproduce

Go to the left/right side cargo bay door in the Main Shuttle Bay. 

![image](https://user-images.githubusercontent.com/5162659/37311123-87dd71fc-261c-11e8-9aea-538661ecc7e1.png)

![image](https://user-images.githubusercontent.com/5162659/37311131-8de837c6-261c-11e8-823c-5393bdb3c3ff.png)

![image](https://user-images.githubusercontent.com/5162659/37311200-d4d7f9b4-261c-11e8-8bb0-ebbdab6a12ca.png)

**Comment by nkjellman** [comment]
I don't think that they should be locked. In the previous build there was a bunch of corridors there that aren't loading now.

**Comment by trekkeriii** [comment]
The Phaser ranges are gone. That's where they were.

**Comment by nkjellman** [comment]
@trekkeriii They are loading in my game.

@TheStrato I notice I was getting lag spikes when I would walk by these doors. I don't get freezing in the turbo lift. I am guessing that the lag spikes are related to the hallways here. So you may need to split up that map as it is probably a lot to load at once.

**Comment by trekkeriii** [comment]
Yeah, initially they didn't. Might be related to the lagginess in Q1,

**Comment by nkjellman** [comment]
It may be due to all of the missing textures for that hallway. It probably needs to draw the squares on the fly, and there is a lot of it. The other possibility is that the style hallway they added is higher poly than the regular hallway style seen in the show. The fact that its large may be an issue. On the other hand V9 had lag spike issues when you would leave the Main Shuttle Bay.

**Comment by jeppelykke** [comment]
@HPringles I not moved this, as in HF1 there is a phaser range

**Comment by TheStrato** [comment]
Ticket no longer relevant.
