### ISSUE TITLE
V0010-QA2 Z-Fighting In Main Shuttle Bay

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#302]
Right side of the Main Shuttle Bay door wall has z-fighting issues.

What is the expected correct behavior?

Only one wall piece should be here.

![image](https://user-images.githubusercontent.com/5162659/37311311-28a000a0-261d-11e8-8bd0-2aa913637005.png)

**Comment by HPringles** [comment]
Duped - Unsure which issue - jeppe knows

**Comment by MrPeppow** [comment]
Can Confirm on Linux

**Comment by MrPeppow** [comment]
Not Fixed in HF1

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
