### ISSUE TITLE
V0010-QA2 - Ten Forward Starboard entryway mesh alignment 

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#304]
**Summary**

Gap between meshes on starboard entryway to Ten Forward, from outside facing inside

***What is the expected correct behavior?***

no gap

**Steps to reproduce**

1.Travel to Ten Forward Starboard side
2.Approach entry door.
3.Observe gap on left of door entry.

**Relevant logs and/or screenshots**

![screen shot 2018-03-12 at 6 36 17 pm](https://user-images.githubusercontent.com/35311046/37313449-ac48c57e-2625-11e8-9153-9d8cb6169e75.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by Gary-Baggins** [comment]
Can confirm I have seen this too  
https://cdn.discordapp.com/attachments/422792557605552131/422803995954774026/unknown.png

**Comment by jgbr** [comment]
@HPringles Mac and windows, graphics

**Comment by dapperrobotbear** [comment]
Fixed in >QA4

**Comment by Gary-Baggins** [comment]
Fixed in GM! windows @TheStrato @HPringles

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
