### ISSUE TITLE
V0010-QA2 - Replicator Function (2-issues)

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#305]
**Summary**

Issue 1: If using the replicators anywhere, when you attempt to "grab" the item being replicated too soon it triggers the replicator action instead of collecting the item and can then cause unexpected behavior.

Issue 2: If triggering the replicators anywhere, if you trigger the device twice in quick succession (double-click speed), you get either the issue above, or two objects replicated within one another simultaneously.  The replicator will then continue to operate unexpectedly, including allowing you to collect some of the items, or triggering another round of replications.

***What is the expected correct behavior?***

Issue 1: Grabbing the item under replication should be restricted until the action completes.

Issue 2: The replicator should have a cool-down on triggering so that two objects can't be replicated simultaneously.

**Steps to reproduce**

1.Travel to a replicator (Mine were in 10 forward and the nearby-to-port lounge)
2.Trigger replicator via action button anywhere in it's vicinity
3.Trigger action button again, soon after the first press, while pointing at replicated object 

**Relevant logs and/or screenshots**

Issue 1:
![screen shot 2018-03-12 at 6 38 25 pm](https://user-images.githubusercontent.com/35311046/37313703-c720530c-2626-11e8-8569-1cbda517cf15.png)

Issue 2:
![screen shot 2018-03-12 at 6 41 13 pm](https://user-images.githubusercontent.com/35311046/37313709-ce4aef52-2626-11e8-96ef-2715dc50a193.png)

**Possible fixes**

I'd suggest making the replicator activator into a clickable object (perhaps on the control panel above) to avoid accidental triggering when trying to collect your replicated object too soon (Issue1).

It would also be a good idea to set a delay or cool-down on the trigger in general, to avoid multiple replications (Issue2), or accidentally recycling an object you meant to collect (Issue 1 and Issue 2).

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by dapperrobotbear** [comment]
Fixed in >QA4. Turns out things were still happening in the background when the replicator was triggered again, so I added an inUse boolean to prevent re-activation while it was in progress.

**Comment by Gary-Baggins** [comment]
My attempt to replicate this resulted in the item vanishing in GM1 @dapperrobotbear @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
