### ISSUE TITLE
V0010-QA2 Default Input Conflicts.

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#306]
**Summary**

The default input keys cause conflicts. Roll right conflicts with the use key, move left conflicts with headbob.

***What is the expected correct behavior?***

The keys shouldn't conflict. They also need to be better mapped because the current setup is not very good at all.

**Steps to reproduce**

1. Delete or rename your GameSettings.sav file located in "C:\Users\[USER_NAME]\AppData\Local\Stage9\Saved\SaveGames", or run Stage 9 on a new computer. I am not sure where the GameSettings.sav is located on Mac.

**Possible fixes**

I have designed an appropriate config for the keyboard and mouse, as well as for an Xbox 360/Xbox One/PS3/PS4 controller. I believe this will work for Stage 9. NOTE: It flags a few things as button conflicts, but they aren't since those things are not used in the same context. I do believe that you will be able to make a better setup in the future if we could configure the walking, shuttle flying, and ship flying controls independently.
![2018-03-12 8](https://user-images.githubusercontent.com/29221029/37313776-b4a0de20-261e-11e8-9e4f-1d35654f4fb5.png)
![2018-03-12 9](https://user-images.githubusercontent.com/29221029/37313783-bb9eb396-261e-11e8-9454-d0e0c05d14f8.png)
![2018-03-12 10](https://user-images.githubusercontent.com/29221029/37313797-c2a0aac8-261e-11e8-9cb4-c5604f51af7b.png)
![2018-03-12 11](https://user-images.githubusercontent.com/29221029/37313803-c93156bc-261e-11e8-8ae6-d4b43fab063f.png)
![2018-03-12 12](https://user-images.githubusercontent.com/29221029/37313810-d0a4481e-261e-11e8-8e69-97e000239891.png)
![2018-03-12 13](https://user-images.githubusercontent.com/29221029/37313820-dde3178a-261e-11e8-8a34-026682bf2e6b.png)

For the Shuttle open/close input, as well as the warp button input, it would be RT in this case to be consistent with the turbolift menu.

Additionally the Holodeck arch toggle would be LB.

In the future, I think that when the input is redesigned for separate context, it can be improved, however this will do for now.

**Comment by nkjellman** [comment]
@TheStrato @scragnog I know the comments were removed, but I saw Scragnog's question in my email.

The issue isn't fixed in QA3. It is actually worse. The clicking bug from 009 is back. The mouse does not get sucked into Stage 9. When you click, the game minimizes.

**Comment by nkjellman** [comment]
@TheStrato @scragnog An update. So it seems that I was having the minimize issue because the game started up in Window mode. This seems to happen when you go full screen. I think this is an Unreal Engine issue and not a Stage 9 issue.

Regarding the on click events breaking when you change input, I can confirm now that it is sorta fixed. It is back to the way it was in previous builds where you can only use the left mouse button. However this was to be expected. It is still fully functional with my custom setup.

**Comment by scragnog** [comment]
default input keys are improved now as per #348 

@dapperrobotbear I've confirmed that you can't click on the warp button when you're in the chair. There is a widgetinteraction component on the fps camera, any thoughts?

**Comment by scragnog** [comment]
all fixed now

**Comment by Gary-Baggins** [comment]
No conflicts upon fresh install on windows @TheStrato @HPringles

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
