### ISSUE TITLE
V0010-QA2 Can remove Holodeck Panels

### ISSUE THREAD

**Issue by trekkeriii** [dapperrobotbear/Stage9#308]
**Summary**
I can pick up Holodeck Panel. 

***What is the expected correct behavior?***

Should stay on the wall.
**Steps to reproduce**

1. Grab a phaser
2. Go to Holodeck panel
3. Pick it up

**Relevant logs and/or screenshots**

![20180312212951_1](https://user-images.githubusercontent.com/4651111/37317652-87b94190-263c-11e8-9807-a5d5839fd6bc.jpg)
![20180312202931_1](https://user-images.githubusercontent.com/4651111/37316206-2afa01d6-2634-11e8-9a3e-aa24325ccf24.jpg)
![20180312203834_1](https://user-images.githubusercontent.com/4651111/37316636-9cc00494-2636-11e8-95e9-fbb7656678a7.jpg)

(Paste any relevant logs - please use code blocks  to format console output,
logs, and code as it's very hard to read otherwise.)

Whatever you do, don't load the program from the panel from inside the Holodeck
**Possible fixes**

**Comment by Gary-Baggins** [comment]
Confirmed.

**Comment by Jaredsfs1** [comment]
Confirmed on Mac

![screen shot 2018-03-12 at 9 24 38 pm](https://user-images.githubusercontent.com/35311046/37355473-4237c870-26ba-11e8-9e66-e1e6a9d03986.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by dapperrobotbear** [comment]
Please reconfirm against >=QA4

**Comment by cheveffect09** [comment]
Confirmed Fixed in QA4

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
