### ISSUE TITLE
V0010-QA2 Deck 3 Mesh near top of stairs

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#309]
Summary
The wall does not mesh with the corridor at the top of the split stairs (I went up the left side) from Main Shuttle Bay to Deck 3 (across from the ships' bell, near probe/torpedo).   Didn't see this listed in other Deck 3 reports.

Expected Result:
Mated corner

Reproducible Steps:
1. Ascend stairs closest to the open probe/torpedo casing in Main SHuttle Bay
2. Look at corner at top of stairs

Screenshot:
![image](https://user-images.githubusercontent.com/34050343/37316450-88ca68a4-2635-11e8-97aa-86b232a86a1d.png)

**Comment by kaadaq** [comment]
Also a floor seam, same location:
![image](https://user-images.githubusercontent.com/34050343/37316463-ab2aed10-2635-11e8-92c4-c71dbe8ce0f5.png)

**Comment by scragnog** [comment]
please reconfirm this in QA3. This issue was resolved a while ago, it's possible that it isn't in the QA release you tested.

**Comment by kaadaq** [comment]
NOT fixed.   Still see it in QA3

**Comment by TheStrato** [comment]
Issue not resolved. Placing back in the pipeline.

**Comment by scragnog** [comment]
fiiiiinally fixed! I was looking in the wrong place :-/

**Comment by Sciencekeeper** [comment]
@TheStrato confirmed fix QA4Win

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
