### ISSUE TITLE
Doorframe into Stellar Cartography is to high can't walk over.

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#31]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

When entering  Stellar Cartography just after the main large door, you see a small doorframe before stepping onto the platform. The doorframe from the ground up is to high that you can't walk over it.

![stage9 screenshot 2017 11 26 - 13 53 14 51](https://user-images.githubusercontent.com/33987322/33240199-9e65fce0-d2b2-11e7-9052-272c1ce627b9.png)

**Comment by scragnog** [comment]
Boom! Fixed! Thanks!
