### ISSUE TITLE
V0010-QA2 Deck 3 Tractor Console Strange Behavior

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#311]
Summary
Getting very strange behavior out of the upstairs console that can activate tractor beam. (One on the right in the picture, directly above the runabout)
1. After hitting enter on the console to display the pop-up, and enter again to clear it, moving pointer above the console and hitting enter causes pop-up to flicker on and off, but not selectable.
2. Activating the tractor beam from the right hand console causes view to snap looking down into the carpet.    Alt-mouse moves VERY slowly to try to shift field of view. 
3. Ultimately, I was not able to control anything with it.

Expected Result:
Pop-up only activates when clicking the console.  Once tractor beam is activated, view should be sufficient to see what you are controlling.

Reproducible steps:
(See Summary)

Screenshot:
![image](https://user-images.githubusercontent.com/34050343/37316788-7d29b1b0-2637-11e8-8352-ec8ab1b2bb9f.png)

**Comment by Jaredsfs1** [comment]
@TheStrato  Unable to validate on QA3 - Mac.  Station functions as expected, though it would be nice if the view angle were a little better, it is working as it should.

**Comment by TheStrato** [comment]
@kaadaq Is this still a problem on Win?

**Comment by kaadaq** [comment]
I still had trouble with it in QA3, especially when standing back a few
steps from the console.   Once tractor is on, focus goes to the carpet, and
camera movement gets VERY slow.    Can't see, barely move...

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
