### ISSUE TITLE
V0010-QA2 Main Shuttlebay Bell does not Chime

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#312]
Summary
Ship's bell does not chime.   Looks like the clapper/knocker is missing.

Expected performance
CLANG!

Reproducible Steps
1. Press enter on ship's bell
2. Move it back and forth

Screenshot:
![image](https://user-images.githubusercontent.com/34050343/37317014-e26360f2-2638-11e8-8852-8b1a97a001ad.png)

**Comment by Gary-Baggins** [comment]
Confirmed.

**Comment by HPringles** [comment]
I was able to make this work - will retest to night

**Comment by Jaredsfs1** [comment]
This functions on Mac fine, but does get a little crazy on the physics movement depending on how you move it.

**Comment by TheStrato** [comment]
Reported as intermittent, possibly due to OE. Closing this ticket.
