### ISSUE TITLE
V0010-QA2 Deck 4 - Multiple "Shuttle 05"

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#313]
Summary
All Type 7 shuttlecraft (the big "Papa Bear" ones) seem to have the same "Shuttlecraft 05" label.  

Expected Result:
Unique labels

Reproduce:
Shuttlecraft Sagan and Argo are nose to tail parked by the ship's bell.   Check port and starboard near the stern

Screenshot:
Sagan
![image](https://user-images.githubusercontent.com/34050343/37317177-ad1b58f4-2639-11e8-8320-42397dc3f76a.png)

Argo
![image](https://user-images.githubusercontent.com/34050343/37317190-c0a928e2-2639-11e8-9139-06d0595dbcb2.png)

Tereshkova (also has an issue with name disappearing into the RCS thruster):
![image](https://user-images.githubusercontent.com/34050343/37317238-1f90782e-263a-11e8-9015-d0e4e516224f.png)

**Comment by kaadaq** [comment]
Maybe not a bug, but all those shuttles also appeared to be powered up (nacelles lit)?  Looks kind of weird since they are not flyable and not in use.

**Comment by kaadaq** [comment]
Meanwhile, the mama bear shuttles aren't numbered at all.  They just say "Shuttle":

The Dalison:
![image](https://user-images.githubusercontent.com/34050343/37317464-67011d98-263b-11e8-945a-4f5524bf0899.png)

**Comment by scragnog** [comment]
all issues referenced here fixed for QA3

**Comment by kaadaq** [comment]
All issues appear fixed except for the Tereshkova's name, which is still obscured by the RCS thruster on the port side.

There is still ONE shuttlecraft 05 (The "Nye"), which might still be a duplicate with a shuttlePOD (those tend to have low numbers, although I haven't encountered an 05 so far), but the issue is 95% of the way, so I'd be ok with closing it.

@TheStrato, please weight in!

**Comment by TheStrato** [comment]
@scragnog Can the "Tereshkova" name be move from the naming table for that shuttle to the naming table of a larger shuttle class that would have more space so this name stops being truncated by the RCS?

**Comment by kaadaq** [comment]
Lastly, I just realized that the Jeffries in Shuttle Bay 2 is not numbered in QA3.   One more to do!

**Comment by scragnog** [comment]
all fixed now

**Comment by Sciencekeeper** [comment]
@TheStrato fixed confirmed QA4Win

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
