### ISSUE TITLE
V0010-QA2 - Activate Warp Core Breach While in the core room

### ISSUE THREAD

**Issue by cheveffect09** [dapperrobotbear/Stage9#314]
**Summary**
You are able to activate the warp core breach event while you are in the warp core room by looking at the LCARS panel and activating it through the glass

***What is the expected correct behavior?***
The LCARS panel should not be usable through the glass while in warp core room.

**Steps to reproduce**
1. Go to engineering and into the warp core room
2. stand near the window where the event activation console
3. Click to activate the warp core breach event

**Relevant logs and/or screenshots**
![warp core breach](https://user-images.githubusercontent.com/5516753/37316807-529b7cd4-26b5-11e8-8d15-f1af5d170d23.png)

**Comment by jgbr** [comment]
@TheStrato windows and Mac

**Comment by jgbr** [comment]
Also related to 251

**Comment by Jaredsfs1** [comment]
related to #347

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
