### ISSUE TITLE
V0010-QA2  Exterior Hull Collision with Shuttlepod

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#315]
Summary
Landing shuttle on the saucer section leads to partial mesh collision with escape pods

Expected Result:
Mating surfaces

Reproducible steps
1. Land shuttlepod on raised panels outside of observation lounge

Screenshots:
![image](https://user-images.githubusercontent.com/34050343/37317784-3ec99b5a-263d-11e8-909b-622cfbc7a6ec.png)

![image](https://user-images.githubusercontent.com/34050343/37317815-5a0a704c-263d-11e8-8a34-e6d5ed3dd31a.png)

**Comment by Gary-Baggins** [comment]
I believe this is a known issue and will be fixed sometime in the future, @TheStrato this should probably be closed.

**Comment by TheStrato** [comment]
We will leave it for now.

**Comment by Gary-Baggins** [comment]
Confirmed fixed in GM1 @TheStrato @HPringles

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
