### ISSUE TITLE
V0010-QA2 Shuttlebay 2 Pod Door flashes while looking at console

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#316]
Summary:
The door on the shuttlepod in Shuttle Bay 2 flashes in and out of existence while looking down at the LCARS console.   The label on the door is retained.

Expected result:
Door stays solid

Reproducible Steps
1. Enter shuttle bay 2
2. Approach the console nearest the shuttle pod.
3. Tilt view down toward the console.   (Problem does not occur unless looking down)
4. Shuttlepod hatch will flash in and out of existence.  

Screenshot:
![image](https://user-images.githubusercontent.com/34050343/37318971-77a0272c-2643-11e8-8c62-7a1d140abbaf.png)

**Comment by Gary-Baggins** [comment]
Confirmed.

**Comment by scragnog** [comment]
bounds scale issue. bounds increased to 2

**Comment by kaadaq** [comment]
This is fixed!
