### ISSUE TITLE
V0010-QA2 Deck 9 Crew Quarters slot walls have no collisions

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#317]
**Summary**

The little indented spaces where the crew quarters are on deck 9 have no collisions. You can fall through. Even the floor is not solid.

***What is the expected correct behavior?***

You shouldn't fall through the floor.

**Steps to reproduce**

1. Go to deck 9.
2. Walk up to any one of the crew quarters and walk into the indented area.

**Relevant logs and/or screenshots**

![2018-03-12 14](https://user-images.githubusercontent.com/29221029/37319332-b2657bc0-263c-11e8-8f77-6f82ff60b842.jpg)

**Possible fixes**

The mesh around the door, which makes up the walls and floor of the indentation need to have a collision

 mesh added.

**Comment by Gary-Baggins** [comment]
Confirmed.

**Comment by kaadaq** [comment]
Confirmed. Still an issue in QA3

**Comment by kaadaq** [comment]
Confirmed as still an issue in QA4

**Comment by dapperrobotbear** [comment]
Weird. We've had non-colliding frames for ages. :( Fixed. Reconfirm in >QA4

**Comment by jeppelykke** [comment]
@scragnog Confirmed fixed for: Win - V0010-GM1

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
