### ISSUE TITLE
V0010-QA2 Planet atmospheres don't line up with the planet.

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#318]
**Summary**

Often times the planets atmosphere is misaligned with the planet when you move the ship. It appears to be offset. Sometimes it can stay this way if you leave the helm.

***What is the expected correct behavior?***

The atmosphere should line up with the planet at all times.

**Steps to reproduce**

1. Sit at the helm and rotate the ship.
2. You will notice that the atmosphere seems to have a delay when it moves.

**Relevant logs and/or screenshots**

![2018-03-12 15](https://user-images.githubusercontent.com/29221029/37319778-8366d358-263e-11e8-99e4-a902256f4345.png)

**Possible fixes**

If you can anchor the atmosphere to the planet, so when the planet moves, the atmosphere moves with it, rather than moving them separately, that could solve this issue.

**Comment by jgbr** [comment]
@TheStrato windows and Mac

**Comment by dapperrobotbear** [comment]
Please verify against QA4

**Comment by TheStrato** [comment]
Placed in the pipeline.

**Comment by jgbr** [comment]
Fixed on Mac

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
