### ISSUE TITLE
V0010-QA2 Large door frames lacks collisions.

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#319]
**Summary**

The door frames around large doors seem to lack collisions. So far I found this to be the case in the main shuttle bay and the holodeck.

***What is the expected correct behavior?***

There should be collisions present.

**Steps to reproduce**

1. Go to the main shuttle bay or the holodeck.
2. Walk up to the large  doors. You will notice that the frames are not solid.

**Possible fixes**

Add a collision mesh to the large door frame object.

**Comment by HPringles** [comment]
Can you confirm which doors? The double ones or the bulkhead blast doors?

**Comment by nkjellman** [comment]
![image](https://user-images.githubusercontent.com/29221029/37337216-914d26d2-2681-11e8-9df2-0f57e1629bd1.png)
These style doors.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
