### ISSUE TITLE
[Visual] Season 2 to 7 mainbridge LCARD Sciencestation overlapping other console

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#32]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

![stage9 screenshot 2017 11 26 - 13 30 25 02](https://user-images.githubusercontent.com/33987322/33240308-68da9fb6-d2b4-11e7-99c4-82cbbff425be.png)

**Comment by scragnog** [comment]
temporary fix in-place. This bridge will be getting completely revamped in v0.1.0 so this is just a bodge job.
