### ISSUE TITLE
V0010-QA2 Camera positions for the shuttle and ship are awkward.

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#320]
**Summary**

The camera is way off center. It is also awkwardly close to the ship.

***What is the expected correct behavior?***

Center the camera. Perhaps have 3 3rd person cameras. One that is up close (about the same as now), one that is mid distance, and one that is far away. This will allow players to see the exterior of their vehicle better, but it will also allow them to see the surroundings better.

Additionally, I'm sure you are aware of this one, but it would be better if the camera went around the the ship you are flying.

**Steps to reproduce**

1. Fly the Enterprise, or the shuttle in 3rd person.

**Comment by scragnog** [comment]
agreed. We plan to change this for v11 to give the player zoom and orbit control. Won't be fixed for v10 though.

**Comment by jeppelykke** [comment]
@HPringles transferred to Bugz
