### ISSUE TITLE
V0010-QA1 Arboretum graphical issues

### ISSUE THREAD

**Issue by JonathanNStewart** [dapperrobotbear/Stage9#321]
**Summary**

In the arboretum there is a reflection from light behind the wall, and the grass and leafs are poking through the tiles and the container. The PADD lying on the left when you enter has a low resolution picture, even with the Texture Quality set to Epic.

***What is the expected correct behavior?***

No reflection through walls, the foliage should know where not to grow, and the PADD should heed the graphics settings.

**Steps to reproduce**

1. Walk into the arboretum
2. Pick up the PADD

**Relevant logs and/or screenshots**

![arboretumgraphics](https://user-images.githubusercontent.com/37262529/37325608-32a62322-2654-11e8-8215-8197bf73a302.png)
![arboretumpaddtexture](https://user-images.githubusercontent.com/37262529/37325611-3496ee1e-2654-11e8-9799-fdd876a79fb9.png)

**Possible fixes**

Set walls to block light. Cut the grass, and trim the leaves.

MacBook Air (13-inch, Early 2015)
OS: macOS High Sierra (10.13.3)
Processor: 1.6 GHz Intel Core i5
Memory: 4 GB 1600 MHz DDR3
Video: Intel HD Graphics 6000 1536 MB

**Comment by jgbr** [comment]
Verified on Mac, also with some graphics taking time to go from blur into 'defined' @TheStrato Mac

**Comment by jeppelykke** [comment]
@HPringles transferred to Bugz
