### ISSUE TITLE
V0010-QA1 Items picked up are not held in front of you (Mac)

### ISSUE THREAD

**Issue by JonathanNStewart** [dapperrobotbear/Stage9#322]
**Summary**

When in first-person mode (and having the head bob off, although I'm not sure that matters), if you pick up and object, the object is put in your hand while it stays pointing to the ground. When switching to third-person, the object is held in front of you, and stays in front of you when you switch back to first-person. After dropping the item, your hand can stay in the holding position.

***What is the expected correct behavior?***

The items should be held in front of you.

**Steps to reproduce**

1. Go to replicator, Observation Lounge, Arboretum...
2. Pick up an item

**Relevant logs and/or screenshots**

![aiminglow](https://user-images.githubusercontent.com/37262529/37325864-427cd90c-2655-11e8-8c35-f328d47c11f4.png)
![holdmyhand](https://user-images.githubusercontent.com/37262529/37325893-5a6fb4ee-2655-11e8-9fec-b9d256422063.png)

MacBook Air (13-inch, Early 2015)
OS: macOS High Sierra (10.13.3)
Processor: 1.6 GHz Intel Core i5
Memory: 4 GB 1600 MHz DDR3
Video: Intel HD Graphics 6000 1536 MB

**Comment by Gary-Baggins** [comment]
Can confirm this also happens in Windows along with the red marker attached to the hand in the first image 
@TheStrato please tag Windows

**Comment by TheStrato** [comment]
Done.

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
