### ISSUE TITLE
V0010-QA1 Ready Room tricorder glitch

### ISSUE THREAD

**Issue by JonathanNStewart** [dapperrobotbear/Stage9#323]
**Summary**

When entering the Ready Room, and standing in just the right spot and looking in the right direction (I know, horrible for reproducibility), the tricorder on Picard's desk is projecting black triangles. This may be because some of the vertices are being transformed in the wrong way. I tried to reproduce this, but changing graphics settings didn't work the second time. Will continue trying.

***What is the expected correct behavior?***

No black triangles.

**Steps to reproduce**

1. Walk into the ready room
2. Look in the direction of the desk

**Relevant logs and/or screenshots**

![tricorderprojecting](https://user-images.githubusercontent.com/37262529/37326159-81e72e52-2656-11e8-87c5-cdb5ded017a2.png)

**Possible fixes**

Turn off some of the graphical parts of the tricorder.

MacBook Air (13-inch, Early 2015)
OS: macOS High Sierra (10.13.3)
Processor: 1.6 GHz Intel Core i5
Memory: 4 GB 1600 MHz DDR3
Video: Intel HD Graphics 6000 1536 MB

**Comment by jgbr** [comment]
Could not replicated on Mac. The tricorder does however fall through the floor compared to other objects in the room. You can also put things through Picards head but when your drop them, they bounce of the leading edge. Another ticket has raised the issue of hearing bridge noises while ready room doors are closed. @HPringles Mac graphics
