### ISSUE TITLE
V0010-QA2 Random fall out of turbo lifts when changing destination 

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#325]
When attempting to changing direction or where you want to go, the map unloads and you just free fall from space. No ship is visible but outside is.

In this case: I clicked Bridge Bow and then changed Bridge Aft and it chucked me out. 

I then tried this by visiting deck two one place on the deck and then another and it happened again. where a free fell from the ship. I looked up and could see the turbo lift arriving at the map, which was drawn but not the ship.

I then tried Deck 36 and then Deck 10 and it did not happen. So it is limited to changing destination when going to locations on the same deck.

**Comment by Jaredsfs1** [comment]
I think this is more related to specific movement's that the turbo makes,  or specific locations on the turbo network.  I notice it occurs not specifically with moving from one deck to another point on the same deck, but from certain turbo stops or at specific times when the turbo changes direction on the way between stops.  (Deck 8 is a strong offender, I get thrown out leaving Deck 8 - Starboard, Port, and Battle Bridge)

**Comment by jgbr** [comment]
Hmm, this only applied to me when going between locations on the same deck. Maybe its a combination...

**Comment by Jaredsfs1** [comment]
It stands to reason that moving from one turbo on a deck to another on the same deck, makes more forward, backward, and side-to-side movements than going between decks (which would be more up and down)

**Comment by jgbr** [comment]
Yes but I definitely only got it when going between a location on the same deck. Never had an issue with going between decks.

**Comment by MrPeppow** [comment]
Confirmed on Linux

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
