### ISSUE TITLE
V0010-QA2 Deck sounds loading before turbo lift arrives or doors open

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#326]
Summary:

Noises of the deck such as engineering, have the sounds loading before the lift arrives, door opens or when the door is closed. A good example is in main engineering where the warp core 'boom' is apparent. I have tested this elsewhere int he ship for example on the bridge: where you can head bridge noises with the ready room door shut, observation room passage closed and so forth.

**Comment by jgbr** [comment]
Still in QA3

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
