### ISSUE TITLE
V0010-QA2 Duplicate Miles O'Brien.

### ISSUE THREAD

**Issue by Gary-Baggins** [dapperrobotbear/Stage9#327]
Miles O'Brien should only be in transporter room 2 but he can also be found in transporter room 4, I went back and checked QA1 where TR4 is labelled as TR2 so i assume the model is doubles with only the sign changed.

@HPringles please tag Windows, NPC and rooms

**Comment by jgbr** [comment]
The issue from ticket 264 was resolved [double doors] and doors are number correctly, however miles is in TR4 and TR2. Confirmed on a Mac as well. @TheStrato @HPringles Mac

**Comment by HPringles** [comment]
Done

**Comment by scragnog** [comment]
this should be resolved now for qa3

**Comment by HPringles** [comment]
# Resolved In QA3

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
