### ISSUE TITLE
V0010-QA1 Left door of shuttlepods disappearing

### ISSUE THREAD

**Issue by JonathanNStewart** [dapperrobotbear/Stage9#328]
**Summary**

When standing next to a shuttlepod, depending on the angle you look at it, the left door can zap in and out of existence.

***What is the expected correct behavior?***

The side of the shuttlepod should always be opaque.

**Steps to reproduce**

1. Stand next to a shuttle, or sit in one while looking at another
2. Change your viewing angle
3. Sometimes the door will disappear

**Relevant logs and/or screenshots**

![dontleavethedooropen](https://user-images.githubusercontent.com/37262529/37339573-b8652a2c-2680-11e8-8a06-e90114209d1c.png)

**Possible fixes**

Making the door mesh fixed should solve the problem, since the rest of the shuttle is unaffected.

MacBook Air (13-inch, Early 2015)
OS: macOS High Sierra (10.13.3)
Processor: 1.6 GHz Intel Core i5
Memory: 4 GB 1600 MHz DDR3
Video: Intel HD Graphics 6000 1536 MB

**Comment by Jaredsfs1** [comment]
Confirmed. Still present in Mac on QA2. Occurs in both Shuttlebays 1 and 2

First Device:
![screen shot 2018-03-12 at 9 38 55 pm](https://user-images.githubusercontent.com/35311046/37363910-7fc146c0-26cf-11e8-826c-5fd47f7aa815.png)
![screen shot 2018-03-12 at 9 39 11 pm](https://user-images.githubusercontent.com/35311046/37363911-7fcff1b6-26cf-11e8-8ff4-328feae387a0.png)

iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

Second Device:
<img width="1069" alt="screen shot 2018-03-13 at 2 50 07 pm" src="https://user-images.githubusercontent.com/35311046/37363952-9585fc62-26cf-11e8-9b86-d6dc7e7c1e99.png">
<img width="1067" alt="screen shot 2018-03-13 at 2 50 39 pm" src="https://user-images.githubusercontent.com/35311046/37363953-95935f38-26cf-11e8-8fd5-5ae365db384f.png">

MacBook Pro (Retina, 13-inch, Early 2015)
2.7 GHz Intel Core i5
16 GB 1867 MHz DDR3
Intel Iris Graphics 6100 1536 MB

**Comment by kaadaq** [comment]
Similar to #316

**Comment by MrPeppow** [comment]
Confirmed in Linux QA1 
![screenshot_20180314_135329](https://user-images.githubusercontent.com/13747941/37403596-9abc1002-278f-11e8-9858-53734e4f825a.jpeg)

**Comment by MrPeppow** [comment]
The seats on the inside appear and disappear randomly when moving around

**Comment by MrPeppow** [comment]
@HPringles Tag Linux

**Comment by HPringles** [comment]
# Not fixed - GM1

**Comment by MrPeppow** [comment]
Fixed in HF1 @TheStrato @HPringles

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
