### ISSUE TITLE
V0010-QA1 Meshes sticking out of saucer hull

### ISSUE THREAD

**Issue by JonathanNStewart** [dapperrobotbear/Stage9#329]
**Summary**

Parts of the deck 3 and 4 meshes stick through the outer hull. These include the phaser range, the cargo elevator, and three other unidentifiable parts. As a bonus, the floor of the main shuttlebay extends for about a centimetre into the corridor leading to the starboard phaser range. These meshes appear on both sides of the hull, apart from the one closest to the main shuttlebay door, which seems to only appear on the starboard side.

***What is the expected correct behavior?***

Nothing should stick through the outer hull.

**Steps to reproduce**

1. Leave the ship via the main shuttlebay
2. Fly past the left or right side of the main shuttlebay
3. Continue to the cargo elevator hatches

**Relevant logs and/or screenshots**

![cleanyourmeshes](https://user-images.githubusercontent.com/37262529/37340181-e5fb584c-2682-11e8-91b1-58b2437b5dbd.png)
![cargoculled](https://user-images.githubusercontent.com/37262529/37340394-96e8667c-2683-11e8-8e71-31ce8f02455d.png)

**Possible fixes**

Clean up your meshes.

MacBook Air (13-inch, Early 2015)
OS: macOS High Sierra (10.13.3)
Processor: 1.6 GHz Intel Core i5
Memory: 4 GB 1600 MHz DDR3
Video: Intel HD Graphics 6000 1536 MB

**Comment by HPringles** [comment]
# Fixed for QA2

**Comment by TheStrato** [comment]
Fixed in QA2. Closing the ticket.
