### ISSUE TITLE
[Visual] Generation Bridge, Lcards overlapping and doorsigns

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#33]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

Lcards overlapping.
![stage9 screenshot 2017 11 26 - 14 23 47 77](https://user-images.githubusercontent.com/33987322/33240538-87df9288-d2b7-11e7-8804-e3255b485e19.png)
![stage9 screenshot 2017 11 26 - 14 07 30 05](https://user-images.githubusercontent.com/33987322/33240341-f6eb87f2-d2b4-11e7-8faf-dd11b628e3c7.png)

Door signs should be DECK 1, and also some of them have text behind them.

![stage9 screenshot 2017 11 26 - 14 12 50 30](https://user-images.githubusercontent.com/33987322/33240348-0d54e11e-d2b5-11e7-8119-8e385dbdf7bd.png)
![stage9 screenshot 2017 11 26 - 14 13 04 65](https://user-images.githubusercontent.com/33987322/33240349-0d6c2860-d2b5-11e7-9349-2ea4fa3bb132.png)
![stage9 screenshot 2017 11 26 - 14 13 15 38](https://user-images.githubusercontent.com/33987322/33240350-0d826ad0-d2b5-11e7-987f-fae2803724f0.png)
![stage9 screenshot 2017 11 26 - 14 17 59 80](https://user-images.githubusercontent.com/33987322/33240351-0d9a1338-d2b5-11e7-8b27-ad7f914d094a.png)

**Comment by scragnog** [comment]
all fixed!
