### ISSUE TITLE
V0010-QA1 Deck 3: no collision and missing mesh next to cargo elevator

### ISSUE THREAD

**Issue by JonathanNStewart** [dapperrobotbear/Stage9#330]
**Summary**

In the corridor on deck 3 right outside the cargo elevator, there are some meshes missing. The wall separating the corridor from the cargo elevator has no collision, so you can walk right through and fall down to deck 4. There's also an interesting light source on the cargo elevator wall that should be taken care of.

***What is the expected correct behavior?***

The corridor should be closed off, and the wall should be impenetrable.

**Steps to reproduce**

1. Go to the corridor on deck 3 next to the cargo elevator near e.g. door 03-7337
2. Carefully look to your left and right
3. Cross the wall

**Relevant logs and/or screenshots**

![cargo](https://user-images.githubusercontent.com/37262529/37340818-f001dc38-2684-11e8-9ea8-a2a64363977d.png)

**Possible fixes**

Add a mesh, and add collision detection to the wall.

MacBook Air (13-inch, Early 2015)
OS: macOS High Sierra (10.13.3)
Processor: 1.6 GHz Intel Core i5
Memory: 4 GB 1600 MHz DDR3
Video: Intel HD Graphics 6000 1536 MB

**Comment by TheStrato** [comment]
Duplicate. Closing this ticket.
