### ISSUE TITLE
V0010-QA2 - Ship not drawn on external conn control view [Mac]

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#331]
Summary:

When sat in conn position and V pressed to view outside the ship is not drawn. The ship is moveable. This applies when looking externally at the ship in warp, at any system or otherwise.

I tested this over earth and same applies for example.

However this does not apply if you take a shuttle outside or walk on the hull. It only applies when at the conn. 

Note: Bridge kind of drawn!

![untitled](https://user-images.githubusercontent.com/37260734/37341227-8c68074a-26b8-11e8-8516-e1913db87532.jpeg)

**Comment by jgbr** [comment]
@HPringles graphics and Mac , seems to be Mac only

**Comment by HPringles** [comment]
Known issue. Present on both platforms. Duplicate bug. Can I close @thestrato

**Comment by jgbr** [comment]
eh how come people are posting pictures of it working on windows ?

**Comment by HPringles** [comment]
Changing viewscreen mode fixes it

**Comment by jgbr** [comment]
screen artefacts still happen when doing it that way. Theres something there.

**Comment by HPringles** [comment]
It's the same on Windows

**Comment by HPringles** [comment]
It's the same on Windows

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
