### ISSUE TITLE
V0010-QA1 Two viewpoints at the main viewer

### ISSUE THREAD

**Issue by JonathanNStewart** [dapperrobotbear/Stage9#333]
**Summary**

This one is a bit hard to describe. When standing right next to the main viewer on the bridge, and looking down, up, and to the sides, a shell seems to creep up on the general view from different directions but always along a straight line, with a slightly offset view, causing double vision. This may be because you're clipping through the mesh of the view screen and the projected image and actual image are offset from each other.

***What is the expected correct behavior?***

There should be no difference no matter where you look.

**Steps to reproduce**

1. Walk right up to the main viewer on the bridge
2. Look all the way down, or up, and to the sides
3. Parts of the view will be covered by another view

**Relevant logs and/or screenshots**

![twofaced](https://user-images.githubusercontent.com/37262529/37341806-57bc3348-2688-11e8-9103-e858659b0656.png)
![seeingdouble](https://user-images.githubusercontent.com/37262529/37341808-5a5dfdfc-2688-11e8-8270-b3d207fdb216.png)

**Possible fixes**

Align the two views from within and without the bridge. Alternatively, I should drink less.

MacBook Air (13-inch, Early 2015)
OS: macOS High Sierra (10.13.3)
Processor: 1.6 GHz Intel Core i5
Memory: 4 GB 1600 MHz DDR3
Video: Intel HD Graphics 6000 1536 MB

**Comment by scragnog** [comment]
fixed for QA3. We've just blocked the player from getting quite so close to the viewscreen now, so they shouldn't be able to lean their head through the screen.

**Comment by HPringles** [comment]
# Resolved in QA3

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
