### ISSUE TITLE
V0010-QA1 Very different lighting in first- and third-person shuttle view

### ISSUE THREAD

**Issue by JonathanNStewart** [dapperrobotbear/Stage9#334]
**Summary**

When switching between first- and third-person, the lighting changes drastically. This may be related to viewing angle, as Picard can look Caucasian or African depending on angle. The pictures below were taken less than a second apart.

***What is the expected correct behavior?***

The view should basically be the same.

**Steps to reproduce**

1. Fly a shuttle
2. Do a saucer separation to reproduce this exact effect
3. Switch between first- and third-person view

**Relevant logs and/or screenshots**

First-person view
![thelightworld](https://user-images.githubusercontent.com/37262529/37342366-f5ea02a6-2689-11e8-9740-c411179768fd.png)
Third-person view
![thedarkworld](https://user-images.githubusercontent.com/37262529/37342368-f75cc8f8-2689-11e8-8e6e-d9568857c772.png)

**Possible fixes**

Standardise the lighting in some way. Seeing as how many headaches the lighting has been giving you, I know that's not an easy task.

MacBook Air (13-inch, Early 2015)
OS: macOS High Sierra (10.13.3)
Processor: 1.6 GHz Intel Core i5
Memory: 4 GB 1600 MHz DDR3
Video: Intel HD Graphics 6000 1536 MB

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
