### ISSUE TITLE
V0010-QA2 - Deck 25 Nacelle Control Plasma Stream Animation

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#335]
**Summary**

The Plasma stream in Nacelle Control can glitch and become invisible from certain angles, and can remain visible when the injector is disabled.

***What is the expected correct behavior?***

When viewing the active plasma stream, it should be visible from all allowed player positions in the room.  When viewing the deactivated stream space the stream should dissolve or vanish.

**Steps to reproduce**

1.Go to Nacelle Control
2.Unlock the maintenance door from the control on the center console
3.Approach the maintenance door and look through at the plasma stream
4. Observe the stream,  the injectors may be illuminated with plasma running between them, but the stream trailing off into the nacelle housing will be missing.

**Relevant logs and/or screenshots**

![screen shot 2018-03-12 at 10 40 29 pm](https://user-images.githubusercontent.com/35311046/37354793-da358f92-26b8-11e8-8a93-c1e6623ea5b5.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by jgbr** [comment]
Confirmed. @HPringles Mac , need a windows check

**Comment by MrPeppow** [comment]
Confirmed on Linux QA1 @HPringles

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
