### ISSUE TITLE
V0010-QA2 - Deck 25 Nacelle Control Hatch Audio

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#336]
**Summary**

There is no audio clip playing when I close the Nacelle Control hatch, though there is audio when opening it.

***What is the expected correct behavior?***

One of the larger door closing audio clips is expected.

**Steps to reproduce**

1.Go to nacelle control
2.trigger the open hatch control in the central console 
3.wait for the hatch to remain open for a moment
4.trigger the close hatch control
5. observe no audio associated with the close animation.

**Relevant logs and/or screenshots**

![screen shot 2018-03-12 at 10 41 57 pm](https://user-images.githubusercontent.com/35311046/37355055-6f5221e4-26b9-11e8-93e0-862759d822bb.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by jgbr** [comment]
Confirmed issue @HPringles Mac, needs windows confirm

**Comment by MrPeppow** [comment]
Confirmed on Linux QA1 @HPringles

**Comment by dapperrobotbear** [comment]
Please confirm this against QA4

**Comment by HPringles** [comment]
Changed labels to match

**Comment by Gary-Baggins** [comment]
Confirmed fixed in GM1 @TheStrato @HPringles

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
