### ISSUE TITLE
V0010-QA2 - Veridian Asteroids vanishing

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#338]
**Summary**

At the Veridian location, if you move the enterprise or shuttle closer to the asteroid field in the planet's rings you can experience unexpected visual issues where they flicker or dissapear. (Also, they have no collision with the Enterprise or Shuttlecraft.)

***What is the expected correct behavior?***

The asteroids are persistent. And collide with the hull of ships.

**Steps to reproduce**

1.Warp the ship to Veridian
2.Take the Conn and move the ship closer to the planet's rings
3.From various on-board locations, panning your view while looking at the asteroids results in all of them flickering in and out of existence or vanishing altogether. 

**Relevant logs and/or screenshots**

Observation Lounge (Panning camera right)
![screen shot 2018-03-12 at 9 16 13 pm](https://user-images.githubusercontent.com/35311046/37358806-5d3f42b2-26c2-11e8-9fab-db3424ae1985.png)
![screen shot 2018-03-12 at 9 16 16 pm](https://user-images.githubusercontent.com/35311046/37358807-5d4c6fe6-26c2-11e8-80a3-c96bd108aa22.png)
![screen shot 2018-03-12 at 9 16 19 pm](https://user-images.githubusercontent.com/35311046/37358808-5d66e826-26c2-11e8-935c-b9e959efc6d5.png)

Shuttlebay 2 (Panning camera left)
![screen shot 2018-03-12 at 9 36 59 pm](https://user-images.githubusercontent.com/35311046/37358838-74db2436-26c2-11e8-84d9-59e5e776a924.png)
![screen shot 2018-03-12 at 9 37 01 pm](https://user-images.githubusercontent.com/35311046/37358839-74ef8dae-26c2-11e8-9eec-7e3fa07c1dd2.png)
![screen shot 2018-03-12 at 9 37 04 pm](https://user-images.githubusercontent.com/35311046/37358840-74fd5f92-26c2-11e8-8836-aacac4328ec7.png)
![screen shot 2018-03-12 at 9 37 07 pm](https://user-images.githubusercontent.com/35311046/37358841-75091e86-26c2-11e8-8270-0d18241280ff.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by HPringles** [comment]
The collisions are known, the hull currently has no collisions.

@jgbr Can you confirm this bug?

**Comment by scragnog** [comment]
is anyone able to confirm the asteroids disappearing issue? The collision issue won't be resolved in v10, but I'd like to figure out what's going on with the asteroids vanishing as I can't replicate this here.

**Comment by jgbr** [comment]
I can confirm this as a bug as per described, on a Mac.

**Comment by Jaredsfs1** [comment]
@TheStrato or @HPringles you can remove needs validation on this one, since jgbr sees it too, at least on Mac...

**Comment by TheStrato** [comment]
Done.

**Comment by jeppelykke** [comment]
@HPringles transferred to bugz
