### ISSUE TITLE
[Visual] All good things bridge, Sciences station 1 LCARDs over lapping other console

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#34]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

Lcards overlapping other console

![stage9 screenshot 2017 11 26 - 14 23 47 77](https://user-images.githubusercontent.com/33987322/33240393-8b458f1a-d2b5-11e7-992c-c814a14f90a8.png)

**Comment by scragnog** [comment]
temp workaround applied, in lieu of replacement bridge for v0.1.0
