### ISSUE TITLE
V0010-QA2 - Shuttlebay 1 hover/float behavior

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#340]
**Summary**

Shuttles in Shuttlebay 1 float slowly to the ground when moved or activated by the player character.  Shuttles in Shuttlebay 2 do not exhibit this behavior.

***What is the expected correct behavior?***

Not sure which is the expected behavior.  I personally prefer when they hover in place without moving, especially because this also occurs while out in space where I'm sometimes trying to get a screen capture or maneuver into tight spaces or landing spots (making it hard to do so as the shuttles anchor as soon as they contact surfaces).

**Steps to reproduce**

1.Travel to Shuttlebay 1 and enter a shuttle
2.activate the control station to pilot the shuttle
3.press space bar to maneuver up into the air
4. release controls and observe the float down to the deck.  Alternatively step away from the control station or exit the shuttle, and observe it float to the ground.
5. travel to Shuttlebay 2 and enter a shuttle
6.activate the control station to pilot the shuttle
7.press space bar to maneuver up into the air
8. release controls and observe the shuttle remain in place.  Alternatively, step away from the control station or exit the shuttle, and observe it remain in place.
9.  (Flying the shuttle from one bay to the other has no effect, a shuttle from Shuttlebay 1 always acts this way, and a shuttle from Shuttlebay 2 always acts the other way, irrespective of location in game or on map.)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by scragnog** [comment]
resolved in QA4. Type 6, Type 15 and Runabout all have gravity when within shuttlebays, but do not when outside the ship.

**Comment by Gary-Baggins** [comment]
Confirmed in shuttle bays 1 and 2 (except the runabout in bay 2) behaviour is as expected (shuttles slowly float to the floor in the bays and stay static in space) @TheStrato @HPringles

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
