### ISSUE TITLE
V0010-QA2 Saucer seperation , turbolift system still works to visit saucer locations. 

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#341]
You can visit locations in the saucer section even when separated.

I activated saucer separation via the Type 6 shuttle.
I re-entered the ship and went to the turbolfit and ask for deck 10, I arrived at deck ten computer core.
I traveled to ten forward to see the saucer has redocked!

As a side note,  I had red alerted activated before leaving the ship, when re-entering the mysterious turbo lift adventure, it was not at red alert.

**Comment by HPringles** [comment]
# Confirmed - Wont Fix

I believe the devs are not at the stage to be implementing persistence.

@scragnog can you confirm?

**Comment by scragnog** [comment]
confirmed. This is something we want to do, but it requires a lot of modifications for the ship (and turbolifts mostly) to determine if the saucer is or isn't present. Won't be in v10, but we plan to investigate this later.

**Comment by TheStrato** [comment]
Long term obvious goal. Closing this ticket.
