### ISSUE TITLE
V0010-QA2 - Bridge Ceiling Window collision-less

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#342]
**Summary**

There is no collision map for the bridge ceiling porthole.  Phaser fire can pass straight through it.

***What is the expected correct behavior?***

Glass or just collision for objects traveling through the porthole.

**Steps to reproduce**

1.travel to the observation lounge, collect phaser from conference table
2.go to the bridge, fire phaser through ceiling porthole
3.observe phaser fire travel through the porthole and strike any objects outside the ship (including the SkyBox!)

**Relevant logs and/or screenshots**

![screen shot 2018-03-12 at 9 17 28 pm](https://user-images.githubusercontent.com/35311046/37361016-3d5119ac-26c8-11e8-85a5-6bb7d3b6109b.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by scragnog** [comment]
very similiar to #343 in that phasers use line of sight detection, and they can see through the glass, so the beam passes through. No easy solution currently.

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
