### ISSUE TITLE
V0010-QA2 - Captain's Quarters Deck 8 Windows collision-less

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#343]
**Summary**

There is no collision map for the Captain's Quarters on Deck 8. Phaser fire can pass straight through it.

***What is the expected correct behavior?***

Glass or just collision for objects traveling through the porthole.

**Steps to reproduce**

1.travel to Deck 8, captain's quarters, collect phaser from desk
2.face any window in the room, fire phaser through the porthole
3.observe phaser fire travel through the porthole and strike any objects outside the ship (including the SkyBox!)

**Relevant logs and/or screenshots**

![screen shot 2018-03-12 at 10 24 28 pm](https://user-images.githubusercontent.com/35311046/37362355-5285ed22-26cb-11e8-8cc2-188e52a1ae01.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by HPringles** [comment]
# Needs Confirmation

**Comment by jgbr** [comment]
replicated on Mac @HPringles

**Comment by scragnog** [comment]
collision issue resolved. Phasers do use a line trace and might not trace to collision box, but the player could jump out these windows before, no more!

**Comment by jgbr** [comment]
fixed/

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
