### ISSUE TITLE
V0010-QA2 - Captain's Quarters - Deck 8 - Door Audio-less

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#344]
**Summary**

The Starboard-side entryway door into the Captains Quarters does not make noise when used.

***What is the expected correct behavior?***

Standard door slide sound clip.

**Steps to reproduce**

1.Travel to Deck 8, Captains Quarters
2.Use the Starboard-side door to enter and/or exit the quarters
3.Observe no audio clip play upon door activation

**Relevant logs and/or screenshots**

![screen shot 2018-03-12 at 10 25 44 pm](https://user-images.githubusercontent.com/35311046/37366205-326f3e98-26d6-11e8-87e3-09a83ff891fd.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by OssiBRI** [comment]
See [this one](https://github.com/dapperrobotbear/Stage9/issues/274).

**Comment by TheStrato** [comment]
Duplicate. Closing this ticket.
