### ISSUE TITLE
V0010-QA2 - Shuttlebay 1 main doorway texture/clipping issue

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#346]
**Summary**

Depending on the lighting conditions, the wall just outside the Shuttlebay 1 on port and starboard sides can look poorly textured.  It appears that two layers are competing for the same space (exterior/interior).

***What is the expected correct behavior?***

Smooth wall on both sides of the entrance.

**Steps to reproduce**

1.Travel to shuttlebay 1
2.Open the shuttlebay door
3.Observe the wall outside and to the right, and outside and to the left having clipping errors.
4.This can be hard to spot in darker lighting conditions.  See attached screenshot for extreme example.

**Relevant logs and/or screenshots**
![screen shot 2018-03-12 at 11 23 32 pm](https://user-images.githubusercontent.com/35311046/37369883-dd22b0e0-26e0-11e8-86a0-7a58a7e3f24a.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by Jaredsfs1** [comment]
(Ignore the surface of Mars intersecting the "floor" of Deck 3.)

**Comment by scragnog** [comment]
confirmed and fixed for QA4

**Comment by EazyCheeze1978** [comment]
I'm pretty sure the only flickering I saw was the force field, so I'd call this one fixed.

**Comment by Gary-Baggins** [comment]
Not seeing this at any graphics level (low/med/high/epic) confirmed fixed @TheStrato @HPringles

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
