### ISSUE TITLE
V0010-QA2 Warp Core Breach Event Button

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#347]
The Button that triggers the core breach event has no distance limit. You can click it across the end of the room. 

What is the expected correct behavior?

Button trigger should only work when your next to the console. 

Steps to reproduce

Stand anywhere in the room. Where you can see the button. Aim the crosshair on the button. It will trigger the event. 

![image](https://user-images.githubusercontent.com/5162659/37371109-b5721596-26e4-11e8-881a-dc850fd05f81.png)

**Comment by jgbr** [comment]
verified on Mac and in an earlier ticket

**Comment by Jaredsfs1** [comment]
I'm actually cool with that, and it doesn't break immersion because you can trigger it at the station if you wish.  This lets you choose whether to be trapped in the Core chamber, the Chief Engineer's office, or able to run to the turbo and escape!

**Comment by scragnog** [comment]
fixed for qa3. You must now be standing very near to the console to trigger it.

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
