### ISSUE TITLE
V0010-QA1 moving sideways defaults to X and Z, not A and D

### ISSUE THREAD

**Issue by MrPeppow** [dapperrobotbear/Stage9#348]
Summary

The default input keys are mapped to the arrow keys and W,S,X,Z

What is the expected correct behavior?

The keys should be mapped to arrow keys and W,A,S,D

**Comment by MrPeppow** [comment]
@@TheStrato

**Comment by MrPeppow** [comment]
Probably related to issue #306

**Comment by nkjellman** [comment]
Not just that. The USE key is set to E, which interferes with ROLL RIGHT.

Additionally, the alt camera key is awkward. I think the right mouse button would be better. It isn't used in the same context as zoom so theres no issue there.

**Comment by scragnog** [comment]
strafe set to a and d now, so full wasd movement.
roll left is q, roll right is e, interaction key is now f.

**Comment by Gary-Baggins** [comment]
Verified fixed in windows @TheStrato @HPringles

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
