### ISSUE TITLE
V0010-QA1 NPCs have black heads

### ISSUE THREAD

**Issue by Gary-Baggins** [dapperrobotbear/Stage9#349]
NPCs should have proper skin texture on their heads

@TheStrato please tag Linux and npc.

**Comment by TheStrato** [comment]
Here is a recordkeeping ticket for your skin texture issues @scragnog

**Comment by MrPeppow** [comment]
Can confirm

**Comment by scragnog** [comment]
will be fixed for final release on Linux :-)

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
