### ISSUE TITLE
[Visual] Yesterdays Enterprise, Captains door is from Season 2-7.

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#35]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

Incorrect door version
![stage9 screenshot 2017 11 26 - 14 25 52 93](https://user-images.githubusercontent.com/33987322/33240414-d259c088-d2b5-11e7-9e56-2d8742947e59.png)

**Comment by scragnog** [comment]
fixed! Thanks
