### ISSUE TITLE
V0010-QA2 Phaser Fire Breaks Things including main shuttle bay door!

### ISSUE THREAD

**Issue by cheveffect09** [dapperrobotbear/Stage9#350]
**Summary**
If you have a phaser with you while you are in the Main Shuttle Bay and fire at the main door it explodes into peaces and falls off and because you have not told it to open normally the exterior model of the enterprise is not loaded. Also note that if you shoot the anti gravity units they fall on the floor and stop hovering.

***What is the expected correct behavior?***
The beam from the phasers should not destroy the door or cause the hover units to stop hovering.

**Steps to reproduce**
1. Go to the main shuttle bay with a phaser (I just usually grab one from the phaser range rooms)
2. Walk up to the main shuttle bay door and shoot it 
3. watch as the door explodes into multiple lines and falls into space 
4. Also shoot one of the hover units and they collapse.

**Relevant logs and/or screenshots**
![desktop screenshot 2018 03 14 - 11 54 30 93](https://user-images.githubusercontent.com/5516753/37377570-d02c569a-277e-11e8-85a7-0e467a5f1ddd.png)
![desktop screenshot 2018 03 14 - 11 54 34 28](https://user-images.githubusercontent.com/5516753/37377571-d0616d76-277e-11e8-8314-c28baca49810.png)
![desktop screenshot 2018 03 14 - 11 54 35 68](https://user-images.githubusercontent.com/5516753/37377572-d0985cfa-277e-11e8-98f5-2444935d23d9.png)
![desktop screenshot 2018 03 14 - 11 54 46 28](https://user-images.githubusercontent.com/5516753/37377573-d0cd7372-277e-11e8-9786-6b551aec554f.png)
![desktop screenshot 2018 03 14 - 11 58 55 28](https://user-images.githubusercontent.com/5516753/37377654-4d374b40-277f-11e8-8e73-f93bf039ddcd.png)

**Comment by trekkeriii** [comment]
Shuttlebay door re-appears when you open it and does the animation to open, but if you close it, disappears again.

**Comment by nkjellman** [comment]
Is this bad? If you think about it, in the show, a phaser set at maximum can blow holes in walls.

I think this could become a feature in the future.

**Comment by Jaredsfs1** [comment]
Confirmed in QA3 on Mac still, Other objects can also be affected by the phaser that shouldn't be:

Torpedo Casings:
![screen shot 2018-03-14 at 10 57 27 pm](https://user-images.githubusercontent.com/35311046/37473942-9f1f12d2-2845-11e8-9f4c-b79b2d378964.png)

ShuttleCraft Door Panels:
![screen shot 2018-03-14 at 11 23 20 pm](https://user-images.githubusercontent.com/35311046/37474046-d2169b06-2845-11e8-925b-dadc7e3f404e.png)

Bridge Viewscreen:
![screen shot 2018-03-14 at 11 43 14 pm](https://user-images.githubusercontent.com/35311046/37474125-ff3faab4-2845-11e8-9a17-2f3c323214dd.png)

![screen shot 2018-03-14 at 11 12 55 pm](https://user-images.githubusercontent.com/35311046/37474145-0cd7dd0e-2846-11e8-98ad-b8a28dc96f7b.png)

**Comment by scragnog** [comment]
all of these issues are fixed now

**Comment by Sciencekeeper** [comment]
@TheStrato confirmed fix(es)

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
