### ISSUE TITLE
V0010-QA2 Main Shuttlebay Still laggy

### ISSUE THREAD

**Issue by trekkeriii** [dapperrobotbear/Stage9#351]
**Summary**

When moving around the main shuttlebay, notice lag, likely when loading Corridor.

***What is the expected correct behavior?***

No lag, smooth transition moving from one part to the other of the Shuttlebay

**Steps to reproduce**

1. Go Deck 4, move around the Shuttlebay
2.
3.

**Relevant logs and/or screenshots**

(Paste any relevant logs - please use code blocks  to format console output,
logs, and code as it's very hard to read otherwise.)

**Possible fixes**

**Comment by trekkeriii** [comment]
Likely related to #301

**Comment by HPringles** [comment]
# Duplicate of 211

**Comment by TheStrato** [comment]
Duplicate of a more complete ticket. Closing this ticket.
