### ISSUE TITLE
V0010-QA2 Deck 3 Turbolift Labeled Deck 00

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#354]
Summary
Deck 3 Turbolift near the windows that look out across to the bell is labeled "00|Turbolift" instead of 03

Expected result
Label should be 03|Turbolift

Reproducible Steps
1. Climb split stairs across the bay from the ship's bell
2. Head back towards the windows, turn towards TL on the left.

Screenshot:
![image](https://user-images.githubusercontent.com/34050343/37379141-9e4efc20-2708-11e8-8814-f7e7b5616dbb.png)

**Comment by kaadaq** [comment]
Actually, both TL's in this area are labeled 00.

**Comment by kaadaq** [comment]
Similar issue on Deck 10 -- the two angled doors that back up to Ten Forward's bar (that are GNDN), are labeled 00 for the Deck.
![image](https://user-images.githubusercontent.com/34050343/37381039-903274f6-2711-11e8-876b-960ee070b170.png)

**Comment by JonathanNStewart** [comment]
I'll add this here, because it may be part of the same problem. Almost every door on Deck 3 has "Crew Lounge" superimposed on the name of the door.
![doorlabel](https://user-images.githubusercontent.com/37262529/37386429-00c0a632-271e-11e8-8989-921ef4dbe7df.png)

**Comment by scragnog** [comment]
all issues here should be fixed.

**Comment by kaadaq** [comment]
All issues confirmed fixed.  Closing ticket!
