### ISSUE TITLE
V0010-QA2 Inconsistent Window Treatment, Deck 10

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#355]
Summary:
In Ten Forward, I'm able to crawl up onto the windows.  However, in the crew lounges adjacent to Ten Forward, the window area is inaccessible.

Expected Performance
Consistent behavior around similar window styles (all accessible or all inaccessible)

Reproducible Steps
1. Approach fore windows in Ten Forward in either 1st person or 3rd person mode.
2. Jump over table or walk around and climb up on windows
3. Exit Ten Forward via port doors and proceed to crew lounge to port.
4. Approach windows; collision occurs before you can step up on them.

**Comment by scragnog** [comment]
confirmed, but not essential for v10 release.

**Comment by TheStrato** [comment]
NaB. Closing ticket.
