### ISSUE TITLE
V0010-QA2 Odd Collision Physics with Runabout 

### ISSUE THREAD

**Issue by trekkeriii** [dapperrobotbear/Stage9#356]
**Summary**

When colliding with objects in Runabout. Character shows moving to back of Runable

***What is the expected correct behavior?***

Should not move from seat.

**Steps to reproduce**

1. Take Runabout to DS9
2. Run into it,
3.

**Relevant logs and/or screenshots**

(Paste any relevant logs - please use code blocks  to format console output,
logs, and code as it's very hard to read otherwise.)

![20180314001254_1](https://user-images.githubusercontent.com/4651111/37383108-ee49f3ba-271c-11e8-8f92-3323b56a5e5f.jpg)

**Possible fixes**

**Comment by scragnog** [comment]
this is fixed now. spring arm had a length of 300 for fps view, should be 0.

**Comment by Gary-Baggins** [comment]
Confirmed fixed, please close @TheStrato @HPringles

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
