### ISSUE TITLE
V0010-QA1 Door frame passing through turbolift

### ISSUE THREAD

**Issue by JonathanNStewart** [dapperrobotbear/Stage9#357]
**Summary**

When going from the turbolift stop right of the transporter room to Stellar Cartography, just before you reach your destination a door frame comes rushing through the turbolift. It happens very quickly, so it was hard to make a good screenshot of. This is undoubtably not the only occurrence, but one I was able to reproduce.

***What is the expected correct behavior?***

The meshes should load outside of the turbolift.

**Steps to reproduce**

1. Go to the turbolift right of Transporter Room 2
2. Select Stellar Cartography as the destination
3. Look at the turbolift door as you reach your destination

**Relevant logs and/or screenshots**

![doorframe](https://user-images.githubusercontent.com/37262529/37386682-11f0edee-271f-11e8-8d62-655b83f1b3a1.png)

**Possible fixes**

Load the deck after you've arrived, or adjust the turbolift route to not intersect exterior meshes.

MacBook Air (13-inch, Early 2015)
OS: macOS High Sierra (10.13.3)
Processor: 1.6 GHz Intel Core i5
Memory: 4 GB 1600 MHz DDR3
Video: Intel HD Graphics 6000 1536 MB

Another case: #353

**Comment by scragnog** [comment]
no current possible fix for this. This is a result of the turbolift rotating to meet the door.

**Comment by TheStrato** [comment]
NaB. Closing ticket.
