### ISSUE TITLE
V0010-QA1 Can not sit in the control chair of the shuttles

### ISSUE THREAD

**Issue by www2000** [dapperrobotbear/Stage9#358]
**Summary**

Can not press enter on pilot chair to control shuttle/Runabout.

***What is the expected correct behavior?***

After press enter the player sit down and control the shuttle.

**Steps to reproduce**
1. enter a shutle from one of the shuttle bays
2. go to the right seat and press enter to sit on the pilot chair.

**Possible fixes**

Can be some problems with my install (after reinstall i have don't see this behavior)

**Comment by HPringles** [comment]
@www2000 Please update this issue to elaborate and describe the issue further - Please follow the bug report template.

**Comment by scragnog** [comment]
unable to confirm. Is anyone else able to confirm this?

**Comment by HPringles** [comment]
Also unable to confirm.

**Comment by www2000** [comment]
I can also not confirm with the reinstall of stage9.
Can be i was to close to the pilot chair or some file was missing that the reinstall fix.
Can be close for now.

**Comment by TheStrato** [comment]
OP reports issue does not persist. Closing ticket.
