### ISSUE TITLE
[Visual] Generations Bridge. Lcards aligment, Door deck numbers incorrect

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#36]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

**1. Lcards out of aligement on Generation Bridge.** 

![stage9 screenshot 2017 11 26 - 14 07 30 05](https://user-images.githubusercontent.com/33987322/33240446-5e427234-d2b6-11e7-8281-a0aa71177fdb.png)
![stage9 screenshot 2017 11 26 - 14 23 47 77](https://user-images.githubusercontent.com/33987322/33240448-5e582b38-d2b6-11e7-8447-4adb4a97557e.png)

**2. Doors on the Mainbridge are labeled with wrong deck number and double text.** 
![stage9 screenshot 2017 11 26 - 14 18 09 28](https://user-images.githubusercontent.com/33987322/33240462-8b72ff12-d2b6-11e7-8436-3af34631fc7d.png)
![stage9 screenshot 2017 11 26 - 14 28 53 02](https://user-images.githubusercontent.com/33987322/33240463-8b89fab4-d2b6-11e7-901d-aef04eca52a3.png)
![stage9 screenshot 2017 11 26 - 14 29 02 70](https://user-images.githubusercontent.com/33987322/33240464-8b9fce7a-d2b6-11e7-8052-d1d5e8f78b30.png)

**Comment by scragnog** [comment]
all fixed :-D
