### ISSUE TITLE
V0010-QA2 Deck Four upper corridor [Deck 3] wall misaligned and can fall into cargo lift.

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#360]
Summary:

A wall is misaligned and allows the user to walk through it to fall onto the cargo elevator.

Details:

Proceeding to the corridor that runs up a set of steps at the far end of either end of the shuttle bay. Walk towards the cargo elevator wall. The wall which looks like the outside of elevator you can walk through and there is gap. Presuming a wall is missing. 

![1](https://user-images.githubusercontent.com/37260734/37409333-0296191a-2796-11e8-8915-6b80454e8eb3.jpeg)

**Comment by jgbr** [comment]
@HPringles Mac and linux

**Comment by scragnog** [comment]
confirmed and fixed for qa3

**Comment by JonathanNStewart** [comment]
Same issue for mac, which can also be closed if fixed: #330

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
