### ISSUE TITLE
V0010-QA2 Deck Four corridor to Phaser range Port+Starboard

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#361]
Summary:

When entering the corridor on port or starboard of Deck 4 Shuttlebay not the way to the Phaser range, carpeting is wrong.

Details:

Shuttlebay 

floor dot carpet goes into the corridor to joint with a new corridor section which has the standard grey tiling floor. Moving along the corridor the range, resets to the correct floor and corridor. 

![untitled](https://user-images.githubusercontent.com/37260734/37413734-8d9a7cdc-279f-11e8-9c6a-eb6098938e4f.jpeg)

**Comment by jgbr** [comment]
@HPringles Mac, linux, windows

**Comment by Jaredsfs1** [comment]
@TheStrato this has been fixed in QA3 on PC and Mac

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugs
