### ISSUE TITLE
Win - V0010-QA2 - Multi visual bugs Main Bridge

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#363]
**Summary**
Some things that caught my eyes.

***What is the expected correct behavior?***
More relaxing eye experience :D

**Steps to reproduce**
1. Visit all location from screenshots and take a closer look :)

**Relevant logs and/or screenshots**

**The follow highlighted does not animate.**
![inkedstage9 screenshot 2018 03 14 - 17 48 32 11_li](https://user-images.githubusercontent.com/33987322/37418468-963b467e-27b2-11e8-86c4-3232e47530a9.jpg)
![inkedstage9 screenshot 2018 03 14 - 17 42 14 86_li](https://user-images.githubusercontent.com/33987322/37418469-9656578e-27b2-11e8-9299-7e9125d2788f.jpg)

**The following are small visual graphics issue, and small gaps**
![inkedstage9 screenshot 2018 03 14 - 17 34 59 45_li](https://user-images.githubusercontent.com/33987322/37418544-c6ed7cb0-27b2-11e8-80f7-54fee4c8141b.jpg)
![inkedstage9 screenshot 2018 03 14 - 17 44 26 96_li](https://user-images.githubusercontent.com/33987322/37418547-c72fb292-27b2-11e8-83d4-fc8026cc6b4c.jpg)
![inkedstage9 screenshot 2018 03 14 - 17 46 26 57_li](https://user-images.githubusercontent.com/33987322/37418548-c7506b54-27b2-11e8-8987-6e415d074772.jpg)
![inkedstage9 screenshot 2018 03 14 - 17 47 31 80_li](https://user-images.githubusercontent.com/33987322/37418550-c76ffa28-27b2-11e8-9f42-02add99ed09f.jpg)
![inkedstage9 screenshot 2018 03 14 - 17 50 42 52_li](https://user-images.githubusercontent.com/33987322/37418551-c78c90c0-27b2-11e8-9161-2125c336b8fc.jpg)
![inkedstage9 screenshot 2018 03 14 - 17 51 26 13_li](https://user-images.githubusercontent.com/33987322/37418552-c7a756bc-27b2-11e8-9cd0-51b2fdda6f8d.jpg)
![inkedstage9 screenshot 2018 03 14 - 17 52 24 44_li](https://user-images.githubusercontent.com/33987322/37418555-c7c58eb6-27b2-11e8-8b53-86e05872ecc3.jpg)
![inkedstage9 screenshot 2018 03 14 - 17 53 27 14_li](https://user-images.githubusercontent.com/33987322/37418556-c7e66442-27b2-11e8-9b12-d294d963ada0.jpg)
![inkedstage9 screenshot 2018 03 14 - 17 54 37 83_li](https://user-images.githubusercontent.com/33987322/37418557-c8020cb0-27b2-11e8-9105-d01fbbeccbcc.jpg)
![inkedstage9 screenshot 2018 03 14 - 17 56 46 78_li](https://user-images.githubusercontent.com/33987322/37418558-c8202e02-27b2-11e8-9507-f7c603ceb582.jpg)
![inkedstage9 screenshot 2018 03 14 - 17 57 29 38_li](https://user-images.githubusercontent.com/33987322/37418559-c83af4da-27b2-11e8-86d7-abe19faf49dc.jpg)
![stage9 screenshot 2018 03 14 - 17 43 54 19](https://user-images.githubusercontent.com/33987322/37418561-c8720574-27b2-11e8-8fc8-75de307dff2c.png)

View from Emergency Turbolift
![inkedstage9 screenshot 2018 03 14 - 17 37 42 75_li](https://user-images.githubusercontent.com/33987322/37418546-c70d6700-27b2-11e8-8ac3-884e916d92c1.jpg)
View from Emergency Turbolift doorway LOOK UP
![stage9 screenshot 2018 03 14 - 17 39 59 44](https://user-images.githubusercontent.com/33987322/37418560-c854d4ea-27b2-11e8-9b29-1472346b9879.png)

**Possible fixes**
Little touch up here and there.

**Comment by jgbr** [comment]
@HPringles windows and Mac

**Comment by scragnog** [comment]
some of these are fixed. Others will need to be fixed later.

**Comment by jeppelykke** [comment]
The animations side panel on the Mainbridge are confirmed fixed :)

**Comment by Sciencekeeper** [comment]
@TheStrato the majors are fixed a few minors still there QA4Win

**Comment by TheStrato** [comment]
Resolved enough for now. Closing ticket.
