### ISSUE TITLE
Win - V0010-QA2 - Multi visual bugs Deck 01 OBS. Lounge

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#364]
**Summary**
Some things that caught my eyes.

***What is the expected correct behavior?***
More relaxing eye experience :D

**Steps to reproduce**
1. Visit all location from screenshots and take a closer look :)

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 14 - 18 32 55 87](https://user-images.githubusercontent.com/33987322/37420282-b24dd6d4-27b6-11e8-84b8-96f5d2ae660c.png)
![inkedstage9 screenshot 2018 03 14 - 18 28 10 79_li](https://user-images.githubusercontent.com/33987322/37420283-b2694180-27b6-11e8-87ce-b1dd6f64331d.jpg)
![inkedstage9 screenshot 2018 03 14 - 18 30 45 01_li](https://user-images.githubusercontent.com/33987322/37420284-b2817e76-27b6-11e8-8ee8-fb6cdb85bb90.jpg)
![inkedstage9 screenshot 2018 03 14 - 18 31 38 60_li](https://user-images.githubusercontent.com/33987322/37420285-b29a1a08-27b6-11e8-8e7e-3b1343f3efec.jpg)
![inkedstage9 screenshot 2018 03 14 - 18 31 51 02_li](https://user-images.githubusercontent.com/33987322/37420287-b2b66e24-27b6-11e8-82cf-4f2dbcdcd40e.jpg)
![inkedstage9 screenshot 2018 03 14 - 18 35 00 30_li](https://user-images.githubusercontent.com/33987322/37420288-b2d0477c-27b6-11e8-84fb-22608faad3b4.jpg)

**Possible fixes**
Little touch up here and there.

**Comment by scragnog** [comment]
think these are all fixed now. Please check again in QA£ if you can :-)

**Comment by Gary-Baggins** [comment]
Verified fixed in QA3 @TheStrato @HPringles  please close.

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
