### ISSUE TITLE
Win - V0010-QA2 - OBS. Lounge able to stick head though wall.

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#365]
**Summary**
Stepping to close to these "things" allows you to stick head though wall.

***What is the expected correct behavior?***
Not to stick head though the wall.

**Steps to reproduce**
1. Visit Obs. Lounge
2. step close to these things :D

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 14 - 18 33 52 80](https://user-images.githubusercontent.com/33987322/37420466-276c6bc4-27b7-11e8-8084-2f710c689d0d.png)
![stage9 screenshot 2018 03 14 - 18 34 01 52](https://user-images.githubusercontent.com/33987322/37420481-2f581752-27b7-11e8-8ec6-98ab1c5d3717.png)
![stage9 screenshot 2018 03 14 - 18 34 08 69](https://user-images.githubusercontent.com/33987322/37420482-2f78f5f8-27b7-11e8-983b-cded409c9319.png)

**Comment by scragnog** [comment]
fixed for QA3

**Comment by Gary-Baggins** [comment]
Verified fixed in QA3 @TheStrato @HPringles  please close.

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
