### ISSUE TITLE
Win - V0010-QA2 Veridian planet shimmering

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#366]
Summary

Planet texture shimmers at higher speed showing banks of textures in any camera view.

What is the expected correct behavior?

Nice pretty atmosphere. 

Steps to reproduce

1.Travel to veridian. 
2.view planet from conn, view screen or any perspective.

![untitled2](https://user-images.githubusercontent.com/37260734/37420956-0a78c460-27b0-11e8-9944-d896f2fac7e8.jpeg)

**Comment by Gary-Baggins** [comment]
I am seeing "flickering" on windows please tag @TheStrato @HPringles

**Comment by jgbr** [comment]
Flickering/High speed shimmering.

**Comment by TheStrato** [comment]
Placed in the pipeline.

**Comment by scragnog** [comment]
confirmed. This planet material was borked (all planet materials to be overhaulked for v11 anyway) so I've switched to another, equally pretty, but not bugged different material.

**Comment by Sciencekeeper** [comment]
@TheStrato fixed QA4Win

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
