### ISSUE TITLE
Win - V0010-QA2 - Multi bugs in Captains Ready Room

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#367]
**Summary**
Jumping in different locations allows you to jump up though the ceiling 

***What is the expected correct behavior?***
Not to jump though the ceiling.

**Steps to reproduce**
1. Go to the locations and jump like crazy person.

**Relevant logs and/or screenshots**
![inkedstage9 screenshot 2018 03 14 - 18 47 03 47_li](https://user-images.githubusercontent.com/33987322/37421048-a1b71b3a-27b8-11e8-8bed-688ce6dc5cba.jpg)

**Inside Captains Readyroom side room with the replicator.** 
![stage9 screenshot 2018 03 14 - 18 47 38 16](https://user-images.githubusercontent.com/33987322/37421120-cb3f35d2-27b8-11e8-8c17-b45dff99d7ec.png)

**Jumping up near Captains Readyroom window there is a gab on top of the frame.** 
![stage9 screenshot 2018 03 14 - 18 46 07 64](https://user-images.githubusercontent.com/33987322/37421154-e0807168-27b8-11e8-9ffa-7d06501c93c4.png)

**Possible fixes**
Don't jump around :D

**Comment by scragnog** [comment]
couldn't confirm getting through the ceiling by jumping onto that corner table. confirmed the issue in the replicator room, fixed. the gap at the top of the window isn't essential to be fixed, you only see it if you go bouncing around.

**Comment by HPringles** [comment]
# Resolved in QA3

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
