### ISSUE TITLE
Win - V0010-QA2 - Deck 02 | Escape pods rooms issues.

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#369]
**Summary**
If you enter some escape pods on Deck 02, you notice wall issues.  

You can jump though ceiling/walls in every room, and in 4 rooms there is a wall glitch. 

On Deck 02 Rooms: 6898, 6811, 6797, 6887

***What is the expected correct behavior?***
Clean walls.

**Steps to reproduce**
1. Enter Escape pods room: 6898, 6811, 6797, 6887

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 14 - 19 11 23 96](https://user-images.githubusercontent.com/33987322/37422649-f771c270-27bb-11e8-9851-09f67d98678b.png)
![stage9 screenshot 2018 03 14 - 19 03 47 59](https://user-images.githubusercontent.com/33987322/37422650-f78e2e2e-27bb-11e8-84d5-7ff10f04b762.png)
![stage9 screenshot 2018 03 14 - 19 07 32 11](https://user-images.githubusercontent.com/33987322/37422651-f7aae320-27bb-11e8-8757-a4db536e3487.png)
![stage9 screenshot 2018 03 14 - 19 08 15 47](https://user-images.githubusercontent.com/33987322/37422652-f7c4c43e-27bb-11e8-8acd-41203b71a528.png)
![stage9 screenshot 2018 03 14 - 19 08 22 19](https://user-images.githubusercontent.com/33987322/37422653-f7df0a1a-27bb-11e8-9319-a4b5ec0f0e7c.png)

**Possible fixes**

**Comment by scragnog** [comment]
not high priority, will push back until after v10

**Comment by TheStrato** [comment]
Push. Closing ticket.
