### ISSUE TITLE
Win - V0010-QA2 - Deck 02 Corridors visuals 

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#370]
**Summary**
On Deck 02 at the corridors outside of rooms: 6913 & 6926 there is a small floor and wall visual issue.

***What is the expected correct behavior?***
Clean connecting floor and walls.

**Steps to reproduce**
1. Visit Deck 02 find rooms: 6913 & 6926 
2. Turn around and look at the end of the corridors. 

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 14 - 19 19 41 88](https://user-images.githubusercontent.com/33987322/37423057-2a817bd2-27bd-11e8-9474-d086e0cd5ab9.png)
![stage9 screenshot 2018 03 14 - 19 18 41 84](https://user-images.githubusercontent.com/33987322/37423058-2a9948d4-27bd-11e8-909a-8f64f6348171.png)
![stage9 screenshot 2018 03 14 - 19 18 45 30](https://user-images.githubusercontent.com/33987322/37423059-2ab1debc-27bd-11e8-9edb-7945af276442.png)
![stage9 screenshot 2018 03 14 - 19 19 35 86](https://user-images.githubusercontent.com/33987322/37423060-2ad46d2e-27bd-11e8-89cc-731a46c3f614.png)
![stage9 screenshot 2018 03 14 - 19 27 14 10](https://user-images.githubusercontent.com/33987322/37423363-ecf86dba-27bd-11e8-9fd9-f6efdaed8ec7.png)

**Deck 02 Corridor wall outside Rooms: 6898 & 6887**
The following wall posts needs to be moved more out towards the corridor to match the rest of the design. 
![stage9 screenshot 2018 03 14 - 19 26 46 33](https://user-images.githubusercontent.com/33987322/37423443-264a63d4-27be-11e8-9a29-d4e941e42ad9.png)
![stage9 screenshot 2018 03 14 - 19 25 10 80](https://user-images.githubusercontent.com/33987322/37423444-266684f6-27be-11e8-84a1-2acacb3bc4a7.png)

**Deck 02 Corridor gap outside Room: 4465**
![stage9 screenshot 2018 03 14 - 19 33 15 87](https://user-images.githubusercontent.com/33987322/37423669-b987df32-27be-11e8-9684-9254be2b568a.png)

**Deck 02 Corridor gap outside Room: 5070 in the corner of the 2 corridor meets**
![stage9 screenshot 2018 03 14 - 19 35 44 11](https://user-images.githubusercontent.com/33987322/37423761-f5158630-27be-11e8-88ca-d048ce71b589.png)

**Deck 02 Corridor gap outside Room: 2909 in the corner of the 2 corridor meets**
![stage9 screenshot 2018 03 14 - 19 37 52 74](https://user-images.githubusercontent.com/33987322/37423869-3c977cde-27bf-11e8-9428-1ee02b7ae0e3.png)

**Comment by jeppelykke** [comment]
Updated with some more visuals issues...

**Comment by scragnog** [comment]
some of these are fixed, others aren't really a problem (like the last 2 pics) as such.

**Comment by jeppelykke** [comment]
Not fixed in QA4

**Comment by Sciencekeeper** [comment]
@TheStrato please change Tag - not fixed

**Comment by TheStrato** [comment]
This one will be pushed for now. We will come back to it later.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
