### ISSUE TITLE
Win - V0010-QA2 - Deck 03| 2595 & 2599 both doors goes to "Control Room" should have same door number

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#371]
**Summary**
2 Doors leads to the same big Control Room for shuttlebay with driffent room numbers.

Deck 03 Room 2595 & 2599 they should have same room number as it's one and same room they open up to.

***What is the expected correct behavior?***
Same room doors on both rooms. 

**Steps to reproduce**
1. Visit Deck 03 Upper and look room doors 2595 & 2599.

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 14 - 19 42 14 07](https://user-images.githubusercontent.com/33987322/37424464-cee131d8-27c0-11e8-8f8a-22b94e52279d.png)
![stage9 screenshot 2018 03 14 - 19 42 24 40](https://user-images.githubusercontent.com/33987322/37424465-cefc39f6-27c0-11e8-9267-e11bb44e844a.png)

**Possible fixes**

**Comment by dapperrobotbear** [comment]
I think I'm fine with this. As it could be argued that the numbers are per door, not necessarily per room.

**Comment by dapperrobotbear** [comment]
Fixed in QA4. Both doors now say 2597.

**Comment by Gary-Baggins** [comment]
@dapperrobotbear A better solution could be 2597-A and 2597-B, people might need to differentiate between port door/starboard door and aft/bow door.

**Comment by dapperrobotbear** [comment]
I don't see a need for A/B. It should either be different numbers or the same number. I'm fine with this as is for the moment.

**Comment by jeppelykke** [comment]
@scragnog Confirmed fixed for windows

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
