### ISSUE TITLE
V0010-QA3 Standard Size Doors Lighting Glitch

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#372]
One side of the doors will go black at a certain distance.

What is the expected correct behavior?

Both door stay the same color at all distances.

Steps to reproduce

Just look at doors from a far distance.

![image](https://user-images.githubusercontent.com/5162659/37434120-e7baf9d4-27b4-11e8-93b9-0a4af5096c05.png)

![image](https://user-images.githubusercontent.com/5162659/37434209-3252e308-27b5-11e8-94a3-44f75f30b1ab.png)

**Comment by kaadaq** [comment]
Issue confirmed on Deck 3 doors.

**Comment by EazyCheeze1978** [comment]
Confirmed:
<img width="960" alt="2018-03-14 21_07_38-greenshot" src="https://user-images.githubusercontent.com/37255420/37441040-66c1d730-27cd-11e8-9f92-ca2283a9e80d.png">

**Comment by dapperrobotbear** [comment]
This is a regression from QA2 @scragnog

**Comment by Jaredsfs1** [comment]
Yeah, the approximate distance appears to be visible here:

![screen shot 2018-03-14 at 11 11 10 pm](https://user-images.githubusercontent.com/35311046/37476483-a7ec57de-284b-11e8-812b-bce8008c1c06.png)
![screen shot 2018-03-14 at 11 11 21 pm](https://user-images.githubusercontent.com/35311046/37476487-a9e5a0b8-284b-11e8-968a-d052845ef403.png)
![screen shot 2018-03-14 at 11 11 24 pm](https://user-images.githubusercontent.com/35311046/37476492-ac345698-284b-11e8-9874-cf5d48b63831.png)

**Comment by scragnog** [comment]
fixed in all locations

**Comment by jeppelykke** [comment]
@scragnog Confirmed fixed for windows

**Comment by Sciencekeeper** [comment]
@TheStrato fixed QA4Win

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
