### ISSUE TITLE
V0010-QA3  Type 15 Shuttlepod Doors

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#373]
This is more of an enhancement. When opening and closing the door on the Shuttlepod. The animation doesn't reverse at the current point. It will reset to the open or close position only. 

What is the expected correct behavior?

The animation will reverse/go forward at its current animation point. Rather than reset from fully close to fully open.

Steps to reproduce

Open or close the Shuttlepod's door during its animation. 

https://gfycat.com/ObviousPessimisticHyena

**Comment by scragnog** [comment]
woohoo! I fixed a thing! This one is sorted now. The actual door open and close sound still goes on the full length, but until we have a better approach for dynamic length door sounds, this is good enough :-D

**Comment by jeppelykke** [comment]
Animation is clean now... 

New issue arrived, some times if you open both side of the shuttle and then walk over to close it the sound of closing is played. But door animation first kicks in between 10-20sec after.

**Comment by Sciencekeeper** [comment]
@TheStrato looks fine to me

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
