### ISSUE TITLE
V0010-QA3 Shuttle Bay 2 Forcefield

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#374]
When Turning off the Forcefield to suck out all the items. The Forcefield doesn't reactivate itself when you close the doors. Also, once the door closes. The computer again says "Shuttlebay Forcefield Deactivated".

What is the expected correct behavior?

When closing the doors. The Forcefield should turn back on automatically, than shut off once fully closed. Based off what happened in the episode "Disaster". Also not re-trigger the deactivated voice line. 

Steps to reproduce

Deactivate the Forcefield.
Close The Door.

**Comment by scragnog** [comment]
fixed.

**Comment by jeppelykke** [comment]
@scragnog confirmed fixed for windows

**Comment by Sciencekeeper** [comment]
@TheStrato confirmed fix QA4Win

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
