### ISSUE TITLE
V0010-QA3 Deck 8 Captain Quarters Corridor Spine Numbers Visible

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#375]
Spline numbers are on in the corridor on the starboard side of Deck 8's turbolift stop.

What is the expected correct behavior?

The splines number should be off.

Steps to reproduce

Get off on Deck 8 captains quarters. Head right.

![image](https://user-images.githubusercontent.com/5162659/37436663-5f03d5e2-27bf-11e8-9c94-b11c91ffdc29.png)

**Comment by dapperrobotbear** [comment]
Fixed in QA4

**Comment by jeppelykke** [comment]
@TheStrato Confirmed fixed in Windows

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
