### ISSUE TITLE
v0010-QA3 - At a distance, door textures are half black, then they render normally as we get closer

### ISSUE THREAD

**Issue by EazyCheeze1978** [dapperrobotbear/Stage9#377]
**Summary**

When walking around the ship, I encounter the doors, but they are rendered half black at a distance; when I get closer, they're rendered normally.

***What is the expected correct behavior?***

For the doors to look pretty much the same (mipmapping notwithstanding) no matter the distance.

**Steps to reproduce**

1. The doors around the transporter area are too close to effect this effect (heh) so go to Deck 1.
2. Notice the doors on the bridge are half black until you get close!
3. Go to Deck 2 and notice the same thing!

**Relevant logs and/or screenshots**

<img width="960" alt="2018-03-14 21_09_15-greenshot" src="https://user-images.githubusercontent.com/37255420/37440859-a5dcca3e-27cc-11e8-99bc-470f9486080a.png">
<img width="960" alt="2018-03-14 21_07_38-greenshot" src="https://user-images.githubusercontent.com/37255420/37440860-a5f33814-27cc-11e8-8978-85063271d098.png">
<img width="960" alt="2018-03-14 21_07_55-greenshot" src="https://user-images.githubusercontent.com/37255420/37440861-a60e6ff8-27cc-11e8-9ebf-047361064bcd.png">

**Comment by EazyCheeze1978** [comment]
DUPE! Did not notice another issue with this same content. Please close, with my apologies. @TheStrato

**Comment by TheStrato** [comment]
Lol. No worries. Was well written none the less. Duplicate. Closing ticket.
