### ISSUE TITLE
V0010-QA3 Deck 3 Office Deck Door Labels

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#378]
Summary:
Main Shuttle bay observation lounge is labeled Cybernetics Lab, and all doors on the deck are labeled 3|<#> instead of 03|<#> per standard naming convention.

Expected Result
Descriptive label for lounge and zero-padding for single digit deck #.

Reproducible Steps
1. Climb staircase by ships bell in main shuttle bay

Screenshots:
Lounge, down hall to left of staircase.
![image](https://user-images.githubusercontent.com/34050343/37440939-65ff05b8-27d5-11e8-8581-bbf56a40accd.png)

Turbolift at top of main staircase next to Ships Bell:
![image](https://user-images.githubusercontent.com/34050343/37440968-8e418226-27d5-11e8-81c5-d33f222df319.png)

**Comment by dapperrobotbear** [comment]
Fixed in QA4

**Comment by jeppelykke** [comment]
@scragnog Confirmed fixed for windows

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
