### ISSUE TITLE
V0010-QA3 Deck 4 Phase Range Door Numbering

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#379]
Summary
Door numbers on port and starboard phaser range inner chambers (observation and control) show deck 00 on the name plate.   In addition, room numbers for the port side rooms are the same as for the starboard side.

Expected result
Deck 04 displayed, and room numbers unique between port and starboard.

Screenshots:
![image](https://user-images.githubusercontent.com/34050343/37441937-23d76d1a-27da-11e8-9c93-a5f05ca224d6.png)

**Comment by kaadaq** [comment]
Doors in the hallway leading up to the phaser range are similarly labeled 00 for Deck:
![image](https://user-images.githubusercontent.com/34050343/37442006-7583b0a6-27da-11e8-844f-a8637177e814.png)

**Comment by dapperrobotbear** [comment]
Fixed in QA4

**Comment by jeppelykke** [comment]
In Phaser Range 2 (Deck 04 | 1126) and in Phaser Range 1 (Deck 04 | 1169) both inner doors for Range control & observation still have same room numbers. 315 & 320.

**Comment by Sciencekeeper** [comment]
@TheStrato confirmed fix QA4Win

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
