### ISSUE TITLE
V0010-QA1 Ship is not drawn in 3rd person

### ISSUE THREAD

**Issue by MrPeppow** [dapperrobotbear/Stage9#383]
**Summary**

On Linux QA1: When flying the whole Enterprise and changing to 3rd Person, the Ship itself is not drawn.

***What is the expected correct behavior?***

See the ship from the outside

**Steps to reproduce**

1. Sit down on the control chair
2. Toggle to 3rd person view

**Relevant logs and/or screenshots**
Here a zoomed in screenshot:
![screenshot_20180315_104443](https://user-images.githubusercontent.com/13747941/37455821-534e405a-283e-11e8-9b93-d17912e71c9c.jpeg)

**Comment by MrPeppow** [comment]
@HPringles

**Comment by TheStrato** [comment]
Duplicate. Closing this ticket.
