### ISSUE TITLE
V0010-QA1 Very low fps on main bridge

### ISSUE THREAD

**Issue by MrPeppow** [dapperrobotbear/Stage9#384]
**Summary**

On Linux QA1, I'm getting 15fps on main bridge, 25fps in main shuttle bay and about 40-50fps in corridors

***What is the expected correct behavior?***

The main shuttle bay is demanding because of its size. But 40% less fps than there on main bridge seems wrong.

**Comment by MrPeppow** [comment]
@HPringles Tag Linux

**Comment by TheStrato** [comment]
NaB. Closing ticket.
