### ISSUE TITLE
V0010-QA1 Medium shaddow setting behavior

### ISSUE THREAD

**Issue by MrPeppow** [dapperrobotbear/Stage9#385]
**Summary**
Pulling shaddows from low to medium visually changes next to nothing, however my fps dropped by 30%. Pulling them to high changes visually everything, but only costs another ~5%.
Additionally, the captains chair on main bridge has shaddows and everything on medium, wheras everything else on high.
(Summarize the bug encountered concisely)

***What is the expected correct behavior?***
Only the captains chair seems to show the correct behavior:
Low:
![low](https://user-images.githubusercontent.com/13747941/37457108-58b6cbcc-2841-11e8-97c6-d45ab90962fb.jpeg)
Medium:
![medium](https://user-images.githubusercontent.com/13747941/37457126-60a8c7f4-2841-11e8-9fdb-268b3a03cb78.jpeg)
High:
![high](https://user-images.githubusercontent.com/13747941/37457138-687ca040-2841-11e8-8a2f-f6baaedf20c4.jpeg)

**Comment by MrPeppow** [comment]
@HPringles Tag Linux

**Comment by TheStrato** [comment]
Linux is a pesky penguin. Closing this ticket.
