### ISSUE TITLE
V0010-QA3 - Turbolift not finishing journey from anywhere not Deck 8 to Deck 8 - Picard's area

### ISSUE THREAD

**Issue by EazyCheeze1978** [dapperrobotbear/Stage9#387]
**Summary**

When proceeding via turbolift to Deck 8 from the Transporter Room (or even the Bridge, I've found, and I'd assume other higher decks) the journey does not complete - the 'lift's doors do not open (though the outer ones on the deck do) and the sound of the 'lift doesn't end.

***What is the expected correct behavior?***

I should be able to go to Deck 8 normally.

**Steps to reproduce**

1. From the transporter room or a deck higher than Deck 8, go to Deck 8, Picard's quarters area
2. Witness the infinite travel time!
3. But go to the Battle Bridge, then back to Picard's quarters area; the journey completes!
4. Also, coming from a lower deck to Deck 8 - Picard's quarters area never completes either!

**Relevant logs and/or screenshots**

<img width="960" alt="2018-03-15 09_53_15-stage9" src="https://user-images.githubusercontent.com/37255420/37471448-bbae9cb4-2837-11e8-9f08-618104bd9aa7.png">

@TheStrato and @HPringles please assign appropriate tags! :) Thank you.

**Comment by scragnog** [comment]
@dapperrobotbear I'm gonna assign this to you. I can confirm it here, but I've also checked, and the spline points are all setup and configured correctly (and as mentioned, you can reach it from the battle bridge), definitely something odd going on

**Comment by dapperrobotbear** [comment]
Fixed in >QA4

**Comment by EazyCheeze1978** [comment]
Learned this was fixed in my previous testings today. AWESOME! :)

**Comment by TheStrato** [comment]
Resolved. Closing the ticket.
