### ISSUE TITLE
V0010-QA3 - Tractor Beams (Cargo Lift room Deck 2, and elsewhere) can grab NPC's

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#389]
**Summary**

When operating a tractor beam emitter, you can catch NPC's and if lifted, they lock into the falling position.  If you leave them in the beam and exit the station, they will sometimes fall and walk away, but be pulled back if you reactivate the station.  Additionally, the NPC's appear to ignore collision with objects and walls while under tractor control. 

***What is the expected correct behavior?***

Either NPC's should be able to be picked up and collide with objects and walls as expected.

OR, NPC's should be immune to being tractor-ed.

And, Things/NPC's left in the emitter beam when the Player leaves the control station should remain stationary and not be released while the beam continues to operate.

**Steps to reproduce**

1.Travel to the Cargo elevator room (Deck 2)
2.Activate one of the tractor emitters
3.Direct the beam to an NPC in range
4. Collect the NPC; lift them up and set them down.  Pass them through walls or static objects in the room.
5. Set them on the ground or lift them in the air, then disconnect from the station (via the "e" key)
6. Observe them start walking away or slowly drop to the ground and walk away.
7. Re-connect to station
8. observe the NPC pulled instantly back to where they had been left when you disconnected.

**Relevant logs and/or screenshots**

![screen shot 2018-03-13 at 11 52 55 pm](https://user-images.githubusercontent.com/35311046/37473265-6304c338-2844-11e8-8c64-b8bb2a074c1e.png)
![screen shot 2018-03-13 at 11 50 46 pm](https://user-images.githubusercontent.com/35311046/37473266-6312014c-2844-11e8-8258-67f488990303.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by HPringles** [comment]
# Confirmed

**Comment by scragnog** [comment]
@dapperrobotbear I don't think there's a ton we can do about the collision stuff (maybe there is, I'm not sure) but that thing where they're getting dragged back into position after reactivating the console is a problem. Thoughts?

**Comment by dapperrobotbear** [comment]
I'll see what I can do. IMO not critical for v10

**Comment by jeppelykke** [comment]
@HPringles Transferred to bugz
