### ISSUE TITLE
V0010-QA3 - Bridge View Screen affected by Phaser 

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#390]
**Summary**

Related to: #350, New to QA3, the Bridge view screen is now susceptible to phaser fire, knocking it into the porthole view behind. 

***What is the expected correct behavior?***

View Screen should be immune to, or "damaged" by phaser fire, not bug out.

**Steps to reproduce**

1.Travel to the bridge
2.Collect a phaser (one available from the Observation Lounge)
3.Fire it at the Main Bridge View Screen
4. observe the parallax layer of the screen fall when struck
5. this was not present in QA1 and QA2

**Relevant logs and/or screenshots**

Primary issue:
![screen shot 2018-03-14 at 11 12 51 pm](https://user-images.githubusercontent.com/35311046/37476248-0c55df20-284b-11e8-9ca4-78bd0573bb7f.png)
![screen shot 2018-03-14 at 11 12 55 pm](https://user-images.githubusercontent.com/35311046/37476253-0ef9dfec-284b-11e8-8f6d-1d09e0bca0c1.png)
![screen shot 2018-03-14 at 11 12 57 pm](https://user-images.githubusercontent.com/35311046/37476274-1a67edba-284b-11e8-8537-e5791bb496a0.png)

Particularly Problematic when the alternate views from the Tactical station are active:
![screen shot 2018-03-14 at 11 43 12 pm](https://user-images.githubusercontent.com/35311046/37476333-4a3657ca-284b-11e8-85c3-9763677ba794.png)
![screen shot 2018-03-14 at 11 43 14 pm](https://user-images.githubusercontent.com/35311046/37476336-4d0865ec-284b-11e8-8feb-8ce808b013e0.png)
![screen shot 2018-03-14 at 11 43 54 pm](https://user-images.githubusercontent.com/35311046/37476341-4ff88700-284b-11e8-8558-b8540c09233f.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by scragnog** [comment]
very odd. Not sure how this crept in. Resolved now.

**Comment by MrPeppow** [comment]
Linux QA1 cant confirm, however there is something weird:
![screenshot_20180314_131241](https://user-images.githubusercontent.com/13747941/37516133-6a63407c-290d-11e8-9278-9d6a4a9d4182.jpeg)

**Comment by Sciencekeeper** [comment]
@TheStrato this is fixes in QA4 Win. But the Problem MrPeppow screenshotted is still there. The beam just dissapears in thin air

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
