### ISSUE TITLE
Win - V0010-QA3 - Deck 06 Transporter room 2 (5393) O'brian leaves his station

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#392]
**Summary**
When you beam in, and walk out and into Transpoter room 1, and let both doors close and then return to transporter room 2, then O'brain has left his station.

***What is the expected correct behavior?***
That O'brian remained at his station. 

**Steps to reproduce**
1. Start Game
2. Go into Transporter room 1 Let both doors to Transpoter room 1 & 2 close.
3.  Go back into Transporter room 2.
4. O'Brian is now gone.

**Relevant logs and/or screenshots**

![stage9 screenshot 2018 03 15 - 17 30 50 61](https://user-images.githubusercontent.com/33987322/37477213-5c46ac36-2877-11e8-9e0d-36d8bec60570.png)
![stage9 screenshot 2018 03 15 - 17 30 53 71](https://user-images.githubusercontent.com/33987322/37477216-5df14ef6-2877-11e8-8adf-188088ff7fb7.png)
![stage9 screenshot 2018 03 15 - 17 31 54 20](https://user-images.githubusercontent.com/33987322/37477219-5f32effe-2877-11e8-81cf-d248701e158a.png)

**Comment by jgbr** [comment]
verified on mac

**Comment by scragnog** [comment]
Fixed now. I asked Riker to give O'Brien a stern talking to. He won't be leaving his duty station again any time soon!

**Comment by jeppelykke** [comment]
@scragnog Confirmed Fixed for Windows

**Comment by jgbr** [comment]
confirmed fixed for Mac

**Comment by Sciencekeeper** [comment]
@TheStrato confirmed fix WinQA4

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
