### ISSUE TITLE
Win - V0010-QA3 - Deck 03 outside of room 2595 & 2599 invisible wall

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#393]
**Summary**
Outside of both Control Room on Deck 03 rooms: 2595 & 2599 is an invisible wall.

***What is the expected correct behavior?***
Solid wall.

**Steps to reproduce**
1. Goto Deck 3 - Upper Shuttlebay 
2. Goto control room 2595

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 15 - 17 56 32 85](https://user-images.githubusercontent.com/33987322/37478494-aa146072-287a-11e8-9111-a580f3112855.png)
![stage9 screenshot 2018 03 15 - 17 56 45 48](https://user-images.githubusercontent.com/33987322/37478495-aa2df2bc-287a-11e8-941f-e5e942ca0c60.png)

**Comment by jeppelykke** [comment]
@HPringles Please delete, duplicate post :(

**Comment by scragnog** [comment]
@dapperrobotbear have you fixed this? I'm seeing a different wall in the editor here now, one without the tags :-/

**Comment by TheStrato** [comment]
Duplicate. Closing this ticket.
