### ISSUE TITLE
Win - V0010-QA3 - Deck 36 Main Engineering 2 ceiling gaps.

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#394]
**Summary**
Visit to Deck 36 noticed a few graphics issues. 

***What is the expected correct behavior?***
Solid ceilings 

**Steps to reproduce**
1. Head to Deck 36  Main Engineering. 
2. Step out of the turbolift and look up at the ceiling. 
3. Walk into Main Engineering and look at the ceiling infront of door: 1405

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 15 - 18 07 56 97](https://user-images.githubusercontent.com/33987322/37479273-8b8d0080-287c-11e8-9af1-53158117dd31.png)
![stage9 screenshot 2018 03 15 - 18 08 16 38](https://user-images.githubusercontent.com/33987322/37479274-8bafbfd0-287c-11e8-9c22-75d844b6b32c.png)

**Comment by scragnog** [comment]
both issues fixed now

**Comment by jeppelykke** [comment]
@scragnog confirmed fixed for Windows

**Comment by Sciencekeeper** [comment]
@TheStrato fixed QA4Win

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
