### ISSUE TITLE
V0010-QA3 Missing Junction On Deck 6

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#395]
There's a missing Corridor behind this force field on Deck 6. Near door labeled 2020 Astrophysics Lab. 

What is the expected correct behavior?

A door or junction point should be in place.

Steps to reproduce

Head to your left from Transporter Room 4. 

![image](https://user-images.githubusercontent.com/5162659/37491120-227223cc-2873-11e8-8138-ba4cbad493dd.png)
![image](https://user-images.githubusercontent.com/5162659/37491126-28f3969a-2873-11e8-90e5-a755dc7771e7.png)

**Comment by scragnog** [comment]
fixed in qa4

**Comment by jeppelykke** [comment]
@scragnog confirmed fixed for windows

**Comment by Sciencekeeper** [comment]
@TheStrato confirmed fix QA4

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
