### ISSUE TITLE
 V0010-QA3 Deck 12 Visible In Holodeck

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#397]
All Holodeck TNG Bridges show deck 12 visible below in the view screen. 

What is the expected correct behavior?

Deck 12 should not be visible outside on the view screen.

Steps to reproduce

Load any TNG Bridge type
Look down on the left side of the view screen. Standing on top of it.

![image](https://user-images.githubusercontent.com/5162659/37548879-8339c7da-2951-11e8-81ad-91f1b48034ab.png)

**Comment by scragnog** [comment]
known issue, won't fix for v10

**Comment by jeppelykke** [comment]
@HPringles transferred to Bugz
