### ISSUE TITLE
V0010-QA4 - Holodeck door needs a if arch visible door on, if arch hidden door should be off flag

### ISSUE THREAD

**Issue by cheveffect09** [dapperrobotbear/Stage9#399]
**Summary**
While in the Holodeck you can force your way out of the holodeck through the closed invisible arch, also if you close the arch while the holodeck door is open it allows you to walk easily through.

**What is the expected correct behavior?**
When the arch is closed while the player is on the holodeck it should not allow you to leave.

**Steps to reproduce**
1. Go to any holodeck and run a program and enter.
2. Remember where the arch is and close it and try to walk through a few times and it will force you back into the corridor.
3. Or make sure to leave the holodeck door open and close the arch and it allows you to just walk through.

**Comment by TheStrato** [comment]
Lacking detail at my request. Priority repair.

**Comment by jeppelykke** [comment]
Load a holo program, walk into the holodeck goto other side of the room, hit 'Q' to hide ARC, walk back into the location the arc is, you be bouncing bit back and forth but at some point you be teleport back to the corridor, and doors will be open and you can reenter if you want to.

**Comment by scragnog** [comment]
fixed now

**Comment by EazyCheeze1978** [comment]
Okay, I think this is fixed but now a similar issue... you hide the arch all right, but if you do so when the door is open, then you show the arch again, the door stays open no matter your distance from it (when you're still in the program (in my case the 1701 bridge). When you go back out to the holodeck corridor, the door closes properly. And when you return to the program from there, the door closes properly. So, mostly fixed, but another tiny issue which is probably not worth worrying about for now?

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
