### ISSUE TITLE
Game is starting up VR on PC Version

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#4]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

When launching the game, it also starts up Steam VR system.

**Comment by scragnog** [comment]
Possible fix implemented - SteamVR disabled for the desktop project. There may be repercussions here as some blueprints do reference VR functionality even in desktop mode.
