### ISSUE TITLE
10 forward steps can block you from walking up to seating area

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#40]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**
If you walk up incorrectly to the steps up to seating area, say like this: 
![stage9 screenshot 2017 11 26 - 22 05 05 11](https://user-images.githubusercontent.com/33987322/33244392-7ea3f120-d2f6-11e7-8310-cbf3109b6a76.png)

Then when you try to walk up the steps you get stuck by invisible wall. 
![stage9 screenshot 2017 11 26 - 22 05 11 53](https://user-images.githubusercontent.com/33987322/33244394-82f4afa8-d2f6-11e7-8899-c07e025b4547.png)

Even if you walk all the way back to the bar and try to walk up the steps correctly, you still get stuck by the invisible wall. 

You can how ever jump over the steps and it "disappears" and you can go up and down the steps without issues.

**Comment by scragnog** [comment]
should be resolved now
