### ISSUE TITLE
V0010-QA4 Bell Striker Hanging Outside Of Bell

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#400]
The Bell striker in the Main Shuttlebay is hanging below the bell and is not interacting when the bell swings.

What is the expected correct behavior?
Bell Striker should be under the bell swinging inside.

![image](https://user-images.githubusercontent.com/5162659/37556054-ecc8c208-29c6-11e8-9b2f-abc8445ff460.png)

**Comment by HPringles** [comment]
# Confirmed Issue

**Comment by scragnog** [comment]
this is intermittent and hard to resolve, will push back to post v10
