### ISSUE TITLE
V0010-QA4 Mac Graphics fail, Mac OS build unusable/unstable. 

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#402]
Summary:

Randomly loading maps results in a black screen with graphics distortion. The Mac does not crash but their is no way to get out of it. QA4 is generally unusable. 

How to replicate:

Head to the bridge
On exiting the turbo lift you are greeted with a black screen.
Tried changing graphics settings, alert settings and combinations and destinations. 
Also clean redownload and restart, no difference. 

Verfication:

Three Mac users were able to verify and replicate.
Limited to Mac only. Only tested on 10.13.3. [HS]

Wider observations:

1. This is not due to integrated versus discrete graphics.
2. QA1 and 2 were stable, with 2 performing the best.
3. For some QA3 resulted in a hard crash of the entire Mac, of if it did work, extremely choppy performance. Only way to solve was to actually hold power button off to hard reset. 
4. QA4 is generally unusable. 

note: 'graphics snow across' screen in bars. Open picture below to see up close.

![untitled](https://user-images.githubusercontent.com/37260734/37556784-b0f0ab8e-29f2-11e8-8ebe-f4dda7021f34.jpeg)

**Comment by scragnog** [comment]
@dapperrobotbear critical issue. Unable to confirm here. Confirmed not occuring on Windows packaged builds.

**Comment by jgbr** [comment]
1 more Mac user confirmed this issue

**Comment by dapperrobotbear** [comment]
I believe this has something to do with the SM4/SM5 rendered we're using. As a workaround you can hit the "tab" key, and under the "Video" section set your "Bloom" to 0, and hit apply. That should clear the static.

**Comment by mikebarber1** [comment]
@dapperrobotbear Confirmed - bloom set to 0 fixed the issue

**Comment by mikebarber1** [comment]
@dapperrobotbear Well, fix is probably too strong of a word. I can walk around but it's super laggy at times and the video still glitches out on occasion.

**Comment by dapperrobotbear** [comment]
That might just be the rest of the game….we're still trying to find the right balance.

**Comment by jgbr** [comment]
Even with this fix I’d probably say it’s near unusable :(

**Comment by dapperrobotbear** [comment]
Please confirm against >QA4

**Comment by jgbr** [comment]
I can report that it appears to now be stable.

However some lighting issues have become an issue, but from the point of view of a GM, you are in business.

**Comment by jgbr** [comment]
Note the shadow issues and chair int he middle, random graphics like this appear. 

![untitled](https://user-images.githubusercontent.com/37260734/37565542-129b8b28-2aa3-11e8-9207-9a87fa7f1d17.jpeg)

**Comment by jgbr** [comment]
![untitled](https://user-images.githubusercontent.com/37260734/37565739-818a95d0-2aa6-11e8-8d4d-a29d4d92e55c.jpeg)

**Comment by jgbr** [comment]
I'd still say that QA2 graphics were best and worked fine, if that is any help.

**Comment by jgbr** [comment]
So if you put settings on low or medium but shadows to high it gets better. 
![untitled](https://user-images.githubusercontent.com/37260734/37570819-8d305dca-2aec-11e8-9a3f-d18eb8178b53.jpeg)

**Comment by jgbr** [comment]
Epic settings, datas eyes looking like a demon are reflections of light. epic an shadows max solves most of it. 
![untitled](https://user-images.githubusercontent.com/37260734/37570955-73624f3c-2aee-11e8-9f29-811d244ad5a7.jpeg)

**Comment by jgbr** [comment]
Also when going epic, the outside view, you see [for example] the planet and station at Jupiter drawn in high detail. When you view it through the view screen, they go to fairly low res models.

**Comment by tenko23** [comment]
I can confirm some lighting issues and shadow glitches also.

**Comment by jeppelykke** [comment]
@HPringles transferred to bugz
