### ISSUE TITLE
Nacelle "neck" improperly lighted.

### ISSUE THREAD

**Issue by metaphim428** [dapperrobotbear/Stage9#403]
**Summary**

The tip glows red, the sides glow blue, the neck glows too.

***What is the expected correct behavior?***
The tip glows red, the sides glow blue, the neck doesn't glow.

**Possible fixes**
Make the lights spotlights that point in opposite directions inside the nacelle or put some kind of blocking material there so the light doesn't bleed through.

![stage9-win64-shipping screenshot 2018 03 17 - 19 24 28 64](https://user-images.githubusercontent.com/6857446/37559616-4d6dd886-29e6-11e8-83a3-5bdde26813ba.png)

**Comment by dapperrobotbear** [comment]
Fixed in >QA4

**Comment by EazyCheeze1978** [comment]
@TheStrato this is confirmed fixed! :)

**Comment by TheStrato** [comment]
Resolved. Closing the ticket.
