### ISSUE TITLE
V0010-GM - Debris from station remains 'stuck' to ship.

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#404]
Summary:

When blowing up an object or station [in this case outside mars/jupiter] the debris becomes stuck to the ship.

When you move the ship, debris moves with it. 

Steps:
Fire a torpedo from the Bridge.
Conn the ship after explosion. 

Tested on Mac GM

![untitled](https://user-images.githubusercontent.com/37260734/37565585-b3038070-2aa3-11e8-9b0c-a808a46b4d07.jpeg)

**Comment by kaadaq** [comment]
This is confirmed.   Fired the torpedo, sat at conn, and adjusted to a course to starboard; the debris field relocated.    Took the ship to warp, and the debris stuck to the ship for a couple of seconds before disappearing.

Win10 on an Athlon X2.   @TheStrato  please mark confirmed

![image](https://user-images.githubusercontent.com/34050343/37574820-eb2db5d2-2af9-11e8-9478-1ae455603a3e.png)

**Comment by jeppelykke** [comment]
@HPringles transferred to Bugz
