### ISSUE TITLE
V0010-GM NPC on/off not persisted from menu to game 

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#407]
**Basic Info**

Discord Name(If Applicable) : jgbr
Operating System: OSX 10.13.3

**Summary**

When disabling or enabling NPC's on the menu home screen, it does not persist into the game.

IE: NPC's off in menu, you'll find them back when actually in game.

***What is the expected correct behavior?***

Off means off, on means on.

**Comment by jeppelykke** [comment]
@HPringles transferred to Bugz
