### ISSUE TITLE
V10GM Port side 10 forward turbo lift non functional

### ISSUE THREAD

**Issue by Gary-Baggins** [dapperrobotbear/Stage9#408]
**Basic Info**
The turbo lift by the port side exit to 10 forward is non functional
Discord Name Gary_Baggins   
   
You can enter and select a destination at which point the doors close but you do not go anywhere, there is also no option in other lifts to go to that location.

Turbo lift should be operational.

**Steps to reproduce**

1. Go to turbo lift nearest the port side exit to 10 forward
2. Select destination
3. Grow old waiting to go anywhere

Please tag Windows and Bugs @TheStrato @HPringles

**Comment by jgbr** [comment]
On Mac too

**Comment by jeppelykke** [comment]
@HPringles transferred to Bugz
