### ISSUE TITLE
[Visual] Small gap in carpet very visual at this point

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#41]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**
Just outside of Deck 10 Door 3458 looking down towards Ten Forward. 

![stage9 screenshot 2017 11 26 - 22 31 26 76](https://user-images.githubusercontent.com/33987322/33244558-346ceca2-d2fa-11e7-8a4e-7cf35091cf7a.png)

**Comment by scragnog** [comment]
resolved
