### ISSUE TITLE
V0010-GM1 Party Mode lights don't shut off

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#410]
**Basic Info**

Discord Name(If Applicable):   kaadaq
CPU:  Athlon x2
GPU:  GT710
Operating System:   win10

**Summary**

Turning off party mode video shortly after starting causes bridge lights to stay flashing

***What is the expected correct behavior?***

Lights stay normal

**Steps to reproduce**

1. Activate party mode on capt chair
2. As soon as audio starts, deactivate party mode via same method
3. lights will begin to flash and stay flashing >5min

**Relevant screenshots**

N/A

**Comment by jgbr** [comment]
verified on Mac also

**Comment by jgbr** [comment]
![untitled](https://user-images.githubusercontent.com/37260734/37583284-b5f38208-2b48-11e8-9150-6f10e4a13c3f.jpeg)

**Comment by tenko23** [comment]
Can't replicate on my Mac.

CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
