### ISSUE TITLE
V0010-GM1 Pogo button does not exist sat down only stood up

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#411]
**Basic Info**

Discord Name(If Applicable):   jgbr
Operating System:   Mac 10.13.3

**Summary**

The button to activate party move only activates if stood up and looking at side control panel of command chair.

***What is the expected correct behavior?***

Sit down and stand up and work.

**Steps to reproduce**

Sit down, no area of either side of chair works to active mode.

**Comment by jgbr** [comment]
When activating stood up the video can be stopped and started. however the party mode lights continue till you reset the game. 
![untitled](https://user-images.githubusercontent.com/37260734/37583271-9fcc960e-2b48-11e8-8c1c-75ef375b0247.jpeg)

**Comment by jeppelykke** [comment]
@HPringles transferred to Bugz
