### ISSUE TITLE
V0010-GM1 Borg attack torpedo Wrong direction

### ISSUE THREAD

**Issue by jgbr** [dapperrobotbear/Stage9#412]
Discord Name(If Applicable):   jgbr

Operating System:  Mac  10.13.3

**Summary**

When the Borg vessel fires a torpedo it appears out of no where if you move the ship to always hit the bow.

If you move the ship, the torpedo appears out of no where to always hit the bow.

***What is the expected correct behavior?***

The torpedo should hit the facing hull/shields from the direction of the Borg vessel. 

**Steps to reproduce**

Move the ship via the conn 
Let the Borg attack
note the torpedo coming at you from bow on no matter how you move the ship.

**Comment by TheStrato** [comment]
Placed in the pipeline.

**Comment by dapperrobotbear** [comment]
You're not really supposed to be able to move the ship.

**Comment by TheStrato** [comment]
Giving the current setup this is NaB. Closing ticket.
