### ISSUE TITLE
V0010-GM1 Non-Functioning Turbolift, Deck 4

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#413]
**Basic Info**

Discord Name(If Applicable):   kaadaq
CPU:  Athlon X2
GPU:  GT710
Operating System:   Win10

**Summary**

Turbolift in Main Shuttlebay stalls when attempting to go to Deck 1

***What is the expected correct behavior?***

Travel to Deck 1

**Steps to reproduce**

1.  Go to Main Shuttle Bay via Deck 04 Stop 03 (Center Forward Port)
2. Walk around to the other side, and enter Turbolift near Shuttle Descartes
3. Select Main Bridge Bow
4. Wait forever.

**Relevant screenshots**

![image](https://user-images.githubusercontent.com/34050343/37571370-21a9b728-2ad2-11e8-9c8e-4c7a403bc3b7.png)

**Comment by kaadaq** [comment]
Note that this Turbolift is on the starboard side.   Perhaps an issue crossing port to starboard or vice versa?
@HPringles, please tag.

**Comment by dapperrobotbear** [comment]
Missing junction point.
Fixed in >GM1

**Comment by tenko23** [comment]
Fix verified on a Mac.

**Comment by OssiBRI** [comment]
Still there on WIN Release V10. I'm travelling for over five minutes, now. Don't know which turbo lift I'm using, used the emergency transport out of a shuttle.

**Comment by Hackmancoltaire** [comment]
@OssiBRI please indicate the place you are taking the turbolift FROM and TO, according to the name in the menu. Thanks.

**Comment by OssiBRI** [comment]
As I've written: I took a lift (don't nie which one) to lower main bay. Took a shuttle and emergeny transported back to a lift. Then tried to get to deck 1.

**Comment by dapperrobotbear** [comment]
Without knowing how to exactly repeat the issue we can’t test it. It’s a big ship with lots of turbolift entry points

**Comment by tenko23** [comment]
I've had the same problem when doing an emergency transport from a shuttlecraft.  The turbolift does not move - not sure which lift it is, either ;p .

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
