### ISSUE TITLE
V0010-QA4 - Shuttle Craft Type 6 Number Text Shifts Position.

### ISSUE THREAD

**Issue by cheveffect09** [dapperrobotbear/Stage9#414]
**Summary**
The number of the type 6 shuttle craft text slightly shifts position when you first open the door of the craft.
example "Shuttle 42" changes to "Shuttle   42"

***What is the expected correct behavior?***
The text should appear the same way as it did before you open the shuttle craft door.

**Steps to reproduce**
1. Walk up to any Type 6 shuttle craft
2. Look at it on an angle as I have in the pictures below
3. Press the open door button and watch the number text shift position

**Relevant screenshots**
![text 1](https://user-images.githubusercontent.com/5516753/37573133-9dc58788-2b68-11e8-98f3-e19ed9dcce03.png)
![text 2](https://user-images.githubusercontent.com/5516753/37573134-9df9f536-2b68-11e8-9518-d7df4d5e9570.png)

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
