### ISSUE TITLE
V0010-GM-1 Deck 4 Main Shuttle Bay Consoles persistent even though room respawned

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#415]
**Basic Info**

Discord Name(If Applicable):   kaadaq
CPU:  Athlon X2
GPU:  GT710
Operating System:   Win10

**Summary**

The main shuttle bay consoles are persistent about the state of the bay door, even if the room respawns to its original state.

***What is the expected correct behavior?***
If room respawns with door closed, consoles should read "Open Door"

**Steps to reproduce**

1.  Enter Main Shuttle Bay
2. Use console to open the bay door
3. Exit the Main Shuttle Bay via Turbolift to another deck.
4. Return to Main Shuttle bay and access console

**Relevant screenshots**

![image](https://user-images.githubusercontent.com/34050343/37575927-0a55c228-2b00-11e8-82f4-f1c77fc52cf7.png)

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
