### ISSUE TITLE
V0010-GM1 Nine-Forward fall through the floor

### ISSUE THREAD

**Issue by MrPeppow** [dapperrobotbear/Stage9#416]
Discord Name(If Applicable): Sev  
CPU:  Ryzen 1700X
GPU:  1050 TI
Operating System:   Arch Linux

**Summary**
In Nine-Forward next to the couches at the windows you seem to be able to walk up. If you do you fall through the floor

**Relevant screenshots**
Walk up there and you will fall through:
![screenshot_20180319_105541](https://user-images.githubusercontent.com/13747941/37589137-9e0892d4-2b64-11e8-9784-f7131939b4ad.jpeg)

**Comment by Jaredsfs1** [comment]
Exists in QA3 on Mac,  Unsure about newer releases.

**Comment by MrPeppow** [comment]
Exists on Linux release version

**Comment by MrPeppow** [comment]
@HPringles Is fixed in HF1

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
