### ISSUE TITLE
V0010 - Holodeck - Going behind the arch on the 1701 bridge in the holodeck will throw you into space...

### ISSUE THREAD

**Issue by tenko23** [dapperrobotbear/Stage9#419]
**Basic Info**

Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Summary**
When you go behind the arch on the 1701 bridge in the holodeck, you either fall right into space or space appears around you - causing one to get stuck.... so you either have to fall into space or do an emergency transport.

***What is the expected correct behavior?***

Should not happen???  Should be able to go right back onto the 1701's bridge without falling into space.

**Steps to reproduce**

1.  Go to a holodeck.
2.  Load the 1701 (original Enterprise) bridge program.  Enter.
3.  Go to the left and go behind the arch.
4.  The bridge disappears on the holodeck & if you don't fall into space right away, you can see the corridor next to the holodeck, the unloaded holodeck nearby and space behind - to which you eventually have to fall into space or do an emergency transport.  Trapped!

**Relevant screenshots**

![screen shot 2018-03-19 at 11 20 25 am](https://user-images.githubusercontent.com/34230416/37608173-e02323e8-2b67-11e8-837b-063fb59380bf.jpg)

Thanks!

**Comment by HPringles** [comment]
I thought this was already fixed @scragnog

**Comment by MrPeppow** [comment]
Can confirm on Linux HF1

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
