### ISSUE TITLE
[Visual] Enterprise School Class place numbers around the corridor :)

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#42]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**
Seems Enterprise teacher and kids forget to clean up after Math in school today...

Just outside Deck 10 Room: 0583
![stage9 screenshot 2017 11 26 - 22 32 59 55](https://user-images.githubusercontent.com/33987322/33244569-70a5a984-d2fa-11e7-9176-7c6651ffd9e9.png)

**Comment by scragnog** [comment]
fixed
