### ISSUE TITLE
V0010 - Exterior - Type 15/16 Shuttlepod Nacelles Have Holes

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#420]
The top and bottom finned back parts of the Nacelles have minor holes in the model.

***What is the expected correct behavior?***
No visible see-through of the environment. 

**Steps to reproduce**
Go into 3rd person view while driving the type 15/16 Shuttlepod

![image](https://user-images.githubusercontent.com/5162659/37617135-8f2c957a-2b88-11e8-8b52-dd12e5c74d3e.png)

**Comment by jeppelykke** [comment]
@HPringles Confirmed in V0010 HF1 

![stage9 screenshot 2018 03 20 - 19 45 33 54](https://user-images.githubusercontent.com/33987322/37676137-64eaa384-2c77-11e8-8e02-47874ce6775a.png)
![stage9 screenshot 2018 03 20 - 19 46 05 67](https://user-images.githubusercontent.com/33987322/37676138-65079c8c-2c77-11e8-821f-56b3a3f830c0.png)

**Comment by MrPeppow** [comment]
Can confirm on Linux @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
