### ISSUE TITLE
Bell clapper in main shuttlebay not attached

### ISSUE THREAD

**Issue by tuvok2018** [dapperrobotbear/Stage9#423]
**Basic Info**
Started the game and went immediately to main shuttle bay. When approaching the bell the clapper was not attached and floating partly into the floor.

Discord Name(If Applicable):   
CPU: Ryzen 1800x
GPU:  Nividia 1080ti
Operating System:   Windows 10

**Summary**
Sometimes the bell is normal but if you interact pressing E the bell acts like it is now being picked up. It acts unpredictably as it will not return to normal once used at times. Very odd.
--->

***What is the expected correct behavior?***
Left click should be used instead of E to enable it to ring in a fixed manner

Bell with clapper hanging down normally

**Steps to reproduce**

1.Start game
2.Enter turbo lift
3.Select main shuttle bay deck 4/ center/ forward starboard
4. Goto bell and ring it.

**Relevant screenshots**
usercontent.com/36381392/37626732-0a14eebe-2bc9-11e8-8bbb-adbd439d2b45.jpg)
![bell clapper not attached](https://user-images.githubusercontent.com/36381392/37626736-0f052362-2bc9-11e8-933f-7873a7df1151.jpg)

**Comment by tenko23** [comment]
Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

Noticed that earlier (Mac version)... the first time I noticed it, the clapper was halfway embedded into the floor.  Just a moment ago, no clapper!  Yikes (and no clanging either, I believe)!!!

(image is of the bell tilted towards the player - no clapper to be seen anywhere ;p !~)

![screen shot 2018-03-19 at 8 34 55 pm](https://user-images.githubusercontent.com/34230416/37630952-5351b936-2bb5-11e8-9014-ef11547a76f9.jpg)

**Comment by OssiBRI** [comment]
Confirmed in V0010 Windows (bell clapper is stuck in the floor):

![grafik](https://user-images.githubusercontent.com/34159074/37650972-df95c136-2c36-11e8-90ed-a04f7cb39f09.png)

**Comment by jeppelykke** [comment]
I have following in V0010 HF1!

![stage9 screenshot 2018 03 20 - 19 43 28 53](https://user-images.githubusercontent.com/33987322/37676018-0fc57050-2c77-11e8-8a65-131f850156b3.png)
![stage9 screenshot 2018 03 20 - 19 43 36 10](https://user-images.githubusercontent.com/33987322/37676019-0fdf543e-2c77-11e8-9cc8-8c32c59edef7.png)

**Comment by tenko23** [comment]
@TheStrato - Please tag as Bug, Windows, Mac.  Thanks!

**Comment by jeppelykke** [comment]
@HPringles This has been transferred to Bugz....  (double bug report) Bug report: #400
