### ISSUE TITLE
V0010 - Deck 1 - Entire Bridge - Model Clipping

### ISSUE THREAD

**Issue by dpr47** [dapperrobotbear/Stage9#425]
**Basic Info**

Discord Name(If Applicable):   OSUBrit
CPU:  
GPU:  GTX 1060
Operating System:   Windows 10

**Summary**
Selecting 'Viewscreen Saucer View' then going to the helm and pitching the ship forward (with some forward motion) results in the exterior ship mode clipping through the bridge, when I exited the helm I then became stuck inside the ship models and forced to restart.

***What is the expected correct behavior?***

uhh... not clipping through the ship model

**Steps to reproduce**

1. Set viewscreen to Saucer View
2. Go to helm and pitch the ship downward about 45 degrees
3. exit helm

**Relevant screenshots**

**Comment by MrPeppow** [comment]
Thats what happend in the release video?

**Comment by dpr47** [comment]
Yes, I didn't watch the release video until after I submitted the bug, but it's the same problem.

**Comment by Gary-Baggins** [comment]
Unable to recreate this in HF1, can someone else confirm? @TheStrato @HPringles

**Comment by tenko23** [comment]
Seems to work ok on a Mac - can't replicate.

**Comment by jeppelykke** [comment]
@HPringles transferred to bugz
