### ISSUE TITLE
V0010 - Deck 10 - Wide Junction near to Ten Forward, Missing Bracing on corridor wall

### ISSUE THREAD

**Issue by mdtauk** [dapperrobotbear/Stage9#427]
**Basic Info**

Discord Name(If Applicable):   mdtaUK
CPU:  Ryzen 7 1700
GPU:  Geforce 1060
Operating System:   Windows 10 Fall Creators Update

**Summary**

There is a section of wall which should have bracing separating sections, but they are not visible

***What is the expected correct behavior?***
The Bracing should be there

**Steps to reproduce**

1. Walk to area
2. See the wall
3. Facepalm?? :)

**Relevant screenshots**
![stage9_003](https://user-images.githubusercontent.com/7389110/37640709-c4007f56-2c0e-11e8-8115-abb638aa09e6.png)

**Comment by tenko23** [comment]
Confirmed on a Mac.  You can see where the spine begins in the near-left and dead ends on the ceiling.

![screen shot 2018-03-20 at 6 43 12 pm](https://user-images.githubusercontent.com/34230416/37688550-ad2b3626-2c6e-11e8-90b1-fb45a22cfb07.jpg)

**Comment by kaadaq** [comment]
Confirmed in V0010-HF1 on Win10.  If you're looking for this, it's right at the junction at the end of the long spine corridor on the opposite end as Ten Forward.

@TheStrato, please remove Needs Validation and put in pipeline.

**Comment by tenko23** [comment]
@TheStrato - Please add Mac to it also.

**Comment by jeppelykke** [comment]
@HPringles transferred to Bugz
