### ISSUE TITLE
V0010 Warp from Earth to Juriet causes crash

### ISSUE THREAD

**Issue by MrPeppow** [dapperrobotbear/Stage9#428]
Discord Name(If Applicable): Sev  
CPU:  Ryzen 1700X
GPU:  1050 TI
Operating System:   Arch Linux

**Summary**
Warping from Earth to Juriet causes crash

**Steps to reproduce**
1. Go to main bridge
2. Warp 9 to Earth
3. Warp 9 to Juriet ->
Crashes right before arriving

**Comment by MrPeppow** [comment]
@HPringles Tag Linux

**Comment by TheStrato** [comment]
@MrPeppow Can you repeat this and get your crash report for it.

**Comment by MrPeppow** [comment]
Thats the log File:
After reading through it I noticed many sound loading issues. That made me notice that I hardly every hear music in stage 9...

[Stage9Linux.log](https://github.com/dapperrobotbear/Stage9/files/1829422/Stage9Linux.log)

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
