### ISSUE TITLE
V0010 [Win] Engineering: Dome behind warp core goes through the floor

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#429]
V0010 - Deck 36 - Engineering - Dome behint the warp core goes right through the floor--->
**Basic Info**

Discord Name(If Applicable): Ossi
Windows 7 Home Premium SP1 64x
Intel Core i5-2430M CPU 2.40 GHz
8.00 GB RAM
NVIDIA GeForce GT 540M

**Summary**
The newly added dome behind the warp core goes directly through the floor.

***What is the expected correct behavior?***

There should be a hole in the floor for the dome to fit thorugh.

**Steps to reproduce**

1. Go to Main Engineering
2. Walk around the warp core
3. Look to where the dome behind the core meets the floor (see screenshot an with arrow).

**Relevant screenshots**

![grafik](https://user-images.githubusercontent.com/34159074/37650441-3ad81fa0-2c35-11e8-8506-94d54204d902.png)

**Comment by Gary-Baggins** [comment]
Confirmed, please tag windows and accuracy @TheStrato @HPringles

**Comment by tenko23** [comment]
Confirmed on a Mac.  Please add Mac to it also, @TheStrato .

![screen shot 2018-03-24 at 2 34 46 am](https://user-images.githubusercontent.com/34230416/37861640-0856eef6-2f0c-11e8-8b82-50384d6f84e4.jpg)

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
