### ISSUE TITLE
V0010 HF1 Turbolift from Shuttle Bay 2 goes nowhere

### ISSUE THREAD

**Issue by Gary-Baggins** [dapperrobotbear/Stage9#433]
**Basic Info**
Turbo lift stays at stop

Discord Name(If Applicable):Gary_Baggins   

**Summary**
Selecting any location from the Shuttle Bay turbo lift (have tested 3 so far) results in you just staying in place.

***What is the expected correct behavior?***
The turbo lift should move.

**Steps to reproduce**
1. Go to Shuttle Bay 2
2. Select any destination on the menu
3. Once again grow old waiting to go anywhere.

@TheStrato @HPringles please tag windows, bugs and turbo lift.

**Comment by OssiBRI** [comment]
Confirmed. I tried to get to engineering and nothing happend, accept for the locked door. This time, I put my head through the door and saw this:

![grafik](https://user-images.githubusercontent.com/34159074/37678580-c29907f8-2c7e-11e8-9a34-6343f52c642d.png)

No moving, no nothing.

**Comment by Gary-Baggins** [comment]
@scragnog @dapperrobotbear

**Comment by dapperrobotbear** [comment]
Please indicate location of turbolift. Possibly picture of door.

**Comment by dapperrobotbear** [comment]
Shuttlebay 2 (deck 13) should only have 1 accessible turbolift.

**Comment by Gary-Baggins** [comment]
@dapperrobotbear that is correct, there is only one.

**Comment by dapperrobotbear** [comment]
Ok. Confirmed there was a point mis-alignment. Fixed for the next release (whenever that is). You can get there, but can't leave. Take a shuttle to the main shuttlebay or Restart.

**Comment by tenko23** [comment]
Even though it's fixed, please add Mac to it... same issue here.

@scragnog @dapperrobotbear

**Comment by kaadaq** [comment]
Fixed in >HF-1, @TheStrato @HPringles

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
