### ISSUE TITLE
V0010 HF1 Floor mesh in Worf's quarters

### ISSUE THREAD

**Issue by Gary-Baggins** [dapperrobotbear/Stage9#434]
**Basic Info**
You are able to fall through the floor in Worf's quarters.

Discord Name(If Applicable):Gary_Baggins   

**Summary**
Part of the floor mesh is missing.

***What is the expected correct behavior?***

You should not fall through the floor.

**Steps to reproduce**

1. Go to Worf's quarters.
2. Stand in the corner pictured below.
3. Say goodbye to your family as you freeze in Space.

**Relevant screenshots**
![image](https://user-images.githubusercontent.com/35035873/37657416-ccc5accc-2c42-11e8-9c8e-6c5891555a30.png)

Please tag Windows and rooms @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
