### ISSUE TITLE
V0010 HF1 Pogo video doesnt play

### ISSUE THREAD

**Issue by MrPeppow** [dapperrobotbear/Stage9#435]
**Basic Info**
Discord Name(If Applicable): Sev  
CPU:  Ryzen 1700X
GPU:  1050TI
Operating System:   Arch Linux KDE

**Summary**
The Pogo Video doesnt play on Linux. Disco Lights work.

**Comment by MrPeppow** [comment]
@TheStrato @HPringles Tag Linux

**Comment by ask-compu** [comment]
`[2018.03.20-07.16.40:770][172]LogMediaUtils: Error: Cannot play file://../../../Stage9Linux/Content/Movies/pogo.mp4, because none of the enabled media player plug-ins support it:`

**Comment by tenko23** [comment]
Mine plays, but it's pretty darn choppy.  Seems choppier when sitting in the Captain's chair.  On a Mac.

CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
