### ISSUE TITLE
V0010 HF1 Fall out of Turbolift

### ISSUE THREAD

**Issue by MrPeppow** [dapperrobotbear/Stage9#436]
**Basic Info**
Discord Name(If Applicable):   Sev
CPU:  Ryzen 1700X
GPU:  1050TI
Operating System:   Arch Linux

**Summary**
Turbolifting to Nacelle Control can make you fall out of the lift

**Steps to reproduce**
1. Start fresh game
2. Enter the Turbolift and set Nacelle Control as Target
3. Right after the Turbolift pulled you into its center, press the button again.
4. -> You're falling

@HPringles @TheStrato Tag Linux

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
