### ISSUE TITLE
V0010 HF1 Fall through Nacelle

### ISSUE THREAD

**Issue by MrPeppow** [dapperrobotbear/Stage9#437]
**Basic Info**
Discord Name(If Applicable):   Sev
CPU:  Ryzen 1700X
GPU:  1050TI
Operating System:   Arch Linux

**Summary**
You can jump into the Nacelle itself and then fall through.

***What is the expected correct behavior?***
Either add a collision mesh or make it impossible to jump there

**Steps to reproduce**
1. Set character speed to run
2. Open Nacelle Hatch
3. Jump inside on this plasma nozzle
4. Jump in direction of the plasma stream into the Nacelle..

**Comment by MrPeppow** [comment]
@HPringles @TheStrato Tag Linux

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
