### ISSUE TITLE
Win - V0010 HF1 - Captains Quarters blue light shine though walls.

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#438]
**Basic Info**
Discord Name:   Jeppe Lykke
CPU:  Intel Core i7-3770K CPU @ 3.50GHz
GPU:  Nvidia GeForce GTX 1070
Operating System:  Windows 10 Pro 64Bit, 16GB Ram

**Summary**
Inside Captain Picard's quarters, behind his work place, he has a blue light around picture on wall. 
This light shine though the wall out in the corridor. 

***What is the expected correct behavior?***
Clean wall with no blue lights.

**Steps to reproduce**
1. Go to Deck 8 - Captain's Quarters
2. Look at wall left of door (see blue light)
3. Go inside Captain's Quarters you can see the light comes from blue light around picture behind the work place.

**Relevant screenshots**

![stage9 screenshot 2018 03 20 - 19 07 16 89](https://user-images.githubusercontent.com/33987322/37675120-bb938e88-2c74-11e8-9b88-4d0e47b5dd09.png)
![stage9 screenshot 2018 03 20 - 19 07 22 52](https://user-images.githubusercontent.com/33987322/37675122-bcd95796-2c74-11e8-8ec1-450805264de9.png)

**Comment by tenko23** [comment]
It's a goofy bug.  The only way I can make it happen is to walk right up to the bulkhead in question... the blue light will appear for a few seconds (along with illuminating that segment of the corridor with a bit more, whitish light) and then disappears.  Wash, rinse, repeat.  Weird!  On a Mac.

![screen shot 2018-03-20 at 7 37 45 pm](https://user-images.githubusercontent.com/34230416/37690047-9ee57c2c-2c76-11e8-9869-144d68c66deb.jpg)

**Comment by Gary-Baggins** [comment]
Confirmed, please tag windows, rooms and corridors @TheStrato @HPringles

**Comment by tenko23** [comment]
Please also add Mac on here too, @TheStrato @HPringles .

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
