### ISSUE TITLE
Win - V0010 HF1 - Shuttlebay 2 Wall miss alignment.

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#439]
**Basic Info**
Discord Name:   Jeppe Lykke
CPU:  Intel Core i7-3770K CPU @ 3.50GHz
GPU:  Nvidia GeForce GTX 1070
Operating System:  Windows 10 Pro 64Bit, 16GB Ram

**Summary**
A wall next to outer door is to high, should be lowerd to align with rest of the walls. 

***What is the expected correct behavior?***
A nice OCD-FREE room :)

**Steps to reproduce**
1. Head to Shuttlebay 2
2. Look at the wall next to outer door.

**Relevant screenshots**
![stage9 screenshot 2018 03 20 - 18 52 21 60](https://user-images.githubusercontent.com/33987322/37675287-30f2944e-2c75-11e8-9ea1-fe0e8e01d60b.png)

**Comment by tenko23** [comment]
Confirmed on a Mac.  You can see where the left and the right of the main shuttlebay door do not match.

![screen shot 2018-03-20 at 7 19 31 pm](https://user-images.githubusercontent.com/34230416/37689553-b3976a98-2c73-11e8-9666-1bac43907fc4.jpg)

**Comment by Gary-Baggins** [comment]
Confirmed, please tag windows, mac and rooms @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
