### ISSUE TITLE
Win - V0010 HF1 - Main Shuttlebay PC Preforming issue (lagging bad) near Dock 10 / Dock 9

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#441]
**Basic Info**
Discord Name:   Jeppe Lykke
CPU:  Intel Core i7-3770K CPU @ 3.50GHz
GPU:  Nvidia GeForce GTX 1070
Operating System:  Windows 10 Pro 64Bit, 16GB Ram

**Summary**
Been spending some time around Shuttlebay and each time i come around to location of Dock 6-10, my PC Preforming drops and game freezes for 1-2 sec. 

***What is the expected correct behavior?***
More stable PC preforms 

**Steps to reproduce**
1. Go to Main Shuttlebay
2. Find Dock 6,7,89 and 10. 
3. Walk/Run around that area and PC freezes. 

**Relevant screenshots**
![stage9 screenshot 2018 03 20 - 20 11 36 36](https://user-images.githubusercontent.com/33987322/37677403-414a6cc6-2c7b-11e8-9937-d7d5d9a3a905.png)

**Comment by kaadaq** [comment]
Unable to validate repeatably.  I get freezes from time to time in the MSB, and while it does happen if I run around between Docks 6 & 10, it also happens over by Dock 5, and on the other side of the bay.   So I can't validate that it's specifically and issue with those Docks.

**Comment by Gary-Baggins** [comment]
Even on my low end machine I am able to sprint around the area of docks 9 & 10, the only time I got any significant lag/freezing was going behind the shuttle in dock 10. @TheStrato @HPringles

**Comment by TheStrato** [comment]
General performance issues that aren't repeatable. Will close for now as performance increases are always a Dev concern.
