### ISSUE TITLE
Win - V0010 HF1 - Main Shuttlebay Photon Torpedo Incorrect Console diagnostics 

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#442]
**Basic Info**
Discord Name:   Jeppe Lykke
CPU:  Intel Core i7-3770K CPU @ 3.50GHz
GPU:  Nvidia GeForce GTX 1070
Operating System:  Windows 10 Pro 64Bit, 16GB Ram

**Summary**
The console next to the open Photon Torpedo showing the Diagnostics, is showing Shuttle Diagnostics. 

***What is the expected correct behavior?***
The Photon Torpedo Diagnostics is a image of the Photon and not a shuttle and label. Photon Torpedo Diagnostics. 

**Steps to reproduce**
1. Go to Main Shuttlebay
2. Look at the Photon Torpedo Diagnostics terminal. (A cross from the Bell)

**Relevant screenshots**
![stage9 screenshot 2018 03 20 - 20 08 34 03](https://user-images.githubusercontent.com/33987322/37677790-52e242e6-2c7c-11e8-96cd-edbe3b41ffd2.png)

**Comment by OssiBRI** [comment]
![grafik](https://user-images.githubusercontent.com/34159074/37704702-dc2ffd2c-2cf9-11e8-853d-e3d19fd0818c.png)
Correct. But on the other hand, it reads "SHUTTLE DIAGNOSTICS" on the terminal, so maybe this console isn't linked to the torpedo (although there isn't a shuttle nearby, just a few work bees to the left from POV).

**Comment by Gary-Baggins** [comment]
Confirmed in WINV10HF1, please tag Windows and accuracy @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@HPringles  Transferred to Bugz
