### ISSUE TITLE
V0010 - In turboloft - Near bridge - Sun illuminates the inside of the turbolift, when heading up to the bridge...

### ISSUE THREAD

**Issue by tenko23** [dapperrobotbear/Stage9#444]
**Basic Info**

Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Summary**
When heading up to the bridge's bow via turbolift... when almost arriving at the bridge, the sun briefly illuminates the turbolift.  Attached is a screenshot of one of those brief moments of illumination.

***What is the expected correct behavior?***

The sun shouldn't shine in the turbolift... at least when the turbolift doors are shut.

**Steps to reproduce**

1.  Start game.
2.  Go to the nearest turbolift.
3.  Choose bridge bow for destination.  Near the destination, the sun will illuminate for a few brief moments.

**Relevant screenshots**

![screen shot 2018-03-20 at 6 49 44 pm](https://user-images.githubusercontent.com/34230416/37689104-37636988-2c71-11e8-85a2-afac95f38211.jpg)

Thanks!

**Comment by Gary-Baggins** [comment]
Confirmed in V10HF1, please tag windows and turbo lifts @TheStrato @HPringles

**Comment by tenko23** [comment]
@TheStrato - Please add Mac to this as well.

**Comment by tenko23** [comment]
Will also mention that something similar happens when heading to some other destinations around the ship via turboloft... especially to the Main Engineering stop, although these look more like ship corridor lights (or something to that effect) coming into the lift from the outside.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
