### ISSUE TITLE
V0010 - Bridge - Under main viewscreen - Too many lights underneath the viewscreen on bridge...

### ISSUE THREAD

**Issue by tenko23** [dapperrobotbear/Stage9#445]
**Basic Info**

Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Summary**
Not trying to be nitpicky, but I heard that this is a new bridge model.  On the panel below the viewscreen - the one in the middle... the one with the two lights that fly outwards (never really knew its true purpose).  Anyways, in the new model, there are too many lights appearing for accuracy.  Attached is a screenshot of how it looks - as of now.  Also attached is a screenshot from the series.  As you can see, there should only be two points of light and they should not overlap when starting a new cycle.

***What is the expected correct behavior?***

Two points of light that do not overlap when staring a new cycle.

**Steps to reproduce**

1.  On bridge look towards viewscreen.
2.  You will see them below the viewscreen and what they currently do.

**Relevant screenshots**

![screen shot 2018-03-20 at 6 52 55 pm](https://user-images.githubusercontent.com/34230416/37689315-52a0a4b2-2c72-11e8-9047-e995d59df659.jpg)
![screen shot 2018-03-20 at 7 05 39 pm](https://user-images.githubusercontent.com/34230416/37689320-5738476e-2c72-11e8-8712-7c136d6ce660.jpg)

Thanks!

**Comment by OssiBRI** [comment]
The Same in the Windows version. The old bridge did it correct (except from going from sides to The mid). The New one does Knight Rider.

**Comment by Gary-Baggins** [comment]
Confirmed in V10HF1, please tag accuracy @TheStrato @HPringles 

https://www.google.co.uk/search?rlz=1C1CHBD_en-GBGB775GB775&tbm=isch&q=enterprise+d+viewscreen&backchip=g_5:uss+enterprise+bridge&chips=q:enterprise+d+viewscreen&sa=X&ved=0ahUKEwitn6uBo4LaAhVFGsAKHa7sBOsQ3VYIJigA&biw=1280&bih=590&dpr=1.5

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
