### ISSUE TITLE
V0010 - Shuttlebay 2 - Near main, outer door - Blue hue on ceiling, from forcefield in Shuttlebay 2, is in the wrong position & angle...

### ISSUE THREAD

**Issue by tenko23** [dapperrobotbear/Stage9#446]
**Basic Info**

Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Summary**
When the shuttlebay's door is open and the forcefield is activated in Shuttlebay 2, the blue hue that's created by the forcefield glows at the wrong angle.  It also appears that the glow is coming from the corner of the bulkhead, were there is no forcefield.

***What is the expected correct behavior?***

No blue hues in these corners... or if there are, then at the angle coming from the forcefield itself.

**Steps to reproduce**

1.  Go to Shuttlebay 2.
2.  Open main shuttlebay door.
3.  Look at the position and angle the blue hue is coming from on the ceiling (left-side by door, at least).  Looks a bit out of whack ;p .

**Relevant screenshots**

![screen shot 2018-03-19 at 11 35 18 pm](https://user-images.githubusercontent.com/34230416/37689744-d78e7472-2c74-11e8-8162-a50693abe29d.jpg)

Thanks!

**Comment by kaadaq** [comment]
Unable to validate.   From everything I can see, the forcefield appears right in the center of the blue glow:
![image](https://user-images.githubusercontent.com/34050343/37858870-829a1a1a-2ee1-11e8-83fb-7c542ea7ec9f.png)

Other side, without markup:
![image](https://user-images.githubusercontent.com/34050343/37858859-649af82c-2ee1-11e8-9208-9d67353376aa.png)

I think this is an optical illusion.   @TheStrato, @HPringles, recommend closing this one.

**Comment by TheStrato** [comment]
Actually, I see what they mean and it is messed up. Will assign this one to Scragnog and he can assign it to the correct Dev.

**Comment by kaadaq** [comment]
WOW, did I misread this one.   Apologies!   I was looking for the *forcefield* coming out of the bulkhead, not the reflection.  Thanks for catching my error, @TheStrato!

**Comment by TheStrato** [comment]
No problem.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
