### ISSUE TITLE
v0010 - Deck 9 - Picard's Quaters - Whistle tune

### ISSUE THREAD

**Issue by Lufferov** [dapperrobotbear/Stage9#447]
**Basic Info**

Discord Name(If Applicable):  Lufferov 
CPU:  Core i7-4790
GPU:  GeForce 980Ti
Operating System:   Windows 10

**Summary**

If you pick up and play the Captain's Whistle, if you then drop it, the tune continues to play.

***What is the expected correct behavior?***

The tune should stop if the whistle is dropped.

**Steps to reproduce**

1. Pick up Whistle
2. Play Whistle
3. Drop Whistle

**Relevant screenshots**

**Comment by tenko23** [comment]
Confirmed on a Mac.  To get it to work... you have to hold down the mouse button to make it play and at the same time, hit enter to drop - it will keep playing.  Letting go of the mouse button and then dropping won't have the same effect.

**Comment by kaadaq** [comment]
Confirmed on Win 10 via the method described by @tenko23 -- clicked to play, held mouse button while I dropped it.  Music continued to play.

Music stops if I let go of the mouse button before I drop it.    It does not stop if I let go of the button AFTER I drop it.

@HPringles, please mark as a bug.

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
