### ISSUE TITLE
V0010-Deck 9-Hallways/9 Forward-Shot walls of with a phaser

### ISSUE THREAD

**Issue by AtlasRiker** [dapperrobotbear/Stage9#449]
**Basic Info**

Discord Name(If Applicable):   Atlas #4073
CPU:  AMD A10-7860K Radeon R7
GPU:  GEFORCE GTX 1050Ti
Operating System:  Windows 10 Pro 

**Summary**
Was able to shoot, using a phaser, at wall panels on deck 9 hallways and parts in 9 forward allowing them to fall into space and be pushed about like props. I tried to achieve the same results on other Decks, but to no success.

***What is the expected correct behavior?***

The panels not to fall into space so i can fall out.

**Steps to reproduce**

1.Get a phaser
2.Go to Deck 9
3.Shoot at wall panels

**Relevant screenshots**

![20180321214126_1](https://user-images.githubusercontent.com/37638854/37739618-9cc1c98c-2d52-11e8-88d9-43b8a0c67b02.jpg)
![20180321214112_1](https://user-images.githubusercontent.com/37638854/37739639-ac6144bc-2d52-11e8-88a3-657997e44f83.jpg)
![20180321212213_1](https://user-images.githubusercontent.com/37638854/37739643-b2344e7a-2d52-11e8-8bd6-1cdf5ae789da.jpg)
![20180321212552_1](https://user-images.githubusercontent.com/37638854/37739651-b965dc04-2d52-11e8-828f-1e1a235ec81a.jpg)

**Comment by tenko23** [comment]
Although I can't totally recreate, I managed to get a couple of bulkheads by Nine-Forward to bulge in.  On a Mac.

![screen shot 2018-03-21 at 6 53 32 pm](https://user-images.githubusercontent.com/34230416/37744116-86a7e4cc-2d3b-11e8-8d71-60adde9537a5.jpg)

**Comment by relavis** [comment]
I've noticed that all of the wall panels that can fall off are not hooked up to the red alert system. This may help to find out which are which.

**Comment by kaadaq** [comment]
Confirmed in Windows on V010-HF1 near Crew Quarters 09|6863 (aft & port of Nine Forward)  @TheStrato or @HPringles , please tag as a bug
![image](https://user-images.githubusercontent.com/34050343/37745840-8f292b30-2d4d-11e8-9a35-53d966a02f77.png)

**Comment by kaadaq** [comment]
Not just the non-red alert panels.  I was able to dislodge the opposite side as well.
![image](https://user-images.githubusercontent.com/34050343/37745894-d5426bb8-2d4d-11e8-8110-a7363364717e.png)

**Comment by kaadaq** [comment]
@TheStrato, I think that's it.

**Comment by jeppelykke** [comment]
@TheStrato moved!

**Comment by jeppelykke** [comment]
@HPringles Transferred to Bugz
