### ISSUE TITLE
V0010-HF1 Deck 3/4 MSB Observation Corridor Unmatched Junction

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#450]
**Basic Info**

Discord Name(If Applicable):   kaadaq
CPU:  Athlon X2
GPU:  GT710
Operating System:   Win10

**Summary**

Observation area above Dock 17 has an unmated corridor junction.   Also, turbolift at end of hallway does not have deck label.

***What is the expected correct behavior?***
Seamless mesh

**Steps to reproduce**

1.  Go upstairs by the runabout
2.  Proceed through the door straight ahead, turn left and proceed through door
3.  Advance to corridor junction

**Relevant screenshots**

![image](https://user-images.githubusercontent.com/34050343/37747682-ba5671c4-2d56-11e8-9eda-e19f69fdfbc4.png)

![image](https://user-images.githubusercontent.com/34050343/37747748-03192f32-2d57-11e8-831f-fe245c150874.png)

@TheStrato - Needs Validation

**Comment by tenko23** [comment]
Confirmed on Mac, although it is particularly interesting here ;o ... walking on thin air xD !!!~
Port side.

![screen shot 2018-03-21 at 9 52 48 pm](https://user-images.githubusercontent.com/34230416/37748595-648f5430-2d52-11e8-8dda-20409ee1ee69.jpg)
![screen shot 2018-03-21 at 9 50 48 pm](https://user-images.githubusercontent.com/34230416/37748596-64a18df8-2d52-11e8-9b06-116e8b885d8d.jpg)

@TheStrato

**Comment by tenko23** [comment]
@HPringles - please add Mac to the list.

**Comment by TheStrato** [comment]
Added Mac.
