### ISSUE TITLE
V0010 - Turbolift - Deck 9, stop 4 - Stuck & unavailable...

### ISSUE THREAD

**Issue by tenko23** [dapperrobotbear/Stage9#451]
**Basic Info**

Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Summary**
On any turbolift, choose option four for deck nine.  It does not have a destination stop and most of the time, you'll get stuck in the turbolift.  Also attached is a screenshot, looking out once getting stuck.

***What is the expected correct behavior?***

Either no option or a route to the stop.

**Steps to reproduce**

1.  Go to any turbolift.
2.  Choose deck 9.
3.  Choose stop 4.  No-go.

**Relevant screenshots**

![screen shot 2018-03-21 at 7 01 25 pm](https://user-images.githubusercontent.com/34230416/37748789-2254cbf8-2d53-11e8-8846-35b8bb78acb7.jpg)
![screen shot 2018-03-21 at 6 59 59 pm](https://user-images.githubusercontent.com/34230416/37748790-2263ba1e-2d53-11e8-8de7-acc121b8c05c.jpg)

Thanks!

**Comment by kaadaq** [comment]
Validated in Win10.   @HPringles please tag as a Turbolift bug.

**Comment by Gary-Baggins** [comment]
Confirmed in V10HF1, please tag turbo lifts @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@TheStrato Moved!
