### ISSUE TITLE
V0010 - Deck 9 - Outside of Nine-Forward - Outer space flickers in & out...

### ISSUE THREAD

**Issue by tenko23** [dapperrobotbear/Stage9#452]
**Basic Info**

Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Summary**
When looking though the windows in the door to Nine-Forward - the doors facing the outer windows inside... whatever is outside in outer space will flicker in-and-out of existence.  Not sure if it's a graphics problem on my end, but thought I'd report it anyways.

***What is the expected correct behavior?***

Outside should stay in existence.

**Steps to reproduce**

1.  Go to deck 9.
2.  Stand outside of Nine-Forward... behind the doors that face the outside windows.
3.  Look through the door windows, into Nine-Forward.
4.  Observe.  Outer space beyond (outside of the outer windows in Nine-Forward) might flicker in-and-out of existence.

**Relevant screenshots**

![screen shot 2018-03-21 at 6 54 16 pm 2](https://user-images.githubusercontent.com/34230416/37749273-3ccf5316-2d55-11e8-9515-3ebd228a317f.jpg)
![screen shot 2018-03-21 at 6 54 16 pm 1](https://user-images.githubusercontent.com/34230416/37749274-3ce01598-2d55-11e8-8f9b-e876f56a78a7.jpg)

Thanks!

**Comment by kaadaq** [comment]
Unable to validate.   

I've stood in pretty much the same position (see below), tried different camera angles, moved forward and back, and strafed side to side, standing still in each new position for over a minute, and did not have space wink out once.   And I'm running an inferior graphics card (GT710)

![image](https://user-images.githubusercontent.com/34050343/37791007-74e534ee-2dde-11e8-9489-9d3abdf5bcfe.png)

@HPringles I think this can be closed.

**Comment by tenko23** [comment]
Could be different on a Mac and a Windows machine ;o (perhaps :) )~

**Comment by kaadaq** [comment]
Yikes!   Great point.  I missed that this was reported on a Mac.   @HPringles, ignore me! :)

**Comment by Gary-Baggins** [comment]
Unable to confirm in V10HF1, this could be a machine related issue @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@TheStrato moved!
