### ISSUE TITLE
V0010-HF1 Deck 10/12/Multiple Ragdoll NPC's fall through floor

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#453]
**Basic Info**

Discord Name(If Applicable):   kaadaq
CPU:  Athlon X2
GPU:  GT710
Operating System:   Win10

**Summary**

Incapacitating NPC's in corridors often results in them falling through the floor.  I've personally encountered this in Deck 12 outside of sickbay, following a hypospray attack, as well as Deck 10 midships as a result of phaser fire.

***What is the expected correct behavior?***
NPC body should be on the floor.

**Steps to reproduce**

1.  Grab a phaser
2. Travel to Deck 10 spine corridor (for example) where it necks down moving away from Ten Forward
3. Shoot an NPC
4. Wave buh-bye

**Relevant screenshots**

![image](https://user-images.githubusercontent.com/34050343/37749406-2997d99a-2d5e-11e8-81a1-6ffde0b2136a.png)

**Comment by tenko23** [comment]
Confirmed on Deck 12 using a Mac.

**Comment by tenko23** [comment]
Mmm, I might have gotten a screenshot - hard to tell.

![screen shot 2018-03-22 at 12 19 04 am](https://user-images.githubusercontent.com/34230416/37752879-13ca24a6-2d68-11e8-9ea0-c308edfcef03.jpg)

**Comment by OssiBRI** [comment]
On deck 12 they do this, too if you hypospray them (v10hf1 Win). Didn't try a phaser in that deck, yet.

**Comment by kaadaq** [comment]
@TheStrato, looks like this one is validated by multiple users on multiple platforms.   Mac, Win, Corridor, NPC please?

**Comment by jeppelykke** [comment]
@TheStrato Moved!
