### ISSUE TITLE
V0010-HF1 Deck 6 - Emergency Transport Doesn't work if no TL used

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#454]
**Basic Info**

Discord Name(If Applicable):   kaadaq
CPU:  Athlon X2
GPU:  GT710
Operating System:   Win10

**Summary**

Emergency Transport does not work if you have not spawned a Turbolift.   

User Fox reports that this happened even after visited other decks, but was not able to replicate this.   It's possible, though that if for some reason the last TL despawns, ET would also become inoperative.

***What is the expected correct behavior?***
Either a TL is spawned on your last deck and takes you to it, OR emergency transport defaults to the transporter room if no turbolift is available.

**Steps to reproduce**

1.  Start a new game session
2.  Step out into the corridor.  Feel free to run around, as long as you don't trigger an TL doors.
3. Attempt to emergency transport.
3.

**Relevant screenshots**

N/A

**Comment by tenko23** [comment]
Can confirm using a Mac.  Attached is a series of four screenshots as the transport happens.

**Steps to reproduce**

1.  Start game.
2.  Walk out of the Transporter Room.
3.  Immediately do an emergency transport (or in the area away from the nearest turbolift).  You will remain in the same spot - even after transport.


![screen shot 2018-03-22 at 12 23 38 am](https://user-images.githubusercontent.com/34230416/37752796-bb6f6870-2d67-11e8-95e4-9b8b13e4ec19.jpg)
![screen shot 2018-03-22 at 12 23 41 am](https://user-images.githubusercontent.com/34230416/37752800-bfcd38de-2d67-11e8-8577-14498e7c133a.jpg)
![screen shot 2018-03-22 at 12 23 43 am](https://user-images.githubusercontent.com/34230416/37752804-c27c502e-2d67-11e8-9232-8dffc6422a29.jpg)
![screen shot 2018-03-22 at 12 23 45 am](https://user-images.githubusercontent.com/34230416/37752809-c534e18c-2d67-11e8-8c91-71d1e8f6d073.jpg)

**Comment by Gary-Baggins** [comment]
Confirmed in V10HF1 please tag windows and rooms @TheStrato @HPringles

**Comment by TheStrato** [comment]
Perhaps this should follow suit with changing the player start location and transport you back to the transporter room.

**Comment by tenko23** [comment]
@TheStrato - Please add Mac to the list, too.

**Comment by jeppelykke** [comment]
@TheStrato moved!
