### ISSUE TITLE
v0010 - Deck 6 - Transporter Room 2 - O'Brien - Balding in wrong spot???

### ISSUE THREAD

**Issue by tenko23** [dapperrobotbear/Stage9#455]
**Basic Info**

Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Summary**

Got a sneak-peek of O'Brien - behind O'Brien, in Transporter Room 2.  Is he balding in the wrong spot ;p ???

***What is the expected correct behavior?***

Should have hair near his neck, with the rest of his hair?

**Steps to reproduce**

1.  Go to Transporter Room 2.
2.  Sneak behind O'Brien - without him noticing.
3.  Look at the back of his head... looks a little off ;p .

**Relevant screenshots**

![screen shot 2018-03-21 at 12 10 13 am](https://user-images.githubusercontent.com/34230416/37749863-fbbaee6e-2d57-11e8-9037-e66e8510d0df.jpg)

Thanks!

**Comment by kaadaq** [comment]
Validated.
![image](https://user-images.githubusercontent.com/34050343/37790495-19198314-2ddd-11e8-9057-eb6655ceeab2.png)

@HPringles suggest removing Needs Validation and apply Accuracy tag

**Comment by Gary-Baggins** [comment]
Confirmed in V10HF1 please tag npc @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@TheStrato moved!
