### ISSUE TITLE
v0010 - Deck 8 - Next to Picard's quarters (at the corridor junction) - Unmatched corridors (computer access panels & red alert light strips)...

### ISSUE THREAD

**Issue by tenko23** [dapperrobotbear/Stage9#456]
**Basic Info**

Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Summary**
At the corridor junction by Picard's quarters - when looking both towards and away from his quarters, the corridors do not match (in the one direction, it is walled off by a forcefield, so might have not been totally worked on yet).  Towards Picard's quarters, the computer access panels are opposite of the quarters.  In the opposite direction, they are along the bulkhead adjacent to the quarters.

***What is the expected correct behavior?***

Not exactly sure which side they should be on... no good examples from the series, but both sides probably should match.

**Steps to reproduce**

1.  Go to deck 8 - at the corridor junction near Picard's quarters.
2.  Look in both directions - towards and away (opposite) from his quarters.
3.  You will see.

**Relevant screenshots**

![screen shot 2018-03-22 at 12 51 31 am](https://user-images.githubusercontent.com/34230416/37753915-40744d4c-2d6d-11e8-92ca-3c6e66b62e34.jpg)
![screen shot 2018-03-22 at 12 51 39 am](https://user-images.githubusercontent.com/34230416/37753901-32ca4c32-2d6d-11e8-8888-9c37cc36db33.jpg)

Thanks!

*Edit - just noticed that the red alert light strips are doing the same thing.

**Comment by tenko23** [comment]
Same area as #198 .

**Comment by kaadaq** [comment]
This is validated.  Screenshot below.  Note how the red alert light is on the far wall in the active corridor, and on the opposite wall behind the forcefield.   Should probably be consistent.

![image](https://user-images.githubusercontent.com/34050343/37790326-8f9f343a-2ddc-11e8-8178-6aceabef61f0.png)

**Comment by kaadaq** [comment]
@TheStrato , please add corridor tag and remove needs validation

**Comment by jeppelykke** [comment]
@TheStrato Moved!
