### ISSUE TITLE
V0010-HF1 [Win] "Generations Bridge" (Holodeck, Deck 12) Issues

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#457]
**Basic Info**

Discord Name(If Applicable):   Ossi
CPU:  Intel Core i5-2430M CPU 2.40 GHz 8.00 GB RAM
GPU:  NVIDIA GeForce GT 540M
Operating System:  Windows 7 Home Premium SP1 64x 

**Summary**

***What is the expected correct behavior?***
1: There shouldn't be a hole in the bridge.
2: Indicators should blink at red alert / light up at yellow alert.

**Steps to reproduce**

Hole in the wall:
1. Go to deck 12, Holodecks and start the Generations bridge programm in the first holodeck.
2. Go to the console at the dedication plaque.
3. Stand at the console and look down.

Alert issues:
1. Go to deck 12, Holodecks and start the Generations bridge programm in the first holodeck.
2. Go to red/yellow alert.
3. Look at the indicators.

**Relevant screenshots**

![grafik](https://user-images.githubusercontent.com/34159074/37791522-ba099e4a-2e09-11e8-9500-1d4985ee69af.png)
![grafik](https://user-images.githubusercontent.com/34159074/37791536-c10e3098-2e09-11e8-801b-832df7c9d338.png)
![grafik](https://user-images.githubusercontent.com/34159074/37791549-c66f9e1e-2e09-11e8-95d2-eb6c85a4d7e1.png)

**Comment by Gary-Baggins** [comment]
Both issues confirmed in V10HF1 please tag rooms @TheStrato @HPringles

**Comment by tenko23** [comment]
Ah, there's something similar with #458 , holes and the arch with this Generations bridge... can see right into space ;p (from the chair platform)!  On a Mac.

![screen shot 2018-03-24 at 2 27 14 am](https://user-images.githubusercontent.com/34230416/37861759-66e1bbe8-2f0e-11e8-875d-aae74328be19.jpg)

**Comment by tenko23** [comment]
Wanted to mention - when I was on the Generations bridge, taking the above screenshot... the viewscreen - what was outside, "flickered".  Similar to issue #452 (both on a Mac).

**Comment by jeppelykke** [comment]
@TheStrato moved!
