### ISSUE TITLE
V0010-HF1 [Win] Deck 12 Holodecks-Corridor Floor too deep

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#458]
**Basic Info**

Discord Name(If Applicable): Ossi
CPU: Intel Core i5-2430M CPU 2.40 GHz 8.00 GB RAM
GPU: NVIDIA GeForce GT 540M
Operating System: Windows 7 Home Premium SP1 64x 

**Summary**

In the holodeck corridor on deck 12 the floor appears to be too deep. There's a gab through which you can see into space.
***What is the expected correct behavior?***
Solid corridors.

No stars
**Steps to reproduce**

1. Go to deck 12, Holodecks
2. Leave the lift.
3. Look down to where the walls shoukd meet the floor.

**Relevant screenshots**

![grafik](https://user-images.githubusercontent.com/34159074/37792285-b2024934-2e0b-11e8-8986-1d85ab5f8e26.png)

**Comment by tenko23** [comment]
Confirmed on a Mac.  The two don't match up nicely.

![screen shot 2018-03-23 at 2 33 00 am](https://user-images.githubusercontent.com/34230416/37816956-f6916a1c-2e42-11e8-8cc9-0e48d533656a.jpg)
![screen shot 2018-03-23 at 2 32 50 am](https://user-images.githubusercontent.com/34230416/37816957-f6a36924-2e42-11e8-8a4c-334666f13b3b.jpg)

**Comment by Gary-Baggins** [comment]
Confirmed in V10HF1 please tag corridors @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@TheStrato moved!
