### ISSUE TITLE
V0010-HF1 [Win] - Deck 02 Crew Lounge - No saucer visible outside the windows

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#459]
**Basic Info**

Discord Name(If Applicable): Ossi
CPU: Intel Core i5-2430M CPU 2.40 GHz 8.00 GB RAM
GPU: NVIDIA GeForce GT 540M
Operating System: Windows 7 Home Premium SP1 64x

**Summary**

When you look out of the windows of the crew lounge on deck two, there's no part of the saucer section visible.

***What is the expected correct behavior?***
You should see the fron half of the saucer section outside.

**Steps to reproduce**

1. Go to deck 02.
2. Find the crew lounge.
3. Move to the windows and look out.

**Relevant screenshots**

![grafik](https://user-images.githubusercontent.com/34159074/37792737-e6efab22-2e0c-11e8-8156-0995e8b2912f.png)

**Comment by Gary-Baggins** [comment]
Confirmed in V10HF1 please tag windows, mac and accuracy @TheStrato @HPringles

**Comment by jeppelykke** [comment]
@TheStrato moved!
