### ISSUE TITLE
V0010-HF1 [Win] Deck 35 Nacelle Control - Walk through forcefield + gab between meshes

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#460]
**Basic Info**

Discord Name(If Applicable): Ossi
CPU: Intel Core i5-2430M CPU 2.40 GHz 8.00 GB RAM
GPU: NVIDIA GeForce GT 540M
Operating System: Windows 7 Home Premium SP1 64x

**Summary**
When you open the hatch to the plasma stream, you can walk through the activated forcefield, plus there is a gab between the control room and the plasma stream room.

***What is the expected correct behavior?***
The forcefield should keep me from falling into the plasma stream room. Also, when the hatch is open, you shouldn't be able to see into space.

**Steps to reproduce**

1. Go to nacelle control.
2. Open the obsrevation hatch.
3. Walk up to the hatch and enter the hatch. Walk right up to the forcefield and look down. --> See the stars outside.
4. Jump through the forcefield and pray, that you haven't forgotten to open the Maintenance Door.

**Relevant screenshots**

![grafik](https://user-images.githubusercontent.com/34159074/37798602-862aeb42-2e1d-11e8-9f1d-09495067cf81.png)

**Comment by tenko23** [comment]
Can confirm both on a Mac.  I think that forcefield issue has been there in previous versions, also ;o ~

![screen shot 2018-03-23 at 2 47 41 am](https://user-images.githubusercontent.com/34230416/37817380-99beaf46-2e44-11e8-96c5-5528ff24e786.jpg)

**Comment by Gary-Baggins** [comment]
Both the gap in the mesh and being able to walk through the force field are confirmed on V10HF1 please tag missing mesh and rooms @TheStrato  @HPringles
