### ISSUE TITLE
v0010 - Turbolofts - Turbolifts will force-jump you back into them after selecting a destination, then quickly running out...

### ISSUE THREAD

**Issue by tenko23** [dapperrobotbear/Stage9#461]
**Basic Info**

Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Summary**
When you go into any turbolift, select a level and before departure, run out of it... you will magically appear back in the turbolift, even though you were previously in the corridor.  Attached are screenshots of the series of events.

***What is the expected correct behavior?***

The turbolift should take off alone and leave you alone on deck.

**Steps to reproduce**

1.  Go into any turbolift.
2.  Select a destination.
3.  Before the doors close, run out.
4.  Boom!  You're back in the lift.

**Relevant screenshots**

![screen shot 2018-03-22 at 7 33 40 pm](https://user-images.githubusercontent.com/34230416/37805586-2dcc1b38-2e09-11e8-951c-181368cbf31e.jpg)
![screen shot 2018-03-22 at 7 33 54 pm](https://user-images.githubusercontent.com/34230416/37805587-305b4ce8-2e09-11e8-8879-64de69e1b4a1.jpg)
![screen shot 2018-03-22 at 7 33 57 pm](https://user-images.githubusercontent.com/34230416/37805589-324c4e44-2e09-11e8-989a-f939752fc724.jpg)
![screen shot 2018-03-22 at 7 33 59 pm](https://user-images.githubusercontent.com/34230416/37805590-33f0fb32-2e09-11e8-8ec9-4dd2fe37475a.jpg)

Thanks!

**Comment by kaadaq** [comment]
This is verified.   Can stand outside the turbolift and activate a destination and you jump inside.
May need to reduce the distance from which you can operate the panel.

@TheStrato @HPringles , please flags as a Turbolift Bug
