### ISSUE TITLE
V10- Turbolift Menu - All 

### ISSUE THREAD

**Issue by Cacille** [dapperrobotbear/Stage9#462]
Comment from Youtube - "Brian" 

I made this comment in a prev release - not sure if you saw it. I am fairly sure that when referring to the front or back of the bridge (or any room) you would use the terms "fore" and "aft" as opposed to "bow" or "stern". This is just a detail for the turbolift destination list which lists "Bridge - bow" or "Shuttlebay - bow". I'd appreciate knowing if you've seen/agreed with this comment. Love the project, awesome work!﻿

Cacille has commented that she has seen this comment and added it here and that if it's fixed in the future version, he is why it is. And if it isn't, then there's a reason (canon or otherwise) the name is kept.

**Comment by Gary-Baggins** [comment]
https://en.wikipedia.org/wiki/Aft
https://en.wikipedia.org/wiki/Stern
"The difference between aft and stern is that aft is the inside (onboard) rearmost part of the vessel, while stern refers to the outside (offboard) rearmost part of the vessel. The stern is opposite the bow, the "outside" (offboard) of the front of the boat"

https://en.wikipedia.org/wiki/Bow_(ship)
"The bow /baʊ/ is the forward part of the hull of a ship or boat, the point that is usually most forward when the vessel is underway. Both of the adjectives fore and forward mean towards the bow. The other end of the boat is the stern."

I believe there are also terms for "forward of middle" and "rear of middle" but that might confuse things further, I would suggest only using bow and aft. 
@TheStrato @HPringles tag accuracy
