### ISSUE TITLE
v0010 - Shuttlecraft - Encounter with Borg - Alert sounds and attack...

### ISSUE THREAD

**Issue by tenko23** [dapperrobotbear/Stage9#463]
**Basic Info**

Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Summary**
When encountering the Borg in a shuttlecraft... within the shuttlecraft, you will hear bridge alert sounds (yellow alert, red alert, etc.).  Typically, shuttlecraft do not have these types of alert sounds in TNG.  Also, when the Enterprise is attacked/hit by the Borg's energy weapon, the shuttlecraft will also shake, as if it were hit (not the case).

***What is the expected correct behavior?***

The going-ons in the shuttlecraft, during the Borg attack, should not mimic what happens on the bridge of the Enterprise.

**Steps to reproduce**

1.  Go to bridge and set course for Jouret IV, warp 1 (or 2, if you're fast enough).
2.  Head to the nearest shuttlecraft (preferably in Shuttlebay 2).
3.  Exit the ship in a shuttlecraft and get slightly ahead of the Enterprise.
4.  Once the Borg attack commences, the described will occur.  Also go to third person view mode, to observe the attack.

**Relevant screenshots**

No screenshots, due to sequence.

Thanks!

**Comment by kaadaq** [comment]
Can confirm this in Windows 10 -- the full scripted sequence displays, even if you are not on board the Enterprise.  Not sure if this is actually a bug. 

@HPringles @TheStrato , your call.  NaB Enhancement?   Or Accuracy Bug?
