### ISSUE TITLE
v0010 - Turbolifts - Selecting destination with phaser - Selection target off...

### ISSUE THREAD

**Issue by tenko23** [dapperrobotbear/Stage9#464]
**Basic Info**

Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Summary**
When holding a phaser and selecting a destination in a turbolift, the selection target is off... meaning where you point is not what you're actually hitting.  In the attached image, the selection target (little round dot - I guess that's what you call it ;p ) is toward the center-right of the destination panel... but what is actually being selected is the very bottom-right edge of the "Turbolift - Select Destination" bar (in red).

***What is the expected correct behavior?***

The two should probably align a bit better...

**Steps to reproduce**

1.  Go to any turbolift with a phaser.
2.  Try to select a destination.
3.  You will see that the alignment is off.  Whatever you are closest to will highlight in red/light yellow/light purple, but does not match the selection target (am I saying this right???).

**Relevant screenshots**

![screen shot 2018-03-23 at 1 35 05 am](https://user-images.githubusercontent.com/34230416/37816601-b18c3060-2e41-11e8-87b4-9e5cf2c08ca0.jpg)

Thanks!

**Comment by kaadaq** [comment]
I have observed this as well.  It's pretty tricky to operate. @TheStrato @HPringles please put this in pipeline.
