### ISSUE TITLE
V 0010 Win - Yellow Alert no Sound - Red Alert Generations Bridge wrong sound

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#465]
**Summary**
1. The yellow Alert has no Sound when activated by player neither on the bridge nor in the corridors. In the borg event it’s perfect. 

2. In V9 the Generations Bridge had its own red alert sound. That got lost during transition to the holodeck. 

***What is the expected correct behavior?***

1. You should hear a yellow alert sound when activating yellow alert. Like in the borg encounter. 

2. The red alert on generations bridge should sound different than on the other bridges. Like in V9

**Steps to reproduce**

1. Turn on yellow alert 
2. Turn on red alert in the holodeck while running the generations bridge program 

**Relevant screenshots**
None. It’s a sound issue 🤷‍♂️😊

**Comment by tenko23** [comment]
Agree and confirmed on a Mac.

**Comment by tenko23** [comment]
@TheStrato - Please also add Window to this.
