### ISSUE TITLE
V0010-HF1 Shoot out Main Shuttle Bay Doors from outside

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#467]
**Basic Info**

Discord Name(If Applicable):   kaadaq
CPU:  Athlon X2
GPU:  GT710
Operating System:   Win10

**Summary**

The previous issue with being able to shoot out the main shuttlebay doors still occurs, if you stand OUTSIDE the bay doors and fire at them.

***What is the expected correct behavior?***

Doors should be solid and resist phaser fire.

**Steps to reproduce**

1. Go to Shuttlebay 2
2. Pick up the phaser rifle
3. Open the shuttlebay door and deactivate the forcefield
4. Go EVA and climb up onto the saucer section
5. Fire at the shuttlebay door.

**Relevant screenshots**

![image](https://user-images.githubusercontent.com/34050343/37858952-ecd30c9c-2ee2-11e8-8995-35009eaab701.png)

**Comment by tenko23** [comment]
Yeah, that's pretty awesome ;D !  Glad there aren't any Romulans trying to get in ;p .  On a Mac.

![screen shot 2018-03-24 at 3 33 03 pm](https://user-images.githubusercontent.com/34230416/37868702-d30ebfa4-2f78-11e8-877d-95f5316f181d.jpg)
![screen shot 2018-03-24 at 3 33 07 pm](https://user-images.githubusercontent.com/34230416/37868703-d4a1beca-2f78-11e8-8052-b5a2bbff3160.jpg)
