### ISSUE TITLE
V0010 / V0010HF1 [Win] - Deck 01 spawns reeeaaaal slow

### ISSUE THREAD

**Issue by OssiBRI** [dapperrobotbear/Stage9#469]
**Basic Info**

Discord Name(If Applicable): Ossi
CPU: Intel Core i5-2430M CPU 2.40 GHz 8.00 GB RAM
GPU: NVIDIA GeForce GT 540M
Operating System: Windows 7 Home Premium SP1 64x

**Summary**

When going to deck 01, the mesh spawns real slow. When the turbolift doors open (no matter which one), there are about five seconds where there's only space and doors. When leaving the lift while this, you fall out of the ship. This also happens, when entering the ready room or conference room from the bridge and vice versa. This only happens on deck 01.

***What is the expected correct behavior?***
Open the lift doors, *afert* the room is spawn. With ready room and observation, maybe the rooms should be spawn together with the main bridge mesh.

**Steps to reproduce**

There should be rooms behind the doors.

1. Go to the bridge or ready room or observation lounge.

**Relevant screenshots**

![grafik](https://user-images.githubusercontent.com/34159074/37867569-076dfb76-2f9b-11e8-86dc-330f567a0e3e.png)
![grafik](https://user-images.githubusercontent.com/34159074/37867578-1b933008-2f9b-11e8-9453-38d120db8d41.png)
![grafik](https://user-images.githubusercontent.com/34159074/37867582-28d10182-2f9b-11e8-9b89-b74c374a2701.png)

**Comment by tenko23** [comment]
Totally agree.  Although my lag isn't as bad, the lag on my computer is almost comparable to dominoes falling... kind'a like a cascading effect.  On a Mac.

CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3
