### ISSUE TITLE
V0010-HF1 Deck 10 - Wall missing collision near Ten Forward stbd door

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#471]
**Basic Info**

Discord Name(If Applicable):   kaadaq
CPU:  Ryzen 3 1200
GPU:  GTX1050 Ti
Operating System:   Win 10

**Summary**

One whole side of the corridor just aft of Ten Forward is missing collision -- you can walk through into space.

***What is the expected correct behavior?***
Solid walls

**Steps to reproduce**

1.  Take TL to Deck 10, stop 00
2.  Step out of TL to first junction -- can see Ten Forward doors to the right
3. Turn to the left and step through any of these wall segments into space.  Problem is consistent all the way down to the other end.

**Relevant screenshots**

![image](https://user-images.githubusercontent.com/34050343/37885478-6aedfb54-3083-11e8-8684-39288caf53a6.png)

@TheStrato @HPringles, please mark Needs Validation for other testers to confirm.

**Comment by tenko23** [comment]
Cannot replicate the problem on a Mac.

**Comment by kaadaq** [comment]
Fixed in >HF-1, @TheStrato @HPringles

**Comment by TheStrato** [comment]
Resolved. Closing this ticket.
