### ISSUE TITLE
V0010-ONGOING-1  Multiple Decks - NPC Render Issues

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#473]
**Basic Info**

Discord Name(If Applicable):   kaadaq
CPU:  Ryzen 3 1200
GPU:  GTX1050
Operating System:   Win10

**Summary**

Many of the NPC's have eyes, but no rendered heads.   Others have a Frankenstein-y look about them.

***What is the expected correct behavior?***

Something that won't give me nightmares.

**Steps to reproduce**

1.  Travel to Deck 12.  Find some NPC's
2.  Travel to Deck 9, find other NPC's

**Relevant screenshots**

![image](https://user-images.githubusercontent.com/34050343/38005478-c48ca7b4-320e-11e8-951c-c59c648ea018.png)

**Comment by kaadaq** [comment]
@TheStrato @HPringles, please tag.

**Comment by kaadaq** [comment]
Interestingly, Deck 1 NPC's seem to do just fine:
![image](https://user-images.githubusercontent.com/34050343/38006750-53dd7f4c-3214-11e8-9993-a18a0687550d.png)

**Comment by tenko23** [comment]
Cannot confirm any rendering issues, with this issue, on a Mac.

**Comment by kaadaq** [comment]
Also, NPC's in Data's Quarters are stuck in Default Pose:
![image](https://user-images.githubusercontent.com/34050343/38008443-b80657a2-321c-11e8-926c-8e7b2bcb8ba4.png)

**Comment by HPringles** [comment]
Build failure per Dapper, closing.
