### ISSUE TITLE
V0010-ONGOING-1 Turbolift Issues

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#474]
**Basic Info**

Discord Name(If Applicable):   kaadaq
CPU:  Ryzen 3 1200
GPU:  GTX1050 Ti
Operating System:   Win10

**Summary**

Turbolift doors don't seem to seal all the way (light shining through top part) while standing outside.  Inside, map is missing from control display for certain decks (only decks 4 & 10 display), .  Also, while TL is moving, doors are invisible.  Can see the motion of the turbolift through the model with space backdrop.

***What is the expected correct behavior?***

Doors are sealed, map is displayed, and doors are visible closed during motion.

**Steps to reproduce**

1.  Approach Turbolift stop 09|00 from outside
2.  Enter Turbolift
3.  Move to another destination

**Relevant screenshots**

![image](https://user-images.githubusercontent.com/34050343/38005765-34bf95a4-3210-11e8-87ce-1bd23128f642.png)

![image](https://user-images.githubusercontent.com/34050343/38005848-95f92c72-3210-11e8-86de-fe26ef9dfa49.png)

![image](https://user-images.githubusercontent.com/34050343/38005826-810595a8-3210-11e8-8ff1-86da02afcdcc.png)

@TheStrato @HPringles please tag

**Comment by kaadaq** [comment]
Missing door frame, Deck 1 | Bow
![image](https://user-images.githubusercontent.com/34050343/38007338-f7e0c05c-3216-11e8-8125-982e49de37bb.png)

**Comment by HPringles** [comment]
Build failure per Dapper, closing.
