### ISSUE TITLE
v0010-ONGOING-1 Main Bridge Yellow Alert Persistent

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#476]
**Basic Info**

Discord Name(If Applicable):   kaadaq
CPU:  Ryzen 3 1200
GPU:  GTX1050 Ti
Operating System: Win10   

**Summary**

Upon entering the main bridge, yellow alert is active.   If you turn it off, leave the bridge and re-enter, yellow alert is re-enabled.

***What is the expected correct behavior?***
Persistent state for alert status

**Steps to reproduce**

1.  Go to Main Bridge.  Observe yellow alert panels lit.
2.  Go to settings menu and select "Normal".  Observe yellow alert panels unlit.
3.  Enter the ready Room, wait for doors to close, then re-enter bridge.  Observe yellow alert panels re-list

**Relevant screenshots**

![image](https://user-images.githubusercontent.com/34050343/38006986-4a919c2e-3215-11e8-938f-0b45a830e27a.png)

@TheStrato @HPringles, please tag

**Comment by HPringles** [comment]
Build failure per Dapper, closing.
