### ISSUE TITLE
V0010-ONGOING-1 Warp Destinations Not Loading

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#479]
**Basic Info**

Discord Name(If Applicable):   kaadaq
CPU:  Ryzen 3 1200
GPU:  GTX1050 Ti
Operating System:   Win10

**Summary**

Warping to any other destination results in a blank starfield and loss of navigation visual/sound. 

***What is the expected correct behavior?***

**Steps to reproduce**

1.  From conn while at Jupiter, Warp to Unexplored Sector (or any other location).   Ship enters warp with animation.
2.  Upon arrival, observe black space (no starfield)
3. Attempt to warp to another destination.  No animation, no sound, no change in background.

**Relevant screenshots**

![image](https://user-images.githubusercontent.com/34050343/38007540-e551aa2c-3217-11e8-830d-6efa6adca931.png)

@TheStrato @HPringles please tag

**Comment by HPringles** [comment]
Build failure per Dapper, closing.
