### ISSUE TITLE
v0010-ONGOING-1 - Runabout - Phasers Can Shoot Through Parts Of The Cockpit

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#481]
The monitors (the black reflective glass) the ceiling, floor and doors. Are not solid to weapons fire. You can fire right through them.

***What is the expected correct behavior?***

Cockpit walls should be solid for Phasers. 

**Steps to reproduce**

Go into Runabout with a Phaser. And shoot the black panels next to the windows. 

![image](https://user-images.githubusercontent.com/5162659/38007839-74e05246-3219-11e8-92cc-cc8863fb9001.png)

**Comment by HPringles** [comment]
Build failure per Dapper, closing.
