### ISSUE TITLE
Playing Intro sequence, can't skip!

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#5]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

If you choose playing Intro sequence, there no options to skip or stop.

**Comment by scragnog** [comment]
spacebar or escape will end the sequence and go back to the main menu now
