### ISSUE TITLE
Missing collisions in main shuttlebay

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#50]
So far I found two issues.
-Part of the corridor on the right side of the shuttle bay has an unsold floor. You fall through.
-The handrails on the stairs in the main shuttlebay have no collision.

**Comment by scragnog** [comment]
handrail issue resolved.

no clue where you mean for the unsolid floor. I've checked the collision view and there was an issue near the cargo elevator, did you mean there?

**Comment by harryingles** [comment]
the unsolid floor is deck 3 portside corridor, just after the exit from the main shuttlebay bow door.

**Comment by scragnog** [comment]
still having trouble locating this. You mentioned Deck 3, so the upper deck of the shuttlebay? Is this after you've gone up the stairs?

**Comment by Sciencekeeper** [comment]
It sounds like the big Me and a few others already reported earlier. The location is correct but the one I’m talking about is Deck 4. There is really a corridor you fall right through into space.

**Comment by Sciencekeeper** [comment]
Bug of course. Auto correct... 
It’s the corridor right side when you look at the ship from front view. Left side if you look at it from the shuttlebay doors

**Comment by Sciencekeeper** [comment]
Damn I got it exactly wrong. Opposite side I’m so sorry. Just tried again

**Comment by scragnog** [comment]
FINALLY FOUND IT! Fixed now. Thanks guys.
