### ISSUE TITLE
[Visual]Skin and hair colors not present

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#51]
I have a GTX 970 and am using Windows 10.

The skin tones do not load. The characters have white skin and hair. The only one that has color is Data, however he doesn't look 100% right ether. His skin looks a tad pale. Also the little hair that Picard has seems to be a slightly darker tone than the other NPC's.

On a side  note, Data's neck clips with his collar on his left side. Additionally the NPC's on the front bridge stations are placed slightly to far back, meaning that they clip with the chairs slightly.

**Comment by dapperrobotbear** [comment]
Set your graphics quality to High.

**Comment by scragnog** [comment]
please confirm what happens when you change between the 3 graphics quality settings in the menu.

the neck clip issue a known bug, and is the result of the current animations we're using, which need to be overhauled. Same with the chair clipping.

**Comment by Sciencekeeper** [comment]
I had this issue as well. Just restarted the game and it worked. Didn’t change graphic settings in between. Can it be that something isn’t correct loaded while starting the game?

**Comment by scragnog** [comment]
It's possible, but I don't know why it would happen. Haven't seen it here, but then maybe that's because I've got the source files.

**Comment by Sciencekeeper** [comment]
![9b532c58-b64a-4f24-b552-05679b64da18](https://user-images.githubusercontent.com/33996890/33280500-99a632f6-d3a2-11e7-86bc-7ddfda19bc96.png)

**Comment by Sciencekeeper** [comment]
Looks like this. Problem is it was a one time thing happpend the first time I opened stage 9. I can’t duplicate the issue.

**Comment by TheStrato** [comment]
Was this related to the new missing skin textures issue @scragnog ?

**Comment by TheStrato** [comment]
Most likely not an issue anymore. Closing this ticket.
