### ISSUE TITLE
[Visual] Gab between Legs and Torso on players Char.

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#52]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**
If you 1st person looks down and to left, your see a small gab between the legs and torso. 

![stage9 screenshot 2017 11 27 - 19 36 54 67](https://user-images.githubusercontent.com/33987322/33283450-235fa51e-d3ac-11e7-8f34-f49ec3d54600.png)

**Comment by scragnog** [comment]
thanks. this is a known issue. There's a minor vertex snapping issue on this mesh when using animations. We'll be rebuilding it soon and will resolve this one then.
