### ISSUE TITLE
[Visual] Enterprise Name on back of shuttles floating mid air

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#53]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

Open up a shuttlecraft and look up at the name tag: NCC-1701-D on back of the shuttle is floating mid air.

![stage9 screenshot 2017 11 27 - 19 32 59 61](https://user-images.githubusercontent.com/33987322/33283510-56d8012a-d3ac-11e7-8417-f5530469f26a.png)

**Comment by scragnog** [comment]
super good catch! Fixed for final release, but not in time for QA release 2.
