### ISSUE TITLE
Deck1: Bridge - blind spot on main viewer 

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#54]
![image](https://user-images.githubusercontent.com/33996890/33287482-1636f9c0-d3b9-11e7-827b-31f654037d18.jpg)
On the left side of the main viewer is blind spot. If you are close to it it looks like the Space isn’t going completely to the right side. Or something is in the way.

**Comment by scragnog** [comment]
Known bug. This is because the turbolift at the front of the bridge can be seen floating in space when it's been spawned. This is just a bodge solution. We're replacing this bridge for v0.1.0 so this duct tape fix will have to work for this release.
