### ISSUE TITLE
Deck 1 - Observation Lounge- Panels floating kind of over the chairs 

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#55]
![image](https://user-images.githubusercontent.com/33996890/33287670-bc5a08d8-d3b9-11e7-92e9-29f37ad60700.jpg)

The panels in observation lounge should be on the conference table. There floating over the chairs of Riker and worf instead

**Comment by scragnog** [comment]
Hah. This is my fault. Duh! Fixed.
