### ISSUE TITLE
At Warp there are sometimes no Stars visible outside the ship

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#56]
I still didn’t figure out how to replicate this. It just sometimes happens. Main viewer and every window is just black.

GTX 1060 6 GB - win 10 - i5 core

**Comment by scragnog** [comment]
Out of curiosity, is it possible that they were visible, just not very bright? We did reduce the amount of particles and their brightness. I'm wondering if it could be that.

**Comment by Sciencekeeper** [comment]
No that’s not it. Sometimes it works sometimes - after destroying the satellite - they’re gone. The windows are completely black. 

If I start the pre release and just go to Warp 9 I see the stars. All is working. If I start the game fire the torpedo and destroy the satellite sometimes the torpedo is visible only a second because the animation is super fast. Then go to Warp 9 with debris floating around the stars are gone. Everything is just black outside.

Steps are: 
Start game
Fire torpedo 
Go to Warp 9 

Maybe it’s just my PC

**Comment by Sciencekeeper** [comment]
Ossi Reported the same issue in Discord. His specs:

Windows 7 Home Premium SP1 64x
Intel Core i5-2430M CPU  2.40 GHz
8.00 GB RAM
NVIDIA GeForce GT 540M

**Comment by OssiBRI** [comment]
I just had a hunch an switched v-sync off. The warp stars are back :-)

**Comment by Gary-Baggins** [comment]
This is either not replicate-able or fixed @TheStrato please close.

**Comment by OssiBRI** [comment]
This seems to be related to The grafic drivers. I did an update and The Stars were there. Next update: Gone again. Update: Back, ect, blabla...

**Comment by TheStrato** [comment]
@OssiBRI So this is an issue that you are still having in v10 QA2 for Windows? What is your Discord name on the testers team?

**Comment by Sciencekeeper** [comment]
@TheStrato this Problem doesn‘t exist anymore. It was in the Testing Build of V9 - can be closed.

**Comment by OssiBRI** [comment]
@TheStrato I'm mit in the QA Team ( would ne glad if i were), this is an old v9 related Problem. I only brought it up again, since it was mentioned, it would not be replicatable.

**Comment by TheStrato** [comment]
@OssiBRI Ping me in the general channel of the server and I will see what I can do.

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
