### ISSUE TITLE
Ship wide Alert Status doesn’t apply on other Decks

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#57]
At present it affects the Deck your on. If you change a map via Turbolift It turns to normal and you have to go to Red Alert again.

**Comment by scragnog** [comment]
@dapperrobotbear any ideas? I'm sure this was working previously. Confirmed here though, the new maps aren't picking up alert status so the walls aren't flashing and the NPCs aren't running around all panicky.

**Comment by TheStrato** [comment]
I have traveled to several decks since I turned it on, the NPC's aren't running anymore but the panels on the walls are still flashing.

**Comment by dapperrobotbear** [comment]
I think I can confirm this. We'll log it and try to have it fixed for v9-VR

**Comment by OssiBRI** [comment]
Works on 0.0.9, doesn't work on 0.0.9.1 VR.

**Comment by Sciencekeeper** [comment]
-> That is still an issue in V10 QA2 some Walls are flashing - others are not

**Comment by dapperrobotbear** [comment]
If you can provide exact replication steps it would be helpful. I definitely made changes to how this works and I can't get this behavior anymore. Thanks.

**Comment by Sciencekeeper** [comment]
It is a lot better now. Just turn on red alert on any Deck and take a walk on Deck 2. You see that many walls are in red alert. A few others are not anymore. If I turn on red alert on Deck 2 all walks are lightning up. 

Same on Deck 10. I haven’t figured out a real pattern yet..

Tell you what as soon as i’m Home from work I will start swiping the whole ship for walls that are not on red alert if I startet it on another Deck. If you need it sooner maybe another tester will help find a pattern here.

**Comment by TheStrato** [comment]
No rush @Sciencekeeper

**Comment by jgbr** [comment]
I was able to verify this on Mac.

I visited the outside corridor of the bride and observation room which were not at red alert.

I then went to engineering and found red alert on some of the panels only.

I then went to ten forward and some panels also had this.

I can not find a pattern.

**Comment by OssiBRI** [comment]
If it helps: It didn't work correctly in V8. Went well in V9. Didn't work in V9.1-VR (about as incorrect as in v8). Doesn't seem to work in V10 (cannot tell, I'm not in the QA-group). So - in my oppinion - the error must have been "placed" somewhen between v9 and v9.1, or for v9.1 ff. you took data from v8, without the corrections for v9.

**Comment by Sciencekeeper** [comment]
I GOT IT!!!!

Sooooo. 

1. Turn on Red Alert on the Bridge. 
2. Travel to Deck 9
3. go to the "Central Corridor" I#M talking about the big one, leading to Nine Forward
4. Follow the Corridor and keep looking right and left on every junction
5. You will notice that the corridors where the Crew Quarters are (not the Standard Corridors) are not lighting up

That's what I'm talking about. Seems that everything else works. So the Deck 2 Screenshots are actually resolved like @dapperrobotbear thought

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
