### ISSUE TITLE
On Deck 2 from Room 4439 to 2918 have wrong deck number

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#58]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

On Deck 2 from Room 4439 to Room 2918 the deck numbers are incorrectly labeled. 

![stage9 screenshot 2017 11 27 - 21 34 51 81](https://user-images.githubusercontent.com/33987322/33288132-760f5552-d3bb-11e7-9b36-356d02b62e2a.png)
![stage9 screenshot 2017 11 27 - 21 37 54 96](https://user-images.githubusercontent.com/33987322/33288133-762c7fd8-d3bb-11e7-934b-053c1f25a9cd.png)

**Comment by scragnog** [comment]
well spotted! Fixed.
