### ISSUE TITLE
Deck 4 - Space visible beneath Doors

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#59]
In the same corridors you used to fall out of the ship space is visible at some doors and on the ground 

In the corridors at the other side of main shuttle bay (deck4) Same issue

**Comment by Sciencekeeper** [comment]
Update - at some doors you can see outside the ship right left and under the door 
![image](https://user-images.githubusercontent.com/33996890/33288317-154c00a2-d3bc-11e7-8f45-c6071837e0de.jpg) 


This is 04 1118

**Comment by Sciencekeeper** [comment]
At some point the ground has holes - still the hallway you used to fall of the ship 
![image](https://user-images.githubusercontent.com/33996890/33288429-8b8e2538-d3bc-11e7-9a61-a82d1a49b181.jpg)

**Comment by scragnog** [comment]
gaps underneath doors, known issue. No resolution yet. The other issues mentioned here should be resolved.
