### ISSUE TITLE
Turbolift kicks you out going to Main shuttlebay center

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#6]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

If you take the turbolift to Main shuttlebay Center, it will kick you out of the turbolift, and if you walk a few steps you fall though the world. 

![stage9 screenshot 2017 11 25 - 21 08 13 15](https://user-images.githubusercontent.com/33987322/33234426-eea9fbfc-d226-11e7-9e4c-4821f80afdeb.png)

**Comment by scragnog** [comment]
this is resolved now
