### ISSUE TITLE
Deck 2 Room 3646 door frame has a gab on both side

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#60]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

![stage9 screenshot 2017 11 27 - 21 42 52 63](https://user-images.githubusercontent.com/33987322/33288275-f9695344-d3bb-11e7-8ed4-d30d9fb352a8.png)

**Comment by scragnog** [comment]
well spotted. resolved.
