### ISSUE TITLE
Deck 3 Room 4912 Control Room, Big glass windows (grey line, alignment issue)

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#63]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**
If you walk up to the glass at center window and the sides of the left windows you notice a grey line.

![stage9 screenshot 2017 11 27 - 21 53 07 72](https://user-images.githubusercontent.com/33987322/33288849-edd90540-d3bd-11e7-8748-5e998d2fceff.png)
![stage9 screenshot 2017 11 27 - 21 53 14 54](https://user-images.githubusercontent.com/33987322/33288850-edf841f8-d3bd-11e7-91cc-0745f75a3b53.png)
![stage9 screenshot 2017 11 27 - 21 53 35 37](https://user-images.githubusercontent.com/33987322/33288851-ee117a92-d3bd-11e7-90aa-5b36468a5aa5.png)

**Comment by scragnog** [comment]
adjusted the placement now. This should be resolved (or at least, much better)
