### ISSUE TITLE
Deck 6 - Door 06 538 Astrophysics Lab opens only for very thin people 

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#64]
![image](https://user-images.githubusercontent.com/33996890/33289095-b02ffa18-d3be-11e7-959d-dcb3aff2ec01.jpg)

**Comment by dapperrobotbear** [comment]
Wow. Never seen THAT one before.

**Comment by Gary-Baggins** [comment]
@dapperrobotbear was this room removed? I am unable to locate it to verify.

**Comment by Sciencekeeper** [comment]
No it’s still there 😉 maybe the room number changed. But I saw it in v10 QA2 there is not actually a room there. It’s just the door it doesn’t open. But the door is sooooo small

**Comment by Gary-Baggins** [comment]
I can not find this room on deck 6 @TheStrato @HPringles

**Comment by TheStrato** [comment]
@Gary-Baggins Well @Sciencekeeper said it was still there in QA2 so that covers the "needs validation" label. Perhaps if @Sciencekeeper could give us a turn map(i.e. come out of TL and make 3 left and a right) one of the Dev's can find this and fix it.

**Comment by dapperrobotbear** [comment]
I was pretty sure I fixed this one. :-/ Maybe I missed a door somewhere.

**Comment by Sciencekeeper** [comment]
@dapperrobotbear I am sorry! Seems to be my mistake. I can't find it anymore. Sorry to waste your time. Maybe i used one of the previous builds by mistake i have a real collection of QA releases and release Versions of Stage 9 by now. Again.... Sorry!

**Comment by Sciencekeeper** [comment]
It clearly was fixed between QA 1 and 2 (Win)

**Comment by TheStrato** [comment]
Resolved. Closing ticket.
