### ISSUE TITLE
Deck 3 Room 5530, 4202, 3783 and 5111 Window alignment issue!

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#65]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

All have windows issue with grey line. and looks out of alignment.  

![stage9 screenshot 2017 11 27 - 22 02 38 04](https://user-images.githubusercontent.com/33987322/33289230-2a349864-d3bf-11e7-9d58-df91f448b416.png)
![stage9 screenshot 2017 11 27 - 22 03 13 36](https://user-images.githubusercontent.com/33987322/33289231-2a519630-d3bf-11e7-9ab1-7984ec40ebe1.png)

**Comment by scragnog** [comment]
fixed now
