### ISSUE TITLE
Deck 9 - there are corridor walls missing all around nine forward 

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#66]
![image](https://user-images.githubusercontent.com/33996890/33289298-5955ae30-d3bf-11e7-9d30-ddc76a823847.jpg)

**Comment by jeppelykke** [comment]
![stage9 screenshot 2017 11 27 - 23 01 17 99](https://user-images.githubusercontent.com/33987322/33291681-e6dbe6fa-d3c6-11e7-9efb-75b36d80cb4c.png)

**Comment by Gary-Baggins** [comment]
I no longer see these errors, please close @TheStrato @HPringles

**Comment by Gary-Baggins** [comment]
wrong ticket, ignore me

**Comment by Gary-Baggins** [comment]
Ok i have the right ticket this time, there are no missing walls around 9 forward please close @HPringles
