### ISSUE TITLE
Deck 10 - Hallway Computercore first corridor in direction to ten forward - there is also space on the floor showing between 2 corridors 

### ISSUE THREAD

**Issue by Sciencekeeper** [dapperrobotbear/Stage9#67]

**Comment by scragnog** [comment]
@dapperrobotbear looks to be related to the spline hallway issue where carpet pieces along the same spline end up having gaps between them

**Comment by Gary-Baggins** [comment]
I no longer see these errors, please close @TheStrato @HPringles
