### ISSUE TITLE
Deck 4 Room 2959/3497 and 4202/4743 NPC spawning in close off area and trapped 

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#68]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

Deck 4 Room 2959 + 3497 (same room 2 different door numbers, both side of room)
Deck 4 Room 4202 + 4743 (same room 2 different door numbers, both side of room)

**Comment by Gary-Baggins** [comment]
NPCs spawn where they will and usually behind force fields, please close @TheStrato @HPringles
