### ISSUE TITLE
Turbolift Error if you goto Deck 6 (Transporter 1,2,3,4) you can't use Turbolift to leave Deck 6

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#69]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

You can take turbolift fine to: Transporter Room 1&2 or 3&4, 

**But:**
If you take Turbolift from Transport 1&2 to Transporter Room 3&4
or
If you take Turbolift from Transport 3&4 to Transporter Room 1&2

You fall though the world.

**EDIT** 
You can't take Turbolift anywhere off Deck 6, then you get kicked off, you trapped on Deck 6

![stage9 screenshot 2017 11 27 - 22 28 39 67](https://user-images.githubusercontent.com/33987322/33290264-729e5862-d3c2-11e7-99f4-2ce88b57d595.png)
![stage9 screenshot 2017 11 27 - 22 28 04 01](https://user-images.githubusercontent.com/33987322/33290270-78af1dc2-d3c2-11e7-90c0-994f7ac0b663.png)

**Comment by Gary-Baggins** [comment]
Issue no longer present, please close @TheStrato @HPringles
