### ISSUE TITLE
in Mainshuttlebay Door sign is mirrored 

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#7]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**
Also on the door behind the stairs is mirrored. 

![stage9 screenshot 2017 11 25 - 21 11 55 36](https://user-images.githubusercontent.com/33987322/33234438-21da8b2c-d227-11e7-8795-bb3290f71c9c.png)

**Comment by scragnog** [comment]
well spotted! Fixed these now :-)
