### ISSUE TITLE
[Deck 1:Bridge]Object dropped on the floor vanish

### ISSUE THREAD

**Issue by sylario** [dapperrobotbear/Stage9#70]
WHen you drop a pad or a tricorder on the ramp it "sink" in the inclined floor.
EDIT . in fact it happen on all of the bridge.

**Comment by Gary-Baggins** [comment]
Issue is still present, please tag Windows and props @TheStrato

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
