### ISSUE TITLE
Shuttle Bug - Remote buttons stop responding

### ISSUE THREAD

**Issue by HPringles** [dapperrobotbear/Stage9#73]
If you click the remote buttons in the shuttles too many times, they stop working, and the door control buttons stop working too. Driving still works though

SUBMITTED BY ARCHER

**Comment by Gary-Baggins** [comment]
Whilst I can duplicate this it might just be my computer, needs further testing, please tag windows @TheStrato @HPringles

**Comment by kaadaq** [comment]
Confirmed in GM-1.    I clicked on the remote buttons several times (Main-2-Main-2-Main), and eventually caused the MSB door to open without actually spawning the shuttlebay.  

![image](https://user-images.githubusercontent.com/34050343/37576332-4a73f850-2b02-11e8-8fff-039e3fa8878e.png)

This one is pretty far fetched.  Still, might be good to disable both buttons once a click is made until the doors have completed their motion and the bay is spawned.

@TheStrato please update.

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
