### ISSUE TITLE
Door set to the wrong colour(grey)

### ISSUE THREAD

**Issue by HPringles** [dapperrobotbear/Stage9#74]
This door on deck 9 is the wrong colour

SUBMITTED BY ARCHER

**Comment by dapperrobotbear** [comment]
Is there supposed to be picture here?

**Comment by Gary-Baggins** [comment]
This ticket needs more information (pictures/locations) @TheStrato @HPringles

**Comment by HPringles** [comment]
I remember submitting this one - it was a correct door but I never closed it.
