### ISSUE TITLE
Dead area in the ceiling of 9 forward

### ISSUE THREAD

**Issue by HPringles** [dapperrobotbear/Stage9#75]
There is a dead area in the ceiling - See photo

![](https://cdn.discordapp.com/attachments/384819283647004672/384822217483223050/unknown.png)

**Comment by Gary-Baggins** [comment]
@HPringles as this is your report I will let you check this one, I can't really go to deck 9.

**Comment by kaadaq** [comment]
Phenomenal catch, @HPringles.   I can confirm this in GM-1.   I think your screenshot was the port side ceiling window.  It's even more visible if you're at Jupiter and you face to the starboard side.   Is there something up there that's blocking the view??

![image](https://user-images.githubusercontent.com/34050343/37575073-878b42a4-2afb-11e8-9b96-69de4307e9cb.png)

@TheStrato please advance

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
