### ISSUE TITLE
Deck 8 - Outside Capt. Picards quarters, and at turbolift, gab in floor

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#76]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

Just outside Turbolift.
![stage9 screenshot 2017 11 27 - 22 44 12 96](https://user-images.githubusercontent.com/33987322/33291090-0904f962-d3c5-11e7-823b-260ba7ed33ed.png)

Floor is out of alignment. and you can see out in space!
![stage9 screenshot 2017 11 27 - 22 45 17 17](https://user-images.githubusercontent.com/33987322/33291091-0921a29c-d3c5-11e7-813f-5cf94a7eadd7.png)
![stage9 screenshot 2017 11 27 - 22 45 24 90](https://user-images.githubusercontent.com/33987322/33291092-093906a8-d3c5-11e7-9df8-33b99050de66.png)

**Comment by Gary-Baggins** [comment]
I'm tempted to say close this as there is maybe a pixel gap outside both doors to Picard's quarters but I will leave it up to you once again @TheStrato @HPringles
