### ISSUE TITLE
Battle Bridge, gap in floor between the bridge and Turbolift

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#78]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

Gab in floor, 
![stage9 screenshot 2017 11 27 - 22 51 33 33](https://user-images.githubusercontent.com/33987322/33291301-a4825808-d3c5-11e7-9a82-6156cd1083e2.png)

**Comment by Gary-Baggins** [comment]
Gap is till there please tag windows and corridors @TheStrato @HPringles

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
