### ISSUE TITLE
Can't change graphics settings to Epic

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#79]
It seems I can only go to High. When I go to Epic, it dose not move the slider over.

Also as a side note, I noticed for a few builds now that when you adjust the audio settings, and restart the game, the settings revert to default. By that I mean that the actual effect goes back to default. The sliders stay where you had them. You just need to go back in and reapply the settings.

**Comment by dapperrobotbear** [comment]
The Epic graphics setting was removed (or should have been)

**Comment by nkjellman** [comment]
Why?

**Comment by Gary-Baggins** [comment]
Epic graphics option re-added and usable, please close @TheStrato @HPringles

**Comment by HPringles** [comment]
Done
