### ISSUE TITLE
Deck 3 Room 4202 NPC spawns in correct in chairs

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#8]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**
Deck 3 Room 4202 NPC spawns incorrectly in the chair.

![stage9 screenshot 2017 11 25 - 21 13 12 59](https://user-images.githubusercontent.com/33987322/33234468-8eb1c594-d227-11e7-8419-c27176c91d07.png)

**Comment by scragnog** [comment]
fixed :-D
