### ISSUE TITLE
Shuttle door opened automatically

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#80]
I noticed when I flew my shuttle back into the bay (main shuttle bay), the back door opened up automatically. I'm not sure if this was a feature or not.

**Comment by Gary-Baggins** [comment]
i won't be able to test this @TheStrato @HPringles

**Comment by HPringles** [comment]
@scragnog Can you confirm if this is a bug or a feature?

**Comment by TheStrato** [comment]
The door closes when you are in flight mode so is this really a problem or is it "vallet mode". Closing ticket.
