### ISSUE TITLE
Deck 9 - In Nine Forward is a image that flickers on and off

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#81]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

a wall image is flicking on and off when..

![stage9 screenshot 2017 11 27 - 23 02 31 58](https://user-images.githubusercontent.com/33987322/33291765-42bfa876-d3c7-11e7-8494-6c1785b9b9c5.png)
![stage9 screenshot 2017 11 27 - 23 02 31 83](https://user-images.githubusercontent.com/33987322/33291766-42d85a42-d3c7-11e7-8602-290407a7b320.png)

**Comment by scragnog** [comment]
fixed
