### ISSUE TITLE
Occasionally game locks up when using turbolift

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#82]
On a rare occasion, the game will completely freeze. To the point where you cant minimize it.

This is when you use a turbolift and select another deck, is when it can happen. You hear the turbolift start moving, then it freezes.

This happened to me just now, and it happened once yesterday. Both times it happened was when I left the main shuttle bay.

**Comment by Gary-Baggins** [comment]
I cannot replicate this even with my low end machine, please close @TheStrato @HPringles
