### ISSUE TITLE
Deck 10 Just out side of Turbolift Ten Forward Starboard

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#83]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

There is gab in the floors and walls around the exit of the 2 turbolifts. 

![stage9 screenshot 2017 11 27 - 23 12 11 32](https://user-images.githubusercontent.com/33987322/33292267-e9a57d54-d3c8-11e7-96da-5f2d4a15f2b4.png)
![stage9 screenshot 2017 11 27 - 23 12 16 53](https://user-images.githubusercontent.com/33987322/33292268-e9bc371a-d3c8-11e7-8abb-d4a765ddeda4.png)

**Comment by Gary-Baggins** [comment]
There is maybe a one pixel gap in the floor but i will leave this open and add to it as there is a "curve" in the floor in the same location, 10 Forward starboard turbo lift exit and walk straight ahead just past the right hand turn to enter 10FW. please tag windows and corridors @TheStrato @HPringles

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
