### ISSUE TITLE
Turbolift on Deck 9 gets stuck open

### ISSUE THREAD

**Issue by HPringles** [dapperrobotbear/Stage9#84]
Turbolift next to the incorrectly coloured door gets stuck open when opened.

Across from 4532(biophysics)

SUBMITTED BY ARCHER

![](https://cdn.discordapp.com/attachments/384819283647004672/384827671684579338/unknown.png)

**Comment by kaadaq** [comment]
Also had this happen on the main bridge when leaving the Ready Room.   TL door opened and closed several times, then stayed open while I sat in the command chair.

**Comment by Gary-Baggins** [comment]
Correction, many turbo lift doors are getting stuck open on deck 9, please tag windows and bug @TheStrato @HPringles

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
