### ISSUE TITLE
Deck 10 Room 5055 End of hall way, wall alignment is off + floating chairs

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#85]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

![stage9 screenshot 2017 11 27 - 23 18 10 30](https://user-images.githubusercontent.com/33987322/33292397-6137568a-d3c9-11e7-9e42-b112eca9b241.png)
![stage9 screenshot 2017 11 27 - 23 18 14 16](https://user-images.githubusercontent.com/33987322/33292398-614f6fcc-d3c9-11e7-8e98-4ad2f386c88f.png)

Floating chairs
![stage9 screenshot 2017 11 27 - 23 20 57 09](https://user-images.githubusercontent.com/33987322/33292493-b3a84140-d3c9-11e7-97dd-0f4b728342d9.png)
![stage9 screenshot 2017 11 27 - 23 20 59 50](https://user-images.githubusercontent.com/33987322/33292494-b3bff7b8-d3c9-11e7-9fa8-fc6b6d56b011.png)

**Comment by Gary-Baggins** [comment]
Not entirely sure of the location but i found an area visually similar with no floating furniture or wall alignment problems, please close @TheStrato @HPringles
