### ISSUE TITLE
Battle bridge Issues

### ISSUE THREAD

**Issue by harryingles** [dapperrobotbear/Stage9#86]
Overlapping Lcars panels

![](https://cdn.discordapp.com/attachments/384819283647004672/384829571146579968/unknown.png)

And you can go through the ceiling if you stand on the back chars

![](https://cdn.discordapp.com/attachments/384819283647004672/384829863409877002/unknown.png)

SUBMITTED BY ARCHER

**Comment by scragnog** [comment]
Both fixed. Always blows my mind the things you guys will do to find these bugs, jumping on the backs of chairs! Thanks.
