### ISSUE TITLE
Turbolift routing from 10 Forward Hallways bugged!

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#88]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

1)
Take the turbo lift to: Forward Hallway | Port side, and then take turbo lift to Ten Forward | Starboard it reroutes you to Computer Core...

2)
Take the turbo lift to: Forward Hallway | Starboard side, and then take turbo lift to Ten Forward | Starboard it kicks you out with big error sound as if you ask the turbolift to go to same location you at.

![stage9 screenshot 2017 11 27 - 23 35 34 24](https://user-images.githubusercontent.com/33987322/33293270-885505ca-d3cc-11e7-8b99-6cba73e3acd0.png)

**Comment by Gary-Baggins** [comment]
unable to recreate please close @TheStrato @HPringles
