### ISSUE TITLE
Deck 12 - HMO Office door is locked

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#89]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

The door leading into HMO Office is locked, the door is across of Deck 12 room: 6555

![stage9 screenshot 2017 11 27 - 23 51 24 36](https://user-images.githubusercontent.com/33987322/33293817-5af3cfa6-d3ce-11e7-8cb6-67e588667a98.png)

**Comment by harryingles** [comment]
I saw this too, however if you go into headbob mode, and walk at the door you merge through slightly and see there is nothing there yet, so I believe it was locked as there isnt nothin to walk into.

@scragnog @dapperrobotbear Am I right?

**Comment by jeppelykke** [comment]
Nope sorry, you wrong :P 

If you go into Sickbay turn left into "Dr. Crusher office" that's the HMO Office :) 
Think door was unlocked on earlier version but is locked in this one.

**Comment by dapperrobotbear** [comment]
That door is intentionally locked because the sickbay set is not angled the same way as the corridor for that section of the ship. It's a known issue.

**Comment by Gary-Baggins** [comment]
This is still present but as dapper stated it's intentional, i'll leave this one up to you guys @TheStrato @HPringles
