### ISSUE TITLE
height issue Sitting in Captains chair main bridge

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#9]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 2017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release
**Bug Report:**

When sitting in Captains chair on main bridge, the camera goes down to seat level, and you height is just under shoulder of the NPC's, also your entire body disappears. 

![stage9 screenshot 2017 11 25 - 21 09 24 63](https://user-images.githubusercontent.com/33987322/33234476-af32b256-d227-11e7-8cb9-0eaafc7d5d7d.png)

**Comment by scragnog** [comment]
fixed!
