### ISSUE TITLE
Deck 12 - holodecks 6,7,8,9 gab between turbolift and deck 12

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#90]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**
Gab in the floor in Turbolift at:  Holodecks 6,7,8,9
![stage9 screenshot 2017 11 27 - 23 57 24 06](https://user-images.githubusercontent.com/33987322/33293959-e17f3916-d3ce-11e7-9b64-b370eb5e2356.png)

**Comment by Gary-Baggins** [comment]
Still present, please tag Windows and corridors @TheStrato @HPringles

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
