### ISSUE TITLE
Deck 12 - Sickbay wall gab just next to turbolift

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#91]
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

Exit turbolift at Sickbay.
![stage9 screenshot 2017 11 28 - 00 02 05 65](https://user-images.githubusercontent.com/33987322/33294131-819099b8-d3cf-11e7-9201-14a6dc710633.png)

**Comment by scragnog** [comment]
fixed
