### ISSUE TITLE
Turbolift getting stuck observation.

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#93]
Not sure if this helps but I noticed that when the turbolift gets stuck, it happens when you get in one that you didn't come in on. But not just that, I believe it happens when the one you entered is not on the list.

For example, Deck 9 only has Stellar Cartography Starboard. However there are multiple shafts on that deck. I bet that is why turbolifts are getting stuck.. Since its not on the destination list, it doesn't know where to go.

**Comment by Sciencekeeper** [comment]
The second part seems to be the issue. 

I can’t replicate the first part. If I for example go to ten forward and use the computer core lift to go on it works.

**Comment by Gary-Baggins** [comment]
Still an issue, please tag windows and bug @TheStrato @HPringles

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
