### ISSUE TITLE
Toggling 1st/3rd person view resets the head bob setting

### ISSUE THREAD

**Issue by Bt-btt** [dapperrobotbear/Stage9#95]
When you are in 1st person mode with head bob off and switch to 3rd person mode and back to 1st person mode, the head bob resets to on again and the player model is visible again. 
Also the camera is slightly set behind the player model. 
Press the Head Bob button two times and everything is normal again as it should be

**Comment by scragnog** [comment]
I *think* this is fixed now. Made some changes to the player character to help with shuttle interaction and reapplied some of the logic to use when changing character mode.
