### ISSUE TITLE
Wrong orientation of sitting on some chairs

### ISSUE THREAD

**Issue by Bt-btt** [dapperrobotbear/Stage9#98]
The bar stools and the bench in the big starboard crew lounge on the deck 3 (in the central column of the main shuttle bay) orientate the player wrong, when sitting on them. The chairs are fine.

Also in the main control room of the main shuttle bay, the right (portside) seat has a wrong sitting orientation too.

**Comment by scragnog** [comment]
good catch! These are all fixed now.
