### ISSUE TITLE
3rd Person Camera doesn't collide with Shuttle.

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#99]
I thought I posted this one, but I can't find it. Anyways, the camera in 3rd person does not collide with the shuttle.

Edit: It appears that the camera will still collide with the rear door, but not the rest of the shuttle. I'm guessing that this is a flag Unreal Engine has with collisions. If so, you guys should use it on the invisible walls that stop you from jumping off the ledge in Stellar Cartography.

**Comment by scragnog** [comment]
Implemented first fix for this but I noticed that it's still not quite working right. Have applied a second fix now, will be in final release.
